[1단계 - 장바구니] 돔하디(이동현) 미션 제출합니다.
woowacourse/react-shopping-cart pull request #103
Opened 2022-05-12 08:59 UTC by DomMorello

> 안녕하세요 리뷰어님 :) 돔하디입니다.
> 이번 미션에서 처음 Redux 를 사용해봤는데 Thunk와 함께 사용하면서 사용방법에 익숙해지는 것이 매우 어려웠습니다.
> 페어와 함께 페어프로그래밍으로 진행하다보니 개인적인 학습이 많이 부족해서 보완점이 많을 것 같습니다ㅠ
> 미흡한 부분에 대해서 피드백 주시면 감사하겠습니다!

## [데모페이지]()

### 기능 구현 목록
 - Redux, Thunk 를 활용한 상태 관리
 - JSON Server
 - router를 이용한 페이지 이동
 - 상품 목록
 - 상품 목록을 장바구니에 추가
 - 컴포넌트별 Storybook 작성

...작성중

2022-05-13 09:41 UTC, inwalter99 commented
안녕하세요. 리뷰어 월터입니다.
다름이 아니라 리뷰가 조금 늦어질 것 같아 미리 양해의 말씀을 드리려고 왔습니다 🥲 
개인적인 사정이 있어서 시간을 못내고 있습니다 ㅜ.ㅜ 리뷰를 어느정돈 해놨는데 아직 부족해서,,, 늦어도 48시간 전에는 리뷰드리도록 할게요!
그전까지 추가로 반영할 게 있으시면 반영부탁드립니다!

2022-05-14 07:18 UTC, inwalter99 requested changes
안녕하세요 돔하디 :) 
기다려주셔서 감사합니다.
전반적으로 컴포넌트나 코드에 대해서는 크게 리뷰드릴 점이 크게 없네요 👍  
다만, 아직 `redux` 를 사용하는 부분에 있어서는 조금 어색한 부분들이 있는 것 같습니다. 
파일 구조를 `action,` `reducer,` `store,` `type` 으로 나누어주셨다고 했는데요, 이 부분들에 각각 역할과 이렇게 분리해 본 의도를 설명부탁드릴 수 있을까요?

추가로 주신 질문들에 대해서는 코멘트로 따로 달아드리도록 하겠습니다!
수고하셨어요! 코멘트 확인부탁드릴게용

2022-05-14 07:20 UTC, inwalter99 commented
> 리액트를 하면서 처음으로 styled component를 사용했습니다. 스타일 관련 css 정보들만 담고 있는 컴포넌트를 만들어서 자체적으로 Styled라는 네이밍 컨벤션을 갖고 있습니다.� 컴포넌트로 사용할 수 있다보니 재사용성이 매우 좋을 것 같은데 실제로 제 미션에서는 재사용성을 잘 활용하지 못한 한계가 분명히 존재합니다. 어떤 식으로 활용해야 styled component의 강점을 잘 살릴 수 있는지는 아직 잘 모르겠습니다 :(

`styled component` 는 크게 대단한 게 아니라 단순히 css 로 스타일링 하던 걸 css-in-js 로 변경되고 컴포넌트와 결합해 스타일링하는 것이라고 생각하고 있습니다. 그렇기 때문에 styled component 를 분리해서 생각하는 게 아니라 그냥 컴포넌트 관점에서 재사용성을 고려해보면 어떨까요? 

사실 프로젝트가 크지 않은 환경에서 재사용성이 매우 잘 드러나는 게 쉬운 일이 아니기 때문에 styled component 의 기본적인 사용법 정도만 익히는 걸 목표로 해보는 것을 추천드립니다!

2022-05-14 07:22 UTC, inwalter99 commented
> Redux 를 처음 사용해보는데 파일 구조를 actions.js, reducer.js, store.js, types.js 로 나눴습니다. 이 모든 파일들의 코드들이 서로 협력하면서 Redux store를 통해 상태를 관리하게 되는데 이 일련의 과정에 아직도 익숙하지가 않습니다. 그래서 실제로 이 부분에서 Loading이나 Error 핸들링을 추가적으로 구현하려는 노력을 했음에도 불구하고 결과적으로 구현을 하지 못했습니다. 

저도 이 부분이 사실 좀 아쉬운데요! 먼저  **thunk 에서 비동기 문제를 어떻게 해결하고자 했는지**부터 살펴보시면 좋을 것 같아요 :) 왜 thunk 가 나오게 됐는지 이해하다보면 thunk 의 사용법도 알게 되고, 말씀주신 loading 과 error 핸들링도 가능해지리라 생각합니다! 
추가로 위의 코멘트에서 언급했던 것과 같이 현재 정의한 리덕스 구조에 대해서 정리해서 공유해주시면 좋을 것 같습니다..ㅎㅎ

2022-05-14 07:31 UTC, inwalter99 commented
> 스토리북을 실행시켜 보면 ProductListContainer 컴포넌트의 스토리북에서 에러가 납니다. 에러 메세지는 Provider를 제공해줘야 한다고 하지만 실제로 store 를 import 해서 decorators 로 Provider 를 제공해줘도 문제가 해결되는 것은 아닙니다. 에러는 발생하지 않지만 화면에 어떤 것도 렌더링 하지 않습니다.
> 이유는 실제로 해당 컴포넌트에서는 Redux store 내부에 있는 값들을 map으로 돌면서 리스트를 렌더링 하는데 store에 접근을 못하는 것 같습니다. 해결 방법으로 MockStore를 만들어서 진행하는 법이 있는 것 같은데 많은 시간을 들여 시도를 해보다가 잘 이해하지 못한체 넘어갔습니다 :(

`실제로 store 를 import 해서 decorators 로 Provider 를 제공해줘도 문제가 해결되는 것은 아닙니다. 에러는 발생하지 않지만 화면에 어떤 것도 렌더링 하지 않습니다.`
store 에 데이터가 없어서 그런 것 아닐까요..? 

우리가 index.js > App.js 환경에서 마운트하는 `ProductListContainer` 와 달리 
스토리북 환경은 완전히 우리 프로덕트와 독립된 환경입니다! 스토리북 프로젝트를 위해 Provider 를 주입하고, 목데이터를 주입하는 api 패칭 하는 로직을 넣어주든해야 데이터가 보일 듯 하네요..!

추가로 스토리북 환경에서 Header 도 에러가 나는 이유도 비슷한 이유입니다 :)

2022-05-14 07:33 UTC, DomMorello commented on src/components/Header/Header.jsx
> +import { CART_SIZE, COLOR, PATH } from '../../constants';
이 부분에 대해서 다른 크루의 피드백을 보고 적용해보려고 했는데 바쁘게 진행하다보니 스킵했던 부분이네요 ㅠ!

다시 한 번 상기해줘서 감사합니다! 이 기능을 사용해서 import 문들을 깔끔하게 정리해보겠습니다!

2022-05-14 07:52 UTC, DomMorello commented on src/stories/Introduction.stories.mdx
> +import { Meta } from '@storybook/addon-docs';
지레짐작으로 삭제하면 안 될 것 같은 느낌으로 삭제를 안 했었는데 피드백을 보고 실제로 삭제해도 정상적으로 작동하는 것을 확인했습니다. 새로운 것을  또 배웠네요 ㅎㅎㅎ 감사합니다!

2022-05-14 07:53 UTC, DomMorello commented on src/components/shared/styles.jsx
> +export const UnstyledButton = styled.button`
리뷰어님이 이해하신 의도가 맞습니다. 페어의 의견으로 `UnstyledButton` 이라는 네이밍을 했는데 지금 생각해보니 뭐하러 그렇게 했나 싶습니다.... 스타일을 갖고 있고 공통적으로 사용되는 특징인데 이 부분 다시 네이밍 고민해서 개선해보겠습니다 ㅎㅎㅎ

`default` 키워드를 사용한다면 좀 더 예측하기 쉬운 네이밍이 될 것 같습니다!

2022-05-14 07:54 UTC, DomMorello commented on src/components/Main/ProductListContainer.jsx
> +
제가 개선해보려고 노력했던 부분인데 redux 를 더 이해하고 어떻게 구현할지 공부해서 구현해보겠습니다.

그리고 결과가 없을 때의 상황도 고려해서 추가하겠습니다 감사합니다!

2022-05-14 08:01 UTC, DomMorello commented on build/asset-manifest.json
> +{
맞습니다ㅠ PR 마감 시간에 배포에 문제가 생겨서 이것저것 시도해보다가 실수로 올린 것 같습니다! 주의하겠습니다!

2022-05-14 08:01 UTC, DomMorello commented on src/store/actions.js
> +};
제가 아쉬웠던 부분인데 최우선으로 생각하고 구현을 해보도록 하겠습니다! 감사합니다!

2022-05-16 05:47 UTC, DomMorello commented on src/components/Main/Product.jsx
> +};
다시 생각해보니 carts 라는 데이터를 store에서 관리하고 있는데 이 부분을 redux 로 사용하지 않는 근거가 없는 것 같습니다. store에서 관리될 수 있도록 수정하겠습니다!

2022-05-16 05:47 UTC, DomMorello commented on src/components/Main/Product.jsx
> +    }
한 번 확인해보겠습니다!

2022-05-17 10:27 UTC, DomMorello commented on src/components/Header/Header.jsx
> +import { CART_SIZE, COLOR, PATH } from '../../constants';
`absolute-imports` 적용 했습니다!

[해당커밋](https://github.com/woowacourse/react-shopping-cart/pull/103/commits/1729300d5e96f5b03881133894dddf1b1e8f3900)

2022-05-17 10:28 UTC, DomMorello commented on src/components/shared/styles.jsx
> +export const UnstyledButton = styled.button`
`Unstyled`라는 네이밍이 어색하다는 생각이 들고 리뷰어님도 의도를 바로 파악하지 못한 부분을 생각해서 `Default` 키워드를 사용해서 의도를 드러낸 네이밍으로 수정했습니다!

[해당 커밋](https://github.com/woowacourse/react-shopping-cart/pull/103/commits/ec6b121d90131f4050ee1ec3775fddedad923831)

2022-05-17 10:30 UTC, DomMorello commented on src/components/Main/ProductListContainer.jsx
> +
일단은 디자인보다는 기능을 구현하기 위해서 컴포넌트로 나누진 않았지만 로딩, 결과없음, 에러를 핸들링하는 로직을 추가했습니다! 

[로딩, 에러 핸들링 커밋](https://github.com/woowacourse/react-shopping-cart/pull/103/commits/690b60d0d54382f581ab7d38454ae548e24c47ac)

[결과 없음 커밋](https://github.com/woowacourse/react-shopping-cart/pull/103/commits/df4efc64af1b76d90ff6d7217110f71e019f5dd5)

2022-05-17 10:32 UTC, DomMorello commented on src/components/Main/Product.jsx
> +};
장바구니 추가, 제거를 redux 에서 관리하는 상태로 업데이트해주었고 그 과정에서 api 레이어가 thunk 부분으로 분리되었습니다!

[해당커밋](https://github.com/woowacourse/react-shopping-cart/pull/103/commits/262e682dc62d7385a12f60e4ac4a7dc0123d872c)

2022-05-17 10:33 UTC, DomMorello commented on src/components/Main/Product.jsx
> +    }
동작하지 않는 것으로 확인했습니다! 이 부분은 에러 핸들링하는 과정에서 삭제되었습니다!

[해당커밋](https://github.com/woowacourse/react-shopping-cart/pull/103/commits/690b60d0d54382f581ab7d38454ae548e24c47ac)

2022-05-17 10:34 UTC, DomMorello commented on src/store/actions.js
> +};
위에서도 언급했지만 가장 시간이 오래 걸린 부분이었는데 UI 측면에서 많이 부족하지만 일단 시간이 부족한 상황에서 기능 구현을 우선으로 구현했습니다! 

[해당커밋](https://github.com/woowacourse/react-shopping-cart/pull/103/commits/690b60d0d54382f581ab7d38454ae548e24c47ac)

2022-05-17 11:09 UTC, DomMorello commented
> 안녕하세요 월터님! 피드백을 열심히 반영했습니다! 고민했던 부분들이 있는데 그 부분들에 대해서 월터님의 소중한 의견을 공유해주신다면 감사하겠습니다 :)

## 피드백 반영
#### Alert 동작 확인 및 수정
#### 불필요한 Storybook init시 생성되는 파일 삭제
#### Unstyled 의도를 드러내도록 네이밍 수정
#### absolute-imports 적용
#### 장바구니 추가 제거 시 redux 사용
#### 로딩,에러, 결과없음 렌더링

## 고민했던 부분
### store 디렉토리 하위 항목 구성
월터님께서 기존의 store 디렉토리 구조에 대해서 설명을 부탁했었는데 사실 그 부분을 대답하기 위해서 여러 고민을 했습니다. 그런데 페어와 함께 디렉토리 구조를 짜면서 Redux 패턴에서 **주요 개념으로 나뉘는 기준**으로 디렉토리를 나눴던 것이 전부였습니다. Flux 패턴에서 주요개념으로 설명되는 것들을 참고하다보니 처음에는 **actions, types, reducer, store**로 나누었었습니다.

하지만 redux 를 제가 직접 응용하고 확장하면서 그런 폴더 구조로는 가독성이 조금 떨어진다는 생각을 했습니다. 그래서 제 나름대로 고민을 하고 결정한 구조가 현재의 구조입니다. 여기서는 가장 중요하게 생각한 부분이 **도메인으로 파일을 나눈다는 것**입니다.

redux 파일 구조에 대해서 공부를 하다 보니 **덕 패턴**이라는 것이 있는 것을 알았습니다. redux 에서도 toolkit에서 해당 패턴을 차용해서 구현했다는 것을 알게 되었습니다. 제가 구현한 것이 **덕 패턴**을 제대로 구현한 것은 아닌 것 같지만 제 의도는 이렇습니다. redux 공식 문서 중에 리팩토링 하는 과정이 있는데 그 부분에서 **도메인별로 reducer를 나누는 과정**이 있었습니다. 제 redux store 에는 크게 products, carts 이렇게 두 개의 도메인이 존재합니다.

각각의 도메인에 개별의 리듀서, 액션크리에이터 등이 존재하며 **도메인별로 파일을 나누는 것이 다른 개발자가 봤을 때 파일구성만 보고도 쉽게 이해할 수 있을 것이라고 생각해서 현재와 같은 store/products.js, store/carts.js 구조로 수정**했습니다 :)

### 로딩과 에러 핸들링
redux를 사용해서 로딩과 에러를 핸들링하는 방법에 대해서 많이 고민을 했습니다. 그런데 많은 개발자들이 **loading, error 에 대한 상태를 redux store에서 관리**하는 것을 알 수 있었습니다. 

이 부분을 적용하는 과정에서 어려웠던 점이 있었는데 바로 **error 상황에서 error 상태를 업데이트 해준 이후에 error를 다시 초기화**해줘야 한다는 것이었습니다. 에러가 처음 발생한 시점에 error상태를 업데이트 해준 다음에 그대로 두면 정상적인 액션 이후에도 에러를 감지하게 될 테니까 다시 초기화를 해줘야 했습니다. 이 문제를 해결하기 위해서 **다른 모든 성공적인 action에서 error 상태를 다시 초기값인 null로 지정**해주었습니다.

그런데 이 과정에서 문제가 있었습니다. Product 컴포넌트에서 예를 들어, `dispatch(deleteCart())` 를 통해서 API 콜을 했는데 여기서 에러가 발생했을 경우에 carts 도메인에 있는 cartsError 를 업데이트 해줍니다. 그런 이후에 다른 action 을 호출하지 않은 상태에서 라우팅을 통해 다른 컴포넌트로 이동했다가 다시 ProductListContainer 컴포넌트로 돌아올 때 useEffect 훅에서 load를 하면서 error를 초기화해주는데 **그 순서가 뒤바뀌어서 에러를 먼저 감지하고 alert를 띄운 이후에 error가 null로 초기화**됩니다.

사용자 입장에서는 치명적인 버그이기 때문에 이 문제를 해결하기 위해 고민을 했습니다.

1. finally 구문에서 error 초기화하기
error를 생성하는 action에서 finally 구문을 추가하여 catch에서 store의 error를 업데이트 해주고 바로 finally에서 error를 null로 초기화해줬었습니다. 제가 처음에 생각한 것은 일단 상태가 변경되었으니 rerender 되면서 alert를 띄우고 그 이후에 바로 error가 null로 초기화돼서 문제를 해결할거라고 생각했지만 error 상태를 useSelector로 가져오는 ProductListContainer에서 상태변화를 감지하지 못한다는 것을 확인했습니다. 그 원인을 잘 모르겠습니다.

2. 1번 상황에서 실험적으로 finally 구문 안에서 `setTimeout(() => {/* error를 null로 초기화하는 action 코드 */}, 0)` 을 해줬더니 실제로 잘 작동했습니다. 이를 통해서 store 업데이트가 동기적으로 발생하는 과정에서 queue에 들어가는 순서가 조금 달라진다는 것을 알았습니다. 그런데 이런 해결방법은 적절하지 않다고 생각해서 채택하지 않았습니다.

3. 결과적으로 라우팅 했을 때 error을 초기화해주는 action을 실행하지 않아서 생긴 문제임을 파악하고 useEffect 내 cleanup 함수에서 error 를 null 로 초기화해주는 `cleanError` action을 `dispatch`해주었습니다. 이렇게 하면 라우팅하면서 unmount될 때 error를 초기화해줘서 다시 mount한 경우에 에러 alert가 뜨는 경우를 방지할 수 있었습니다.

## 미흡한 부분
- 스토리북은 필수구현이 아닌 상황이어서 일단은 step2 필수 요구사항을 마무리하고 그 이후에 수정하려고 합니다 :(

> 설명이 장황하고 길어진 점에 대해서 죄송합니다 ㅠㅠ제가 겪었던 문제를 좀 더 정확하게 전달하고자 노력하다보니 PR에 항상 글이 길어진다는 느낌이 드는데 이 부분도 개선해야 한다고 생각합니다... 긴 PR 글 읽어주셔서 감사합니다. 전달이 제대로 되지 않은 부분이 있다면 슬랙 DM으로 문의 주시면 최대한 빠르게 소통하도록 하겠습니다 감사합니다 잘 부탁드립니다 :)

2022-05-18 12:47 UTC, inwalter99 approved these changes
수고하셨어요 돔하디 :) 
고민 길게 남겨주셔서 감사해요! 코드에 대해서는 2단계로 가도 좋을 것 같아요! 2단계에서 뵙겠습니다 👍 

고민 나눠주신 것에 대한 제 의견은 따로 코멘트 달도록 하겠습니다!

2022-05-18 12:47 UTC, inwalter99 commented on src/components/Main/Product.jsx
> +  };
async 가 필요할까요~?

2022-05-18 12:47 UTC, inwalter99 commented on src/index.jsx
> +const store = createStore(rootReducer, applyMiddleware(thunk));
reducer 가 많아질수록, 다른 미들웨어가 추가될수록 점점 커질 코드겠죠~? + 이 로직들은 여기선 굳이 알 필요 없고 store 만 있음 되니
따로 파일을 분리해 store 만 가져와 Provider 에 주입만 할 수 있도록 2단계 때 수정해주세요~~

2022-05-18 12:47 UTC, merged

2022-05-18 12:54 UTC, inwalter99 commented
> store 디렉토리 하위 항목 구성

먼저, 치열한 고민의 결과로 돔하디님만의 구조가 탄생하게 된 게 너무 좋습니다! 이미 지겹도록 들어오셨겠지만 코드와 구조에 정답은 없거든요ㅎ
`다른 개발자가 봤을 때 파일구성만 보고도 쉽게 이해할 수 있을 것이라고 생각해서 현재와 같은 store/products.js, store/carts.js 구조로 수정` => 그 결과 저도 덕분에 쉽게 이해했습니다! 
다만 한가지 의견을 드리고 싶은 건 도메인 별로 actions, reducer 등을 파일을 나누어도 좋겠다 생각이 들어요. 왜냐하면 지금에야 액션도 적고 하고 지금 loadProducts 만해도 코드양이 꽤 많은데요, 만약 하나라도 추가가 되면 한 파일 내에 정의되어있다면 역할이 섞여 오히려 가독성이 떨어질 것 같다는 생각을 했습니다.
물론! 지금 기능에는 best 라고 생각합니다. 👍 👍 👍 👍   
(제가 말씀드린 예시는 `store/products/reducer.js` `store/products/action.js` 같이 한 뎁스가 더 생기는 것을 말해봤습니다..)

2022-05-18 13:12 UTC, inwalter99 commented
> 로딩과 에러 핸들링

먼저 `"설명이 장황하고 길어진 점에 대해서 죄송합니다 ㅠㅠ제가 겪었던 문제를 좀 더 정확하게 전달하고자 노력하다보니 PR에 항상 글이 길어진다는 느낌이 드는데"`  라고 말씀을 해주셨는데요, 사실 저희는 보다 강력한 소통 도구가 있습니다..! 바로 `예시 코드`인데요.
저도 주절주절할 때가 많은데, 그럴 때 `예시 코드`를 작성해 첨부하다보면 설명이 조금은 더 간결해지고 이해하기도 훨씬 쉬워지더라구요!
아무래도 글로만 설명하면 다른 코드를 상상해서 제대로 전달이 되지 않을 수 있는데, `예시 코드`를 던지면 문제 상황 등이 온전히 전달되어서 이해와 소통에도 훨씬 좋습니다! (저도 잘 이해를 못하겠어서 드리는 말은...맞습니다!)


> error 상태를 업데이트 해준 이후에 error를 다시 초기화해줘야 한다는 것이었습니다. 에러가 처음 발생한 시점에 error상태를 업데이트 해준 다음에 그대로 두면 정상적인 액션 이후에도 에러를 감지하게 될 테니까 다시 초기화를 해줘야 했습니다. 

이 부분은 실제 예시를 통해 어떤 상황인지 구체적으로 들었으면 이해가 좀 더 쉬웠을 것 같아요.
`error상태를 업데이트 해준 다음에 그대로 두면 정상적인 액션 이후` -> error 가 발생한 상황에서 새로고침이 아닌 다시 시도하기나 그런 기능이 있는가? 아니면 메인페이지에서 에러가 발생한 다음 다시 장바구니갔다가 다시 메인페이지로 돌아왔을 때의 상황인가 등...

> 그런데 이 과정에서 문제가 있었습니다. �Product 컴포넌트에서 예를 들어, dispatch(deleteCart()) 를 통해서 API 콜을 했는데 여기서 에러가 발생했을 경우에 carts 도메인에 있는 cartsError 를 업데이트 해줍니다. 그런 이후에 다른 action 을 호출하지 않은 상태에서 라우팅을 통해 다른 컴포넌트로 이동했다가 다시 ProductListContainer 컴포넌트로 돌아올 때 useEffect 훅에서 load를 하면서 error를 초기화해주는데 그 순서가 뒤바뀌어서 에러를 먼저 감지하고 alert를 띄운 이후에 error가 null로 초기화됩니다.

Product 컴포넌트에서 ... 다른 컴포넌트로 이동했다가... ProductListContainer 컴포넌트로 돌아올 때... 가 잘 이해되지 않습니다.
이런 상황일까요?
1. 메인페이지에서 장바구니 추가/삭제를 요청함
2. 장바구니 추가/삭제가 오래걸리는 상황)

2022-05-18 13:15 UTC, inwalter99 commented
> 로딩과 에러 핸들링

먼저 `"설명이 장황하고 길어진 점에 대해서 죄송합니다 ㅠㅠ제가 겪었던 문제를 좀 더 정확하게 전달하고자 노력하다보니 PR에 항상 글이 길어진다는 느낌이 드는데"`  라고 말씀을 해주셨는데요, 사실 저희는 보다 강력한 소통 도구가 있습니다..! 바로 `예시 코드`인데요.
저도 주절주절할 때가 많은데, 그럴 때 `예시 코드`를 작성해 첨부하다보면 설명이 조금은 더 간결해지고 이해하기도 훨씬 쉬워지더라구요!
아무래도 글로만 설명하면 다른 코드를 상상해서 제대로 전달이 되지 않을 수 있는데, `예시 코드`를 던지면 문제 상황 등이 온전히 전달되어서 이해와 소통에도 훨씬 좋습니다! (저도 잘 이해를 못하겠어서 드리는 말은...맞습니다!)


> error 상태를 업데이트 해준 이후에 error를 다시 초기화해줘야 한다는 것이었습니다. 에러가 처음 발생한 시점에 error상태를 업데이트 해준 다음에 그대로 두면 정상적인 액션 이후에도 에러를 감지하게 될 테니까 다시 초기화를 해줘야 했습니다. 

이 부분은 실제 예시를 통해 어떤 상황인지 구체적으로 들었으면 이해가 좀 더 쉬웠을 것 같아요.
`error상태를 업데이트 해준 다음에 그대로 두면 정상적인 액션 이후` -> error 가 발생한 상황에서 새로고침이 아닌 다시 시도하기나 그런 기능이 있는가? 아니면 메인페이지에서 에러가 발생한 다음 다시 장바구니갔다가 다시 메인페이지로 돌아왔을 때의 상황인가 등...

> 그런데 이 과정에서 문제가 있었습니다. �Product 컴포넌트에서 예를 들어, dispatch(deleteCart()) 를 통해서 API 콜을 했는데 여기서 에러가 발생했을 경우에 carts 도메인에 있는 cartsError 를 업데이트 해줍니다. 그런 이후에 다른 action 을 호출하지 않은 상태에서 라우팅을 통해 다른 컴포넌트로 이동했다가 다시 ProductListContainer 컴포넌트로 돌아올 때 useEffect 훅에서 load를 하면서 error를 초기화해주는데 그 순서가 뒤바뀌어서 에러를 먼저 감지하고 alert를 띄운 이후에 error가 null로 초기화됩니다.

Product 컴포넌트에서 ... 다른 컴포넌트로 이동했다가... ProductListContainer 컴포넌트로 돌아올 때... 가 잘 이해되지 않습니다.
그런데 왜 `cartsError` 를 다같이 사용할까요? `addCart,` `deleteCart,` `loadCarts` 모두 다 다른 API 이고, 로딩도 에러도 독립적이어야하지 않을까요 @.@????

2022-05-18 13:28 UTC, DomMorello commented on src/components/Main/Product.jsx
> +  };
하..맞네요 ... 그 부분을 꼼꼼하게 확인하지 못했던 것 같습니다! 이 부분 수정하겠습니다!

2022-05-18 13:29 UTC, DomMorello commented on src/index.jsx
> +const store = createStore(rootReducer, applyMiddleware(thunk));
더 확장될 가능성이 있는 코드이니 store 라는 파일을 따로 만들어서 관리하도록 수정하겠습니다!

2022-05-18 13:36 UTC, DomMorello commented
윌터님 피드백 잘 확인했습니다! 코드를 함께 첨부해서 설명하는 정성이 부족했던 부분이 가장 아쉬운 PR이네요ㅜ 

원활한 소통을 위해서 예시코드를 적극적으로 활용해서 step2 에서는 잘 활용하도록 하겠습니다! 커뮤니케이션에 대한 피드백 주셔서 감사합니다! 이제부터는 문제 설명 시에 무조건 코드와 함께 설명하는 습관을 갖겠습니다! ㅎㅎㅎㅎ

로딩, 에러가 독립적으로 존재해야 하지 않을까에 대한 부분 더 고민해보겠습니다! 

스토리북 관련해서는 실제 브라우저처럼 작동해야 하지 않을까란 생각을 했던 것이었는데 step2 에서 다른 test 요구사항을 구현하면서 더 고민하고 다시 자세하게 질문드리겠습니다! 

정성 가득한 피드백을 받아서 좋은 시간이었던 것 같습니다! 이대로 step2 에서도 제가 고민한 부분들을 공유하도록 하겠습니다. 감사합니다 :)