[2단계 - 장바구니] 유세지(김용래) 미션 제출합니다.
woowacourse/react-shopping-cart pull request #113
Opened 2022-05-21 16:00 UTC by usageness

## 📢 프로젝트 결과물은 아래 링크를 확인해주세요!
### [🚩 데모 페이지](https://usageness.github.io/react-shopping-cart/)
### [📕 스토리북 페이지](https://6288fe31fa10be003a6144cb-mycfvusgzd.chromatic.com/)

---

**안녕하세요, 아사님!**

좋은 주말 보내고 계신가요? 저는 이번 미션에선 유독 버그가 많이 터져서 디버깅하느라 이틀을 보냈네요 😥
힘들었지만 그만큼 많이 배우고 즐겼던 시간인 것 같아요. 새로 알게 된 내용도 많았고, 재밌는 라이브러리도 많이 발견했네요!
시간적 여유가 더 있었다면 구현해보고 싶은 것들이 많았지만, 일정 상 다음으로 미루고 빠르게 제출해야 할 것 같아요. (다음주 테코톡을 준비하러 가야하네요...😭)

혹시 **"이런걸 더 구현해보면 좋겠다"** 하는 기능이나 기술적인 부분이 있다면
되도록 피드백 기간내로, 안되면 혼자서라도 꼭 해보겠습니다!
부담없이 남겨주세요 😊

## 구현한 요구사항이에요

### 🚩 기능 요구사항

- [x] 메인 화면에서 현재 판매중인 상품들을 볼 수 있어야 한다.
- [x] 장바구니 버튼을 눌러 상품을 장바구니에 담을 수 있어야 한다.
- [x] JSON 서버를 통하여 상품 목록을 불러올 수 있어야 한다.
- [x] 장바구니 페이지에서 장바구니에 담긴 상태를 확인할 수 있어야 한다.
- [x] 상세정보 페이지에서 특정 상품의 상세 정보를 확인할 수 있어야 한다.
- [x] MSW를 활용하여 API를 Mocking 하여야 한다.

### ✔️ 테스트 요구사항

- [x] 구현 사항에 대해 단위 테스트를 진행하여야 한다.
- [x] 스토리북을 이용해 컴포넌트의 UI를 확인할 수 있어야 한다.

## 이렇게 구현했어요
![image](https://user-images.githubusercontent.com/28296575/169658899-d171fdb1-aec8-4a6b-8813-9c435e44fc85.png)

## 질문 사항
### 복잡해진 레이아웃
이번 피그마 시안에서 레이아웃이 복잡해짐에 따라, 만들어줘야 할 컴포넌트도 많아졌습니다.
요구사항에 맞는 스타일 컴포넌트를 모두 작성하자니 너무 많아지는 스타일 파일의 관리도 어렵고,
하나하나 붙여줘야 할 네이밍도 고역이어서 하나씩 만들어주는 것은 포기하였습니다.
대신, 공통적으로 가지는 요소를 최대한 분리하여 상세한 속성은 인라인으로 넘겨주는 방법을 선택했습니다.

예시로, 장바구니 페이지에 많이 들어간 `FlexWrapper` 스타일 컴포넌트 입니다.
```js
// CartProductItem/index.jsx
<CommonStyled.FlexWrapper margin="0" width="100%" justifyContent="space-between">
          <Styled.Title>{name}</Styled.Title>
          <IconButton onClick={onClickDeleteButton} icon={아이콘_코드.DELETE} />
        </CommonStyled.FlexWrapper>
        <CommonStyled.FlexWrapper margin="0" width="120px" justifyContent="flex-end">
          <Counter id={id} count={count} handleItemCount={handleItemCount()} />
        </CommonStyled.FlexWrapper>
        <CommonStyled.FlexWrapper margin="0" width="100%" justifyContent="flex-end">
          <CommonStyled.Text padding="0.5rem 0">
            {price.toLocaleString('ko-KR')}원
          </CommonStyled.Text>
        </CommonStyled.FlexWrapper>
```

```js
// CommonStyle/styles.js
const FlexWrapper = styled.div`
  display: flex;
  margin: ${(props) => props.margin || '0 auto'};
  padding: ${(props) => props.padding || '0'};
  flex-direction: ${(props) => props.flexDirection || 'row'};
  width: ${(props) => props.width || '100%'};
  height: ${(props) => props.height || 'unset'};
  align-items: ${(props) => props.alignItems || 'center'};
  justify-content: ${(props) => props.justifyContent};
`;
```

나름 복잡성을 최대한 줄였다고 생각했지만, 근본적인 복잡함은 남아있어 더 좋은 방법을 생각해보고 있습니다.
혹시 이런 경우에 참고할 수 있는 키워드가 있을까요?

### 리덕스.. 이대로 괜찮은걸까?

리덕스를 사용하며 동작 방식이 눈에 익다보니 지금은 흐름이 조금 읽히는 것 같은데,
아무리 생각해도 엄청나게... 큰 프로젝트가 아니라면 굳이 flux 패턴을 고집하기 보다는
context API 를 통해서 유동적으로 구조를 짜주는게 오히려 더 효율적일 수 있어보여요.
미션의 규모가 작아서 그런지 불편하다는 느낌이 한 켠에 남아있네요...

게다가 airbnb 홈페이지에서도 리덕스를 걷어내주고 있다는 이야기를 듣고 보니
과연 리덕스가 모든 프로젝트에서 사용해야 할 만큼 좋은 아키텍쳐를 만들어 줄 수 있나? 에 대한 의문이 들어요.
제 지식과 경험이 짧아 그런것일지 모르겠지만 😭 아사님이 생각하시는 리덕스는 어떤지 궁금해요 !!

---

step을 진행하며 조금씩이지만 리덕스 (flux 패턴) 에 대한 이해가 생기는 것 같아요 :)
이번 step2도 잘 부탁드리겠습니다! 좋은 주말 보내세요 😊

2022-05-22 16:32 UTC, EungyuCho requested changes
안녕하세요 세지님~ 리뷰가 조금 늦었네요 🙏 
미션 완성하신다고 고생하셨어요! 

세지님의 테코톡.. 기대되네요 😮 
숨 꾹 참고 기다리고 있을게요!

우선 질문을 볼까요?~

> 나름 복잡성을 최대한 줄였다고 생각했지만, 근본적인 복잡함은 남아있어 더 좋은 방법을 생각해보고 있습니다. 혹시 이런 경우에 참고할 수 있는 키워드가 있을까요?

`FlexWrapper` 컴포넌트의 복잡성을 줄이는 방법을 질문해주신 것 같은데요!
라이브러리처럼 범용적으로 사용한다면 지금 작성해주신대로가 가장 현명하다고 생각해요.
디자인 시안이 있고 통일성 있게 컴포넌트 크기를 조정할 수 있다면 이런식으로 가능할 것 같아요.
```typescript
const Example = () => (
  <Box flexCenter>
    <Text as='h2'>아사 블로그</Title>
    <Button theme="primary" size="lg">팔로우 하기</Button>
  </Box>
)
```
위 size나 theme 속성처럼 좁은 선택지를 주고 해당 속성에 따라 여러 css 스타일을 변경해주면 더 간단하게 해결할 수 있다고 생각해요. 이전처럼 컴포넌트가 유동적으로 스타일을 변경해주기는 힘들겠지만.. 디자인 시안에 따라서 복잡성을 줄여볼 수 있는 방법이라 생각해요.. 😅

요건 어디까지 말랑말랑한 컴포넌트를 만들어주는게 편할지 다시 정해보시면 좋을 것 같아요~

> 아사님이 생각하시는 리덕스는 어떤지 궁금해요 !!

최근에는 서버의 데이터를 그대로 사용하는 경우가 많아 react-query를 주로 사용했었어요.
날것의 redux로 실제 프로젝트를 해본적은 없지만 saga까지 약간 만져본 경험으로는... 좋지 않았던 것 같네요 😅 

작성해야하는 코드가 너무 많아서 불만족스러웠고 reselect로 최적화도 해줘야하고.. 😢  
그래서 저는 fetching 라이브러리(react-query)와 가벼운 recoil, jotai를 선택하거나 모듈화가 필요하다면 mobx를 주로 사용하고 있어요. ~~저는 간단한게 좋아요~~

createStore를 사용하셨을 때 함수가 deprecated된걸 확인하셨을텐데요~ 
deprecated된 [이유](https://redux.js.org/introduction/why-rtk-is-redux-today)를 보시면 redux 팀도 비슷한 고민을 하고있었던 걸 볼 수 있어요 🙂 
 
> 되도록 피드백 기간내로, 안되면 혼자서라도 꼭 해보겠습니다!

피드백 기간이 끝나고 머지가 되더라도 계속 이어가도 무방합니당 😆 

벌써 주말이 끝났네요! 월요일인데 이번주도 힘내시길 바래요~~
이번주도 힘내서 달려봅시다 😎

2022-05-23 06:41 UTC, usageness commented on package.json
> +    "chromatic": "npx chromatic --project-token=e68e7f4dc3ee"
오.. 안됩니다... 세상에... 😮

2022-05-23 10:55 UTC, usageness commented on src/constants/index.js
> +};
한글 변수는 복잡한 내용을 간결하고 명확하게 나타내는 장점이 있지만,
영어로 된 코드에서 마주치면 확실히 이질감이 드는 느낌이에요.
그래도 타입과 상수까지는 복잡하지 않더라도 한글로 통일하려고 했던게
나름대로의 일관성을 지키려는 시도였는데 생각해보니 굳이 지켜줄 필요는 없는 규칙이었던 것 같아요 😊

말씀하신 것처럼 `상수`에 대한 네이밍으로는 고민이 많았어요.
보통 이런 경우에는 간단히 `Number` 정도로만 지정해주었는데 한글로 번역하자니 `숫자`....?
너무 큰 범위에서 설정 한 것 같고, `주문수량` 으로 한정하자니 너무 작은 범위 같고...

매직넘버가 그렇게 많은 프로젝트가 아니지만, 우선은 `숫자` 정도로 변경할게요!
~~변경하면서도 확신이 안드네요 😭~~

2022-05-23 11:53 UTC, usageness commented on src/hooks/useCheckBox.js
> +  };
> 사용하는 곳에서 선택된 상품들을 삭제하려다보니 자연스럽게 네이밍이 훅으로 섞여들어온 것 같은데

정확합니다...! 먼저 컴포넌트 단에서 기능을 구현하고, 훅으로 분리해주면서 네이밍을 수정해주지 않았어요.
저도 사용 컴포넌트 기준이 아닌, 훅을 기준으로 네이밍이 정해져야 하는게 맞다고 생각합니다!

[✏️ : useCheckBox의 deleteSelectedItem 함수 이름 변경](https://github.com/woowacourse/react-shopping-cart/pull/113/commits/348f76f6823d5b63c4236cecb942dfa255cc6747)

2022-05-23 12:21 UTC, usageness commented on src/hooks/useCheckBox.js
> +    });
제가 뭔가 잘못 했었나봐요... 배열 요소가 하나일때는 삭제가 잘 안돼서 추가했었는데...
다시 해보니까 잘 되네요 😥 제가 왜 그랬을까요......?

2022-05-26 07:25 UTC, usageness commented on src/hooks/useCheckBox.js
> +  const [checkedList, setCheckedList] = useState([]);
기존의 checkList가 id 값만 넣고 비교하는 구조라 이 부분 유지하면서 변경했습니다!
setSelectAllCheck 없어지니까 속이 시원하네요 ❤

[♻️ : useCheckBox 구조 개선](https://github.com/woowacourse/react-shopping-cart/pull/113/commits/9260dda8ab6d721f833d7d4ad4abea3a20d80436)

2022-05-26 09:19 UTC, usageness commented on src/components/Snackbar/index.jsx
> +  }
스토리북 전용 config 파일을 만들어서 해결해보았는데...
이런건 어떨까요??

[🔧 : storybook config 파일 생성 및 적용](https://github.com/woowacourse/react-shopping-cart/pull/113/commits/1026e65908a0ecebcbe23b29bf71adda9dc57230)

2022-05-27 06:53 UTC, usageness commented on src/pages/ProductDetail.jsx
> +  );
맞아요... EmptyProductItem이 노출되었다가 로드되는건 유저 입장에서는 좋지 않을 것 같아요!
리듀서의 비동기 액션 처리 부분에 PENDING 상태를 추가하고,
이 상태일때는 상세 페이지에서 스켈레톤 애니메이션이 보이도록 수정했습니다 😊

[✨ : 비동기 액션에 PENDING 상태 추가](https://github.com/woowacourse/react-shopping-cart/pull/113/commits/eb6be21ef143fba4cb6bf8339858df1377b8b88b)
[✨ : 상품 상세 페이지 로딩시 스켈레톤 애니메이션 추가](https://github.com/woowacourse/react-shopping-cart/pull/113/commits/4df57e843f9eee0ef41cacf4a9dd42da1eb2d4c8)

2022-05-27 16:38 UTC, usageness commented on src/__test__/Reducer.test.js
> +    });
CombineReducer를 해줘서 reducer를 분리하기가 어려워졌는데
이것도 일종의 코드 부채(?) 가 될 것 같은 느낌이에요 😥
초기 상태와 업데이트 함수를 선언해서 사용해주었습니다 👀

[♻️ : reducer 테스트 코드 함수로 중복 제거](https://github.com/woowacourse/react-shopping-cart/pull/113/commits/bda239e792f8a40851d20fa25430d25f8d4018a6)

2022-05-27 18:02 UTC, usageness commented on src/components/CartProductItem/index.jsx
> +        </CommonStyled.FlexWrapper>
아.......... 의도가... 아닙니다... 😅

[💄 : Container, Wrapper 구분 적용](https://github.com/woowacourse/react-shopping-cart/pull/113/commits/1e7ab3581d8b2a792b6ee43d36a0d3edb7ade881)

2022-05-27 18:23 UTC, EungyuCho commented on src/constants/index.js
> +};
한글로 네이밍을 지어야 한다는 강박관념에 안빠져도 괜찮을 것 같아요😆
한글로 한다면 주문정도가 적당할거같네요 🙂

2022-05-27 18:29 UTC, usageness commented on src/stories/Layout.stories.js
> +);
템플릿 반복을 컴포넌트로 빼주는건 얼핏 떠올렸었는데
전역 설정도 가능한지는 몰랐네요!
컴포넌트로 만들어주는 대신 전역에서 한 번만 주입해주었습니다!

[🔧 : 스토리북 템플릿 전역 설정](https://github.com/woowacourse/react-shopping-cart/pull/113/commits/669440b1346f22010e744c3a228ff0985c41bf93)

2022-05-27 18:39 UTC, usageness commented
아사님 😭 기다려주셔서 정말 감사합니다!
피드백 모두 반영했고, 한 가지 문제 사항이 있어서 같이 남깁니다!

chromatic 명령어의 토큰을 지우며 현재 public 디렉토리에 있는 msw 파일의 체크섬 변수도 함께
환경 변수를 이용해 `process.env.REACT_APP_INTEGRITY_CHECKSUM` 으로 숨겨주려고 했는데,
src/ 하위 폴더가 아니어서인지 변수 값을 제대로 읽어오지 못하고 있는 상황이 발생했습니다.

혹시 public 디렉토리 내에는 환경 변수 적용이 불가능한 걸까요..?
체크섬 변수라 그냥 노출해도 괜찮을것 같다는 생각은 들지만... 혹여나 문제가 될지 궁금하네요 😮

2022-05-28 05:46 UTC, EungyuCho commented on src/stories/Layout.stories.js
> +);
세지님 혹시 DetailProductItem, ProductItem 스토리북이 정상적으로 스토리가 렌더링되나요?..

2022-05-28 06:13 UTC, EungyuCho commented
> **아사님!!!** 😭 기다려주셔서 정말 감사합니다! 피드백 모두 반영했고, 한 가지 문제 사항이 있어서 같이 남깁니다!
> 
> chromatic 명령어의 토큰을 지우며 현재 public 디렉토리에 있는 msw 파일의 체크섬 변수도 함께 환경 변수를 이용해 `process.env.REACT_APP_INTEGRITY_CHECKSUM` 으로 숨겨주려고 했는데, src/ 하위 폴더가 아니어서인지 변수 값을 제대로 읽어오지 못하고 있는 상황이 발생했습니다.
> 
> 혹시 public 디렉토리 내에는 환경 변수 적용이 불가능한 걸까요..? 체크섬 변수라 그냥 노출해도 괜찮을것 같다는 생각은 들지만... 혹여나 문제가 될지 궁금하네요 😮

public 디렉터리에서도 html파일에서는`<div src="%REACT_APP_WHATEVER%">환경변수가 적용된 element</div>` 이런식으로 끼워넣을 수 있거든요!

정확히 어떻게 실행되는지 구조를 모르겠기도하고..
<img width="372" alt="스크린샷 2022-05-28 오후 3 11 18" src="https://user-images.githubusercontent.com/53712717/170812729-abf6b4ec-69d2-4de8-addf-306342de82d3.png">

위에 적혀있듯이 mock service worker가 프로덕션에 함께 번들링 되지도 않고.. 
주의사항에 이런게 적혀있으니 해당 파일 데이터를 환경변수로 바꾸는건 과감하게 Pass해도 괜찮을 것 같네요 😅

2022-05-28 06:16 UTC, EungyuCho approved these changes
안녕하세요 세지님 👀 

페이먼츠 미션도 하셔야할텐데 장바구니 미션 피드백까지 병행하시느라 쉽지 않으셨을텐데 잘 반영해주셨네요!
스토리북에 조금 문제가 남아있는 것 같긴 하지만 우선 병행하는게 쉽지 않으실 것 같아 추가적인 구현은 세지님의 몫으로 넘기고  approve하겠습니다...!

정말 고생 많으셨어요!! 🎉

2022-05-28 06:16 UTC, merged

2022-05-28 06:36 UTC, usageness commented on src/stories/Layout.stories.js
> +);
테스트용 snackbar store를 전역에서 로드해주며
Provider가 꼬이면서 기존 product 상태를 불러오지 못했던것 같아요!
snackbar config를 원래 자리로 내려주고, snackbar 스토리북에서만 불러오는 것으로
해결해주었습니다!! 꼼꼼히 확인하고 PR 드렸어야 하는데 죄송해요 😥

![image](https://user-images.githubusercontent.com/28296575/170813602-6cf69f83-6b07-4d4d-ae6f-e70c7afe08f3.png)

2022-05-28 06:38 UTC, usageness commented on src/stories/CartProductItem.stories.js
> +  price: 50000,
인터렉션을 통해서 데이터 변경도 확인할 수 있도록 수정해볼게요!
좋은 지적 감사합니다 🥰