[2단계 - 장바구니] 마르코(장원석) 미션 제출합니다.
woowacourse/react-shopping-cart pull request #116
Opened 2022-05-21 20:57 UTC by wonsss

안녕하세요. 월터님. 마르코입니다. 지난번에 좋은 리뷰 주셔서 감사합니다.  
추가구현도 몇 가지 더 시도하고 싶었는데 시간이 부족하네요. 필수구현사항 위주로 구현 완료하였습니다.
msw로 서버 모킹을 하였습니다. msw 핸들러 내에 로직을 추가하였기 때문에, 배포할 때 사용했던 json-server의 api와는 조금 다른 부분이 있습니다. 로컬에서 구동하면 정상작동합니다.

![shoppingcart](https://user-images.githubusercontent.com/59413128/169667503-f7569637-af6e-4268-9fc1-3f43dc1cf930.gif)

## 로컬 구동 방법
- npm install
  - npm 패키지 설치
- npm run start
  - 로컬 구동
- npm run test
  - jest 단위 테스트 실행
- npm run storybook
  - 로컬 스토리북 구동

## 스토리북 데모페이지
- [step2 스토리북 데모페이지](https://627cd06ea27170004a54a0ed-shuuxltqvd.chromatic.com/)

## Step2 구현사항
- [x]  MSW를 활용하여 API Mocking
- [x] 단위테스트
	- [x] reducer 테스트(product, productList, cartList, orderList) 
	- [x] thunk 및 외부API 연동 테스트(product, productList, cartList, orderList) 
	- [x] 컴포넌트 렌더 테스트(CartOrder)
- [x]  장바구니 페이지 : Cart
	  - [x]  상품 목록 페이지에서 장바구니 모양 버튼을 누르면 바로 상품을 장바구니에 담는다.
	  - [x] 상품 목록 페이지에서 장바구니에 담긴 상품의 버튼은 색상이 변한다.
	  - [x]  장바구니 버튼을 누를 때마다 장바구니에 담긴 해당 상품의 수량이 1씩 증가한다.	
	  - [x] 상품을 장바구니에 담으면 Header의 장바구니 메뉴 옆 숫자가 증가한다.
	  - [x] 상세페이지에서 장바구니 버튼을 누르면, 장바구니에 담겼다는 팝업이 표시된다.(이미 담긴 상품인 경우 해당 메시지가 표시된다)
	  - [x] 장바구니에서 개별 상품의 체크박스 선택에 따라 결제 예상 상품 계산 및 상품 삭제가 가능하다.
	  - [x]  장바구니에서 선택한 상품을 삭제할 수 있다.
	  - [x] 장바구니에서 개별 상품의 수량을 인풋을 통해 수정할 수 있다.
	  - [x] 장바구니에서 주문하기 버튼을 클릭하면 API에 orderList를 POST하고 주문 페이지로 이동한다.
	  	- (아직 주문 페이지 컴포넌트를 구현하지 않았기 때문에, 확인용으로만 주문 페이지에 API에서 GET한 orderList를 간단한 텍스트로만 표시함)

## 고민 및 질문
### 커스텀 훅
- 변경된 데이터를 상태에 저장(POST, PATCH, DELETE)하는 경우, 리덕스가 아닌 API에만 저장했습니다. 그리고 리덕스는 API에서 데이터를 GET할 때 thunk와 함께 사용했습니다. 왜냐하면 데이터가 변경된 경우 API에 저장한 후 API에서 리덕스로 상태를 다시 가져와도 괜찮겠다고 생각했기 때문입니다. 그래서 커스텀훅으로 usePost, usePatch, useDelete를 만들어 관련 로직에 사용하였습니다. 이와 같은 접근 방식에 예상되는 문제점이나 다른 적절한 대안은 무엇이 있는지 궁금합니다. 

- 커스텀훅에서도 뭔가 조금 더 공용으로 쓰는 훅이 있고, 그렇지 못하고 특정 페이지에서 주로 사용되는 훅이 생겼습니다. 그래서 제 편의상 조금 더 알아보기 쉽게 hooks 폴더 내에 shared 폴더를 만들어 그 안에 조금 더 공용적인 훅들을 이동시켰습니다. 이렇게 하는 방식에 대해서 어떻게 생각하시나요? 그리고 월터님께서 커스텀훅을 조금 더 효율적으로 관리하는 방법에는 무엇이 있는지 궁금합니다.

### MSW 서버 모킹
msw에서 기존의 json-server의 api와는 정확히 같지는 않지만 제 프로젝트에서는 조금 더 편리한 방식으로 모킹했습니다.
그런데 msw 핸들러 내에 이러한 로직을 담는 것이 적절할 지 의문입니다. 또는 그냥 로직 없이 mock data만 반환하도록 하는 것이 나을까요? 

## 폴더구조
```
📦src
 ┣ 📂assets
 ┃ ┣ 📂mock
 ┃ ┃ ┗ 📜index.js
 ┃ ┣ 📂png
 ┃ ┃ ┣ 📜emptyImg.png
 ┃ ┃ ┣ 📜errorApiImg.png
 ┃ ┃ ┗ 📜notFoundImg.png
 ┃ ┗ 📂svg
 ┃ ┃ ┣ 📜bigCart.svg
 ┃ ┃ ┣ 📜smallCart.svg
 ┃ ┃ ┣ 📜spinner.svg
 ┃ ┃ ┗ 📜trash.svg
 ┣ 📂components
 ┃ ┣ 📂Button
 ┃ ┃ ┣ 📜Button.jsx
 ┃ ┃ ┣ 📜Button.stories.js
 ┃ ┃ ┗ 📜index.js
 ┃ ┣ 📂CartItem
 ┃ ┃ ┣ 📜CartItem.jsx
 ┃ ┃ ┣ 📜CartItem.stories.js
 ┃ ┃ ┗ 📜index.js
 ┃ ┣ 📂CartOrder
 ┃ ┃ ┣ 📂__tests__
 ┃ ┃ ┃ ┗ 📜cartOrder.test.jsx
 ┃ ┃ ┣ 📜CartOrder.jsx
 ┃ ┃ ┣ 📜CartOrder.stories.js
 ┃ ┃ ┗ 📜index.js
 ┃ ┣ 📂CartPopup
 ┃ ┃ ┣ 📜CartPopup.jsx
 ┃ ┃ ┣ 📜CartPopup.stories.js
 ┃ ┃ ┗ 📜index.js
 ┃ ┣ 📂CartTable
 ┃ ┃ ┣ 📜CartTable.jsx
 ┃ ┃ ┣ 📜CartTable.stories.js
 ┃ ┃ ┗ 📜index.js
 ┃ ┣ 📂Checkbox
 ┃ ┃ ┣ 📜Checkbox.jsx
 ┃ ┃ ┣ 📜Checkbox.stories.js
 ┃ ┃ ┗ 📜index.js
 ┃ ┣ 📂Circle
 ┃ ┃ ┣ 📜Circle.jsx
 ┃ ┃ ┣ 📜Circle.stories.js
 ┃ ┃ ┗ 📜index.js
 ┃ ┣ 📂Header
 ┃ ┃ ┣ 📜Header.jsx
 ┃ ┃ ┣ 📜Header.stories.js
 ┃ ┃ ┗ 📜index.js
 ┃ ┣ 📂ImgWrapper
 ┃ ┃ ┣ 📜ImgWrapper.jsx
 ┃ ┃ ┣ 📜ImgWrapper.stories.js
 ┃ ┃ ┗ 📜index.js
 ┃ ┣ 📂MenuItem
 ┃ ┃ ┣ 📜index.js
 ┃ ┃ ┣ 📜MenuItem.jsx
 ┃ ┃ ┗ 📜MenuItem.stories.js
 ┃ ┣ 📂ProductContainer
 ┃ ┃ ┣ 📜index.js
 ┃ ┃ ┣ 📜ProductContainer.jsx
 ┃ ┃ ┗ 📜ProductContainer.stories.js
 ┃ ┣ 📂ProductDetail
 ┃ ┃ ┣ 📂__tests__
 ┃ ┃ ┣ 📜index.js
 ┃ ┃ ┣ 📜ProductDetail.jsx
 ┃ ┃ ┗ 📜ProductDetail.stories.js
 ┃ ┣ 📂ProductItem
 ┃ ┃ ┣ 📜index.js
 ┃ ┃ ┣ 📜ProductItem.jsx
 ┃ ┃ ┗ 📜ProductItem.stories.js
 ┃ ┣ 📂QuantityInput
 ┃ ┃ ┣ 📜index.js
 ┃ ┃ ┣ 📜QuantityInput.jsx
 ┃ ┃ ┗ 📜QuantityInput.stories.js
 ┃ ┣ 📂Skeleton
 ┃ ┃ ┣ 📜index.js
 ┃ ┃ ┣ 📜Skeleton.jsx
 ┃ ┃ ┗ 📜Skeleton.stories.js
 ┃ ┣ 📂SkeletonList
 ┃ ┃ ┣ 📜index.js
 ┃ ┃ ┣ 📜SkeletonList.jsx
 ┃ ┃ ┗ 📜SkeletonList.stories.js
 ┃ ┣ 📂TitleHeader
 ┃ ┃ ┣ 📜index.js
 ┃ ┃ ┣ 📜TitleHeader.jsx
 ┃ ┃ ┗ 📜TitleHeader.stories.js
 ┃ ┗ 📜Layout.jsx
 ┣ 📂constants
 ┃ ┗ 📜path.js
 ┣ 📂hooks
 ┃ ┣ 📂shared
 ┃ ┃ ┣ 📜useDelete.js
 ┃ ┃ ┣ 📜usePatch.js
 ┃ ┃ ┣ 📜usePost.js
 ┃ ┃ ┗ 📜useReduxState.js
 ┃ ┣ 📜useGetCartList.js
 ┃ ┣ 📜useGetOrderList.js
 ┃ ┣ 📜useGetProduct.js
 ┃ ┗ 📜useGetProductList.js
 ┣ 📂mocks
 ┃ ┣ 📜handlers.js
 ┃ ┗ 📜worker.js
 ┣ 📂pages
 ┃ ┣ 📂Cart
 ┃ ┃ ┣ 📜Cart.jsx
 ┃ ┃ ┗ 📜index.js
 ┃ ┣ 📂NotFound
 ┃ ┃ ┣ 📜index.js
 ┃ ┃ ┗ 📜NotFound.jsx
 ┃ ┣ 📂Order
 ┃ ┃ ┣ 📜index.js
 ┃ ┃ ┗ 📜Order.jsx
 ┃ ┣ 📂Product
 ┃ ┃ ┣ 📜index.js
 ┃ ┃ ┗ 📜Product.jsx
 ┃ ┣ 📂ProductList
 ┃ ┃ ┣ 📜index.js
 ┃ ┃ ┗ 📜ProductList.jsx
 ┃ ┗ 📜index.js
 ┣ 📂reducers
 ┃ ┣ 📂cartList
 ┃ ┃ ┣ 📂__tests__
 ┃ ┃ ┃ ┣ 📜cartListReducer.test.js
 ┃ ┃ ┃ ┗ 📜cartListThunk.test.js
 ┃ ┃ ┣ 📜cartList.actions.js
 ┃ ┃ ┣ 📜cartList.reducer.js
 ┃ ┃ ┗ 📜cartList.thunks.js
 ┃ ┣ 📂orderList
 ┃ ┃ ┣ 📂__tests__
 ┃ ┃ ┃ ┣ 📜orderListReducer.test.js
 ┃ ┃ ┃ ┗ 📜orderListThunk.test.js
 ┃ ┃ ┣ 📜orderList.actions.js
 ┃ ┃ ┣ 📜orderList.reducer.js
 ┃ ┃ ┗ 📜orderList.thunks.js
 ┃ ┣ 📂product
 ┃ ┃ ┣ 📂__tests__
 ┃ ┃ ┃ ┣ 📜productReducer.test.js
 ┃ ┃ ┃ ┗ 📜productThunk.test.js
 ┃ ┃ ┣ 📜product.actions.js
 ┃ ┃ ┣ 📜product.reducer.js
 ┃ ┃ ┗ 📜product.thunks.js
 ┃ ┣ 📂productList
 ┃ ┃ ┣ 📂__tests__
 ┃ ┃ ┃ ┣ 📜productListReducer.test.js
 ┃ ┃ ┃ ┗ 📜productListThunk.test.js
 ┃ ┃ ┣ 📜productList.actions.js
 ┃ ┃ ┣ 📜productList.reducer.js
 ┃ ┃ ┗ 📜productList.thunks.js
 ┃ ┗ 📜rootReducer.js
 ┣ 📂store
 ┃ ┗ 📜configureStore.js
 ┣ 📂styles
 ┃ ┣ 📜GlobalStyle.js
 ┃ ┗ 📜ThemeStyle.js
 ┣ 📂utils
 ┃ ┣ 📜apiClient.js
 ┃ ┗ 📜comma.js
 ┣ 📜App.js
 ┣ 📜fixture.js
 ┗ 📜index.js
```

2022-05-22 23:51 UTC, inwalter99 requested changes
코드 잘 봤습니다 :)
리덕스나 컴포넌트 분리 및 관리는 어느정도 이해를 바탕으로 잘하고 계신 것 같아요 👍
대신 사소한 부분들을 몇몇 놓치고 계신 것 같아 코멘트 드렸습니다. 
그리고 `usePost`, `usePatch`, `useProduct` 등 마르코 만의 고민들이 담긴 결과물들이 있어 흥미롭게 코드를 봤습니다. 이 과정에서 한 고민들 나눠주셔서 감사하고, 제 생각을 따로 코멘트로 남기겠습니다!

고생하셨습니다 :)

2022-05-22 23:51 UTC, inwalter99 commented on src/components/CartItem/CartItem.jsx
> +    await getCartList();
`getCartList` 가 `promise` 를 반환하나용?
```suggestion
    getCartList();
```

2022-05-22 23:51 UTC, inwalter99 commented on src/reducers/product/__tests__/productReducer.test.js
> +    ).toEqual(expectedProduct);
테스트를 작성하는 방법 중 하나로 when-given-then 패턴이 있는데요, https://kchanguk.tistory.com/40
꽤 자주 쓰고, 개인적으로 테스트 코드를 읽을 때 확실히 의도를 드러낼 수 있다고 생각하기 때문에 한 번 차용해보는 것도 좋을 것 같습니다 :)

2022-05-22 23:51 UTC, inwalter99 commented on src/pages/Cart/Cart.jsx
> +    setTotalPrice(totalPrice);
컴포넌트 내에서 계산한 값을 바로 사용하는 것과 어떤 차이가 있을까용?

const checkedItemList = ~~~
const totalPrice = ~~~

2022-05-22 23:58 UTC, inwalter99 commented
> 변경된 데이터를 상태에 저장(POST, PATCH, DELETE)하는 경우, 리덕스가 아닌 API에만 저장했습니다. 그리고 리덕스는 API에서 데이터를 GET할 때 thunk와 함께 사용했습니다. 왜냐하면 데이터가 변경된 경우 API에 저장한 후 API에서 리덕스로 상태를 다시 가져와도 괜찮겠다고 생각했기 때문입니다. 그래서 커스텀훅으로 usePost, usePatch, useDelete를 만들어 관련 로직에 사용하였습니다. 이와 같은 접근 방식에 
> 예상되는 문제점이나 다른 적절한 대안은 무엇이 있는지 궁금합니다.

`리덕스가 아닌 API에만 저장했습니다.`  라는 말이 잘 이해가 가지 않네요ㅠ 제가 이해한 걸로는 현재의 상태를 변경시키는 `API` 로직은 따로 상태를 직접 수정하지 않고 `API` 후 다시 `GET` 요청을 통해 데이터를 최신화시킨다고 이해를 해봤습니다. 개인적으로 나쁜 접근은 아니라고 생각합니다 :) 다만 만들어주신 `usePost` 를 제외하고 `usePatch`, `useDelete` 는 범용성이 떨어지는 것 같아요. 그냥 `API` 콜을 하기 위해 커스텀 훅을 하나 만든 느낌입니다. 차라리 공통 `useApi` 을 만들어 `method`, `data`, `params` 등 주입받아도 문제 없지 않을까 생각해봅니다.

하나 예상되는 문제점은 우리가 스토어를 사용하는 이유와 연관된 문제인데요, 주로 `props drilling` 을 피하기 위해서 사용하는데, `usePost` 같은 훅에서 나온 결과값이나 상태, 에러 등을 여러 곳에서 사용해야한다면 로직이 스토어로 이동할 것 같고 일관성이 깨지게 되어 오히려 혼란이 가중될 것 같다는 생각도 드네요 :); 그외엔 모두 좋습니다 :) 

참고로 `react-query,` `rtk query`, `swr` 등을 찾아보시면 좋을 것 같아요 :) 질문에 대한 답을 또는 또 다른 인사이트를 얻으실 수도 있을 것 같습니다.

2022-05-23 00:03 UTC, inwalter99 commented
> 커스텀훅에서도 뭔가 조금 더 공용으로 쓰는 훅이 있고, 그렇지 못하고 특정 페이지에서 주로 사용되는 훅이 생겼습니다. 그래서 제 편의상 조금 더 알아보기 쉽게 hooks 폴더 내에 shared 폴더를 만들어 그 안에 조금 더 공용적인 훅들을 이동시켰습니다. 이렇게 하는 방식에 대해서 어떻게 생각하시나요? 그리고 월터님께서 커스텀훅을 조금 더 효율적으로 관리하는 방법에는 무엇이 있는지 궁금합니다.

저는 완전 좋습니다!  `useReduxState`, `useProduct` 등으로 래핑했기 때문에 나중에 리덕스 대신 다른 걸 좀 더 쉽게 변경할 수 있지 않을까라는 기대도 됩니다.
그리고 커스텀훅이라고 하면 너무 방대한 개념이라... 지금처럼 데이터를 핸들링하는 훅이 있을 수도 있고, 모달을 제어하는 훅이 있을 수도 있고 해서 어떻게 해야 효율적으로 관리해야하는 지는 좀 어려운 질문 같습니다.

2022-05-23 00:03 UTC, inwalter99 commented
> msw에서 기존의 json-server의 api와는 정확히 같지는 않지만 제 프로젝트에서는 조금 더 편리한 방식으로 모킹했습니다. 그런데 msw 핸들러 내에 이러한 로직을 담는 것이 적절할 지 의문입니다. 또는 그냥 로직 없이 mock data만 반환하도록 하는 것이 나을까요?

복잡한 로직이 아니라 단순히 생성,수정,삭제를 하기 위해 로직이 껴있고 mock 이 휘발성만 가진다면 괜찮다고 생각합니다 ;)

2022-05-23 01:25 UTC, wonsss commented on package.json
> +    "detect-node": "^2.1.0",
필요 없는 패키지입니다. 지운다는 걸 깜박했네요ㅠ

2022-05-23 03:06 UTC, wonsss commented on package.json
> +    "@testing-library/user-event": "^13.5.0",
좋은 질문 주셔서 감사합니다.
이번 기회에 검색해 본 결과, 다음과 같은 내용을 알게 됐습니다.

우선 `dependencies`와 `devDependencies`는 다음과 같은 차이점이 있습니다.
 `dependencies`는 앱 로직과 연관되므로 런타임에도 계속 쓰일 필요가 있어 배포할 때 포함됩니다. 그러나 `devDependencies`는 앱 로직과 직접적 연관은 없고 로컬 개발 및 테스트할 때만 필요하여 배포할 때 포함되지 않습니다. 이렇게 구분해서 설치해야 빌드시간도 줄이고 배포할 때 불필요한 라이브러리를 포함시키지 않을 것입니다. 테스트 라이브러리 또한 로컬에서 개발할 때만 사용하므로, `devDependencies`에 포함되는 것이 적절합니다.
> 참고 [npm](https://docs.npmjs.com/specifying-dependencies-and-devdependencies-in-a-package-json-file)

그런데 create-react-app을 이용해서 시작하면 "@testing-library` 등 모든 라이브러리가  처음부터 `dependencies`에 추가되어 있어서 의문이 들었습니다. 검색해보니, Dan이 CRA Github 이슈에서 다음과 같이 답변을 했었네요. 

<img width="919" alt="스크린샷 2022-05-23 오전 11 17 14" src="https://user-images.githubusercontent.com/59413128/169730969-d1718eb2-6ba9-4d9c-93d8-ff33cf6bcf21.png">

> "Node 앱이면 런타임에 배포되므로 `dependencies`와 `devDependencies`를 나누는 것이 의미있습니다. 따라서`devDependencies`를 배포하고 싶지 않을 수 있습니다.
CRA의 경우, 결과물이 static build입니다. 그래서 모든 `dependencies`는 `devDependencies`입니다. 심지어 React 등 라이브러리도 마찬가지입니다. 이것들은 모두 빌드할 때에만 사용됩니다. 
그러나 모든 것을 `build dependencies`에 넣는 것은 서버에 첫 배포 시 몇몇의 배포 스크립트들에 문제가 있을 수 있습니다. 그래서 대신에 모든 것을 `regular dependencies`에 넣는 것이 더 쉬운 선택이었습니다." - DAN-

즉, CRA에서는 항상 번들링하여 배포하므로 Node 앱과 달리, 항상 모든 dependency 라이브러리가 사용되어 `dependencies`와 `devDependencies`의 구분이 의미 없다는 말인 것 같습니다.😱  

구분에 의미가 없다는 말이 사실인지 확인하기 위해, `dependencies`에 있는 라이브러리들을 모두 `devDependencies`로 옮긴 후 배포해봤는데, 사이트는 전과 같이 잘 동작하는 것을 확인했습니다. 

그런데 제가 잘못 이해한 건지, 다음과 같은 의문이 계속 남습니다. 검색해봐도 원하는 답을 얻기가 힘드네요. 혹시 월터님의 의견은 어떠신지 궁금합니다.
- 그런데 CRA가 왜 Node 앱이 아닌 건가요? 
- 그렇다면 CRA에서는 dependecy를 구분할 필요가 있을까요?
- CRA를 사용하지 않고 직접 설정한 React 프로젝트의 경우에는 CRA와 달리 dependency를 구분해줘야 할까요?

> 참고 [해당 이슈](https://github.com/facebook/create-react-app/issues/6180)

2022-05-24 07:23 UTC, wonsss commented on src/App.js
> +            <Route path="/" element={<ProductList />} />
넵 ! PATH.ROOT라는 이름으로 상수화했습니다 :)

2022-05-24 07:27 UTC, wonsss commented on src/components/CartOrder/CartOrder.jsx
> +    navigate('/order');
넵 수정했습니다. :)

2022-05-24 07:27 UTC, wonsss commented on src/components/CartPopup/CartPopup.jsx
> +      <Styled.CartLink to="/cart">장바구니로 가기</Styled.CartLink>
ㅎㅎ 깜박했었네요. 상수 관련된 부분 다 같이 수정했습니다. 꼼꼼히 봐주셔서 감사합니다.
[refactor: 경로 상수화](https://github.com/woowacourse/react-shopping-cart/pull/116/commits/47a139b4074cba5aba9cffdbc9fe8ce326bbf45e)

2022-05-24 07:38 UTC, wonsss commented on src/hooks/shared/useDelete.js
> +      });
ㅎㅎㅎ앗 그렇네요. 의도한 건 아니고 깜박했습니다. 알려주셔서 감사해요!
async/await로 통일했습니다.
[refactor: promise를 async await 문법으로 통일](https://github.com/woowacourse/react-shopping-cart/pull/116/commits/ad4cce6adef609b3fbf24dad1d7b34d72d1355ea)

2022-05-24 11:17 UTC, wonsss commented on src/hooks/useGetCartList.js
> +  };
넵. 맞아요.. 혼란스럽네용 😵 💫  일단 해당 훅들을 다 비슷하게 수정해봤어요. 아래에 [리뷰 주신 내용](https://github.com/woowacourse/react-shopping-cart/pull/116#discussion_r878937048)에 댓글 단 커밋에 포함되는 수정사항입니다. 아래 커밋처럼 수정하는 건 어떨까요? 혹시 제안해주실 방향 있으시면 말씀 부탁드려요! 😄 

[refactor: useEffect를 커스텀훅에서 추출하여 컴포넌트로 이동](https://github.com/woowacourse/react-shopping-cart/pull/116/commits/2d067d9f5d7497db3e2eb47fdd369d35dca17d20)
[refactor: 비슷한 커스텀훅의 로직 통일](https://github.com/woowacourse/react-shopping-cart/pull/116/commits/d9cef17ed57821cafe96e4a121f292ec189f6d6e)

2022-05-24 12:45 UTC, wonsss commented on src/components/CartTable/CartTable.jsx
> +    await getCartList();
좋은 질문 감사합니다! 
forEach가 callback들을 비동기로 실행하기 때문에 현재처럼 await를 붙이는 것은 기대하는 대로 동작하지 않네요!!
만약  의도대로 동작하게 하려면, promise.all을 사용해야 할 것 같아요. 
[fix : forEach에 잘못 붙인 await를 promise.all로 변경](https://github.com/woowacourse/react-shopping-cart/pull/116/commits/8832f7d5c15bb569b0b01438a7e5a5630455b439)

2022-05-24 13:02 UTC, wonsss commented on src/hooks/useGetOrderList.js
> +  };
헉 ㅠㅠ 이건 아무리 고민해도 잘 모르겠습니다. 지금 잘 되고 있는 것 같아서요. 어떻게 수정하면 좋을지 힌트 주실 수 있으실까요?

2022-05-25 10:38 UTC, wonsss commented on src/components/CartItem/CartItem.jsx
> +    await getCartList();
`getCartList()`를 콘솔로그로 찍어보니까  pending인 promise가 반환됨을 확인했습니다. 
하지만 이 handleDeleteButton에서 getCartList가 마지막에 호출되니까 굳이 await할 필요는 없을 것 같습니다.
혹시 제가 잘못 이해했을까용..? 그렇다면, 질문해주신 내용 관련하여 더 자세한 설명 부탁드려도 괜찮을까요? 😄

2022-05-25 11:27 UTC, wonsss commented on src/reducers/cartList/__tests__/cartListThunk.test.js
> +  afterAll(() => server.close());
안내해주신 링크의 코드와 제 코드를 비교해보고 차이가 있는 부분을 수정해봤습니다.
혹시 이 외에 개선할 부분이 더 있을까요? 😄 

[fix: msw setupTest에서 리턴 대신 함수 실행](https://github.com/woowacourse/react-shopping-cart/pull/116/commits/021b23fa50019d56b92aeedbd788ca27348f65bf)

2022-05-25 11:44 UTC, wonsss commented on src/fixture.js
> +export const mockProductList = [
`asset/mock 에 있는 목데이터`는 msw가 모킹할 때 사용하는 데이터로 썼습니다. 그리고 나중에 테스트코드를 작성하면서 여러 목데이터가 필요하여 테스트코드만을 위해 fixture를 추가로 만들었습니다. 두 파일 모두 미리 만들어둔 더미 데이터라는 면에서 같으며 productList라는 더미데이터를 같이 갖고 있기도 합니다. 따라서 하나의 파일로 합치는 게 좋을까요?

2022-05-25 14:32 UTC, inwalter99 requested changes
수고하셨습니다 마르코!
머지하고 싶지만, 아직 서로 이해가 다른 부분이 있어..토론을 좀 더 하시죠ㅎ 😏
디펜던시는 내일 아침에 맑은 정신으로 제 의견 써보겠습니다!! 기다리실까봐(?) 먼저 작성드립니다.
코멘트 확인부탁드려요!

2022-05-25 14:32 UTC, inwalter99 commented on src/hooks/useGetOrderList.js
> +  };
`getOrderList` 가 동기적으로 작동하는 걸 기대하고 작성하신 것 같은데요.. 
`dispatch` 가 `promise` 를 반환하나요? 제가 보기엔 불필요한 `await` 인것 같은데.. @.@

2022-05-25 14:32 UTC, inwalter99 commented on src/components/CartItem/CartItem.jsx
> +    await getCartList();
https://github.com/woowacourse/react-shopping-cart/pull/116/files#diff-0b2547716375601cff7f0470f07888023053a3bacc0b8c311868c40753d9a25fR7-R9 를 먼저 봐야할 것 같아요 :)
`getCartList`가 `async` 로 작성되어있으니까 promise 를 반환하는 건 맞는데, `getCartList` 내부를 보면 의도대로 동작할 진 의문이네요..! (await dispatch....?! await getCartList() 만 보면 동기로 동작할 것 같은데 사실은 아니..)

2022-05-25 14:32 UTC, inwalter99 commented on src/reducers/cartList/__tests__/cartListThunk.test.js
> +  afterAll(() => server.close());
앗,, https://create-react-app.dev/docs/running-tests/#initializing-test-environment msw 를 초기화하는 과정이 중복되니 setUpTests.js 를 만들어 작성하라는 뜻이었습니다 ;) + https://mswjs.io/docs/getting-started/integrate/node

2022-05-25 14:32 UTC, inwalter99 commented on package.json
> +    "@testing-library/user-event": "^13.5.0",
저 요건 내일 아침에 다시 작성해드리곘습니다! 😴

2022-05-26 06:25 UTC, wonsss commented on src/hooks/useGetOrderList.js
> +  };
앗.  애초에 getOrderList 함수를 불필요하게 async로 만들었기 때문에 promise를 반환한다고 착각했었네요. async await를 아래 커밋처럼 불필요한 곳에서는 떼어냈을 때, getOrderList 다음에 확인용 콘솔로그 메시지를 작성하고, MSW에서 orderList를 get하는 메서드에 delay를 주더라도, 순서대로 실행완료되는 것을 확인했어요. 따라서 getOrderList는 await가 없더라도 동기적으로 작동하는 코드였네요. 제가 이해한 부분을 잘 설명하진 못한 것 같은데, 월터님 덕분에 잘 이해하게 된 것 같아요!!  감사합니다 🙇  😄 

[refactor: promise가 아닌 값에 불필요하게 준 await 제거](https://github.com/woowacourse/react-shopping-cart/pull/116/commits/9f8e571fc0ee3d7fc0c8328f63927b304fe34013)

2022-05-26 06:27 UTC, wonsss commented on src/components/CartItem/CartItem.jsx
> +    await getCartList();
https://github.com/woowacourse/react-shopping-cart/pull/116#discussion_r882355241

위에서 주신 리뷰와 동일한 맥락인 것 같아서 해당 답변 붙여드려요.
감사합니다!

2022-05-26 06:44 UTC, wonsss commented on src/reducers/cartList/__tests__/cartListThunk.test.js
> +  afterAll(() => server.close());
자세한 설명 감사합니다! 이해했어요! 👍 중복되는 초기화 과정을 setupTests.js에 작성하여 리팩토링했습니다. 테스트 통과 확인했습니다.

[refactor: 테스트 시 공통 MSW api mocking을 setupTests에 설정](https://github.com/woowacourse/react-shopping-cart/pull/116/commits/c40249c61e1692c9b79a5455d9c48c3c73c8ff3e)

2022-05-26 06:45 UTC, wonsss commented
> 앗,, [create-react-app.dev/docs/running-tests/#initializing-test-environment](https://create-react-app.dev/docs/running-tests/#initializing-test-environment) msw 를 초기화하는 과정이 중복되니 setUpTests.js 를 만들어 작성하라는 뜻이었습니다 ;) + [mswjs.io/docs/getting-started/integrate/node](https://mswjs.io/docs/getting-started/integrate/node)

자세한 설명 감사합니다! 이해했어요! 👍 중복되는 초기화 과정을 setupTests.js에 작성하여 리팩토링했습니다. 테스트 통과 확인했습니다.

[refactor: 테스트 시 공통 MSW api mocking을 setupTests에 설정](https://github.com/woowacourse/react-shopping-cart/pull/116/commits/c40249c61e1692c9b79a5455d9c48c3c73c8ff3e)

2022-05-27 15:02 UTC, inwalter99 commented on package.json
> +    "@testing-library/user-event": "^13.5.0",
> 내일 아침이... 죄송합니다... 우테코 방문해서라도 사죄드리고 싶네요ㅜㅜ

먼저, 내용에 대해서 이해를 해주신 게 맞습니다?
별도로 `그렇다면 웹팩으로 번들링되는 react에서는 dependecy와 devDependecy를 구분할 필요가 있을까요? 단순히 다른 개발자들과 더 나은 커뮤니케이션을 하기 위해 구분하는 걸까요?` 요것에 대해 궁금증을 품으신 거라고 이해를 했습니다!

저는 그럼에도 나누어 작성해야한다고 생각하는데요. 리액트만 개발하면 문제 없겠지만, 다른 것들도 개발하게 될 일이 많기 때문에, 동일하게 관리해야 좋다고 생각하고, dependencies 도 다른 패키지들이 업데이트되고, 어떤 것들은 업데이트되지 않으면서 발목을 잡을 때가 있는데 그때의 관리차원에서라도 분리시키는 게 좋지 않나?라는 생각을 갖고 있습니다!

https://github.com/vercel/next.js/discussions/14000 요것도 한 번 읽어보세요~~

2022-05-27 15:03 UTC, inwalter99 approved these changes
마지막까지 코드 잘 반영해주셔서 감사합니다 :) 
2단계 머지하도록 하겠습니다!

2022-05-27 15:03 UTC, merged