[2단계 - 장바구니] 우연(전연지) 미션 제출합니다.
woowacourse/react-shopping-cart pull request #138
Opened 2022-05-23 08:10 UTC by ronci

아사님! 2단계 기능구현 완료했습니다!
이번에도 피드백 잘 부탁드립니다!

# 기능 구현 목록

- [x] 장바구니 페이지
  - [x] 전체 선택 체크박스
    - [x] '전체 선택' 체크박스를 눌렀을 때
      - [x] 장바구니에 있는 모든 상품이 선택된다.
      - [x] '전체 선택' 텍스트가 '선택 해제'로 바뀐다.
    - [x] '선택 해제' 체크박스를 눌렀을 때
      - [x] 장바구니에 있는 모든 상품 선택이 해제된다.
      - [x] '선택 해제' 텍스트가 '전체 선택'로 바뀐다.
  - [x] 상품 삭제 버튼
    - [x] 선택된 상품 개수와 함께 삭제할지 사용자에게 확인한다.
    - [x] 사용자가 삭제 확인을 했을 때 선택된 상품이 장바구니에서 제거된다.
  - [x] 배송 상품
    - [x] 배송 상품 뒤에 장바구니에 있는 상품들의 개수를 출력한다.
    - [x] 버튼을 눌렀을 때 상품 개수를 바꿀 수 있다.
      - [x] 최소 상품개수는 1개이다.
    - [x] 쓰레기통 버튼을 눌렀을 때 사용자에게 상품의 이름과 함께 삭제할지 사용자에게 확인한다.
  - [x] 결제 예상 금액
    - [x] 선택된 상품들의 총 가격을 출력한다.
    - [x] 주문하기와 선택된 상품들의 개수를 함께 출력한다.
- [x] 단위 테스트
- [x] MSW를 활용해 API Mocking

2022-05-23 16:51 UTC, EungyuCho reviewed
오늘 추가적으로 더 달겠습니다 🙏 
늦어져서 죄송합니다 😢

2022-05-23 16:51 UTC, EungyuCho commented on react-shopping-cart/src/components/PaymentAmountContainer/PaymentAmountContainer.component.jsx
> +  }, [data, orderList, shoppingCart]);
해당 컴포넌트에서 결제예상금액의 총 금액을 어떻게 산출하는지 알 필요가 있을까요?
훅으로 빼도 무방하겠다고 생각이 들었어요 🤔

2022-05-23 16:51 UTC, EungyuCho commented on react-shopping-cart/src/components/@shared/BorderBox/BorderBox.component.jsx
> +const BorderBox = styled.div`
FlexBox와 BorderBox를 분리해주신 이유가 있을까요? 👀

2022-05-24 02:00 UTC, ronci commented
아사님 질문이 있습니다!
제가 이번에 `Suspense`의 필요성을 느껴서 `Suspense`를 사용해보려고 했습니다!
그래서 다음과 같이 구현하려고 했습니다.
```jsx
function ShoppingCartList() {
  const { data } = useFetch(`${process.env.REACT_APP_API_HOST}/product`);
    return ( 
      <Suspense fallback={<Loading />}>
        {/* code */}
	  <ShoppingCartListContainer data={data} />
        {/* code */}
    </Suspense>
  );
}
```
하지만 `Suspense`가 작동되지 않는 문제가 있었습니다…
다양하게 도전해봤지만 원하는 동작이 되지않아서 고민입니다ㅠ

혹시 어떻게 해야할지 힌트 하나 얻을 수 있을까요..?

2022-05-24 15:45 UTC, EungyuCho commented
> 아사님 질문이 있습니다! 제가 이번에 `Suspense`의 필요성을 느껴서 `Suspense`를 사용해보려고 했습니다! 그래서 다음과 같이 구현하려고 했습니다.
> 
> ```js
> function ShoppingCartList() {
>   const { data } = useFetch(`${process.env.REACT_APP_API_HOST}/product`);
>     return ( 
>       <Suspense fallback={<Loading />}>
>         {/* code */}
> 	  <ShoppingCartListContainer data={data} />
>         {/* code */}
>     </Suspense>
>   );
> }
> ```
> 
> 하지만 `Suspense`가 작동되지 않는 문제가 있었습니다… 다양하게 도전해봤지만 원하는 동작이 되지않아서 고민입니다ㅠ
> 
> 혹시 어떻게 해야할지 힌트 하나 얻을 수 있을까요..?

요게.. Data fetching 로직을 suspense 관련 [인터페이스](https://velog.io/@imnotmoon/React-Suspense-ErrorBoundary-%EC%A7%81%EC%A0%91-%EB%A7%8C%EB%93%A4%EA%B8%B0)로 구현해줘야해요 ㅜ

2022-05-24 17:54 UTC, EungyuCho requested changes
안녕하세요 우연님! 
코멘트 몇가지 남겨드렸는데 확인 부탁드릴게요 🙂 

reducer 테스트 코드가 조금 더 있으면 좋겠어요! 여유가 되신다면 우연님이 생각하시는 유의미한 테스트 코드가 무엇일지 생각해보고 추가해봅시다!~

스텝 2 작성하시느라 고생하셨어요!

2022-05-24 17:54 UTC, EungyuCho commented on react-shopping-cart/src/__tests__/shoppingCartAction.test.jsx
> +});
해당 테스트파일에서 얻을 수 있는 점은 무엇인지 궁금해요!

2022-05-24 17:54 UTC, EungyuCho commented on react-shopping-cart/src/pages/ShoppingCartList/ShoppingCartList.page.jsx
> +      });
deleteItem이 filter를 사용하는걸로 알고있는데 forEach를 순회를 돌면서 매번 filter로 걸러주는게 좋은 방법인지 잘 모르겠어요 🤔

2022-05-24 17:54 UTC, EungyuCho commented on react-shopping-cart/src/mocks/handlers.js
> +    res(ctx.status(202, 'Mocked status'), ctx.json([...products]))
202가 의도하신걸까요? 😮

2022-05-24 17:54 UTC, EungyuCho commented on react-shopping-cart/src/components/ShoppingCartListItem/ShoppingCartListItem.component.jsx
> +    }
```suggestion
    const toggleItem = checked ? deleteSpecificItem : addSpecificItem;
    
    dispatch(toggleItem(id));
```
삼항 연산자를 활용하면 어떨까요~?

2022-05-24 17:54 UTC, EungyuCho commented on react-shopping-cart/src/components/Header/Header.component.jsx
> +    <HeaderContainer as="header">
HeaderContainer 자체로 header 태그인게 더 자연스러워 보이는데요 😢 
FlexBox를 재활용 하는 편이 더 깔끔하다고 생각하실까요?

2022-05-25 07:33 UTC, ronci commented on react-shopping-cart/src/pages/ShoppingCartList/ShoppingCartList.page.jsx
> +  const checked = orderList.length === shoppingCart.length;
장바구니에 담은 상품이 없을때 아예 disabled되도록 수정했습니다! [7a39f20](https://github.com/woowacourse/react-shopping-cart/pull/138/commits/7a39f205fc2adf85c886ff1aa50a0dc068d529ac)
추가적으로 삭제버튼도 삭제할 상품이 없을때 alert로 사용자에게 알려줄 수 있도록 수정했습니다! [4c50496](https://github.com/woowacourse/react-shopping-cart/pull/138/commits/4c5049676cd46f7cd6fda70731773921322e2243)

2022-05-25 07:37 UTC, ronci commented on react-shopping-cart/src/components/PaymentAmountContainer/PaymentAmountContainer.component.jsx
> +  }, [data, orderList, shoppingCart]);
로직을 분리하는 것이 좋을 것 같아 util함수로 분리하였습니다! [77d8031](https://github.com/woowacourse/react-shopping-cart/pull/138/commits/77d80318f38e377d41e778e8dfd753b78214fb49)

분리하다보니 한가지 고민을 하게 되었습니다.

현재 분리된 함수에서는 data, shoppingList, orderList를 인자로 받고 있습니다.
그러면서 다음 두가지 선택지가 있었습니다.
1. shoppingList, orderList를 함수내부에서 부른다
     - shoppingList와 orderList는 밖에서 useSelector로 가져와서 바로 대입하는 형태이기 때문에 따로 밖에서 할 필요가 없다.
2. shoppingList, orderList를 인자로 받는다.
    - 좀 더 확장성이나 재사용성이 높아질 수 있다.
    - 함수에서 데이터 접근하는 것이 좋은 방법인지 모르겠다.

저는 2번째의 장점이 1번째보다 더 크고 중요하다 생각하여 2번째처럼 구현한 상태입니다!
    
아사님 생각은 어떠신지 여쭤볼 수 있을까요??

2022-05-25 07:53 UTC, ronci commented on react-shopping-cart/src/components/@shared/BorderBox/BorderBox.component.jsx
> +const BorderBox = styled.div`
FlexBox는 간단히 flex로 화면 레이아웃을 구현하기 위해 만든 컴포넌트입니다!
그래서 FlexBox에는 flex와 관련된 옵션들을 추가해놓았습니다.

BorderBox의 경우 div내부에 내용들이 필수적으로 들어가있기때문에
 font와 관련된 옵션을 추가해놓았습니다.

그래서 FlexBox와 BorderBox와는 사용하는 역할이 조금 다르다고 생각하여 따로 분리했습니다!

2022-05-25 07:59 UTC, ronci commented on react-shopping-cart/src/components/ShoppingCartListContainer/ShoppingCartListContainer.component.jsx
> +    `}
border-bottom의 경우 1px로 고정되어있지만,

magin-bottom의 경우 많이 달라질 수 있는 값이라고 생각하여 
margin을 관리할때는 다음과 같이 쓰는 것으로 컨벤션을 설정하였습니다!

2022-05-25 08:20 UTC, ronci commented on react-shopping-cart/src/__tests__/shoppingCartAction.test.jsx
> +});
장바구니 담기 버튼을 눌렀을 때 원하는 액션이 일어나는 지 확인할 수 있는 점인것같습니다.

하지만 현재 코드에서 dispatch가 바로 있어서 큰 테스트의 이점은 없는 것 같긴합니다...💦

나중에 협업 쪽으로 가면 server로 원하는 데이터를 잘 보냈는 지 확인하는 것은 필요할 것 같습니다!

2022-05-25 08:32 UTC, ronci commented on react-shopping-cart/src/pages/ShoppingCartList/ShoppingCartList.page.jsx
> +      });
id배열을 넣으면 배열안에 있는 id들을 삭제하는 액션을 추가해서 수정했습니다! [86bde54](https://github.com/woowacourse/react-shopping-cart/pull/138/commits/86bde545ad55852a16869c691a812fac8d210b89)

2022-05-25 08:38 UTC, ronci commented on react-shopping-cart/src/mocks/handlers.js
> +    res(ctx.status(202, 'Mocked status'), ctx.json([...products]))
앗 200으로 수정했습니다! [1c93bef](https://github.com/woowacourse/react-shopping-cart/pull/138/commits/1c93bef02fcf1ecd248056815203664e061f6742)

2022-05-25 08:40 UTC, ronci commented on react-shopping-cart/src/components/ShoppingCartListItem/ShoppingCartListItem.component.jsx
> +    }
좋은 것 같습니다!! 수정했습니다! [6b65a2d](https://github.com/woowacourse/react-shopping-cart/pull/138/commits/6b65a2d36375631e99f5df08c53a5e9c4f1f5c14)

2022-05-25 08:58 UTC, ronci commented on react-shopping-cart/src/components/Header/Header.component.jsx
> +    <HeaderContainer as="header">
HeaderContainer에서 Flex를 사용해야해서 FlexBox를 이용하고 as로 태그를 재활용하면 괜찮을 것 같아서 다음과 같이 구현했었습니다..!

이런 경우 처음부터 header tag로 구현하고 flex로 추가로 옵션을 주는 것이 좋을까요??

2022-05-26 08:52 UTC, ronci commented
| reducer 테스트 코드가 조금 더 있으면 좋겠어요! 여유가 되신다면 우연님이 생각하시는 유의미한 테스트 코드가 무엇일지 생각해보고 추가해봅시다!~

추가적으로 액션이 일어났을 때 원하는 값으로 바뀌는 지 확인하는 테스트를 추가했습니다! [44c59a4](https://github.com/woowacourse/react-shopping-cart/pull/138/commits/44c59a499a545f334098f16ffa4136f572ebcff0)
추가한 테스트의 경우, 값을 관리하는 중요한 로직이기 때문이기 때문에 테스트가 필요하다고 생각했습니다!

제가 생각하는 유의미한 테스트는
값을 관리하거나 어떤 액션이 일어나는 것을 명시적으로 확인하기 어려울 때 테스트가 유의미하다고 생각합니다!
또는 필수적인 기능들을 테스트로 만들어서 리팩토링할 때 잘 돌아가는 지 확인하는 것도 유의미한 테스트라고 생각합니다!

혹시 아사님이 생각하시는 유의미한 테스트에 대한 의견도 들어볼 수 있을까요??

2022-05-27 05:41 UTC, EungyuCho commented on react-shopping-cart/src/components/PaymentAmountContainer/PaymentAmountContainer.component.jsx
> +  }, [data, orderList, shoppingCart]);
요건 관점의 차이일수도 있다고 느껴지는데요~

데이터의 구조가 완전히 같지 않으면 재활용하기 어려운 데이터다보니 애매하다고 느껴졌어요.

calculatePrice의 인자로 data, shoppingCar, orderList를 지정해주셨는데

사용하는 컴포넌트의 입장에서는 해당 인자의 네이밍이 모호하다고 생각해요. 결국 내부 구조를 들여다 봐야만 재사용할 수 있는 로직이고 내부 로직도 전부 절차적이라.. 만약 해당 훅을 재활용하게 된다면 변경사항에 많이 취약한 구조가 된다고 생각이 드는데요.

재활용과 확장성을 고려하신다면 내부 데이터를 조금 더 명시적으로 표현하고 데이터의 변경에 대한 부분을 훅을 호출하는 컴포넌트가 결정하는게 유연하게 가져갈 수 있는 방법이라고 생각해요.
그게 불가능하다면 1번이 낫다고 판단하여 1번 방향으로 바꾸면 좋겠다는 뉘앙스를 가진 코멘트를 달았었어요 😅

2022-05-27 05:42 UTC, EungyuCho commented on react-shopping-cart/src/components/@shared/BorderBox/BorderBox.component.jsx
> +const BorderBox = styled.div`
내용이 들어가있는 기준이었군요~ 조금 헷갈리긴 하지만 컨벤션이라면 오케입니당 🙆‍♂️

2022-05-27 05:58 UTC, EungyuCho commented on react-shopping-cart/src/components/Header/Header.component.jsx
> +    <HeaderContainer as="header">
Container라는 네이밍이 들어가다보니 애매하게 느껴지는 것 같은데요.. 🤔 
문득 든 생각인데 해당 컴포넌트 navigation아닌가용?..

2022-05-27 06:04 UTC, EungyuCho commented
> 혹시 아사님이 생각하시는 유의미한 테스트에 대한 의견도 들어볼 수 있을까요??

과정으로서는 **좋은 코드를 찾아가는 과정** 결과로는 **인터렉션에 대해 원하는 동작을 보장할 수 있는 테스트**라고 생각해요.
테스트를 작성하면서 사용하기 어려운 형태로 작성하고 있지 않은지 검증하고 좋은 인터페이스로 변경해볼 수 있는 수단이라고 생각하고, 결과로는 화면의 상태가 원하는 의도대로 변경이 이루어지는지 그리고 말씀하신대로 변경사항에 의해 사이드 이펙트가 없는지 검증할 수 있어야한다고 생각해요.

2022-05-27 18:08 UTC, EungyuCho approved these changes
우연님 안녕하세요~

피드백 잘 반영해주셨네요 감사합니다 ㅎㅎ
충분한 것 같아요 Approve 하겠습니다!

추가로 질문주신 부분에 대해서는 답변을 남겨드렸는데 머지후에도 궁금하신점이 있다면 편하게 질문해주세요 🙂

2022-05-27 18:08 UTC, merged

2022-05-28 10:13 UTC, ronci commented on react-shopping-cart/src/components/Header/Header.component.jsx
> +    <HeaderContainer as="header">
이 때 제목이랑 로고 등이 포함되어있다는 점에서 `header`태그를 사용하였습니다!
그리고 현재 장바구니랑 주문목록만 `nav`로 표시하고 있습니다.


아사님의 말씀을 들어보니 전체가 navigation인 것도 맞는 것 같습니다!
그렇지만 저는 header에 현재 link요소들만 들어있는 것이고 현재 컴포넌트는 `header`가 더 잘 어울리지 않을까 생각했습니다...!


그리고 `nav`같은 경우 다음과 같이 공식문서에 적혀있었습니다.
> 문서의 모든 링크가 `nav` 요소 안에 있을 필요는 없습니다. `nav` 요소는 주요 탐색 링크 블록을 위한 요소입니다.

title의 경우도 현재 링크로 연결되어있기 때문에 `nav`속으로 넣어야할까요?? 
지금 제 생각은 장바구니와 주문목록같은 경우 다른 페이지로 연결하기 위한 링크이지만 title같은 경우는 `nav`바깥으로 빼는 것이 더 자연스럽지 않을까 생각합니다..!


또한 추가적으로 찾아보니 다음과 같은 내용을 알 수 있었습니다!
> 스크린 리더 등 장애를 가진 사용자를 위한 사용자 에이전트는 최초 렌더링에서 탐색 전용 콘텐츠를 제외할지 결정할 때 `nav`를 참고합니다.

이때 title이 nav안으로 들어가면 탐색 전용 콘텐츠를 제외한 사용자는 title을 모르는 문제가 발생할 수 있지 않을까요??

<br>
고민한 내용들을 적을려고 하니 주절주절 적게되는것 같네요.

시멘틱하게 코드를 짜려고 하니 답이 정해져있지 않은 것 같아서 여러 방향으로 고민하게 되는 것 같습니다..!
혹시 제 고민에 대한 아사님의 의견 들을 수 있다면 감사하겠습니다!! 🙇‍♀️

2022-05-28 11:14 UTC, EungyuCho commented on react-shopping-cart/src/components/Header/Header.component.jsx
> +    <HeaderContainer as="header">
음.. 아래에 별도로 nav 태그를 as로 넣어두셨네요!
nav 태그가 아예 없는 줄 알고 단 코멘트였어요 🙏 

> title의 경우도 현재 링크로 연결되어있기 때문에 nav속으로 넣어야할까요??

별도로 분리해도 무방하다고 생각합니다~ 
굳이 nav 태그 안에 들어갈 필요성은 없을 것 같아요. (있어도 무방할 것 같기도하고... 이 부분은 알쏭달쏭하네요.. airbnb는 현재 우연님이 작성하신 방식처럼 되어있어요 적어주신 `탐색 전용 콘텐츠를 제외한 사용자는 title을 모르는 문제가 발생할 수 있지 않을까요`요 맥락에서 제외했을 수도 있겠네요.. 😇 )

> 시멘틱하게 코드를 짜려고 하니 답이 정해져있지 않은 것 같아서 여러 방향으로 고민하게 되는 것 같습니다..!

리액트로 넘어오면서 이러한 부분에 소홀해지는 경우가 많은데 대단하신 것 같아요. 👏 👏