[장바구니 미션 Step 1] 헤다(윤다혜) 미션 제출합니다
woowacourse/react-shopping-cart pull request #174
Opened 2023-05-11 08:23 UTC by Dahyeeee

안녕하세요 티케! 만나서 반갑습니다~~ 저는 헤다라고 합니다. 🤗🤗
이번 미션은 노아이즈 @n0eyes  와 함께 했습니다. 똑똑한 크루라 제가 많이 배우면서 진행했습니다. 
제 닉네임은 본명을 뒤집어서 만들었는데 티케의 닉네임은 뜻이 있나요? 궁금하네요! 

[배포페이지](https://dahyeeee.github.io/react-shopping-cart/) [스토리북](https://dahyeeee.github.io/react-shopping-cart/storybook/?path=/docs/example-productitem--docs)
**❗제 github-page 배포는 특이하게 구글에서 보이지 않습니다 ㅠㅠ 다른 브라우저에서 열어서 확인해주세요**

이번 미션은 장바구니 미션의 step1으로 비교적 기능이 적은 미션이었습니다.
요구사항은 (제 언어로 정리하자면)
1. recoil로 상태관리하기
2. 상품을 장바구니에 담으면 장바구니 아이콘 숫자가 변경되기
3. mockData로 상품목록 구현하되 향후 api통신 고려해서 작성하기

였습니다. 

### 시도하고 노력한 점
1. recoil로 cart와 products의 상태를 관리하며 필요한 곳에서 불러 사용했는데 정말 편하고 좋았습니다.
2. 에러 핸들링에 신경썼습니다. 실제 api 통신이 이뤄지고 있지는 않지만 api 통신이 실패했을 때 상황을 대비해 리액트의 errorBoundary를 활용했습니다. 404처럼 에러 페이지로 처리해줘야할 때와 특정 컴포넌트에서( 장바구니 아이콘) 에러가 발생했을 때를 나눠서 처리해줬습니다. 컴포넌트에서 에러가 발생했을 때는 해당 컴포넌트에서 fallback 컴포넌트를 보여줄 수 있게 해줬습니다.
3. Button 컴포넌트를 확장성있게 만들었습니다. step2와 협업에서도 계속 가져다가 쓸 수 있게 크기, 테마를 Props로 받아 다양한 버튼이 만들어지게 했습니다. 이번 스텝에서는 아이템 모달 창의 stepper로 쓰였습니다. 

### 어렵고 아쉬웠던 점
1. 로딩시 스켈레톤을 적용해보고 싶은데 아직 못했습니다! 리팩토링하며 시도해보고 싶습니다.
2. 이번 미션에서 스토리북을 잘 써보고 싶은 욕심이 있었는데 스토리북의 유용성을 많이 느낄 수 있는 컴포넌트가 없다고 생각됐습니다. 그래서 버튼과 제품아이템(ProductItem)만 CDD로 만들었습니다. 
개인적으로 스토리북의 유용성은 재사용과 커스텀이 가능한 컴포넌트를 테스트하고 개발하는 데 있다고 생각되는데, 
티케는 어느정도까지 스토리북을 활용하시는지 궁금합니다. 

### 모달
- 카트 아이콘을 누르면 등장하는 모달창 ( ItemCartDialog.tsx )은 페어인 노아이즈가 이전 미션에서 npm에 배포한 직접 만든 라이브러리입니다. 이왕 만든 모달 창을 활용해보면 좋을 것 같아서 제가 만든 모달보다 커스텀하기 좋은 노아이즈 모달을 이용했습니다. 저도 npm 문서와 페어의 설명을 들으며 모달 사용법을 숙지했고 이해하고 사용했습니다. 

갑자기 좀 뜬금없는 코드가 있어서 당황스러우실까봐 말씀드립니다!  

소소한 리뷰도 열심히 고민하고 재밌게 소통하고 싶습니다. 티케 앞으로 2주간 잘 부탁드립니다. 🥰

2023-05-13 16:23 UTC, devhyun637 requested changes
안녕하세요 헤다~ 티케입니다!
리뷰가 늦어져서 죄송해요 ㅠ.ㅠ

미션에 많은 요구사항이 있는 건 아니라서, 사소한 부분에 집중해서 피드백을 드렸습니다.
리코일에 대해서는 조금 더 공부가 필요해서 다음 리뷰에는 상태관리를 어떻게 했는지 전체적인 측면에서 보면서 피드백을 하도록 노력해볼게용

### 의견 & 질문
> 1️⃣ 에러 핸들링에 신경썼습니다. 실제 api 통신이 이뤄지고 있지는 않지만 api 통신이 실패했을 때 상황을 대비해 리액트의 errorBoundary를 활용했습니다. 404처럼 에러 페이지로 처리해줘야할 때와 특정 컴포넌트에서( 장바구니 아이콘) 에러가 발생했을 때를 나눠서 처리해줬습니다. 컴포넌트에서 에러가 발생했을 때는 해당 컴포넌트에서 fallback 컴포넌트를 보여줄 수 있게 해줬습니다.

`ErrorBoundary`와 `Suspense`를 활용한 부분이 인상적인데요! 두 컴포넌트의 역할은 다른데 왜 조합을 했는지 이유가 궁금해요 :) 또 에러핸들링에 신경을 썼다고 하는게 ErrorBoundary를 썼다고해서 에러핸들링을 신경썼다고 할 수 있을까요? 

> 2️⃣ Button 컴포넌트를 확장성있게 만들었습니다. step2와 협업에서도 계속 가져다가 쓸 수 있게 크기, 테마를 Props로 받아 다양한 버튼이 만들어지게 했습니다. 이번 스텝에서는 아이템 모달 창의 stepper로 쓰였습니다.

오 공통 컴포넌트를 확정성있게 만드는 시도를 했다는 것이 멋있네요! 다만, `type="button"`은 `button`의 기본 타입은 `submit`이라고 생각하는 누군가에겐(실제로 default는 submit임), 이 부분이 원하지 않은 동작으로 이어질 것 같아서, 주석을 추가해주거나 수정하는 게 좋을 것 같아요.

또 매우 좋은 부분을 언급해주셨는데 Step2와 협업에서도 가져다 쓴다고 하셨는데 만약에, 계속 누군가가 내가 만든 공통 컴포넌트를 사용하려면 어떤 것이 더 필요할까요? 매번 어떻게 사용하는지, 필수 props은 무엇인지, 스토리북으로 들어가거나 직접 구현부를 봐야하는 것일까요?

> 3️⃣ 개인적으로 스토리북의 유용성은 재사용과 커스텀이 가능한 컴포넌트를 테스트하고 개발하는 데 있다고 생각되는데, 티케는 어느정도까지 스토리북을 활용하시는지 궁금합니다.

디자인시스템을 만들때는 만든 컴포넌트에 대한 가이드를 다른 개발자에게 주기 위해서 스토리북을 만들어 사용하였습니다. 하지만, 지금은 서비스를 담당하고 있어서 딱히 스토리북을 활용하지는 않아요. 스토리북을 어떻게 활용하는지에 따라서 유용하다고 느끼는 부분이 달라질 것 같은데 '컴포넌트를 테스트한다.'는 어떤 의미를 가지는 걸까용?

2023-05-13 16:23 UTC, devhyun637 commented on src/components/common/Button/Button.styles.tsx
> +  view: 'white' | 'black';
값들을 보면 너무 color 프로퍼티를 위한 것 같아요. 
값의 명칭을 수정하거나, 프로퍼티명을 변경해야할 것 같아요~

2023-05-13 16:23 UTC, devhyun637 commented on src/components/common/Button/Button.styles.tsx
> +          border: 1px solid #bbbbbb;
```suggestion
          border: 1px solid #bbb;
```

도 가능합니다

2023-05-13 16:23 UTC, devhyun637 commented on src/components/common/ErrorBoundary/ErrorBoundary.tsx
> +    return <Suspense fallback={loadingFallback}>{children}</Suspense>;
`Suspense`를 `ErrorBoundary`에 포함한 이유가 있을까요?

2023-05-13 16:23 UTC, devhyun637 commented on src/components/common/Header/Header.styles.tsx
> +`;
`Title`인데 `div`인 이유가 있을까요?

2023-05-13 16:23 UTC, devhyun637 commented on src/components/common/Header/Header.tsx
> +          </ErrorBoundary>
`<CartBadge />`는 왜 에러바운더리로 감싼걸까용 ?.?

2023-05-13 16:23 UTC, devhyun637 commented on src/components/common/Layout/Layout.tsx
> +export const Content = () => {
두 컴포넌트가 함께 있는 이유를 알 수 있을까용?

2023-05-13 16:23 UTC, devhyun637 commented on src/components/common/PageTitle/PageTitle.styles.tsx
> +`;
`PageTitle`의 제목이 `div`라..

2023-05-13 16:23 UTC, devhyun637 commented on src/components/common/QuantityStepper/QuantityStepper.tsx
> +        </Button>
버튼, 아이콘에 대한 아무런 설명이 없는 건 별로 좋지 않습니다. 왜그럴까요?

2023-05-13 16:23 UTC, devhyun637 commented on src/pages/ErrorPage/ErrorPage.tsx
> +      <S.LinkToHome to="/">Home으로 돌아가기</S.LinkToHome>
왜 상수로 만든걸 사용하지 않은걸까요?

2023-05-13 16:23 UTC, devhyun637 commented on src/pages/ProductPage/ProductPage.tsx
> +    <ErrorBoundary errorFallback={<h1>list error...</h1>}>
여긴 왜 `ErrorPage`를 활용하지 않은 것일까요?

2023-05-15 14:24 UTC, Dahyeeee commented on .eslintcache
8c56da8709ee3bb000731f54f237f74e6833d178

2023-05-15 14:25 UTC, Dahyeeee commented on .gitignore
8c56da8709ee3bb000731f54f237f74e6833d178

오..네 생각없이 그냥 CRA이 설정해주는 대로 쓰고 있었네요 😓

2023-05-15 14:26 UTC, Dahyeeee commented on .storybook/main.ts
> +  stories: ["../src/**/*.mdx", "../src/**/*.stories.@(js|jsx|ts|tsx)"],
헤헤 아니여.. f628dc3e5fedf9ad2f0ab72daa2978296d2bb0f4

2023-05-15 14:35 UTC, Dahyeeee commented on package.json
`devDependencies`는 개발환경에서 필요한 라이브러리고 런타임이나 실제 프로덕션 코드에서는 필요없는(?) 친구들이 들어간다고 알고 있습니다! CRA에서 어떤 식으로 이뤄졌는지 몰랐는데 이번 기회에 눈여겨 보았네요. CRA 사용시 유념해서 불필요한 라이브러리(typescript관련 등)가 dependencies에 들어가지 않게 해야겠네요.

2023-05-15 14:36 UTC, Dahyeeee commented on public/data/mockCart.json
> +  "cart": []
앗, fetch로 가져와지는 확인하기 위한 용도로만 만들었습니다. 처음 상태에서는 장바구니에 아무것도 없는게 예상한 행동이 맞습니다.

2023-05-15 14:37 UTC, Dahyeeee commented on public/index.html
> +<html lang="en">
f628dc3e5fedf9ad2f0ab72daa2978296d2bb0f4

한글로 바꾸는 습관이 안들어있네요! 앞으로는 프로젝트 시작부터!!

2023-05-15 14:38 UTC, Dahyeeee commented on src/Router.tsx
> +    <BrowserRouter basename={process.env.PUBLIC_URL}>
`create-browser-route`가 최신문법에 추가된 것을 힐긋 봤는데 개인적으로 직관적이지 않은 것 같아 `BrowserRouter`를 대신 사용했습니다. 
올려주신 공식문서를 보니 `ceate-browser-router`를 사용하길 권고하는 이유가 분명하고 장점이 명확해서 수정했습니다~!

2023-05-15 14:40 UTC, Dahyeeee commented on src/apis/cart.ts
> +};
f57bf421aeba8e2203bf9d474aa2050dd185f638

에러처리를 조금 편협하게 생각하고 처리한 것 같네요. 🥲 try, catch문으로 에러 잡아서 throw 하도록 했습니다! 
에러처리가 좀 어렵게 느껴지는데 좀더 고민하면서 발전시켜 가겠습니다.

2023-05-15 14:45 UTC, Dahyeeee commented on src/apis/index.ts
> +  baseURL: '.',
7819493c5fefaeb16313111dda4da79d8a6208d4

2023-05-15 14:47 UTC, Dahyeeee commented on src/components/ProductPage/ItemCartDialog/ItemCartDialog.tsx
> +      <Dialog.Trigger asChild>
children으로 들어오는 컴포넌트를 Trigger로 사용할 수 있게 해주는 property입니다!

이 모달창은 item이 랜더링 될 때 무조건 같이 item 수에 맞춘 모달이 랜더링 되어야 하는 방식이 맘에 들지 않아서 
자체 모달을 만들고 카트 버튼을 눌러서 모달을 열 때만 랜더링 되도록 수정했습니다!

2023-05-15 14:47 UTC, Dahyeeee commented on src/components/ProductPage/ItemCartDialog/ItemCartDialog.tsx
> +          <S.CartImg alt="cart" src={SHOPPING_CART} />
acd0db632524cabed3cf4d31c518a7c7a6805da8

기능구현과 설계에 집중하다보면 이런 부분을 쉽게 놓치는 것 같네요. 감사합니다 티케!

2023-05-15 14:48 UTC, Dahyeeee commented on src/components/ProductPage/ItemCartDialog/ItemCartDialog.tsx
> +    </Dialog>
91573922dd44c9f676eba8513f4f72bc2971cfa0

취소하기 버튼도 만들었습니다!

2023-05-15 14:52 UTC, Dahyeeee commented on src/components/ProductPage/ProductItem/ProductItem.stories.tsx
허허.. 리스트에 들어가면 리스트의 스타일에 맞춰서 작아져서 고려하지 못했네요. 수정했습니다! 

4a21779fdd5b91063de852ccdc46f9ca4f850d69

2023-05-15 14:53 UTC, Dahyeeee commented on src/components/common/Button/Button.stories.tsx
> +export const Size_SS: Story = {
min-width 로 수정해서 글 길이 만큼 길어지게 했습니다! 
300111a5309dc829856a86947d1bf1514910017a

2023-05-15 14:54 UTC, Dahyeeee commented on src/components/common/Button/Button.styles.tsx
> +  view: 'white' | 'black';
theme으로 하고 싶었는데 style-component에서 사용하려고 하니 예약어라 사용이 안되서 네이밍이 굉장히 어려웠습니다..ㅎㅎ 값을 'dark'와 'light'로 변경해주었습니다! 
b228fe01543ed3a5eee5fbae702ec64102946169

2023-05-15 14:55 UTC, Dahyeeee commented on src/components/common/Header/Header.styles.tsx
> +`;
시멘틱 태그..!! 1c2484767fe33b4b388e7ab64fc74f09fd1c098d

2023-05-15 14:59 UTC, Dahyeeee commented on src/components/common/Header/Header.tsx
> +          </ErrorBoundary>
cart 목록이 api로 들어온다고 생각했고, 그 값을 기반으로 cartBadge에 숫자를 표시해줄 수 있도록 코드를 작성했습니다.
만약 cart에 대한 api 통신이 실패했을 때 전체 페이지가 오류나는 게 아니라 badge에 숫자 표시를 안해주는 상황을 생각해서 ErrorBoundary에서 에러가 잡혔을 때 null을 반환하는 에러처리(아닌 에러처리를) 했습니다. 

사용자나 다른 개발자가 이해할 만한 접근이었을까요...? 🤔

2023-05-15 15:01 UTC, Dahyeeee commented on src/components/common/Layout/Layout.tsx
> +export const Content = () => {
요기는 좀 급하게 작성하다보니 저도 다시 보니 뭐지 싶네요 ^^;;;;
`createBrowserRouter`로 마이그레이션 하면서 두 코드를 합쳤습니다. pageTitle이 필요없는 페이지가 있을 거 같아서 분리했는데 지금으로서는 모든 페이지에 필요해보여서 합쳐서 Layout으로 내보냈습니다. 

f57bf421aeba8e2203bf9d474aa2050dd185f638

2023-05-15 15:03 UTC, Dahyeeee commented on src/components/common/QuantityStepper/QuantityStepper.tsx
> +        </Button>
웹접근성..! 이건 버튼은 정말 설명이 없다면 screen reader가 읽었을 때 뭐하는 녀석인지 알 수가 없겠네요.
[arial-label](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-label) 읽고 적용했습니다! 
1c2484767fe33b4b388e7ab64fc74f09fd1c098d

2023-05-15 15:06 UTC, Dahyeeee commented on src/pages/ErrorPage/ErrorPage.tsx
> +      <S.LinkToHome to="/">Home으로 돌아가기</S.LinkToHome>
앗! 티케가 말해주셔서 인지했습니다. 
Cart같은 라우트 명이 있는게 아니라서 너무 자연스럽게 '/'를 썼네요. 😓

e3cbd84cb51b272ce69fff0bd4562a27fe03a6a3

2023-05-15 15:11 UTC, Dahyeeee commented on src/components/common/ErrorBoundary/ErrorBoundary.tsx
> +    return <Suspense fallback={loadingFallback}>{children}</Suspense>;
`ErrorBoundary` 와 `Suspense` 둘 다 비동기통신시 발생할 상황과 연관되어 있어서 `Suspense`를 `ErrorBoudary`로 감싼 컴포넌트를 만들었습니다. 티케의 질문을 보고 생각해보니 `error`라고 했을 때 비동기 통신 오류뿐 아니라 컴파일 에러, 구문 에러 등 다양한 에러가 발생할 수 있다는 걸 떠올렸습니다. 미션을 진행할 때는 오류가 비동기 통신 중에 발생한다고만 한정해 생각해서 이런 설계가 나왔네요.

둘을 분리시키고, 비동기 통신시에 `ErrorBoundary` 와 `Suspense` 를 드러나게 사용해  ‘비동기 통신이 일어나는 컴포넌트’라는 걸 좀 더 명시적으로 알 수 있게 해줬습니다.

f57bf421aeba8e2203bf9d474aa2050dd185f638 
(요 커밋에 여러가지가 섞여 있네요 ㅠㅠㅠ 다음부터는 새분화해서 커밋하도록 하겠습니다!)

2023-05-15 15:14 UTC, Dahyeeee commented on src/pages/ProductPage/ProductPage.tsx
> +    <ErrorBoundary errorFallback={<h1>list error...</h1>}>
`ErrorPage`는 404같은 큰에러(?)에 적용하고 컴포넌트단의 에러는 해당 컴포넌트를 대체하는 형식으로 설계하려고 했습니다. 
그래서 지금은 404페이지 에러와, `ProductPage` 에러는 router단에서 `errorElement`에 넣어줬습니다.
`ErrorBoundary`를 컴포넌트 단위 에러를 잡는데 사용해줬습니다. 

f57bf421aeba8e2203bf9d474aa2050dd185f638

2023-05-15 15:28 UTC, Dahyeeee commented
티케! 정성스러운 코드리뷰 감사합니다! 
놓치고 있는 부분들을 알 수 있어서 좋았고 에러처리 등 고민할 지점들이 생겨서 의미있었습니다. 

> 오 공통 컴포넌트를 확정성있게 만드는 시도를 했다는 것이 멋있네요! 다만, `type="button"`은 `button`의 기본 타입은 `submit`이라고 생각하는 누군가에겐(실제로 default는 submit임), 이 부분이 원하지 않은 동작으로 이어질 것 같아서, 주석을 추가해주거나 수정하는 게 좋을 것 같아요.
> 또 매우 좋은 부분을 언급해주셨는데 Step2와 협업에서도 가져다 쓴다고 하셨는데 만약에, 계속 누군가가 내가 만든 공통 컴포넌트를 사용하려면 어떤 것이 더 필요할까요? 매번 어떻게 사용하는지, 필수 props은 무엇인지, 스토리북으로 들어가거나 직접 구현부를 봐야하는 것일까요?

 오, 버튼의 타입을 생각해보지 못했네요. 기본 타입을 ‘submit’으로 주고 type을 props로 받아 사용하는 쪽에서 버튼의 타입을 정할 수도 있게 해주면 좋을 것 같네요!

오호.. 누군가 제가 만든 버튼을 사용하려 한다면 저는 당연히 스토리북과 구현부를 봐야한다고 생각했는데 그런 수고로움을 좀 덜 수 있다면 좋겠네요. 일단 가능한 가장 흔하게 쓰이는 기본값을 명확하게 줘서 props를 덜 받거나 없이 가져다 쓸 수 있는 것도 방법일 거 같습니다.

> 스토리북을 어떻게 활용하는지에 따라서 유용하다고 느끼는 부분이 달라질 것 같은데 '컴포넌트를 테스트한다.'는 어떤 의미를 가지는 걸까용?

 실제 서버를 돌리기 전에 컴포넌트만 만들어서 UI적으로 확인하는 것과 컴포넌트의 프롭스에 따른 형태변화 등을 전부 하나씩 코드로 작성하지 않고 확인해 볼 수 있다는 점이 테스트라고 생각했고 유용하다고 느꼈습니다!

---

### **recoil selector**

![image](https://github.com/woowacourse/react-shopping-cart/assets/102305630/866177e2-d41a-4506-9340-e2053ecbaa19)


### **커스텀훅**

![image](https://github.com/woowacourse/react-shopping-cart/assets/102305630/2db5219a-391b-4108-ace8-7187e948fe16)

recoil에서 상태를 받아와서 커스텀훅으로 빼줬는데 그랬더니 recoil에서 쓸 수 있던 selector가 의미가 없어졌습니다.
예를 들어 `카트 배열`을 상태를 atom으로 관리하면서 selector로 카드배열을 가져와 카드배열의 길이를 반환해주는 selector의 역할을 그냥 커스텀 훅 안에서 함수로 해줄 수 있었습니다.
전역상태관리 라이브러리의 장점을 잘 못사용하는 것인가... 싶은데 `recoil`을 안쓰신다면 질문이 이해가 안가실 수 있을 것 같습니다! 혹시 별다른 생각이 없으시다면 이 질문은 그냥 넘기셔도 됩니다!

2023-05-17 23:18 UTC, devhyun637 commented on .eslintcache
등록은 했는데, 기존 파일은 그대로 git에 남아있네용?.?

2023-05-17 23:19 UTC, devhyun637 commented on package.json
CRA에서 이 두가지를 어떻게 다루는지에 대해서도 알아보시면 좋을 것 같아요. 또 `package.json`은 제가 알려드린 것 말고도 script 등 중요한 부분이 많으니 한번 뜯어보시면서 각각이 어떤걸 의미하는지 알아두면 좋아요

2023-05-17 23:20 UTC, devhyun637 commented on public/data/mockCart.json
> +  "cart": []
앗 그러면 이친구는 mockCart가 아니라, 그냥 cart가 아닐까요?

2023-05-17 23:20 UTC, devhyun637 commented on src/Router.tsx
> +    <BrowserRouter basename={process.env.PUBLIC_URL}>
권고하는 이유가 무엇인가요?

2023-05-17 23:22 UTC, devhyun637 commented on src/apis/cart.ts
> +};
아 그런 경우라면 주석을 달아두면 좋을 것 같아요~

2023-05-17 23:29 UTC, devhyun637 commented on src/components/common/QuantityStepper/QuantityStepper.tsx
> +        </Button>
`aria-label `왜 갑자기 영어가..!

2023-05-17 23:51 UTC, devhyun637 commented on src/components/ProductPage/ItemCartDialog/index.tsx
> +            initialValue={1}
이 프로퍼티에서 오류메세지 뜨던데 확인해주세요~

2023-05-17 23:51 UTC, devhyun637 commented on package.json
> +    "react-tiny-dialog": "^0.2.15",
이제 안쓰이니 삭제가 필요하겠죠?

2023-05-17 23:51 UTC, devhyun637 commented on src/components/common/Header/Header.tsx
> +          </ErrorBoundary>
오호 헤다의 말을 들으니 왜 ErrorBoundary를 감쌌는지 이해를 했습니다!

다만, "badge에 숫자 표시를 안해주는 상황"을 오류로 감쌀 필요가 있는지?에 대해서 고민을 해보면 좋을 것 같아요. 장바구니의 수량을 보여주지 않는 것이 서비스 이용에 있어서 어느정도 영향을 미칠까요? (지금은 fallback도 전달해주지 않아서 바로 터질것같은데 맞을까요?)

2023-05-17 23:54 UTC, devhyun637 approved these changes
안녕하세요 헤다~ 티케입니다.
리뷰가 늦어서 죄송합니다ㅠㅠ 꼼꼼하게 피드백 반영을 해주시고 의견도 표현해주셨군요! ❤️

새롭게 만드신 `Modal`도 이유가 분명해서 좋았습니다. 추후에는 이전 미션에서 만든 헤다가 배포한 `Modal`을 적용해보아도 좋을 것 같아요~ (궁금궁금) 몇몇 부분에서 `husky`가 왜 못잡았지? 하는 부분이 있어서 아주 살짝의 코멘트를 달아두었습니다. 다음 단계까지 보완해주시면 좋을 것 같아요! 또 남겨주신 의견에 대해서도 다시 궁금한 점이 있어서 코멘트 남겼는데 이 부분도 확인해주세요! 

다음 Step은 좀 더 빠른 리뷰를 하도록 하겠습니다 🙇‍♀️🙇‍♀️

2023-05-17 23:55 UTC, merged