[장바구니 미션 Step 1] 우스(김영길) 미션 제출합니다.
woowacourse/react-shopping-cart pull request #175
Opened 2023-05-11 08:26 UTC by Gilpop8663

안녕하세요 카일 !  닉네임 우스라고 합니다!

이번 장바구니 미션을 패트릭과 함께 구현했습니다. 반갑습니다 😀👍

## <a href="https://gilpop8663.github.io/react-shopping-cart/">사이트 바로 가기</a>
## <a href="https://gilpop8663.github.io/react-shopping-cart/storybook/">스토리북 바로 가기</a>

## 신경을 써서 구현한 점

1. 환경 설정을 프로젝트 초기에 하고자 했습니다. (절대 경로, import/order, 자동 배포 설정, styled-component의 글로벌 설정, 스토리북 설정 등)

환경 설정을 프로젝트 후반부에 바꾸게 되었을 경우 불편함을 느꼈기 때문입니다. 프로젝트 후반에 바꾸면 모든 상대 경로를 절대 경로로 바꾸는 과정을 거쳐야하는데 이러한 과정을 생략할 수 있어서 좋았습니다. 

2. 폴더 구조

폴더를 컴포넌트 파일과 스토리 북 관련있는 컴포넌트를 가까이 모아둠으로써 유지 보수 쉽도록 의도 하였습니다. 

3. 함수를 분리하여 재 사용 가능한 함수는 utils로 이동시키고, 재 사용이 어려운 함수는 사용하는 함수 가까이에 위치하도록 하였습니다.

4. 테스팅 도구로 스토리북을 선택했습니다.

전의 리엑트 페이먼츠에서 컴포넌트 주도 개발을 하였을 때 컴포넌트 UI를 구현하면서 빠른 피드백을 받을 수 있어 무척 좋았던 기억에 다시 한번 스토리북을 선택했습니다. 이번에도 컴포넌트 주도 개발을 하니 하나를 구현할 때 컴포넌트를 나눠야 할지 안 나눠야 할지 미리 이야기하고 만들 수 있어서 좋았습니다. 상호 작용 테스트도 스토리북을 통해 원하는 스토리를 나타낼 수 있다는 점이 매력적이라고 생각하고 있습니다.

## 구현을 못한 점/아쉬운 점

1. storybook에서 상호작용 테스트를 했으나 배포 과정에서 상호작용이 되지 않는 오류가 났습니다. 상호 작용 테스트가 되지 않습니다.
2. 잘못된 작동을 막기 위해 flag 사용 및 eslint를 통한 useEffect 의 DependencyList에서 권장하는 설정을 무시하는 주석을 추가한 점이 아쉽습니다. 

리뷰해주셔서 감사합니다 카일!

2023-05-12 12:28 UTC, GwangYeol-Im requested changes
안녕하세요 우스~ 미션 구현하시느라 고생 많으셨습니다 ㅎㅎ 앱을 사용해보았을 때 장바구니에 추가된 상품들이 새로고침 시 초기화되어 상태가 따로 저장되지 않는 것이 아쉽네요 😅 이외에 상세한 부분들은 코멘트 확인 부탁드립니다~!

2023-05-12 12:28 UTC, GwangYeol-Im commented on public/logo192.png
CRA init 시 프로젝트 내에서 사용하지 않는 보일러 플레이트들은 정리해주시면 좋을 것 같습니다 😂

2023-05-14 11:17 UTC, Gilpop8663 commented on src/utils/common.ts
> +  isNotError: boolean,
코드 가독성 측면에서 isNotError을 사용하면서 얻는 이점만 생각했습니다.  !isNotError의 경우는 생각하지 못했어서 새로운 시각을 알려주셔서 감사합니다 카일 👍👍

2023-05-14 11:17 UTC, Gilpop8663 commented on src/utils/common.ts
> +export const isNotNumber = (text: string) => {
그렇네요!! 빌트인 된 자체적인 함수를 사용해서 동일한 결과가 나온다면 빌트인 된 함수를 사용하는 것이 더 낫다고 느껴집니다. 👍👍

2023-05-16 09:56 UTC, Gilpop8663 commented
안녕하세요 카일 새로고침까지 구현을 했으나 수량 조절하는 것이 너무 어렵더라구요. 계속 붙잡고 있으면 시간이 많이 지날 것 같아 여기까지 하고 코드 리뷰 받으려고 합니다. 상세하게 리뷰 해주셔서 감사합니다 !

2023-05-17 11:53 UTC, GwangYeol-Im commented on src/recoil/selectors/cartSelector.ts
> +export const cartItemLengthSelector = selector({
넵, 위의 Number 빌트인 객체에 달았던 리뷰와 같은 맥락으로 보면 좋을 것 같아요. 어떤 방법론을 택할 때는 항상 pros and cons가 있다고 생각하는데 장점이 단점을 상쇄할만큼 명확한 이유가 없다면 다른 방법이 있지는 않을지, 혹은 현재 생각하는 방향이 오버 엔지니어링이 아닐지 고려해보시면 좋겠습니다. ㅎㅎ

2023-05-17 11:59 UTC, GwangYeol-Im commented on src/components/ProductList/AddCartButton.tsx
> +  useEffect(() => {
오.. 의도했던 방향을 스스로 찾으신 것 같아 뿌듯하네요 👍 `useEffect`는 말 그대로 부수효과이기에, 이벤트 핸들러가 아닌 컴포넌트의 라이프 사이클에 따라 수행되어야 하는 동작이어야 할 때 사용하는 것이 적절할 듯 합니다. 작성해주신 `addProductToCart`, `removeProductFromCart`는 관련 이벤트 핸들러 내에서 호출하면 코드의 흐름이 더 간결해져 연관성을 파악하기 용이하고 현재와 같은 주석은 달지 않을 수 있을 듯 합니다.

2023-05-17 12:06 UTC, GwangYeol-Im approved these changes
안녕하세요 우스! 리뷰에 달아주신 코멘트를 확인해보았을 때 고민을 많이 하신 흔적이 보여 좋았네요 :) 스스로 좋은 방향을 계속 찾으시려고 하는 것 같아 인상 깊었습니다. 해당 단계는 이만 머지하고 다음 단계에서 뵙도록 할게요 😀

2023-05-17 12:06 UTC, merged