[장바구니 미션 Step 1] 요술토끼(김의천) 미션 제출합니다.
woowacourse/react-shopping-cart pull request #183
Opened 2023-05-11 08:39 UTC by wzrabbit

안녕하세요, 케빈! 처음 뵙겠습니다. 저는 [아인](https://github.com/geuntaek1013)과 함께 페어 프로그래밍을 진행한 요술토끼라고 합니다!

## 데모 페이지 ✨
[데모 페이지!](https://wzrabbit.github.io/react-shopping-cart/)

## 파일 구조 🌌
![구조](https://github.com/wzrabbit/boj-totamjung/assets/87642422/014378aa-aea6-41bd-a527-eb50a6b45657)

## Recoil
이번 미션에서는 `Recoil` 을 사용하라는 요구사항이 있었습니다!

##

2023-05-12 08:33 UTC, JeongBin0227 commented
<img width="372" alt="image" src="https://github.com/woowacourse/react-shopping-cart/assets/45503248/be2ef178-d253-4c74-821f-f49752f60388">
장바구니에 들어있는 상품이 실시간으로 반영되지 않는거 같은데 의도한 방식일까요? (스텝퍼에서 빈화면을 한번 눌러야지 반영됩니다)

2023-05-12 08:36 UTC, JeongBin0227 commented
현재 상품 담을것을 다 제거했을때, 장바구니 갯수에 영향을 안주는 버그가 있는거 같아요~

2023-05-12 08:36 UTC, JeongBin0227 commented
스토리북 주소도 같이 올려주시면 감사합니다!

2023-05-12 08:50 UTC, JeongBin0227 requested changes
안녕하세요 요술토끼~ 
만나서 반갑습니다 이번 미션 리뷰어를 맡게된 케빈입니다!

pr 에도 남겨주셨는데, Recoil 은 처음이고 시간이 충분하지 않아서 아직 다 구현이 덜 되신거 같아요.
지금까지 한 코드 위주로 코멘트 드렸고, 남은 시간 잘 마무리하셔서 다시 스텝1 pr 주시면 좋을거 같아요~

궁금한점 코멘트로 남겨드렸습니다~ 
장바구니 미션하느라 고생하셨습니다 💯

2023-05-12 08:50 UTC, JeongBin0227 commented on public/robots.txt
> +Disallow:
해당 파일은 public 안보다는 루트가 맞지 않을까요?

2023-05-12 08:50 UTC, JeongBin0227 commented on src/components/CartNotificationButton/CartNotificationButton.tsx
> +    <Button>
이렇게 스타일 태그가 공존하면, 해당 태그가 스타일 태그인지 컴포넌트 태그인지 구분하기 어려운 시점이 오는데 어떻게 해결하면 좋을까요?

2023-05-12 08:50 UTC, JeongBin0227 commented on src/components/Header/Header.tsx
> +  width: 49.98px;
헉 이런 소숫점 단위는 어떻게 해서 나오게 되었을까요?

2023-05-12 08:50 UTC, JeongBin0227 commented on src/components/ProductCard/ProductCard.tsx
> +}
ProductCard 타입같은 경우는 여러곳에서 재사용 될수 있어서 공통 타입으로 관리해보면 어떨까요?

2023-05-12 08:50 UTC, JeongBin0227 commented on src/components/ProductCard/ProductCard.tsx
> +  overflow: hidden;
이름이 왜 hidden 일까요?

2023-05-12 08:50 UTC, JeongBin0227 commented on src/components/ProductQuantityInput/ProductQuantityInput.tsx
> +export default ProductQuantityInput;
해당 컴포넌트는 쇼핑몰에서 상당히 다양하게 재사용되는 컴포넌트입니다. 그러다보니 좀더 유연하게 개발되어야하는데요. + 버튼이나 - 버튼을 누를때 step을 얼마나 갈건지, 아니면 더이상 갈수 없는 step 을 받아서 처리하는 구간이 있으면 좋을거같네요~

2023-05-12 08:50 UTC, JeongBin0227 commented on src/components/ProductQuantityInput/ProductQuantityInput.tsx
> +  };
해당 부분을 hook으로 나누어 처리해보면 어떨까요?

2023-05-12 08:50 UTC, JeongBin0227 commented on src/components/CartNotificationButton/CartNotificationButton.tsx
> +  background-color: #04c09e;
개인적으로 저는 이러한 색상이 16진법이 아닌 색상 공용 파일을 만들어서 네이밍으로 알려주면 다른 사람 코드 볼때 이 부분이 어떤부분인지 좀더 파악하기 쉽더라구요
요술토끼는 어떻게 생각하시나요?

2023-05-12 08:50 UTC, JeongBin0227 commented on src/components/ProductQuantityInput/ProductQuantityInput.tsx
> +    setCartProducts({ ...cartProducts, [productId]: Number(e.target.value) });
setCartProducts 함수를 호출할 때, 새로운 객체를 생성하여 상태를 업데이트하고 있습니다. 이렇게 하면 불필요한 객체 생성을 초래할 수 있고 성능에 영향을 줄 수 있어서
```
setCartProducts((prevCartProducts) => ({
    ...prevCartProducts,
    [productId]: Number(e.target.value),
  }));
```
이렇게 개선해보면 어떨까요?

2023-05-12 08:50 UTC, JeongBin0227 commented on src/react-app-env.d.ts
> +/// <reference types="react-scripts" />
해당 파일의 역할은 무엇일까요?

2023-05-12 08:50 UTC, JeongBin0227 commented on README.old.md
> +버그를 발견한다면, [Issues](https://github.com/woowacourse/react-shopping-cart/issues)에 등록해주세요.
old.md 는 불필요하다면 지워주시는게 좋을거같아요~

2023-05-12 12:40 UTC, wzrabbit commented on src/components/Header/Header.tsx
> +  width: 49.98px;
![엄격진지근엄](https://github.com/woowacourse/react-shopping-cart/assets/87642422/43907d0d-dd7b-4a2d-a743-184cf91ef4de)

ㅋㅋㅋ 이건 그냥 페어 프로그래밍을 할 때 재미로 figma 시안에 나온 길이를 정확히 맞춘겁니다!
`50px` 로 설정하면 레이아웃이 깨지거나 줄바꿈이 일어난다든가 그래서 미세하게 줄인 거 아닙니다!

...저 이상한 사람 아니에요

2023-05-12 12:44 UTC, wzrabbit commented on src/components/CartNotificationButton/CartNotificationButton.tsx
> +  background-color: #04c09e;
저도 같은 생각입니다! 이 부분은 아직 제가 styled-components에 익숙하지 않고, 시간도 부족해서 기능부터 구현하다보니 놓게 되어버렸습니다.
css의 색상코드를 그대로 두면 무슨 색상인지 파악하기 쉽지 않겠죠... 당연히 변수를 두고 의미를 부여하면 읽기 편한 코드가 되고 나중에 색상을 변경해야 할 때도 유지보수 측면에서 유리할 것이라고 생각합니다.

말씀하신 부분은 이런 방식과 비슷하게 개선해 보았습니다!
공용 파일을 만들고 색상 변수를 선언하는 것까지는 하지 않았지만, 매우 빈번하게 같은 색상이 사용되는 케이스에서는 당연히 사용할 것입니다!

```tsx
const colors = {
  pureWhite: "#fff",
  gold: "#ffdf7e",
  darkGray: "#222",
};
```
```tsx
const Title = styled.span`
  display: inline-block;
  width: 100px;
  height: 32px;
  color: ${colors.pureWhite};
  line-height: 32px;
  font-family: "Noto Sans KR";
  font-size: 22px;
`;

const Count = styled.span`
  display: inline-block;
  width: 25px;
  height: 25px;
  line-height: 25px;
  background-color: ${colors.gold};
  color: ${colors.darkGray};
  font-family: "Rubik";
  font-weight: 800;
  font-size: 16px;
  border-radius: 13px;
`;
```

2023-05-12 12:46 UTC, wzrabbit commented on README.old.md
> +버그를 발견한다면, [Issues](https://github.com/woowacourse/react-shopping-cart/issues)에 등록해주세요.
물론이죠! Readme 파일을 개선하지 않고 미처 놓쳤습니다 😢 
이런 실수 하지 않도록 더 꼼꼼하게 확인하겠습니다.

2023-05-14 14:08 UTC, wzrabbit commented on src/components/ProductQuantityInput/ProductQuantityInput.tsx
> +    setCartProducts({ ...cartProducts, [productId]: Number(e.target.value) });
state를 업데이트할 때 이전 값을 어떻게 활용할 지 계속해서 고민해 봤는데, 이렇게 하면 사용할 수 있다는 것을 알게 되었습니다, 감사합니다!

케빈의 코멘트를 반영하면서 이 부분의 로직은 custom hook으로 분리하였기 때문에, 이 코드의 변경사항 대신 custom hook에서 적용해 본 것을 여기 올려둡니다.

```tsx
const updateProduct = useCallback(() => {
    if (!isFocused) {
      setCartProducts((previousCartProducts) => ({
        ...previousCartProducts,
        [productId]: Number(inputValue),
      }));
    }
  }, [isFocused, setCartProducts, productId, inputValue]);
```

변경을 이렇게 함으로써, 말씀해 주신 문제를 해결한 것에 대한 장점 외에도 아래와 같은 장점이 생겼습니다.  
- 이전 state 값을 토대로 새로운 state를 설정하는 것이 필요하기에 state 값이 필요했고, 이에 따라 `useRecoilState` 를 사용해야만 했는데, `useSetRecoilState` 로 변경할 수 있게 되었습니다.
- `useSetRecoilState` 를 사용하기 이전에는 한쪽에서만 값을 변경해도 모든 인풋 컴포넌트들이 리랜더링 되야만 했습니다. 이걸 개선해보고 싶었습니다. 인풋 컴포넌트들은 새로운 recoil state로 업데이트하는 역할만을 수행하지, 값을 사용하지는 않았기에 리랜더링이 불필요했거든요. 이를 개선할 수 있었습니다! 이제 인풋의 값을 변경하면 변경된 컴포넌트만 리랜더링이 되네요!
- 덤으로, `cannot update a component ~~ while rendering a different component ~~` 오류도 해결할 수 있었습니다.

<img src="https://user-images.githubusercontent.com/87642422/233828081-bec1bb8b-7c29-4fac-8c67-0c84bb814ee2.png" width="35px" />

2023-05-14 14:10 UTC, wzrabbit commented on src/components/ProductQuantityInput/ProductQuantityInput.tsx
> +  };
수량 인풋의 값을 업데이트할 때의 로직들을 분리하고, recoil을 이용해 업데이트하는 로직도 숨기고 싶어서, 새로운 hook을 만들었습니다!
근데 엄청나게 복잡하고 사용 용도도 한정적입니다! 케빈이 부디 판단해 보시고 어떤 개선점이 있으면 좋을 지 의견을 알려주세요.

2023-05-14 14:14 UTC, wzrabbit commented on src/components/ProductCard/ProductCard.tsx
> +}
네, 공통 타입으로 관리하겠습니다,
다만 이번 Step에서 별도로 공통 타입 파일을 안 만든 것은, 아직 반복적으로 사용되는 타입이 없었어서 그랬습니다!
반복되는 타입들이 더 생긴다면 공통 타입에 더 많은 것들을 채워넣어 보겠습니다!

`src/types/index.ts`

2023-05-14 14:29 UTC, wzrabbit commented on src/components/CartNotificationButton/CartNotificationButton.tsx
> +    <Button>
이 부분은 페어 프로그래밍을 하면서 페어와도 고민해 본 점입니다! 저와 페어 둘 다 `styled-components` 를 전혀 사용해 본 적이 없었지만 새로운 것을 배워보자는 마음가짐으로 사용해 보았고, 그 과정에서 스타일 컴포넌트명들을 짓는 컨벤션도 찾아보곤 했거든요.

케빈이 말씀해 주신 **스타일 태그인지 컴포넌트 태그인지 구분하기 어려운 문제** 는 스타일 컴포넌트를 구분할 수 있도록 스타일 컴포넌트 전체를 감싸도록 `Styled = { ... }` 또는 `S = { ... }` 형태로 객체를 생성한다면, `<Styled.ComponentName>` 또는 `<S.ComponentName>` 와 같이 사용할 수 있게 되고, 이렇게 한다면 컴포넌트 태그들과 구분할 수 있을 것으로 보입니다.

다만 여러 팀들에서 사용하는 컴포넌트들을 검색해 본 결과 `Styled-` 또는 `S-` prefix들을 사용하지 않는 컨벤션도 있었더군요.

케빈이 말씀해 주신 문제점인 **스타일 태그인지 컴포넌트 태그인지 구분하기 어려운 문제** 는 충분히 이해했습니다. 그렇지만 저는 아직까지는 이러한 문제점을 크게 체감하지 못 해, `Styled-` 또는 `S-` 를 붙여야 할 뚜렷한 필요성을 못 느끼고, 반영하지 않았습니다. 아래는 이러한 결정을 내리게 된 제 이유와 생각들입니다. (그냥 제가 느낀 것뿐입니다!)

1. `styled-components` 를 사용하기 이전에도, 저는 기능 없이 스타일만을 담당하는 컴포넌트들을 작은 단위로 쪼개 여러 개를 만들고 import해 사용하곤 했습니다. 이번에도 정의한 스타일 컴포넌트들도 비슷하게 느껴 굳이 구분까지 해야 할 필요성을 느끼지 못 했습니다.
2. 규모가 작은 컴포넌트라면 굳이 사용하지 않더라도 구분이 어렵지 않을 것 같고, 규모가 큰 컴포넌트일 경우 저라면 그 컴포넌트를 대부분의 상황에서 여러 개로 쪼갤 것 같아요.
3. 케빈의 코멘트대로 `Styled-` 또는 `S-` 를 사용해 보았을 때, 일일이 해당 prefix 들을 적는 것이 힘들었고, 저에게는 가독성이 떨어진다고 느꼈습니다.

비록 저는 조금 검색해 본 것이 전부이지만, `styled-components` 에서 스타일 태그와 컴포넌트 태그를 구분할 것인지 아닌지는 정해진 것이 없고 개발자와 팀의 생각에 달렸다고 생각하고 있습니다.

케빈은 다른 팀원과 협업하실 때, 저와 비슷한 생각을 하고 계셨던 분이 계셨나요? 그 분은 어떤 근거로 주장을 하셨나요? **스타일 태그인지 컴포넌트 태그인지 구분하기 어려운 문제** 를 해결했을 때의 이점이 무엇인지 부디 의견을 말씀해 주시면 감사하겠습니다! (저는 아직 이점을 잘 모르고 있는 바보거든요)

<img src="https://user-images.githubusercontent.com/87642422/233928933-505b06b9-5460-4d73-bf1b-4addd84c9e9a.png" width="35px" />

2023-05-14 14:33 UTC, wzrabbit commented on public/robots.txt
> +Disallow:
`robots.txt` 에 대해서는 생각해 본 적이 없었는데 이번 기회에 생각해 볼 수 있게 되었군요!
케빈이 말씀해 주신대로, 해당 파일은 루트에 있어야 검색 엔진이 `robots.txt` 를 읽고 크롤링을 할 수 있겠죠!

그런데, CRA 프로젝트에서는 기본적으로 `/public` 에 이 파일이 생성되고, 빌드했을 경우 `/public` 폴더에 있는 내용물들은 자동으로 루트로 이동하기에 `robots.txt` 또한 루트로 이동하고, 이 경우 빌드된 프로젝트에 한해 검색 엔진이 `robots.txt` 를 읽는데는 어려움이 없을 것으로 생각하고 있습니다!

기능상으로는 문제가 없어 보이는데, 루트에 `robots.txt` 를 두는 것을 선호하시는 이유/추천하시는 이유가 무엇인지, 케빈의 의견을 여쭤봐도 될까요? 혹시 해당 파일의 기능을 생각해봤을 때 루트에 두는 것이 더 적합해서일까요?

2023-05-14 14:44 UTC, wzrabbit commented on src/react-app-env.d.ts
> +/// <reference types="react-scripts" />
```ts
// ...

declare module '*.webp' {
    const src: string;
    export default src;
}

declare module '*.svg' {
  import * as React from 'react';

  export const ReactComponent: React.FunctionComponent<React.SVGProps<
    SVGSVGElement
  > & { title?: string }>;

  const src: string;
  export default src;
}

declare module '*.module.css' {
  const classes: { readonly [key: string]: string };
  export default classes;
}

// ...
```

안으로 들어가보니 이런 식으로 각 파일 확장자들에 대한 글로벌 타입을 선언해 두었더라고요!
이러한 글로벌 타입들이 없다면, TypeScript가 리소스 파일들을 올바르게 인식하고 가져오는 작업을 하지 못 하겠지요.
`react-app-env.d.ts` 는 리소스 파일들에 대한 글로벌 타입들을 선언해 두어 TypeScript에게 이러한 리소스 파일들에 대한 타입을 알려주어, 리소스 파일들을 CRA 프로젝트 내에서 문제 없이 사용할 수 있도록 하는 역할을 수행한다고 생각합니다!

2023-05-14 15:41 UTC, wzrabbit commented on src/components/ProductCard/ProductCard.tsx
> +  overflow: hidden;
죄송합니다, 코멘트를 제대로 이해하지 못했습니다. 혹시 `overflow: hidden` 을 사용한 이유가 무엇인지 여쭤보신 걸까요?
그렇다는 가정하에 저는 답글을 적어보겠습니다...

`overflow: hidden` 을 사용한 것은 `text-overflow: ellipsis` 를 사용하기 위함이었습니다. `ellipsis` 속성을 넣은 이유는 내용이 넘칠 경우 넘친 부분을 `...` 로 생략해 주도록 만들고 싶었기 때문입니다. 상품명이 굉장히 긴 경우를 커버하기 위함이었죠.

여기서 `ellipsis` 속성이 적용되려면 우선 내용이 넘쳐 표시하지 못 하는 상황이 생겨야 하는데, `overflow: hidden` 을 사용하지 않을 경우 기본값인 `overflow: visible` 이 적용되어 글자들이 표시가 안 되는 상황이 일어나지 않아 적용되지 않습니다. 이것이 제가 `overflow: hidden` 을 사용한 이유입니다.

한편 `...` 으로 내용을 생략하면 사용자가 상품명을 전부 확인할 수 없는 단점이 있기에, `title` 속성을 사용하여 사용자가 마우스를 호버할 경우 상품명 전체가 보이도록 개선했습니다.

2023-05-14 15:44 UTC, wzrabbit commented on src/components/ProductQuantityInput/ProductQuantityInput.tsx
> +export default ProductQuantityInput;
좋은 의견 주셔서 감사합니다!
> \+ 버튼이나 - 버튼을 누를때 step을 얼마나 갈건지  

이 아이디어를 활용하여 개발자가 `step` 을 별도 지정할 수 있도록 개선했습니다.
다만 기본적인 상황에서는 `step` 의 단위는 `1` 이 될 것이라 생각해서 값을 `optional` 로 두고 기본값을 `1` 로 설정했습니다.
optional 한 값들이 남용될 경우 optional한 값을 커버하기 위해 그만큼 개발자가 다양한 경우를 고려해야 하고, 이는 유지보수의 어려움으로 이어질 수 있을 거라는 생각이 듭니다.

`step` 을 optional한 값으로 둔 것에 대해, 케빈은 어떻게 생각하시는지 의견이 궁금합니다!

2023-05-14 16:18 UTC, wzrabbit commented
반갑습니다 케빈, 리뷰해 주셔서 감사합니다!
리액트의 전체적인 구조에 대해 감을 잃지 않을 수 있도록 질문 주신 점이 좋았습니다! 케빈이 질문해 주실 당시 모르고 있었던 기본 사전지식들이 있었는데 검색하고 조금이나마 알아볼 수 있는 시간이 되었습니다.

케빈의 코멘트들을 고민해 보고 반영했고요! 케빈의 의견을 알고 싶어서 코멘트를 반영하지 않고 대신 질문을 드린 코멘트들도 있으니, 확인해 주시면 감사하겠습니다!

케빈의 코멘트를 반영한 것 이외에, 저는 아래의 두 가지를 개선해 보았습니다. 

1. 반응형 웹 및 디자인을 변경해 사용자 경험 향상시키기
2. 수량을 변경하는 데 사용하는 Input 버그 수정 및 기능 향상시키기

그럼, 잘 부탁드립니다! Step 1 개선 후 제출하는 것이지만, 개선되어야 하는 점이 많다면 언제든지 Request Changes 주세요!

## 메인 코멘트에 대한 답변 🔈 
> 장바구니에 들어있는 상품이 실시간으로 반영되지 않는거 같은데 의도한 방식일까요? (스텝퍼에서 빈화면을 한번 눌러야지 반영됩니다)  

네! 의도한 방식입니다. 사용자가 입력 중인 상태에서는 아직 사용자가 결정을 하지 않은 상태이므로 스텝퍼의 리랜더링만 일어나고, Recoil 의 state에는 실시간으로 값을 반영하지 않도록 하고 싶었습니다. 이번에 개선해 보았으니 확인해 주시면 감사하겠습니다!

> 현재 상품 담을것을 다 제거했을때, 장바구니 갯수에 영향을 안주는 버그가 있는거 같아요~  

개선 이전은 모르겠지만 개선한 후에는 문제가 없어보이는데, 해당 버그가 아직 남아있는지 확인해 주실 수 있나요?

>스토리북 주소도 같이 올려주시면 감사합니다!  

죄송합니다! 제출 당시에는 스토리북이 작동하지 않아서 주소를 첨부하는 것은 무의미하다고 판단하여 올리지 않았습니다.
지금은 문제 없이 작동하니 주소 드릴게요!

[스토리북](https://wzrabbit.github.io/react-shopping-cart/storybook/)

## 반응형 웹 및 디자인을 변경해 사용자 경험 향상시키기 ✨ 
![반응형](https://github.com/woowacourse/react-shopping-cart/assets/87642422/d312d54a-b988-41ab-b4eb-0158a8b8c12e)
gif 이미지로 설명을 대신합니다! ...네, 이거 제 욕심 맞습니다

## 수량을 변경하는 데 사용하는 Input 버그 수정 및 기능 향상시키기 ✨
### 이거 왜 이렇게 어려워요...?
이번 피드백을 반영하면서 제일 신경 쓴 부분입니다. 값이 비어 있는 경우, 값이 `0` 이 되는 경우 등 고려하기 힘든 케이스들이 많아 구현에 어려움을 겪었습니다.
해결하기 위해 custom hooks를 사용했는데, 굉장히 많은 `state`를 사용했으며 `useEffect` 떡칠까지 하다 보니 더러운 코드가 되었습니다. 개선점이 있다면, 케빈의 조언을 들어보고 싶습니다.

### 여러 불편사항들을 고려하고 해결해 보았습니다
1. 사용자가 `0` 을 입력했을 경우, 제멋대로 입력이 완료되면서 장바구니 버튼으로 컴포넌트가 변경되는 문제
2. 입력된 수가 한 자리일 경우, 입력을 지울 수 없었던 문제
4. 사용자가 값을 입력할 때마다 `recoil` 에 값을 업데이트하는 것. 사용자의 입력이 완료되지도 않았는데 굳이 매번 업데이트를 해야 할까요?
5. 수정한 것은 하나의 인풋인데 모든 인풋들이 리랜더링되는 문제. 이 부분은 `useSetRecoilState` 형태로 변경하고 setter 함수만을 사용하는 것으로 문제를 해결했습니다. 케빈의 코멘트 덕분에 이전 값을 가져올 수 있는 방법도 알게 되었습니다.
6. 사용자가 `step` 을 조작하다면 음수인 경우가 나올 수도 있는 문제

`<input type="number" />` 를 유지하면서 인풋에 빈 값이 나오는 것은 힘들 것이라고 생각하고, 이 부분은 과감하게 `number` 타입을 포기했습니다.
사용자의 입력이 완료되지 않았다면, 값이 `0` 이거나 빈 값이어도 장바구니 아이콘으로 변경되지 않도록 개선했습니다.

### 개선 결과 스크린샷
![simulation](https://github.com/woowacourse/react-shopping-cart/assets/87642422/468dc655-e79e-4386-944e-7ff574bac940)

개선되어야 할 점이 있다면 언제든지 알려 주세요!

2023-05-15 15:20 UTC, JeongBin0227 commented
요술토끼님 배포된 사이트 봤는데 이전 버전보다 너무 발전해서 놀랬습니다... 👍

2023-05-15 15:50 UTC, JeongBin0227 commented
> 기능상으로는 문제가 없어 보이는데, 루트에 robots.txt 를 두는 것을 선호하시는 이유/추천하시는 이유가 무엇인지, 케빈의 의견을 여쭤봐도 될까요? 혹시 해당 파일의 기능을 생각해봤을 때 루트에 두는 것이 더 적합해서일까요?

말씀하신대로, 기능상으로는 문제가 없을 수 있습니다. 하지만 루트에 두길 권장하는 이유는 크게 3가지 정도가 있는데,

1. 검색 엔진은 robots.txt 파일을 찾을 때 기본적으로 웹 사이트의 루트 디렉토리에서 검색합니다. 따라서 검색 엔진이 robots.txt 파일을 가장 빠르게 찾을 수 있도록 루트에 위치시키는 것이 권장됩니다.

2. 프로젝트의 루트 디렉토리에 robots.txt 파일을 배치하면 프로젝트의 주요 구성 요소와 함께 보다 직관적으로 관리할 수 있습니다. 개발자나 다른 사람들이 프로젝트를 검토할 때, 프로젝트의 중요한 설정 파일이 루트 디렉토리에 있기 때문에 더 쉽게 찾을 수 있습니다.

3. 요술토끼가 말씀하신것처럼 `CRA 프로젝트에서는 기본적으로 /public 에 이 파일이 생성되고, 빌드했을 경우 /public 폴더에 있는 내용물들은 자동으로 루트로 이동하기에 robots.txt 또한 루트로 이동하고, 이 경우 빌드된 프로젝트에 한해 검색 엔진이 robots.txt 를 읽는데는 어려움이 없을 것으로 생각하고 있습니다!` 라고 하셨는데, 틀린 말은 아니지만 이것이 100프로 맞는다고 보장할 수는 없습니다. 예를 들어 CRA 프로젝트나 빌드 도구의 설정이 변경되어 /public 폴더의 동작이 바뀌거나 빌드 프로세스가 변경될 수 있습니다.

2023-05-15 16:02 UTC, JeongBin0227 approved these changes
안녕하세요 요술토끼~

너무 리팩토링을 잘해주셨고, 배포된 화면도 몰라보게 바뀐거 같아요 👍 
질문 주신 부분 코멘트로 남겨드리고, 추가 코멘트도 남겨드렸으니 한번 확인해보시면 좋을거같아요!

추가로 hook 관련은 다음 스텝에서 예시 코드로 한번 보여주시면 더 이해가 잘될거 같아요~
스텝1하느라 고생많으셨습니다~ 다음 스텝에서 뵙겠습니다 고생하셨어요~ 💯

2023-05-15 16:03 UTC, merged