[장바구니 미션 Step 2] 수아(최수현) 미션 제출합니다.
woowacourse/react-shopping-cart pull request #197
Opened 2023-05-20 09:09 UTC by chsua

### <a href="https://chsua.github.io/react-shopping-cart/">앱 바로 실행하기</a>
### <a href="https://644f59b87dca7bfe7de2ed67-sjtlyffapm.chromatic.com/">스토리북 바로 실행하기</a>

<br> 

현재 홈페이지로 들어가면 헤더만 있는 화면이 노출됩니다. 상단에 로고를 누르시면 목록으로 들어가실 수 있고, 장바구니를 누르면 장바구니 페이지로 들어가실 수 있습니다.

step2 브랜치를 만드는 과정에서 실수가 있어 이전 커밋들이 다 끌어와졌습니다. 보기 불편하시겠지만 양해 부탁드립니다🥲

그리고 이전에 _"api 에러 핸들링을 어디서 하면 좋을지 생각해보시면 좋겠다고 했는데 요거는 어떻게 진행됐는지 궁금합니다!"_라고 말씀해주셨는데, 제가 1단계에서 리팩토링하다가 리뷰가 누락되었었습니다.. 죄송합니다..! 그래서 이번에 이 부분을 처리하고자 했습니다. 

이전 미션들을 할 때 미션 요구사항은 완성했지만 리팩토링을 하다보니 시간이 너무 오래걸려 리뷰 횟수가 적어졌다고 생각했습니다..! 그래서 아직 2단계를 만족스럽게 코드를 짜지 못했습니다만 1차적으로 기능요구사항들을 구현하였다고 생각하여 pr을 보내고 부족한 부분을 수정하고자 합니다. 

<br> 

### 주요 기능 
- 반응형 웹: 크게 모바일 세로/ 가로, 탭, 모니터 가로길이를 기준으로 작성
- msw 도입: 쇼핑 물품을 msw로 get해와서 렌더링
- 장바구니에 넣은 품목을 로컬 스토리지에 저장
- 오류 처리: 
    - api status에 따른 처리: 400 ~ 599라면 오류 페이지 렌더링
    - api status가 200이지만 get한 데이터가 비어있다면 오류페이지 렌더링
 
<br> 

### 수정 예정
- 절대경로와 상대경로 혼용: 1단계에서 절대경로로 설정했으나 2단계를 진행하며 추가된 폴더의 절대경로가 오류가 발생했습니다. 기능을 구현하는 것이 우선이라고 생각하여 미루었던 것이 지금 하면 오래 걸릴 것 같아 pr을 보내고 수정하고자 합니다.
- msw를 get에서만 사용: 다른 크루들이 post/ delete 등에도 이용하였으나 아직 api와 상호작용하는 것이 어려워 일전에 해본 get만 성공하고 다른 것은 오류가 발생했습니다.. 장바구니와 관련된 api를 패치하는 코드를 어디에 놓아야 할 지 모르겠어서 api를 더 공부하고 시도하고자 합니다. 
- 웹 접근성
- 테스트: 리코일을 이용하는 장바구니 관련 컴포넌트에서 스토리북을 많이 활용하지 못한 것 같아 리코일을 테스트에 적용할 수 있는 방법을 찾고자 합니다. 시도 했으나 자꾸 망가져버려서..🥲 다시 천천히 공부해보겠습니다.

<br> 

### 궁금한 점 
- 리코일로 장바구니 안 품목을 관리합니다. 그래서 장바구니 api와 상호작용할 때 최초 렌더링 한번만 되는 app에서 장바구니 api/get을 하고, 이후 장바구니 state가 업데이트를 관리하는 훅에서 장바구니 api에 delete/post 등을 하고자 했습니다. 이런 방법으로 했더니 오류가 났습니다.. **리코일처럼 한 컴포넌트에서 사용되는 상태가 아닌 전역으로 관리하는 데이터는 api와 상호작용을 언제 해야 하는지 잘 모르겠습니다. 아니면 어차피 장바구니 데이터를 api와 상호작용하니 리코일에서 전역으로 장바구니 정보를 가질 필요가 없는 걸까요..?** 해결하지 못해서 일단 시도했던 관련 코드는 삭제하지 않고, 장바구니를 로컬 스토리지에 저장하여 pr 드립니다.
- **전역에서 사용하는 데이터를 패치하는 과정에서 404같은 에러가 뜬다면 그 전체 화면을 모두 에러를 보이는 화면으로 렌더링해야 할까요?** 가능하다면 에러는 작은 컴포넌트 단위에서 처리되야 한다고 생각합니다. 예로 장바구니 api가 오류가 나더라도 전체 물품 api가 정상적으로 들어온다면 사용자가 물품을 구경이라도 하는 것이 좋지 않을까 생각했습니다. 하지만 그럼 전역에서 관리하는 데이터는 오류가 났다는 것을 어디에 표시해야 하는지 알 수 없어졌습니다.
- 장바구니 페이지에서 체크된 장바구니 물품을 관리합니다. 다른 크루들은 해당 데이터를 리코일에 저장하여 사용했지만 저는 해당 상태는 장바구니 페이지를 벗어나면 전혀 사용되지 않는 상태이고, 그런 상태를 전역으로 관리하는 것보단 2단계정도 드릴링이 일어나는 것이 더 수용가능한 선이라고 생각이 들었습니다. 다만 프로젝트의 페이지가 많아지고 컴포넌트가 더 세세하게 들어가는 경우 무엇을 선택해야 할지 어렵다고 생각합니다. **어디까지 전역으로 관리해야 할지, 혹은 드릴링을 감수하고 useState를 사용해야 할지 리뷰어께서는 어떻게 생각하시나요?**
- 이번에 체크박스 컴포넌트와 수량 조절 컴포넌트를 재활용성 높게 하고자 노력했습니다. 혹시 재활용성을 높이기 위해 더 하면 좋은 것들이 있다면 말씀 부탁드립니다! 

<br> 

많이 다듬지 못한 코드입니다. 상대/절대 경로조차 정리하지 못하고 리뷰 요청드려 죄송합니다ㅠㅠㅠ  감사합니다!

2023-05-20 17:17 UTC, HyeonaKwon reviewed
안녕하세요 수아! 😃

![image](https://github.com/woowacourse/react-shopping-cart/assets/46472795/7a1215b6-9a8f-4b1d-a08e-980324ea0b52)

우선 위의 이미지와 같이 데모페이지가 작동하지 않아 확인할 수가 없었습니다 🥲
그리고.. MR 올리실 때 미션 요구사항을 올려주셔야 제가 드릴 피드백이 있을 것 같습니다. 현재로서는 컴포넌트를 잘 구현했나? 훅을 잘 구현하고 사용하고 있나? 정도만 드릴 수 있을 것 같네요..

아마도 api 에러관련해서는 코멘트에도 남겨뒀지만 ref 사용으로 인해 꼬였을거란 추측을 해봅니당! 그리고 api 에 따른 상태 업데이트에서도 문제가 있었을 것 같구요. 어느 코드가 잘못됐는지, 어떤 에러가 났는지를 알려주시지 않아서 제가 드릴 수 있는 말이 없네요!

#### 질문 답변
1. 리코일 - 장바구니
-> 어디에 코드가 있는지는 모르겠으나.. 장바구니 api 가 장바구니에 있는 아이템 리스트를 불러오는 api 가 맞을까요? 맞다면 해당 api 가 product-list 에서도 사용되나요? 해당 api 가 필요한 페이지에서 호출을 해야지 app 에서 호출하면 그 api 가 필요하지 않은 모든 페이지들도 불필요한 api 콜을 하겠네요.
그리고 말씀해주신 `장바구니 state가 업데이트를 관리하는 훅에서 장바구니 api에 delete/post 등을 하고자 했습니다. 이런 방법으로 했더니 오류가 났습니다..` 요 부분에서는 에러날 부분이 없어보이는데요! 해당 hook 구현이 잘못되지 않았을까 싶습니다.
아직 local state 와 global state 에 대한 개념이 명확하지 않으신 것 같은데 어떤걸 어떻게 관리할지 명확히 구분하시면 좋을 것 같습니다!

2. 404 에러
404 에러는 어떤 에러를 뜻하나요? 예로 주신 장바구니 api 에서 404 에러가 발생할 수가 있나요? api 경로가 잘못되는 일이 없다면 404 에러는 발생하지 않을 것 같구요, 행여나 발생했을 때의 처리는 기획을 어떻게 하느냐에 따라 다를 것 같아요! 근데 장바구니 api 라면 product-list 에서는 해당 컴포넌트만 에러처리를, 장바구니 페이지에서는 전체 에러페이지를 노출할 것 같습니다.

3. 장바구니 상태
![image](https://github.com/woowacourse/react-shopping-cart/assets/46472795/a4ca8836-c48d-421b-bee4-918501ad0557)
요 네비바에 있는 장바구니 내 갯수도 api 를 사용하지 않나요? 여기까지도 같은 api 를 사용한다면 저였으면 전역상태로 관리할 것 같습니다. 만약 다른 api 라면 수아님처럼 로컬 상태로 관리할 것 같아요.

2023-05-20 17:17 UTC, HyeonaKwon approved these changes
안녕하세요 수아! 😃

![image](https://github.com/woowacourse/react-shopping-cart/assets/46472795/7a1215b6-9a8f-4b1d-a08e-980324ea0b52)

우선 위의 이미지와 같이 데모페이지가 작동하지 않아 확인할 수가 없었습니다 🥲
그리고.. MR 올리실 때 미션 요구사항을 올려주셔야 제가 드릴 피드백이 있을 것 같습니다. 현재로서는 컴포넌트를 잘 구현했나? 훅을 잘 구현하고 사용하고 있나? 정도만 드릴 수 있을 것 같네요..

아마도 api 에러관련해서는 코멘트에도 남겨뒀지만 ref 사용으로 인해 꼬였을거란 추측을 해봅니당! 그리고 api 에 따른 상태 업데이트에서도 문제가 있었을 것 같구요. 어느 코드가 잘못됐는지, 어떤 에러가 났는지를 알려주시지 않아서 제가 드릴 수 있는 말이 없네요!

#### 질문 답변
1. 리코일 - 장바구니
-> 어디에 코드가 있는지는 모르겠으나.. 장바구니 api 가 장바구니에 있는 아이템 리스트를 불러오는 api 가 맞을까요? 맞다면 해당 api 가 product-list 에서도 사용되나요? 해당 api 가 필요한 페이지에서 호출을 해야지 app 에서 호출하면 그 api 가 필요하지 않은 모든 페이지들도 불필요한 api 콜을 하겠네요.
그리고 말씀해주신 `장바구니 state가 업데이트를 관리하는 훅에서 장바구니 api에 delete/post 등을 하고자 했습니다. 이런 방법으로 했더니 오류가 났습니다..` 요 부분에서는 에러날 부분이 없어보이는데요! 해당 hook 구현이 잘못되지 않았을까 싶습니다.
아직 local state 와 global state 에 대한 개념이 명확하지 않으신 것 같은데 어떤걸 어떻게 관리할지 명확히 구분하시면 좋을 것 같습니다!

2. 404 에러
404 에러는 어떤 에러를 뜻하나요? 예로 주신 장바구니 api 에서 404 에러가 발생할 수가 있나요? api 경로가 잘못되는 일이 없다면 404 에러는 발생하지 않을 것 같구요, 행여나 발생했을 때의 처리는 기획을 어떻게 하느냐에 따라 다를 것 같아요! 근데 장바구니 api 라면 product-list 에서는 해당 컴포넌트만 에러처리를, 장바구니 페이지에서는 전체 에러페이지를 노출할 것 같습니다.

3. 장바구니 상태
![image](https://github.com/woowacourse/react-shopping-cart/assets/46472795/a4ca8836-c48d-421b-bee4-918501ad0557)
요 네비바에 있는 장바구니 내 갯수도 api 를 사용하지 않나요? 여기까지도 같은 api 를 사용한다면 저였으면 전역상태로 관리할 것 같습니다. 만약 다른 api 라면 수아님처럼 로컬 상태로 관리할 것 같아요.

2023-05-20 17:17 UTC, HyeonaKwon requested changes
실수로 Approve 를 눌렀습니다 🤣 코멘트 확인 부탁드립니다~!

2023-05-23 12:35 UTC, chsua commented on src/api/index.ts
> +};
api에서 post 등을 할 때엔 뒤에 id를 붙여주기 때문에 사용했습니다! 
패치를 수정하면서 굳이 그럴 필요성이 없다는 것을 깨닫고 수정하였습니다!

2023-05-23 13:24 UTC, chsua commented on src/components/Checkbox/index.tsx
> +    <S.ProductItemCheckboxLabel checked={isChecked}>
혹시 제가 어떤 방식인지 모르겠는데 어떤 선택자인지 알려주실 수 있으신가요?? ㅠㅠ 제가 잘 이해하지 못한 것인지 검색을 해도 유효한 결과가 나오지 않습니다..

2023-05-23 13:35 UTC, chsua commented on src/hooks/useFetch/index.ts
> +  const currentHttpStatus = httpStatusError.current;
제가 했던 동작들에서는 이상한 부분은 없었습니다..😂 

useState를 많이 가지고 있으면 좋지 않다고 하여 필수적으로 렌더링의 기준이 되는 상태는 useState로 관리하고, 그 외 부가적으로 상태가 변경되는 -그렇지만 렌더링에서 자유로워야 하는-상태는 ref를 사용하여 짜는 편입니다. 

해당 코드의 경우 httpStatusError는 패치가 요청되었을때(데이터와 로딩 상태가 변화할때) 변화하는 값이라고 생각했습니다. 더불어  try, catch문에서 각각 ref를 바꿔주기 때문에 잘못 설정/누락되는 경우가 없을 것이고, 에더가 발생했다면 수정된 값이 노출될 것이라고 생각하여 문제가 없을 것이라고 생각했습니다. 

혹시 ref를 이런 방식으로 사용되는 것이 옳지 않을까요?🥲 " ref 라 컴포넌트에서 리렌더링으로 잡히지 않을 것 같은데 테스트 해보신건가요?"가 정확하게 어떤 상황일지 예상이 잘 가지 않습니다. 혹시 우려되는 예시를 들어주실 수 있으실까요??

2023-05-23 13:43 UTC, chsua commented on src/index.tsx
> +  }
msw의 경우 gh-pages에서 잘 작동하지 않습니다.🥲 이를 해결하기 위하여 작성해주는 것으로 [msw 페이지](https://mswjs.io/docs/getting-started/integrate/browser#using-homepage-property-in-packagejson)를 참고하였습니다!

2023-05-23 16:21 UTC, chsua commented
### [홈페이지](https://chsua.github.io/react-shopping-cart/product-list)

안녕하세요 헤인티! 

시간이 많이 지나버렸어요 왜 이렇게 시간이 빨리 지날까요 🥲🥲🥲🥲

이전에 생긴 문제는 훅과 관련된 문제였습니다 useFetch를 사용하면서 그 안에 useState를 두었는데, 훅은 컴포넌트에서만 사용이 가능해서 아톰 등에서 사용을 하면 에러가 났습니다. 때문에 이를 해결하고자 그 안에 useState를 없앴습니다.

## 수정 부분
1. msw
 - 이전 : msw 중 product list만 get하여 렌더링
 - 수정: msw에 shopping cart 의 get/post/put/delete 모두 사용
 - 문제점
     1. api통신이 오류가 나더라도 비동기가 연결되어 있지 않기 때문에 로컬스토리지가 변화함.
     2. 굉장히 스파게티 코드...입니다..🥲
     3. 에러처리가 에러페이지에서 alert창으로 수정: 이전에는 훅으로 관리하여 상태를 가지고 렌더링을 조절하였으나 훅을 없애면서 그럼 어디서 처리를 에러페이지를 렌더링 해줘야 하는지 고민을 하다 일단 alert창으로 띄웠습니다.

2. checkbox를 총괄하는 checkbox 
  - 이전: useRef를 사용하여 조절
  - 수정: 일반 변수로 수정

<br> 

이번에 수정한 부분은 많이 없습니다ㅠㅠㅠ 
주신 리뷰 반영하고 api위주로 했습니다만 promise 객체를 다루는 것이 아직 익숙하지 않아 스파게티 코드입니다.. 
자꾸 앓는 소리만 하게 되네요...🥲 
다른 사람 코드 보고 패치를 어떻게 사용하는지 고민해보도록 하겠습니다..

2023-05-24 12:40 UTC, HyeonaKwon commented on src/api/index.ts
> +};
host 는 보통 분기로 관리하지 않고 개별적으로 하나하나 선언하고는 하는데요! 이렇게 host 를 관리하면 비즈니스 로직까지 알아야 어떤 host 가 사용되는지 파악할 수 있어 유지보수 측에서는 어려울 것 같습니다!

2023-05-24 12:42 UTC, HyeonaKwon commented on src/components/Checkbox/index.tsx
> +    <S.ProductItemCheckboxLabel checked={isChecked}>
`& > input:checked &` 이런식으로 찾을 수도 있고 방법은 여러가지일 것 같네요!

2023-05-24 12:44 UTC, HyeonaKwon commented on src/hooks/useCheckedItems/index.ts
> +export default useCheckedItems;
그거는 위의 정보를 모두 같은 컴포넌트가 사용한다는 전제하에 동작하는 코드일거예요! 서로 다른 컴포넌트로 분리 후 각 state 를 불러와서 사용했을 때 과연 전체선택 체크박스가 정상 동작할까요?
리렌더링이 필요한 정보들은 ref 를 사용하지 않는 것이 좋습니다!

2023-05-24 12:46 UTC, HyeonaKwon commented on src/hooks/useFetch/index.ts
> +  const currentHttpStatus = httpStatusError.current;
위와 같은 답변으로 현재는 이 훅에서 제공하는 값들을 같은 컴포넌트에서 사용하고 있기에 다른 정보가 바뀌면서 리렌더링되어 currentHttpStatus 를 최신 값으로 사용할 수 있겠지만, `<ErrorContainer error={currentHttpStatus} />` 가 다른 컴포넌트에서 사용되고 있고 currentHttpStatus 만 불러왔다면 업데이트 되지 않았을거라 생각됩니다!

2023-05-24 13:05 UTC, merged