[1단계 - 장바구니 미션] 유조(조윤호) 미션 제출합니다.
woowacourse/react-shopping-cart pull request #20
Opened 2021-05-13 15:54 UTC by yujo11

##  📖 미션 요구사항

### 🚀 step1

- [X] `REQUIREMENTS.md`에 요구 사항 도출 
- [X] `재사용 가능한 Component` 작성

### 📝 필수 구현 페이지

- [x] 장바구니
- [x] 주문/결제
- [x] 상품 목록
- [x] 주문 목록
---

## 🌏 링크 모음

### 1. Storybook
- [Storybook 링크](https://www.chromatic.com/library?appId=609d4099d6326d0039142d4e)

### 2. 데모 사이트
- [데모 사이트 링크](https://react-shopping-cart-yujo.netlify.app/)

### 3. Visual Studio Code in Web

- [Visual Studio Code in Web 링크](https://github1s.com/yujo11/react-shopping-cart/tree/step1)

2021-05-15 03:37 UTC, ysm0622 requested changes
> User Flow Chart를 처음으로 그려봤습니다. 검색하면서 다른 Flow Chart들을 보고 따라 그려봤는데요. 이런 식으로 그리는게 맞는지 궁금합니다ㅠㅠ 어색하거나 잘못된 점이 있다면 알려주시면 감사하겠습니다!!

- 적절하게 그리신것같습니다! 👍 

> Redux를 처음으로 도입해서 사용했습니다. 스스로 필요에 의해 고민하고 선택한 라이브러리가 아니라서 그런지 "Redux를 꼭 사용해야 할까?"라는 의문이 머리 속에 계속 맴돌고 있습니다. 리뷰어님께서는 어떤 경우에 Redux를 사용하시고 어떤 상태들을 Redux Store로 관리하시는지 궁금합니다!

- 좋은 고민과 생각입니다! 스스로 필요에 의해 도입한 라이브러리가 아니라면 당연히 그런생각이 드는건 자연스럽습니다 👍  저도 개인적인 생각으로는 아직 이정도 규모에서는 전역 상태가 굳이 필요하지 않다고 생각해요.
- 이 커리큘럼에서는 전역 상태, 특히 Redux API를 사용해보고 익히기 위한 방향으로 생각됩니다.
- 개인적으로는 최대한 전역상태를 만들지 않는 편입니다. 
- 전역변수는 좋지 않다고 들으신 적이 있을거예요. 전역변수나 전역상태가 항상 안좋은 것은 아니지만, 최대한 지양하는 편이 좋습니다.
- 전역상태는 전역변수랑 비슷하다고 생각해요.
- 이 State가 정말 앱 전체에 전역적으로 가져야하는 State인가?를 계속 고민해보시면 대부분 특정 컴포넌트안에 격리할 수 있는 상태이거나, 쿠키, 로컬스토리지 등으로 충분히 해결 가능한 경우가 많습니다.

고생하셨어요! 👏 👏 👏 👏 👏

2021-05-15 03:37 UTC, ysm0622 commented on src/components/units/PurchasedItem/PurchasedItem.tsx
> +      <Styled.Image src={image ?? defaultImageURL} alt="김말이" />
alt="김말이" !?!?! ㅋㅋ

2021-05-15 03:37 UTC, ysm0622 commented on src/constants/messages.ts
> +  ADDED_CART_ITEM_FAILURE: '장바구니를 도난 당했습니다! 🚨',
!!!

2021-05-15 03:37 UTC, ysm0622 commented on src/modules/cartItems/actions.ts
> +import * as T from '../../types';
`* as T` 보다 직접 해당 타입을 import 하는게 더 좋을것같아요 👍

2021-05-15 03:37 UTC, ysm0622 commented on src/pages/OrderPage/OrderPage.tsx
> +    setLoading(true);
isLoading State 과 data fetching 이 반복되고있는것같은데
custom hook을 만들어서 추상화해보는 연습을 해보면 좋을것같아요 👍

2021-05-15 04:28 UTC, yujo11 commented on src/components/units/PurchasedItem/PurchasedItem.tsx
> +      <Styled.Image src={image ?? defaultImageURL} alt="김말이" />
수정한다는게 까먹고 있었네요!😅😅😅

감사합니다👍👍👍

2021-05-15 04:32 UTC, yujo11 commented on src/modules/cartItems/actions.ts
> +import * as T from '../../types';
`* as T`로 import 해서 사용하면 types 파일에서 정의된 type이라는걸 확실히 알 수 있다고 생각해서 이렇게 사용했습니다!

직접 해당 타입을 import 했을  때 `* as T` 로 import 한 것과 비교해서 어떤 이점이 있는지 궁금합니다!

2021-05-15 04:32 UTC, yujo11 commented on src/pages/OrderPage/OrderPage.tsx
> +    setLoading(true);
한번 도전해보겠습니다! 감사합니다!!👍👍👍

2021-05-15 04:40 UTC, yujo11 commented on src/constants/messages.ts
> +  ADDED_CART_ITEM_FAILURE: '장바구니를 도난 당했습니다! 🚨',
🚨🚨🚨

2021-05-18 09:53 UTC, yujo11 commented
안녕하세요 크리스님! 피드백 남겨주신 내용 아래와 같이 반영했습니다!

- [X] `<img>`의 `alt`에 적절한 이름이 들어갈 수 있도록 수정 7e522ae
- [x] 반복되는 로직 Custom Hook으로 분리 1240829


>* as T 보다 직접 해당 타입을 import 하는게 더 좋을것같아요 👍

남겨주신 다른 피드백들은 모두 반영하였으나 [다음 리뷰](https://github.com/woowacourse/react-shopping-cart/pull/20#discussion_r632887526)에 대해서는 고민되는 점이 있어 아직 코드에 반영하지 못 했습니다.

댓글로 다음과 같은 내용을 남겼는데 답변 남겨주신다면 큰 도움 될거 같습니다! 감사합니다!

>`* as T`로 import 해서 사용하면 types 파일에서 정의된 type이라는걸 확실히 알 수 있다고 생각해서 이렇게 사용했습니다!
직접 해당 타입을 import 했을  때 `* as T` 로 import 한 것과 비교해서 어떤 이점이 있는지 궁금합니다!

2021-05-21 14:18 UTC, ysm0622 commented on src/modules/cartItems/actions.ts
> +import * as T from '../../types';
TypeScript 언어의 문법과 IDE의 도움으로 인해 타입과 함수, 변수 가 명확히 구분되는데 굳이 T prefix를 붙일필요가 있을까요? 👀 
또한 types 폴더에 꼭 모든 타입을 몰아넣을 필요도 없습니다. 함수를 함수 사용부와 가까이 두는것이 좋듯이, 타입도 해당 타입의 사용부와 가장 가까운 곳에 두는것이 좋다고 생각해요.

2021-05-21 14:20 UTC, ysm0622 approved these changes
피드백 잘 반영해주셔서 감사합니다 👍 

코멘트 남겼습니다!

추가 수정사항은 다음단계에서 수정해주세요!

고생하셨어요! 👏 👏 👏 👏 👏

2021-05-21 14:20 UTC, merged