[장바구니 미션 Step 2] 해온(백솔비) 미션 제출합니다.
woowacourse/react-shopping-cart pull request #202
Opened 2023-05-21 06:53 UTC by hae-on

### ✨ [배포 URL](https://hae-on.github.io/react-shopping-cart/) | 🗒 [스토리북 배포 URL](https://hae-on.github.io/react-shopping-cart/storybook)

서니! 일주일동안 잘 지내셨나요~~
2단계를 마치고 돌아왔습니다!
이번에는 recoil이랑 msw랑 localStorage랑 이것저것 다 섞여서 정말 어려웠는데요..!
그래서 코드도 엉망으로 남게 되었어요...🥺
그래도 일단은 잘 돌아가는 거 같습니다!!!

스토리북 같은 경우는 인터렉션 테스트를 진행하고 있는데
계속 response를 못 받아오는 오류가 있네요 ㅠㅠㅠ
일반 렌더링은 잘 되는데 요청을 하면 바로 에러가 나욥...
이건 PR 올려놓고 더 해결해보도록 하겠습니다!

그럼 리뷰 잘 부탁드립니다~~😊

## ✅ 필수 요구사항
1. 장바구니 페이지
장바구니 페이지 마크업을 완성하고, 상품 목록 페이지와 함께 모바일 환경 대응

2. MSW를 활용한 API Mocking
MSW를 활용하여 실제 서버와 연동될 수 있는 API Mocking을 구현
단순한 Endpoint 변경으로 실제 API 사용이 가능하도록 작업

3. 테스트
장바구니 페이지에서 다양한 사용자 인터렉션에 대한 테스트 케이스를 고민하고, 선택한 테스트 도구를 이용하여 검증

4. 사용자 경험
새로고침 해도, 장바구니에 담은 상품 유지

2023-05-22 03:58 UTC, sunhpark42 requested changes
안녕하세요, 해온~ 작성해주신 코드 확인했습니다. 피드백 할 내용이 크게 없어서, 몇몇 코멘트 남겨두었으니 확인 바랍니다:)

일단은 로컬스토리지 사용 관련해서 의문인 점이 있어서, RC 드리는데용,
'MSW를 활용한 API Mocking' 과 '새로고침 해도, 장바구니에 담은 상품 유지' 에서 localStorage 키, 즉 관리되고 있는 배열이 동일 한 것 같아요.
이렇게 되면 mocking 환경이 동작할때, 그리고 mocking 환경이 동작하지 않을 때 동작이 달라질 수 있는데요, 기본적으로 mocking 환경은 운영환경 즉 배포환경에 영향을 주지 않는 것이 좋습니다. 'MSW를 활용한 API Mocking' 는 개발환경에서의 mocking, '새로고침 해도, 장바구니에 담은 상품 유지' 는 기능이기 때문에 둘을 분리해서 생각해보시면 더 쉬울 것 같아요.

인터랙션 테스트에 잇어서도, 어디까지 테스트 대상으로 삼을 것인지, 서버 API 가 정확히 동작하는 것 까지 테스트 영역으로 잡을 것인지, 그와 관련되지 않은 부분까지만 테스트 영역으로 잡을 것인지도, 같이 고민해보셨으면 좋겠습니다~!

관련해서 더 고민해 보시고, 인터랙션 테스트와 함께 다시 리뷰 요청 부탁드립니다. 수고하셨어요~!

2023-05-22 03:58 UTC, sunhpark42 commented on src/components/Common/AmountCounter.tsx
> +        >
aria-label은 이 페이지의 사용자가 한국인이기 때문에, 한국어로 작성해주면 더 좋을 것 같아요~

2023-05-22 03:58 UTC, sunhpark42 commented on src/domain/cartProductHandler.ts
> +  cartProducts.filter((cartProduct) => cartProduct.product.id !== id);
```suggestion
export const deleteProduct = (cartProducts: CartProduct[], id: number): CartProduct[] =>
  cartProducts.filter((cartProduct) => cartProduct.product.id !== id);
```

와 같이 해당 함수는 함수명만 보고 반환값이 무엇인지 판단하기 어려울 것 같아서, return 타입을 명시해 주어도 좋을 것 같습니다~

2023-05-22 03:58 UTC, sunhpark42 commented on src/mocks/handlers.ts
> +  }),
delay 도 함께 추가해주셨네요 👍👍

2023-05-22 03:58 UTC, sunhpark42 commented on src/recoil/checkedProductData.ts
> +});
checked 상태를 전역상태로 관리해주시는 이유가 있을까요?

2023-05-23 14:29 UTC, hae-on commented on src/components/Common/AmountCounter.tsx
> +        >
맞아요! 사실 스토리북 테스트한다고 임의로 끼워넣은건데 너무 성의없이 작성했네욥 🥲

2023-05-24 22:44 UTC, sunhpark42 approved these changes
안녕하세요 해온~! 수정해주신 부분 확인했습니다. 

> 그리고 인덱스를 이용해서 테스트 했는데, 나중에 백엔드랑 통신하고 테스트 켜보면 인덱스가 바뀌어 실패 테스트가 될 거 같다는 생각이 들었습니다...! 일단은 인덱스인 상태로 나두고 협업 미션에서 재작성해보려고 합니다! 혹시 이에 대한 팁 같은 것이 있을까요..? 인덱스로 요소에 접근하면 나중에 해당 번호의 요소가 없으면 실패 테스트가 되는데...ㅠ....

이 부분에 대해서는, 현재의 경우 서버의 값에 따라서 테스트가 성공하고, 실패하게 될 것 같아요. 프론트엔드 테스트 케이스임에도 서버에 영향을 받게 되지 않을까? 그러면 테스트가 성공했다고 해서, 정말 성공한걸까? 하는 확신이 들지 않을 것 같아요. 되도록 모든 상황에서 정상 작동하는 것을 우리는 바라지만, 테스트의 경우에서는 서버에 대한 의존도를 떨어트리는 것이 오히려 프론트엔드 코드에 대한 신뢰성을 높이는 방법이 아닐까 해요. 그래서 저는 비동기 테스트를 작성할 때 서버 api 통신하는 부분을 항상 성공한다고 가정하고 mockup 을 작성해 테스트를 진행하는 편이에요. 그런 점에서는 현재 해온의 코드도, 서버와의 의존성이 분리만 된다면 충분히 괜찮은 코드가 아닐까 싶긴 합니다.

> 아 그리고 백엔드랑 통신하면 msw는 더 이상 안 쓰나요...? 아님 그것도 handler에서 백엔드 주소를 받아와서 계속 실행을 시키나요?

저희 팀에서는 msw나 다른 목업방식을 를 일반 개발 상황에도 적극적으로 활용하는 편이에요~ 무엇보다도 프론트 코드를 작성할 때 서버의 의존성을 줄일 수 있고, 개발 서버가 임의의 상황으로 인해 제대로 실행되지 않고 있을 때에도 영향을 받지 않을 수 있습니다. 또 실무에서는 백엔드 개발기간, 그리고 프론트 개발기간이 딱딱 백엔드 -> 프론트엔드 순서로 이루어지지는 않기 때문에, 백엔드에서 API 명세를 제공받아, 그걸 기반으로 목업을 사용해서 개발하고, 수정하기도 해요. 하나 더 이점으로 생각하는 것은 회원정보, 데이터의 상태 등을 직접적으로 변경을 위해 테스트 하거나, 에러를 임의로 발생시켜볼 때에도 유용합니다. 네트워크 지연등으로 delay 가 발생하거나, api 통신에서 networkError 케이스를 확인하거나, 혹은 사용자 인터랙션이 많이 필요한, (ex, 장바구니에서 꼭 로그인을 했다, 풀었다) 것들을 직접 조작할 필요 없이, 서버 상태가 안정된 상태라고 한다면 충분히 mock 만으로도 예외 케이스에 대한 확인을 진행할 수 있어서, 유용하게 사용중입니다 ㅎㅎ

이번 미션은 여기서 마무리하도록 할게요. 수고하셨습니다~!

2023-05-24 22:45 UTC, merged