[장바구니 미션 Step 2] 패트릭(박근철) 미션 제출합니다.
woowacourse/react-shopping-cart pull request #208
Opened 2023-05-21 14:55 UTC by GC-Park

안녕하세요 파랑!

스텝 2를 마무리하고 돌아왔습니다! 하하하.. (이렇게 오래 걸릴 줄이야....😂)

이번 미션이 지금까지 했던 미션 중 가장 어려웠던 것 같습니다! 1단계에서 구현한 것에서 장바구니 페이지를 더했을 뿐인데 난이도가 엄청 올랐네요..! 그래도 정말 정말 많이 고민하고 생각하고 공부할 수 있었던 미션이라고 생각합니다.

상태가 변하는 시점, fetch 해오는 시점 등을 고민할 수 있었고 앞으로 백엔드와 협업할 때 어느 부분을 고려해야 할지 생각할 수 있었으며 msw, recoil, react-testing-library 등을 공부할 수 있었습니다.

msw 부분을 적용하는 것이 가장 어려웠던 것 같습니다. 사실 지금도 잘 적용한 것인지 잘못한 부분은 없는지 걱정이 많습니다!

파랑과의 리뷰를 통해 걱정을 줄이고, 모르던 것은 알아가고, 잘못 알고 있는 것들은 바로 잡고 싶은 마음입니다!

많이 부족한 코드입니다. 이번 리뷰도 잘 부탁드립니다. 감사합니다!

## 📚 고민한 부분
✔️ MSW를 이용하여 API를 Mocking하고 리액트에서 비동기 상황에 대해 고민해 봅니다.
✔️ Router를 활용해 여러 페이지 전환을 고려합니다.
✔️ [배민상회](https://mart.baemin.com/) 서비스 참고

## 📝 요구사항
- [x] 장바구니 페이지 마크업 완성
- [x] 상품 목록 페이지와 함께 모바일 환경 대응
- [x] MSW를 활용하여 실제 서버와 연동될 수 있는 API Mocking 구현
- [x] 단순한 Endpoint변경으로 실제 API 사용이 가능하도록 작업
- [x] 장바구니 페이지에서 다양한 사용자 인터렉션에 대한 테스트 케이스를 고민하고, 선택한 테스트 도구를 이용하여 검증
- [x] 새로고침 해도, 장바구니에 담은 상품 유지

## 🔗 링크
[홈페이지 링크](https://gc-park.github.io/react-shopping-cart/)
[스토리북 링크](https://gc-park.github.io/react-shopping-cart/storybook)

2023-05-23 10:34 UTC, InSeong-So requested changes
리뷰가 늦었습니다🙇‍♂️🙇‍♂️🙇‍♂️🙇‍♂️🙇‍♂️🙇‍♂️🙇‍♂️🙇‍♂️
빠르게 진행해볼게요!

데모를 확인해보니 반응형이나 체크박스 기능은 잘 동작하네요! 크게 디자인 적으로 깨지지도 않고, 불편하다고 느껴지는 부분도 적습니다. 고생했어요👏👏👏

패트릭의 코드를 보면서 일관되게 느낀 불편함은 `refetch`인 것 같습니다. 훅으로 있어야 하는지, 함수로 래핑한 이유와 메모이제이션이 되지 않은 부분, 패치 함수의 에러 핸들링 등이겠네요!

그리고 체크박스를 전역 상태로 관리한 부분도... 흠... 지역으로도 충분하지 않을까 하는 생각은 있습니다. 선택 여부 정도만 서버에서 갖는다고 하면, 컴포넌트로서의 체크박스는 지역 상태로도 커버할 수 있을 것 같거든요.

우선 리뷰 몇 가지 남겼는데, 확인해주세요!
미션이 많이 어려울텐데... 피드백 확인 후 재요청 주세요!

고생 많았습니다👏

2023-05-23 10:34 UTC, InSeong-So commented on src/hooks/useCartList.ts
> +    setCheck(false);
```suggestion
    setCheck(checkBox.length === checkBoxTotalId.length);
```

2023-05-23 10:34 UTC, InSeong-So commented on src/hooks/useCartList.ts
> +    if (e.target.checked) {
이벤트 타입은 `React`를 사용하네요...? 이유가 있을까요?

2023-05-23 12:33 UTC, GC-Park commented on src/components/ProductList/AddCartButton.stories.tsx
> +      id={3}
저장이 안되서 정렬이 안됐던 것 같습니다!!

(혹시 id값에 {3} 넣어준 것에 대한 물음일까요?!! 정렬과 id값 중 어떤 의미의 질문인지 헷갈려서요!)

2023-05-23 12:34 UTC, GC-Park commented on src/mocks/browser.ts
> +export const worker = setupWorker(...handlers)
오?!! 혹시 세미콜론이 없어서?!!! 맞을까요?!! 오..!!

2023-05-23 12:36 UTC, GC-Park commented on src/styles/reset.ts
> +body,
css의 공통된 폰트 스타일을 주기 위해 풀었었습니다! 혹시 풀면 안 됐던 것일까요?!

2023-05-23 12:45 UTC, GC-Park commented on src/utils/fetchApi.ts
> +    throw new Error(`api 요청을 실패했습니다! status: ${response.status}`);
try-catch문을 왜 생각하지 못했을까요?!!! 너무나 동의합니다! 수정하도록 하겠습니다!

2023-05-24 05:41 UTC, GC-Park commented on src/components/common/Header/index.tsx
> +  };
메모이제이션을 많이 적용해보고 싶었으나 기능 구현 하는데 정신이 팔려 제대로 공부도 못해보고 제출하였습니다 흑흑..

그래도 파랑이 메모이제이션의 중요성을 알려주셔서 리뷰 제출하고 바로 메모이제이션을 공부해 학습로그에 적었습니다!

지금부터라도 열심히 적용해 보도록 하겠습니다! 감사합니다!!

2023-05-25 03:41 UTC, InSeong-So commented on src/components/ProductList/AddCartButton.stories.tsx
> +      id={3}
Id가 상수로 들어가있어서 남긴 코멘트입니다!

2023-05-25 08:52 UTC, InSeong-So commented on src/styles/reset.ts
> +body,
오 아닙니다! 문제는 아니에요. *.min* 파일은 공백을 제거해서 용량을 줄였다라는 이름으로 많이 사용하거든요.
기존에는 공백이 제거된 상황이었어서 의도하고 풀은건가 했어요!

2023-05-25 08:53 UTC, InSeong-So commented on src/mocks/browser.ts
> +export const worker = setupWorker(...handlers)
너무 코드 스타일이었나 싶네요🥲 프리티어 설정이 어딘 되어있고 안되어있고가 좀 보여서 적은 코멘트였습니다.

2023-05-25 10:27 UTC, GC-Park commented on src/components/common/CheckBox/index.tsx
> +};
React.InputHTMLAttributes<HTMLInputElement>을 상속하여 쓰도록 수정하였습니다!!

+추가
HTMLInputElement을 직접 상속하려고 하면 DOM 인터페이스를 상속하려는 시도합니다. 그러나 리액트는 가상Dom을 사용하기 때문에 리액트에서는 바인딩이 제대로 작동하지 않을 수 있다는 것을 알았습니다!

대신 React.InputHTMLAttributes<HTMLInputElement>를 사용하면 React에서 사용되는 속성들을 올바르게 제공해서 React 컴포넌트와의 연동이 원활하게 이루어집니다!

2023-05-26 01:35 UTC, GC-Park commented on src/components/common/Button/index.tsx
> +};
바로 위의 리뷰와 비슷하게 React.ButtonHTMLAttributes<HTMLButtonElement>을 상속받아 onClick을 props에서 지울 수 있었습니다!

'style props 컨벤션도 만들어두면 어떨까요?'를 해결하기 위해 많이 찾아봤는데 찾을 수 없었습니다. 혹시 힌트를 조금 더 받을 수 있을까요?!!

2023-05-26 04:48 UTC, GC-Park commented on src/components/CartList/CartItem.tsx
> +export default React.memo(CartItem);
직관적인 원시형 props가 많다고 생각해서 메모이제이션을 적용했었는데 refetch 생각을 못했네요!!!

큰 차이가 없을 것 같습니다! 수정하도록 하겠습니다!

2023-05-26 04:53 UTC, GC-Park commented on src/components/CartExpectedPrice/index.tsx
> +export default React.memo(CartExpectedPrice);
memo 필요 없을 것 같습니다! 

그래도 메모이제이션에 대해 공부하고 다시 보니 조금은 알 것 같습니다!

수정하도록 하겠습니다!

2023-05-26 05:09 UTC, GC-Park commented on src/components/CartList/CartItem.tsx
> +    deleteItem();
아이고 ..! removeItem안에서 await을 쓰고 있다가 지울때 같이 못지운 것 같습니다!!

바로 삭제하도록 하겠습니다. 감사합니다!

2023-05-26 05:12 UTC, GC-Park commented on src/hooks/useControlCart.ts
>      const updatedCart = cart.filter((product) => id !== product.id);
아이고 아이고..! 이것도 위에처럼 await을 쓰다 같이 지우지 못한 것 같습니다!

삭제하도록 하겠습니다!

2023-05-27 03:20 UTC, GC-Park commented on src/components/CartExpectedPrice/index.tsx
> +              : (cartTotalPrice + 3000).toLocaleString('ko-KR')}
cartTotalPrice가 부정형인 경우는 장바구니에 품목이 없거나 선택이 모두 삭제 되었을 때 숫자 0이 되어 false가 됩니다!

cartTotalPrice 앞에 !를 넣어주었기 때문에 0원이 되어 false가 되면 true로 인식한 후 '0'이 출력이 되게 했습니다!

배송비를 출력하는 부분에서도 `{!cartTotalPrice ? '0' : '3,000'}` 이렇게 넣어주었는데 품목이 하나도 없으면 배송비도 0원으로 출력되게 했습니다!

2023-05-27 03:51 UTC, GC-Park commented on src/components/ProductList/ProductItem.tsx
> +          addProductToCart={() => addProductToCart(product)}
addProductToCart함수에는 id, name, price, imageUrl이 들어가있는 product가 인자로 필요했기에 이것을 가지고 있는 ProductItem에서 호출 후 넘겨주었습니다.

그런데 useControlCart를 호출 해 addProductToCart을 넘겨주는 것보다 product를 넘겨주는 것이 렌더링에 조금 더 유리할 수도 있겠다 생각이 들었습니다.

파랑의 리뷰를 참고해 수정 후 렌더링을 확인해보니 원래 장바구니가 추가되면 렌더링 되던 ProductItem 컴포넌트가 렌더링 되지 않고 AddCartButton 부분만 렌더링 되는 것을 확인할 수 있었습니다! 

기능 구현도 정말 중요하지만 이러한 최적화 부분도 많이 고민할 수 있도록 노력하겠습니다. 감사합니다!

2023-05-27 04:20 UTC, GC-Park commented on src/hooks/useGetFetch.ts
> +  }
습관적으로 wrapping을 한 것 같습니다 허헣 😂  

외부로부터 의존성이 없으니 `const refetch = fetchData`로 써도 될 것 같습니다! 수정하겠습니다!

2023-05-27 04:33 UTC, GC-Park commented on src/hooks/useControlCart.ts
> +      return product;
동의합니닷!! 수정하도록 하겠습니다!!!

2023-05-27 04:34 UTC, GC-Park commented on src/hooks/useCartList.ts
> +    setCheck(false);
코드를 깔끔하게 작성할 수 있도록 노력하겠습니다!! 이렇게 꼼꼼하게 리뷰 해주셔서 정말 감사합니다!!

2023-05-27 05:03 UTC, GC-Park commented on src/components/ProductList/index.tsx
>    return (
앞으로 대행 문자에 신경 쓰도록 하겠습니다!!

또한 수동 저장을 습관화 해서 prettier 적용을 꼭 시키도록 하겠습니다! 감사합니다!

2023-05-28 01:00 UTC, GC-Park commented on src/hooks/useControlCart.ts
> +  );
checkBoxTotalId 관련 필드를 삭제하고 장바구니 목록으로 대체하였습니다!

그러나 장바구니 페이지에서 물품을 하나씩 삭제할 때 마지막 상품 삭제 후 header의 장바구니 갯수가 변경되지 않는 에러가 발생합니다 😭
어제 하루종일 고민했는데 결국 원인을 찾지 못하고 리뷰를 보냅니다...🥲

혹시 파랑의 도움을 받을 수 있을까요?!

2023-05-28 01:01 UTC, GC-Park commented on src/hooks/useControlCart.ts
> +    const updatedCheckBoxTotalId = checkBoxTotalId.filter(
밑의 리뷰를 수행하며 updatedCheckBoxTotalId를 지울 수 있었습니다!

2023-05-28 01:06 UTC, GC-Park commented on src/hooks/useGetFetch.ts
> +    }
맞습니다!! 에러 부분에 대해 신경쓰지 못했던 것 같습니다 허헣..!

수정하도록 하겠습니다. 감사합니다!

2023-05-28 01:41 UTC, GC-Park commented on src/components/common/BucketCounter/index.tsx
> +  };
원래 만들어져 있던 useBucketCounter로 옮길 수 있었습니다. 

기능 구현 당시에는 refetch함수를 넣을 때 에러가 나서 뺄 수 없다고 생각했는데 이번에는 refetch함수가 인자로 쉽게 들어갔습니다. 

그리고 파랑의 말씀대로  fetchApi 함수가 반복되던 것을 다른 함수로 분리해 보기 좋게 바꿀 수 있었습니다.

사실 이 리뷰는 내가 할 수 있을지 자신감이 안 생겨 계속 피했던 것 같습니다. 제대로 분리했는지 확신은 없지만 생각보다는 쉽게 분리할 수 있었습니다.

여전히 훅으로 분리하는 것은 정말 어렵네요... 허헣 그래도 파랑 덕분에 많은 시도를 해볼 수 있었습니다. 정말 감사합니다.

2023-05-28 01:48 UTC, GC-Park commented on src/components/CartList/index.tsx
> +              refetch={refetch}
저도 refetch 함수를 분리할 수 있다면 정말 좋을 것 같습니다! 그러나.. 감이 안 잡힙니다.. 흑흑 😂 

useGetFetch에서 반환을 해주는 것이고 useCartList에서 불러오는 것이니 '이미 분리되어 있는 것이 아닌가.'라는 생각이 듭니다! 

혹시 힌트를 조금 더 받을 수 있을까요?

2023-05-28 02:09 UTC, GC-Park commented
안녕하세요 파랑! 

피드백 적용을 마치고 돌아왔습니다! 정말 길었던 한 주였습니다 🤣

지금까지 리뷰 중 가장 많은 리뷰를 받기도 했고 최대한 완벽하게 리뷰 반영을 하고 싶은 욕심에 시간이 오래 걸린 것 같습니다.

그러나 저의 역량 부족으로 반영하지 못한 것들도 있고 아예 손대지 못한 부분도 있습니다. 이러한 부분들은 코멘트로 남겨두었고 파랑의 도움을 받고 싶은 마음입니다!

이번 피드백도 잘 부탁드리겠습니다! 감사합니다!

2023-05-30 05:44 UTC, InSeong-So commented on src/hooks/useCartList.ts
> +    if (e.target.checked) {
음? 아 그런 맥락이 아니라...
`React.`으로 전개한, import가 왜 다른지에 대한 코멘트입니다ㅎ 구조 분해 할당을 사용하지 않은 이유가 있나 해서요

2023-05-30 05:45 UTC, InSeong-So commented on src/components/common/CheckBox/index.tsx
> +};
InputHTMLAttributes의 제네릭으로 네이티브 속성을 같이 넘겨주면 된답니다😊 잘 공부했네요

2023-05-30 05:47 UTC, InSeong-So commented on src/components/common/Button/index.tsx
> +};
이걸 참고해볼까요?
[스타일드 컴포넌트](https://styled-components.com/docs/api#transient-props)

2023-05-30 05:48 UTC, InSeong-So commented on src/components/CartExpectedPrice/index.tsx
> +              : (cartTotalPrice + 3000).toLocaleString('ko-KR')}
`0`이 문제라고 생각되네요. 암묵적 타입 변환을 전역적으로 허용하게 되는 상황이라, 이 부분을 명확하게 조건 처리하는 게 좋을 것 같습니다. 장바구니에 담되, 0개가 되는 상황도 없진 않을 것 같아요.

2023-05-30 05:49 UTC, InSeong-So commented on src/components/CartList/index.tsx
> +              refetch={refetch}
`refetch라는 함수를 내려주는 것이 옳은가`에 대한 고민입니다. 해당 내용물이 패치만 해오는 함수의 래핑이라면, 그저 CartItem에서 저 훅을 호출하는 게 좋지 않을까 싶어요.

2023-05-30 05:52 UTC, InSeong-So commented on src/hooks/useControlCart.ts
> +  );
음 이건 패트릭이 미션 중 시간 날 때 디엠을 한 번 주면 좋겠네요😊

문제로 생각되는 것은 `마지막 상품 삭제 후`라고 했을 때에요. 로컬 스토리지에서 get/set을 지속적으로 해오는데, 어떤 행위에서 싱크가 맞지 않은 상황이 있지 않을까 싶습니다.

2023-05-30 05:54 UTC, InSeong-So approved these changes
협업 미션이 힘들텐데, 잘 참아주었어요!
코드는 크게 고칠 부분이 보이지 않아요. 당장 없다는 것이지, 코멘트의 답글로 남겨놓은 내용처럼 `암묵적인` 허용이 몇 개 존재합니다.

협업 미션 이후 패트릭이 작성한 코드를 다시 한 번 보고, 구조적인 문제가 없는지, 훅을 좀 더 잘 쓸 수 있는지, 컴포넌트의 책임은 적당한지 고민해보면 좋겠습니다.

코멘트 답변만 확인해주세요.
미션 고생 많았어요! 협업 미션도 파이팅입니다💪

2023-05-30 05:54 UTC, merged