[장바구니 미션 Step 2] 라잇(강영민) 미션 제출합니다.
woowacourse/react-shopping-cart pull request #225
Opened 2023-05-22 07:43 UTC by kangyeongmin

2023-05-24 07:07 UTC, JeongBin0227 commented
>  케빈도 같은 파일에서 여러 컴포넌트?를 선언하여 사용하는 경우를 보셨을까요?! 궁금합니다!

네 당연하게 같은 파일에서 여러 컴포넌트를 선언하여 사용하는 경우가 있을 수 있습니다.
그것보다도 각 관련된 컴포넌트들 사이의 의존성을 명확하게 표현하고, 관심사를 정확하게 분리하여 이해하기 쉽고 유지보수가 쉽게 하는게 더 중요해 보입니다. 바꾸신 구조는 이전 구조보다 더 명확하고 좋아보이네요~

2023-05-24 07:13 UTC, JeongBin0227 commented
> 현재 useFetch 훅을 보시면, 프론트에서 사용하기 쉬운 형태로(+ step1의 구조를 사용하려다 보니) api에서 fetch 해온 products와 cartItems들을 가공하여 recoil의 productsState에 저장하고 있습니다. 그래서 컴포넌트 리렌더링이 필요할때마다, 새로 recoil의 productsState를 set하고 있는데, 새로운 set을 하기 위해서는 products와 cartItems을 다시 get해야만 합니다.(매우 비효율적인 구조라고 생각이 듭니다..)

제가 텍스트만으로 명확하게 이해한지는 모르겠으나, 제가 이해한 바에서 좀더 랜더링 관련 개선을 해보자면 
데이터 가져오는 부분(get) 과 로직을 분리하여 필요한 경우에만 데이터를 다시 가져오고, 가공 로직은 재사용 가능한 함수로 분리하여 성능을 개선할수있을거 같아요. 또  productsState를 Recoil의 atom이 아닌 selector로 정의하고, 데이터 가공 로직을 selector에서 수행하여 필요한 경우에만 리렌더링을 가져오면서 성능을 개선할수도 있을거 같아요. 제가 만약 잘못이해했으면 다시 알려주세요~

2023-05-24 07:24 UTC, JeongBin0227 requested changes
안녕하세요 라잇~

많이 고민해주셨다고 해서 인지 코드가 많이 깔끔하고 가독성이 좋았던거 같아요!

궁금해주셨던 부분이나 코멘트 드리고 싶은 부분 남겨두었습니다.
중간에 제가 이해를 제대로 했던것인지 애매한 부분이 있었는데 잘못 이해한거라면 다시 말씀부탁드립니다!

스텝2 하느라 고생하셨습니다 👍

2023-05-24 07:24 UTC, JeongBin0227 commented on public/mockServiceWorker.js
> +const INTEGRITY_CHECKSUM = '3d6b9f06410d179a7f7404d4bf4c3c70'
이 값은 무엇일까요??
만약 중요한 값이라면 env 파일로 따로 보관해도 좋겠네요

2023-05-24 07:24 UTC, JeongBin0227 commented on public/mockServiceWorker.js
> +}
이건 번외 얘기인데, 개인적으로 이런 서비스 워커를 할때, 환경에 따라서 (개발환경, 프로덕트 환경) 설정이 중요해서 환경에 따라 스위칭하는 것에 대해서 공부를 해보면 좋을거 같아요

2023-05-27 08:30 UTC, kangyeongmin commented on src/hooks/useCheckBox.ts
> +  );
useCheckBox에서 선택된 Products 객체배열인 recoil atom을 set해주어서 전역적으로 관리가 되고 있습니다!
선택된 Products객체 배열은 나중에 주문하기 기능이 추가됨을 미리 생각하여 전역적으로 관리합니다.

보통 커머스 사이트에서 장바구니 페이지에 들어가면 아이템들이 모두 선택됨의 상태로 해두는 것을 많이 보아서, 저도 초기값을 true(선택됨)으로 설정해두었습니다.
Array.from 이라면
```javascript
Array.from({ length : cartProducts.length}, () => true)
```
으로 쓸 수 있을 것 같은데, 위 방법을 더 추천해주시는 이유가 있으실까용??

2023-05-27 08:46 UTC, kangyeongmin commented on src/hooks/useCheckBox.ts
> +  };
두 배열의 주소값이 같기 때문에 splice를 통해 원본배열을 수정하고 새로 set하는 것이 의미 없는 로직이었군요..!

수정하겠습니다!!

2023-05-27 08:47 UTC, kangyeongmin commented on src/hooks/useQuantity.ts
> +  );
currentProduct로 변경해보았습니다!

2023-05-27 08:48 UTC, kangyeongmin commented on src/hooks/useQuantity.ts
> +      e.target.value === "-0" ||
사용자가 빈값을 입력하거나, -0과 같은 예외적인 숫자를 입력할 시에 둘다 quantity를 0으로 처리하는 로직입니다!

2023-05-27 08:51 UTC, kangyeongmin commented on public/mockServiceWorker.js
> +const INTEGRITY_CHECKSUM = '3d6b9f06410d179a7f7404d4bf4c3c70'
해당 파일은 msw를 브라우저에서 사용하기 위해서 MSW를 서비스 워커에 등록하기 위한
```bash
npx msw init public/ --save
```
명령어를 쳤을 때, 자동으로 생성되는 파일이었습니다!

자동으로 생성되는 파일이기에 수정을 지양하였는데, 그래도 env 파일로 보관하는 것이 좋을까요?

2023-05-27 08:52 UTC, kangyeongmin commented on public/mockServiceWorker.js
> +}
넵! 알겠습니다

2023-05-27 08:58 UTC, kangyeongmin commented
안녕하세요 케빈~

장바구니 협업 미션을 진행하느라 리뷰 반영이 늦어졌네요 ㅠㅠ

현재 협업 미션에서 페어와의 조율 후에
제 코드가 선정되어 해당 프로젝트를 더 고도화 하고 있는 단계에 있는데요!!

따라서, 이번 리뷰 요청에서는 최대한 코멘트 주신 것만 반영하고 
현재 협업 미션의 프로젝트(shopping-cart-prod)의 코드 리팩토링에 박차를 가할 예정입니다!!

이때까지 리뷰해주셔서 감사했습니다!! ☺️

2023-05-28 05:11 UTC, JeongBin0227 approved these changes
안녕하세요 라잇!

수정해주신 부분 확인했습니다~ 해당 프로젝트를 더 고도화 하고 있는 단계가 있다고 하셔서 잘 수정하시면서 프로젝트 잘마무리 하셨으면 좋을거 같아요!

장바구니 미션 하느라 고생많으셨습니다! 
이번 미션은 여기서 머지하겠습니다 다음 미션도 화이팅입니다! 💯

2023-05-28 05:11 UTC, merged