[1단계 - 장바구니 미션] 파란(안영훈) 미션 제출합니다.
woowacourse/react-shopping-cart pull request #246
Opened 2024-05-16 05:56 UTC by greetings1012

# 🚀 프로젝트 실행 방법

.env 파일을 파일 최상위에 저장
npm i
npm run dev

.env 파일은 슬랙 DM으로 드릴게요!

## 🧪 테스트 확인

npm run test

## 😄 신경 쓴 부분

전체적으로 사용자가 불편한 경험을 하지 않는 것을 목표로 프로젝트를 구현했어요.
잘못된 접근의 경우 에러 페이지와 함께 다시 메인 페이지로 돌아가는 버튼을 제공했고, 처음 장바구니 화면을 불러올 때 loader로 fetchCartItemList()를 전달함으로서 사용자가 미완성된 화면을 보지 않도록 했어요.

## 😭 놓친 부분

서버 통신 중 발생하는 error를 캐치하기 위해 ErrorBoundary를 사용하려고 했지만, fetch 로직 자체가 이벤트핸들러 안에서만 실행되어 ErrorBoundary로 에러를 잡아낼 수 없었어요. error를 밖으로 빼내면 ErrorBoundary를 사용할 수 있을 것 같은데, 조금 더 공부 후 가능하면 리팩터링할 때 적용해보려고 해요.

## 🙋 궁금한 점

Suspense를 사용하는 이유를 찾지 못했어요. Suspense를 테스트하는 과정에서 

1. loader를 전달해 초기 화면을 불러옴과 동시에 비동기적으로 초기 데이터 fetch
2. 일단 초기 화면을 불러온 후 Suspense로 로딩중 ui를 표시함과 동시에 데이터 fetch

둘의 속도 차이를 비교했지만, loader를 전달하는 쪽이 '빠른 3g' 환경에서도, 보통 환경에서도 속도가 압도적으로 빨랐어요.
네트워크가 느린 상황이면 어차피 페이지를 불러오는 것 자체가 느릴 것이고, 네트워크가 빠른 경우에는 비동기적으로 데이터를 fetch하는 loader 사용 환경이 더 빠른 동작을 보장한다고 생각하는데 카일의 의견이 궁금해요!

## 🖼️ 컴포넌트 설계

![스크린샷 2024-05-16 오후 2 50 40](https://github.com/woowacourse/react-shopping-cart/assets/41965535/493d4a0f-0106-4fa3-a58a-91f5b2684a2b)

리뷰 잘 부탁드립니다!

## 🌲 파일 구조

📦src
 ┣ 📂apis
 ┃ ┗ 📜index.ts
 ┣ 📂assets
 ┃ ┣ 📂images
 ┃ ┃ ┣ 📂CheckIcon
 ┃ ┃ ┃ ┣ 📜CheckedIcon.svg
 ┃ ┃ ┃ ┗ 📜UncheckedIcon.svg
 ┃ ┃ ┣ 📜EmptyCart.png
 ┃ ┃ ┣ 📜InfoIcon.svg
 ┃ ┃ ┣ 📜LeftArrow.svg
 ┃ ┃ ┣ 📜MainLogo.svg
 ┃ ┃ ┣ 📜MinusIcon.svg
 ┃ ┃ ┗ 📜PlusIcon.svg
 ┃ ┗ 📜index.ts
 ┣ 📂components
 ┃ ┣ 📂Button
 ┃ ┃ ┣ 📂CheckButton
 ┃ ┃ ┃ ┣ 📜CheckButton.style.tsx
 ┃ ┃ ┃ ┗ 📜CheckButton.tsx
 ┃ ┃ ┗ 📂SubmitButton
 ┃ ┃ ┃ ┣ 📜SubmitButton.style.tsx
 ┃ ┃ ┃ ┗ 📜SubmitButton.tsx
 ┃ ┣ 📂CartItem
 ┃ ┃ ┣ 📜CartItem.style.tsx
 ┃ ┃ ┗ 📜CartItem.tsx
 ┃ ┣ 📂CartItemList
 ┃ ┃ ┣ 📜CartItemList.style.tsx
 ┃ ┃ ┗ 📜CartItemList.tsx
 ┃ ┣ 📂Container
 ┃ ┃ ┣ 📂PriceContainer
 ┃ ┃ ┃ ┣ 📜PriceContainer.style.tsx
 ┃ ┃ ┃ ┗ 📜PriceContainer.tsx
 ┃ ┃ ┣ 📂QuantityContainer
 ┃ ┃ ┃ ┣ 📜QuantityContainer.style.tsx
 ┃ ┃ ┃ ┗ 📜QuantityContainer.tsx
 ┃ ┃ ┣ 📂TitleContainer
 ┃ ┃ ┃ ┣ 📜TitleContainer.style.tsx
 ┃ ┃ ┃ ┗ 📜TitleContainer.tsx
 ┃ ┃ ┗ 📂TotalPriceContainer
 ┃ ┃ ┃ ┣ 📜TotalPriceContainer.style.tsx
 ┃ ┃ ┃ ┗ 📜TotalPriceContainer.tsx
 ┃ ┗ 📂Header
 ┃ ┃ ┣ 📜Header.style.tsx
 ┃ ┃ ┗ 📜Header.tsx
 ┣ 📂constants
 ┃ ┣ 📜MESSAGES.ts
 ┃ ┗ 📜PATHS.ts
 ┣ 📂data
 ┃ ┗ 📜cartItemListMockData.ts
 ┣ 📂pages
 ┃ ┣ 📂ErrorPage
 ┃ ┃ ┣ 📜ErrorPage.style.tsx
 ┃ ┃ ┗ 📜ErrorPage.tsx
 ┃ ┣ 📂OrderConfirmPage
 ┃ ┃ ┣ 📜OrderConfirmPage.style.tsx
 ┃ ┃ ┗ 📜OrderConfirmPage.tsx
 ┃ ┗ 📂ShoppingCartPage
 ┃ ┃ ┣ 📜ShoppingCartPage.style.tsx
 ┃ ┃ ┗ 📜ShoppingCartPage.tsx
 ┣ 📂recoil
 ┃ ┣ 📂atoms
 ┃ ┃ ┣ 📜atoms.test.ts
 ┃ ┃ ┗ 📜atoms.ts
 ┃ ┗ 📂selectors
 ┃ ┃ ┣ 📜selectors.test.ts
 ┃ ┃ ┗ 📜selectors.ts
 ┣ 📂styles
 ┃ ┣ 📜Global.style.tsx
 ┃ ┗ 📜theme.ts
 ┣ 📂types
 ┃ ┣ 📜CartItem.type.ts
 ┃ ┗ 📜Product.type.ts
 ┣ 📂utils
 ┃ ┣ 📜auth.ts
 ┃ ┗ 📜calculateDeliveryFee.ts
 ┣ 📜App.tsx
 ┣ 📜index.css
 ┣ 📜main.tsx
 ┗ 📜vite-env.d.ts

2024-05-17 02:41 UTC, igy95 requested changes
안녕하세요 파란~ 다시 만나게 되었네요 :) 미션 수행하시느라 고생 많으셨고 세부 코멘트 확인 부탁드릴게요! error boundary에 대해서는 이 [섹션](https://legacy.reactjs.org/docs/error-boundaries.html#introducing-error-boundaries)의 Note 부분을 위주로 좀 더 읽어보면 좋을 것 같습니다 😀

2024-05-17 02:41 UTC, igy95 commented on src/utils/calculateDeliveryFee.ts
> +export const DELIVERY_FEE_DISCOUNT_THRESHOLD = 100000;
기본 배달 비용과 배달비를 안내도 되는 한도가 제품마다 달라져야 하는 니즈가 생기게 되면, 이 함수에서는 어떤 식으로 재사용성을 열어줄 수 있을까요?

2024-05-17 02:41 UTC, igy95 commented on src/recoil/atoms/atoms.ts
`atoms`, `selectors` 두 레이어로만 나누게 되면, 모든 리코일 상태가 이 두 파일에만 선언될텐데 이렇게 되면 파일이 금방 비대해지지 않을까요? 상태를 모아둔 파일도 긴밀한 관계를 가진 상태끼리 분류해두면 어떨까요?

2024-05-17 02:41 UTC, igy95 commented on src/constants/PATHS.ts
> +  BASE: '/react-shopping-cart/',
```suggestion
  BASE: '/react-shopping-cart',
```

뒤에도 `/`가 붙어있으면 path끼리 조합할 때 `//`가 생기는 경우가 있을 것 같아요!

2024-05-17 02:41 UTC, igy95 commented on src/data/cartItemListMockData.ts
> +};
😂

2024-05-17 02:41 UTC, igy95 commented on src/pages/ErrorPage/ErrorPage.tsx
> +          </p>
error fallback page는 사용자가 어떠한 앱 내에서 어떠한 문제를 마주했을 때 해당 문제가 발생했음을 인지하고 어떻게 대처해야하는지 가이드를 해줘야하는 것이 가장 주된 목적이라고 생각합니다. 하지만 현재 `ErrorPage`를 보면 예상하는 모든 에러 케이스에 대한 메시지를 담고 있기에 사용자 입장에서는 구체적으로 어떤 문제가 발생했는지 쉽게 알 수 없을 것 같아요!

에러를 다루는 방식까지는 현재 요구사항은 아니기에 지금 바로 수정하실 필요는 없지만, 이러한 부분에 대해 한번쯤은 고민해보면 좋을 것 같습니다 ㅎㅎ

2024-05-17 02:41 UTC, igy95 commented on src/App.tsx
> +      loader: () => fetchCartItemList(),
> Suspense를 사용하는 이유를 찾지 못했어요.

에 대한 답변은 여기에 남겨둘게요 !

어떠한 도구나 방법론을 사용할 때 여러 고려사항이 있겠지만 크게는 아래와 같은 사항이 있다고 생각해요.

- 성능
- DX
- 유지보수, 확장을 위한 유연성
- 다른 사람이 코드를 읽을 때 바로 이해 가능한 구조인지
- 현재 프로젝트 내에서 설계한 아키텍처
- 사용 중인 (혹은 사용 예정인) 라이브러리 간 트레이드 오프 비교

때문에 Suspense도 마찬가지로 성능 외에도 다른 사항이 폭넓게 검토되어야 한다고 생각하지만, 그럼에도 현재 구조에서 Suspense의 이점을 잘 모르겠다면 꼭 쓸 필요는 없다고 생각합니다.

다만 `loader` 필드로 data를 fetch 할 수 없는 영역도 있을 것이기 때문에 그러한 부분도 염두에 두면 좋겠네요!

2024-05-17 02:41 UTC, igy95 commented on src/components/CartItemList/CartItemList.tsx
> +    else setSelectedItemList(cartItemList);
```suggestion
    setSelectedItemList(isAllSelected ? [] : cartItemList);
```

2024-05-17 02:41 UTC, igy95 commented on src/recoil/atoms/atoms.ts
> +  };
각 사용처에서 local storage에 접근 가능할 듯 한데, 이 값을 atomEffect로 다룬 이유가 궁금하네요!

2024-05-17 03:15 UTC, greetings1012 commented on src/recoil/atoms/atoms.ts
> +  };
관심사 분리를 중심으로 생각했어요.
ShoppingCartPage에서 localStorage 접근 코드를 관리하게 하면 handler의 길이도 길어지고, selectedCartItemListState를 수정할 때에만 localStorage에 접근하기 때문에 AtomEffect로 선언하여 관리하도록 했습니다!

2024-05-17 03:28 UTC, greetings1012 commented on src/types/Product.type.ts
> +export type TProduct = {
원래는 CartItemProps 등 ~Props 접미사를 붙이는 방식을 사용했었어요.
그런데 CartItem 컴포넌트가 등장하면서 CartItemProps가 2개가 되어야 하는 상황이 발생했어요.
(서버에서 fetch한 아이템의 type과 CartItem 컴포넌트의 interface)
위와 같은 이유때문에 interface에는 props 접미사를 사용하고 type alias에는 헝가리안 컨벤션을 사용하게 되었습니다!

2024-05-17 05:24 UTC, greetings1012 commented on src/constants/PATHS.ts
> +  BASE: '/react-shopping-cart/',
수정했습니다! 그런 경우를 생각을 못했네요 🥹

2024-05-17 05:28 UTC, greetings1012 commented on src/styles/theme.ts
> +const boxHeight = '64px';
small, medium, large 3 개의 값을 지정해놓으면 다양한 박스의 높이와 반응형 ui 적용 등에 유용하게 쓸 수 있겠네요!
수정했습니다!

2024-05-17 05:29 UTC, greetings1012 commented on src/utils/auth.ts
> +export function generateBasicToken(userId: string, userPassword: string): string {
주석 추가했습니다!

2024-05-17 06:42 UTC, greetings1012 commented on src/App.tsx
> +      loader: () => fetchCartItemList(),
현재 상황에서는 Suspense와 loader의 유의미한 차이를 찾기 힘들지만,
추후 한 페이지 안에서 여러 컴포넌트들이 따로 데이터를 fetch해오거나 하는 경우에는 Suspense가 유용하게 쓰일 수 있겠네요!
제가 너무 지금 프로젝트의 경우에만 갖혀 생각을 한 것 같아요.

상세한 답변 감사합니다!

2024-05-17 06:57 UTC, greetings1012 commented on src/utils/calculateDeliveryFee.ts
> +export const DELIVERY_FEE_DISCOUNT_THRESHOLD = 100000;
step2를 살짝 엿보고 왔을 때 도서산간 지역, 해외 등일 경우의 추가 배송비와 쿠폰을 통한 할인 등의 조건이 많이 생겨났는데, 
이 경우에는 도서산간 지역의 추가 배송비 등을 const로 선언한 후 할인 여부 등을 인자로 받아 계산하는 로직을 추가할 것 같아요!
한도 또한 함수의 인자로 전달받도록 바꿀 수 있을 것 같습니다!

2024-05-17 08:08 UTC, greetings1012 commented on src/pages/ErrorPage/ErrorPage.tsx
> +          </p>
피드백을 보고 에러 페이지가 어떻게 에러 상황을 반영할 수 있을까 고민해 보았어요.
useNavigate를 통해 errorpage로 넘어가는 부분에서 state를 통해 상수화된 에러 메시지를 전달하는 기능을 구현했습니다!

2024-05-18 03:19 UTC, igy95 commented on src/types/Product.type.ts
> +export type TProduct = {
모든 interface가 컴포넌트의 props로만 사용되는 건 아니기 때문에 'interface에는 props 접미사를 붙여야한다'는 전제가 수정되어야 하지 않을까 싶네요! 인터페이스는 최대한 개체를 나타내는 이름 나체로 명시적으로 담는 것을 권장하고 각 레이어나 확장된 타입에 맞게 이름을 적절히 붙여주는 것이 좋을 것 같습니다.

```ts
// 원본 데이터
interface Product {}

// 파생 데이터
interface CartProduct extends Product {}

// 컴포넌트의 props
interface ProductItemProps {
  product: Product
}
```

2024-05-18 03:20 UTC, igy95 commented on src/pages/ErrorPage/ErrorPage.tsx
> +          </p>
넵 지금 단계에서는 나쁘지 않은 처리라고 생각합니다~

2024-05-18 03:24 UTC, igy95 commented on src/recoil/atoms/atoms.ts
> +  };
> selectedCartItemListState를 수정할 때에만 localStorage에 접근하기 때문에

이러한 사실은 언제든 바뀔 수 있기에 여기에 초점을 맞춰서 구조를 작성하셨다면 다시 고려해보면 좋을 것 같습니다.

만일 로컬 스토리지의 상태를 업데이트할 때 앱에서도 바로 동기화되길 바라는 목적으로 recoil과 결합한 것이라면 적절한 선택이라고 보이지만, 그게 아니라면 로컬 스토리지를 한번 감싼 유틸을 만들어 사용처에서 간편히 사용할 수 있는 형태로 제공하는 구조도 생각해볼 수 있을 것 같습니다~

2024-05-18 03:26 UTC, igy95 approved these changes
안녕하세요 파란! 빠르게 수정 후 재요청 주셨네요~ 코멘트가 추가로 필요한 부분은 달아두었으니 확인 부탁드리고 추가 수정은 다음 단계에서 같이 진행해주시면 좋을 것 같습니다 ㅎㅎ 다음 단계에서 뵈어요!

2024-05-18 03:26 UTC, merged

2024-05-24 02:39 UTC, chosim-dvlpr commented on src/pages/ShoppingCartPage/recoil/selector/selectedCartItemListSelector.ts
> +export const selectedCartItemListSelector = selectorFamily<boolean, TCartItem>({
selector 대신 selectorFamily를 사용하신 이유가 궁금합니다!

2024-05-24 02:42 UTC, chosim-dvlpr commented on src/pages/ShoppingCartPage/recoil/atom/selectedCartItemListState.ts
> +export const selectedCartItemListState = atom<TCartItem[]>({
api로 불러온 `cartItemList`는 atom으로 관리하지 않은 이유가 있을까요?