[1단계 - 장바구니 미션] 버건디(전태헌) 미션 제출합니다.
woowacourse/react-shopping-cart pull request #251
Opened 2024-05-16 08:11 UTC by brgndyy

추후 작성 예정

2024-05-16 09:30 UTC, brgndyy commented on src/store/atoms.ts
> +export const productsState = atom({
이 `productsState`가 결국에는 `fetchCartItems`라는 비동기 통신을 거쳐서 데이터를 받아오는 초기의 상태인데요..!

이번에 리코일을 처음 써보기도 했는데, 전역 상태 라이브러리에서 서버 상태까지 받아오는거를 처음 해봐서 많이 헷갈렸던것 같습니다.

저는 이 서버에서 초기에 products를 받아오는 부분을 '서버 상태'라고 생각했습니다.

그 후에 이 `products`에 대한 복제본을 하나 만들어서 `클라이언트 상태`로 구분해서 그거로 클라이언트측 상태를 정의해주려고 했는데요.

근데 또 복제본을 만들어주는것이 맞나? 라는 생각이 들었습니다.

서버 상태와 클라이언트 상태에 대한 기준을 어떻게 잡아야할까요 ?

클라이언트측에서 서버 데이터를 받는 순간, 그때부터는 무조건 클라이언트 상태가 되는것일까요 ?

2024-05-16 09:30 UTC, brgndyy commented on src/pages/cart/CartPage.tsx
> +      <Header>
여기서 각 페이지마다 다른 헤더 컴포넌트가 존재해야했는데요..!

각각의 헤더 컴포넌트의 레이아웃은 똑같지만 안에 내용물은 달라서, 헤더 컴포넌트 내부에서 `children` 부분의 컨텐츠만 갈아끼워주는 식으로 구현해보았습니다!

근데 아예 명시적으로 `CartPageHeader`나 `CheckoutPageHeader` 같이 각각의 헤더 컴포넌트를 만들어주는것이 저 가독성이 좋지 않나? 싶은 생각도 들어요!

브콜의 의견 한번 여쭤봐도 될까요 ?

```tsx
Header>
Comment
여기서 각 페이지마다 다른 헤더 컴포넌트가 존재해야했는데요..!

각각의 헤더 컴포넌트의 레이아웃은 똑같지만 안에 내용물은 달라서, 헤더 컴포넌트 내부에서 `children` 부분의 컨텐츠만 갈아끼워주는 식으로 구현해보았습니다!

근데 아예 명시적으로 `CartPageHeader`나 `CheckoutPageHeader` 같이 각각의 헤더 컴포넌트를 만들어주는것이 저 가독성이 좋지 않나? 싶은 생각도 들어요! 

동시에 단순 랩핑 그 이상의 의미가 없지 않나? 라고 의구심도 듭니다..! 

브콜의 의견 한번 여쭤봐도 될까요 ?

- CartHeader (내용물을 내부로 숨김)
```tsx
 <Header>
        <Button variant="header" onClick={handleHomeButtonClick}>
          SHOP
        </Button>
      </Header>
```

2024-05-16 09:30 UTC, brgndyy commented on src/hooks/useQuantityCount.ts
> +  const handleDecrementButton = async () => {
`handleIncrementButton`와 `handleDecrementButton` 이 두개의 로직이 +1 이나 -1만 다르고 전체 로직은 같아서 하나의 함수로 합쳐주어야지 라고 생각했었는데, 시간 관계상 이렇게 구현습니다..! 🥲

2024-05-16 09:45 UTC, brgndyy commented on src/pages/cart/components/CartTotals.tsx
컴포넌트 폴더구조에 관하여 여쭤보고 싶습니다!

현재 pages/해당페이지컴포넌트.tsx/components 안에 

페이지에 해당하는 컴포넌트들을 다 넣어주었는데요! 

src/components 안에는 현재 공용적으로 사용되는 common 컴포넌트들와 레이아웃만을 잡아주는 header 컴포넌트가 존재합니다! 

1. 공용적으로 사용되는 컴포넌트들은 /src/components 폴더안에
2. 페이지 컴포넌트 안에서 사용되는 도메인 관련 컴포넌트들은 pages/components 안에

이런식으로 기준을 잡아서 분리해본것인데, 컴포넌트 응집도를 이런식으로 가져가도 괜찮을까요..!? 

더 나은 컴포넌트 분리가 있을까요 ?

2024-05-16 22:17 UTC, brgndyy commented on src/hooks/useToggleIndividualChecked.ts
> +const useToggleIndividualChecked = ({ id, setAllChecked }: HookProps) => {
개별 아이템들의 체크 상태를 다루는 `useToggleIndividualChecked` 훅입니다.

만약 총 장바구니 데이터가 3개이고, 그중에서 3개가 전부 개별적으로 체크가 됐을때 인자로 받은 setAllChecked 를 true로, 하나라도 체크가 해제 된다면 setAllChecked를 false로 만들어주었는데요.

하나의 개별 체크 상태가 변화하더라도, 결국엔 모든 체크 상태를 순회하면서 모두 체크표시가 되어있는지 아닌지를 판별해야할것 같다고 판단했습니다.

그래서 불가피하게 `setAllChecked`라는 함수를 인자로 받을수 밖에 없었어요! (저 인자로 들어온 setAllChecked는 전역 상태가 아니고 지역상태의 setState입니다.)

근데 로직들을 커스텀훅으로 분리하다보니 setAllChecked가 인자로 들어오는 흐름이 어색하지 않나? 라고 생각이 들었어요.

만약 `setAllChecked`가 인자로 들어오지 않게 하면서도, 전체 체크 상태를 확인해주려면 setAllChecked를 전역 상태로 두어야할거 같은데요..

근데 이 setAllChecked 상태를 전역상태로 둘 필요가 있나? 싶기도 합니다 🥲

( 딱 저 CartList => CartItem의 흐름에서만 쓰이는 상태인거 같아서요..! )

브콜은 어떻게 생각하실지 한번 여쭙고 싶습니다!

2024-05-17 11:36 UTC, Tanney-102 requested changes
안녕하세요 버건디~
리뷰로는 처음뵙네요!
서버 상태에 클라이언트 상태 + 영속성까지.. 신경쓸게 많았을 미션이었네요 ㅎㅎ
질문주신 내용 포함해 코멘트 남겨두었으니 확인부탁드립니다!

2024-05-17 11:36 UTC, Tanney-102 commented on src/store/atoms.ts
> +});
추가로 그냥 id를 key로 해서 넣는 건 많이 위험해 보입니다.
product id라는 게 같은 product 안에서나 유일성이 보장되는 것이지 user id, cart id, ... 등 다른 도메인의 id과 섞이면 많이 혼란 스러울 것 같아요. 하나의 storage key에 하나의 date set을 관리하도록 해주세요.

ex)
```
LocalStorage {
  productCheckedState: {
    [id]: [isChecked]
  }
}
```

2024-05-17 11:36 UTC, Tanney-102 commented on src/store/atoms.ts
> +});
하나만 더 이야기 하자면..
어차피 true/false만 관리하면 되는 것이니 저라면 그냥 set으로 관리했을 것 같아요.

```
LocalStorage {
  checkedProductIds: ["...", ",,,", ...]
}

// 사용처
const checkedIds = new Set(JSON.parse(localStorage.get("checkedProductIds")))
```

2024-05-17 11:36 UTC, Tanney-102 commented on src/store/selectors.ts
> +      const product = products.find((item) => item.id === id);
data를 가져올 때 { [product.id]: product } 형태로 저장하는 방식을 고려해보셔도 좋을 것 같아요. 상품 정보처럼 배열형태로 가져오지만 사용처에서 id로 조회하는 케이스가 많은 경우에 유용합니다.

2024-05-17 11:36 UTC, Tanney-102 commented on src/hooks/useCartNavigate.ts
> +export default useCartNavigate;
꼭 훅으로 분리되었어야 할 내용인지 모르겠어요~
route path가 늘어날 때마다 요렇게 생긴 훅도 늘릴 예정이실까요~?
이미 not found page에서는 그냥 navigate를 바로 사용하는 사례가 생기기도 했네요!

2024-05-17 11:36 UTC, Tanney-102 commented on src/hooks/useDeleteProduct.ts
> +  };
사용처에서 api 호출 => 클라이언트 상태 동기화를 해주기보다 recoil쪽에서 selector를 하나 만들어주면 어떨까요?
api 호출 후에 recoil상태까지 업데이트 해주는~
지금처럼 성공 시 상태를 직접 지워주는 방식도 좋고 delete 후에 한 번더 get요청을 보내는 방식도 고려해보시면 좋겠어요.
서버 상태와 정확하게 동기화 시키기 위해!

2024-05-17 11:36 UTC, Tanney-102 commented on src/hooks/useToggleAllChecked.ts
> +        });
이전 상태를 참조할 때는 항상 주의해주세요..!

```suggestion
        setAllChecked(prev => {
          const newAllChecked = !prev;

          products.forEach((product) => {
            set(isCheckedState(product.id), newAllChecked);
            window.localStorage.setItem(JSON.stringify(product.id), JSON.stringify(newAllChecked));
          });
          
          return newAllChecked
        })
```

2024-05-17 11:36 UTC, Tanney-102 commented on src/hooks/useToggleIndividualChecked.ts
> +const useToggleIndividualChecked = ({ id, setAllChecked }: HookProps) => {
individual checked상태와 all checked상태는 서로 깊게 연관되어 있으므로 하나의 컨텍스트 안에서 관리되는 게 좋아보여요.
같은 훅에서 관리되거나 혹은 Provider로 제공하는 형태면 어떨까 제안드려봅니다.

2024-05-17 11:36 UTC, Tanney-102 commented on src/hooks/useToggleIndividualChecked.ts
> +  }, []);
로컬스토리지에 있는 상태가 여기저기서 마구마구 수정되는 것 같아요.
recoil의 state를 수정하면 => 알아서 storage를 이용해 영속성 관리를 하도록 만들어보면 어떨까요?
recoil은 안써봐서 모르겠지만 recoil persist 어쩌구로 검색하면 좋은 예시가 많이 있을 것 같아요

2024-05-17 11:36 UTC, Tanney-102 commented on src/pages/cart/CartPage.tsx
> +      <Header>
별다른 로직 없이 단순 래핑이라면 취향 차이일 수도 있겠네요~
일반적인 코드를 작성할 때도 가독성을 위해 '굳이' 의미있는 이름의 변수를 선언하기도 하니까요~
어느쪽이 더 유지보수성이 좋다고 생각하는지, 각 Header마다 wrapping 하는 것 외 다른 로직이 들어갈 여지는 없는지를 고려해 판단만 하시면 될듯!

2024-05-17 11:36 UTC, Tanney-102 commented on src/pages/cart/components/CartTotals.tsx
기준이 명확해서 괜찮아보여요! 
물론 앱이 커지면서 A page에서만 쓸 것 같던 컴포넌트인데 B page에서도 필요하네? 와 같은 상황이 발생할 수도 있지만 어떤 구조를 잡든 이런 일은 생기기마련이라 우선은 좋아보입니다.

2024-05-18 07:04 UTC, brgndyy commented on src/store/atoms.ts
> +});
> 필요한 상태는 어떤 아이템이 checked인가 이므로 각 아이템에 대한 identity만 저장하면 충분합니다.

맞는 말씀이에요! 제가 처음에 생각한 방식은

1. selector를 통해 서버 데이터를 받아온다.
2. 이를 클라이언트 측의 state로 담아주어서 이를 관리해준다.

의 방식에서, 2번 단계에서 모든 데이터들에 isChecked 속성이 존재하도록 한번 포맷팅 해주는 방식이었는데요.

뭔가 추상적으로 말씀을 드렸다보니까 상태를 아예 2개로 둔다의 느낌이 됐던것 같습니다 🥲

일단 한번 구현해보고 코드로 말씀드려보도록 하겠습니다!

> 그냥 id를 key로 해서 넣는 건 많이 위험해 보입니다.
> true/false만 관리하면 되는 것이니 저라면 그냥 set으로 관리했을 것 같아요. 

이것도 맞는 말씀이네요! 짚어주셔서 감사합니다 🙇

2024-05-18 07:05 UTC, brgndyy commented on src/store/atoms.ts
> +export const productsState = atom({
말씀 감사합니다!

2024-05-18 07:05 UTC, brgndyy commented on src/pages/cart/CartPage.tsx
> +      <Header>
> Header마다 wrapping 하는 것 외 다른 로직이 들어갈 여지는 없는지

중요한 포인트인거 같습니다! 

말씀 정말 감사합니다 !

2024-05-18 07:06 UTC, brgndyy commented on src/hooks/useToggleIndividualChecked.ts
> +const useToggleIndividualChecked = ({ id, setAllChecked }: HookProps) => {
짚어주셔서 감사합니다! 한번 수정해보도록 하겠습니다 🙇

2024-05-18 07:09 UTC, brgndyy commented on src/api/index.ts
> + */
짚어주셔서 감사합니다!

혹시 하나 더 여쭙고 싶은 부분이 있는데요.

브콜만의 주석으로 제공해주어야할 정보와 주석으로 제공해주지 않아도 될 정보의 기준점이 있으실까요 ?

저도 사소한 부분들까지 주석으로 처리해주진 않아도 된다고 생각하긴하는데, 그렇다면 주석으로 정보를 제공해야할때는 언제일까? 라는 생각이 들어서요!

만약 딱 보기에 이해하기 어려운 코드여서 주석을 달아야만 한다면, 이건 코드 자체를 잘못짠거 아닐까?  주석을 달기보다 조금 더 가독성 좋은 코드를 짜야하는게 우선 아닐까? 라는 생각도 듭니다!

2024-05-18 07:09 UTC, brgndyy commented on src/api/index.ts
> +  }
맞는 말씀이에요! 짚어주셔서 감사합니다 🙇

2024-05-18 07:12 UTC, brgndyy commented on src/api/index.ts
> +  return { success: true };
요청 자체가 `PATCH`나 `DELETE`인 경우에, 서버에 정상적으로 fetch 가 처리가 된 후만 클라이언트 측의 상태를 업데이트 해주어야하지 않나? 라고 생각했습니다!

`GET` 같은경우는 원하는 데이터를 정상적으로 받아온다는 것 자체가 정상적인 요청/응답이 이루어졌다고 판단할수 있을거 같은데,
`POST`, `PATCH`, `DELETE` 같은 경우에는 서버에서 정상적으로 처리가 이루어진것인지 현재 상황에서는 판단하기 힘들것 같다고 생각했어요!

그래서 success라는 값을 두어서, success 가 true일때만(서버에서 정상적으로 요청 처리가 되었을때만) 클라이언트 측의 상태를 업데이트 해주는 형식인데요.

혹시 제가 여기서 놓치고 있는 부분이 있을까요 ..!?

2024-05-18 07:13 UTC, brgndyy commented on src/api/index.ts
> +}
말씀 감사합니다! 

한번 수정해보도록 하겠습니다 :)

2024-05-18 07:14 UTC, brgndyy commented on src/hooks/useToggleAllChecked.ts
> +        });
앗 놓친 부분입니다! 짚어주셔서 감사합니다 🙇

2024-05-18 07:14 UTC, brgndyy commented on src/hooks/useToggleIndividualChecked.ts
> +  }, []);
저도 미션을 진행하면서 이부분이 가장 마음에 걸렸던 부분인데요! 

짚어주셔서 감사합니다.

한번 수정해보도록 하겠습니다 🙇

2024-05-18 09:56 UTC, brgndyy commented on src/store/atoms.ts
> +});
```tsx
export const allCartItemStates = atom({
  key: 'allCartItemStates',
  default: selector({
    key: 'allCartItemStates/Default',
    get: async () => {
      const cartItems = await fetchCartItems();
      const formattedProducts = formatCartItems(cartItems);
      return formattedProducts;
    },
  }),
});
```

제가 말씀드렸던 부분은 이런식으로 비동기 셀렉터로 받아온 데이터를 isChecked 속성을 추가해주도록 하는 포맷팅 레이어를 두는 것이었는데요!

혹시나 이런식으로 구현하는것은 어떻게 생각하실지 여쭈어보아도 괜찮을까요 ?

이런식으로 서버상태를 받아와서 클라이언트측에서 필요한 속성을 추가 해준후에

이제 이 상태가 base 상태가 되어서, 이 base가 되는 상태를 중심으로 여러 selector를 만들어보았습니다! 

정합성 부분이 그래도 어느정도 통일성이 있게 되지 않나? 싶은 생각이 들어서 이런식으로 구현해보았는데, 한번 살펴봐주실수 있으실까요 ..!?

2024-05-18 11:05 UTC, brgndyy commented on src/api/Fetcher.ts
아예 비동기 통신을 Fetcher라는 객체를 만들어서 관리해주었는데요..!

이렇게 하면 재사용성은 높였으나, PATCH 나 DELETE 같이 데이터를 응답으로 받지 않는 경우에 에러가 발생해서 

```ts
     const text = await res.text();
      if (!text) {
        return {} as T;
      }
```

이렇게 빈객체로 변환해주는 작업이 필요했습니다! 

이런식으로 구현하는게 일반적인건가요..?

유틸 비동기 통신 객체를 만들때 더 유연한 방법이 있을까요 ?

2024-05-18 11:05 UTC, brgndyy commented on src/hooks/useCartNavigate.ts
> +export default useCartNavigate;
헉 가독성을 위해서 일단 분리해본것인데요..!

정말 이게 훅으로 분리해야할까 ? 라는 생각이 들긴 들었는데, state가 들어가는 경우 컴포넌트 내에서 가독성을 해친다는 생각에 일단 분리해보았습니다..!

말씀때로 페이지가 늘어나면 날수록 훅도 그만큼 늘어나는 단점이 있겠네요! 짚어주셔서 감사합니다..!

(이 코멘트를 추가 리뷰 요청을 보낸 후에 확인 하게 되었습니다. step2때 꼭 반영하도록 하겠습니다. 🥲)

2024-05-18 11:05 UTC, brgndyy commented on src/hooks/useDeleteProduct.ts
> +  };
아예 기본 베이스 아톰을 포맷팅해준 상태에서 변경해보도록 바꿔보았는데요! 

셀렉터를 최대한 나눠놓은 상태입니다.

한번 확인해주시면 감사하겠습니다!

2024-05-18 11:15 UTC, brgndyy commented on src/pages/cart/components/Cart.tsx
> +export const Cart = ({ children }: PropsWithChildren<object>) => {
후에 더 추가되는 요구사항에 따라 UI가 변경 될수도 있을것 같아 컴파운드 패턴으로 변경해보았습니다!

2024-05-18 11:15 UTC, brgndyy commented on src/store/selectors.ts
> +export const isAllCheckedCartItems = selector({
기본으로 비동기 통신으로 빋이오는 allCarItemsState를 베이스 기반으로 셀렉터 구조를 다시 만들어보았어요!

처음에 atom과 셀렉터의 용도도 잘 몰랐어서 일단 막 구현하다보니 말씀 해주신 것처럼 상태 업데이트의 방향이 일관적이지 않았던거 같습니다.

중앙에 있는 상태를 기준으로 파생되는 상태들을 만들다보니 상태 추적에 용이해졌다고 생각하는데요..!

제가 놓치고 있는 부분이 있거나 잘못 짚은 부분이 있다면 말씀 주시면 감사하겠습니다!

2024-05-20 03:56 UTC, Tanney-102 commented on src/store/atoms.ts
> +});
아하 애초에 상태를 넣을 때 요렇게 한다는 이야기였군요~
클라이언트에서 필요한 필드를 넣어 가공하는 방식도 나쁘지 않습니다!
다만 checked 같은 아이들은 별도의 Set으로 관리하는 게 더 편해보이긴합니다!
말씀 주신 방식대로 하면 checked인 item을 가져오고자 할 때 매번 모든 item을 다 조회해야할 것 같아요

2024-05-20 04:04 UTC, Tanney-102 commented on src/api/index.ts
> + */
말씀주신것처럼 어지간하면 주석을 안 달고 코드 자체로 의미를 이해할 수 있도록 하는 게 베스트 입니다. 
저는 주로 코드를 이해하기 위한 배경 지식이 필수적인 경우에만 주석을 쓰려하는 편이에요.
제가 경험했던 예시를 조금 말씀드리면 특정 이벤트의 fire 시점이 safari 브라우저에서만 달라서 특별히 예외처리를 해줘야 한다거나, 어떤 컴포넌트에서 default prop을 하나주고 있는데 이게 특별한 기획적 의도와 관련있다거나.. 뭐 이런 케이스들?

2024-05-20 04:11 UTC, Tanney-102 commented on src/api/Fetcher.ts
> +      }
👍

2024-05-20 04:11 UTC, Tanney-102 commented on src/api/index.ts
> +  return { success: true };
success가 true가 아닌 값도 될 수 있나요? 실패하는 케이스라면 그 전에 error를 throw 하니까요..!
요청의 성공 '시점'을 잡고 싶었다면 promise 자체로 충분했을 것 같은데 'success'라는 변수가 왜 필요하는지 모르겠어요. 
차라리 return type을 void로 하고 promise의 then/catch로 분기를 하거나 아니면 error를 throw하는 방식이 아니라 success에 true/false를 넣어줘 실제로 사용처에서 의미 있게 분기를 하거나 해주면 좋겠어요.
지금은 에러를 throw 하는 방식과 성공/실패 결과를 반환하는 방식이 혼용되어 있습니다.

```ts
// error를 throw하는 방식
doSomething()
  .then(() => { ... })
  .catch(() => { ... })

// 결과를 반환하는 방식
const { success } = doSomething()

if (success) {
  ...
} else {
  ...
}

```

2024-05-20 04:40 UTC, Tanney-102 approved these changes
안녕하세요 버건디!
반영하시느라 고생 많으셨습니다~
Fetcher 새로 구현하신 것도 잘 봤고 selector도 세부적으로 잘 설계하신 것 같아요! 👍 
몇몇 추가 코멘트 및 기존 코멘트에 reply 달아두었으니 확인 부탁드려요!
사소한 내용들이라 다음 step에서 보시면 좋을 듯 합니다! 고생 많으셨어요~

2024-05-20 04:40 UTC, Tanney-102 commented on src/api/Fetcher.ts
메서드별로 구현체를 다르게 가져가도 좋을 것 같네요~

```ts
const Fetcher = {
  get: () => { ... },
  post: () => { ... },
  delete: () => { ... },
  ...
}
```

2024-05-20 04:40 UTC, Tanney-102 commented on src/services/LocalStorage.ts
이름은 '일반적'(LocalStorage)인데 실제 내용물은 상당히 '구체적'(checkedProducstIds 에 대한 서비스임)이네요..! 네이밍을 바꾸면 어떨까요

2024-05-20 04:40 UTC, merged

2024-05-24 02:49 UTC, cys4585 commented
👍👍👍👍👍👍👍👍👍👍

2024-05-24 02:49 UTC, hwinkr reviewed
스텝 2에서 테스트 추가만 더 해주면 좋을 것 같네여 ㅎㅎ

atom 상태 변경, atom 상태 변경에 따른 selector를 중점으로 테스트 해보면 좋을 것 같아요 ㅎㅎ

코드 잘 봤습니다 👏👏👏

2024-05-24 02:49 UTC, hwinkr commented on src/store/atoms.ts
> +export const allCartItemStates = atom({
[single sourth of truth](https://en.wikipedia.org/wiki/Single_source_of_truth) 👏