[1단계 - 장바구니 미션] 해리(최현웅) 미션 제출합니다.
woowacourse/react-shopping-cart pull request #264
Opened 2024-05-16 08:43 UTC by hwinkr

안녕하세요! 블링 다시 만나게 되어 반갑습니다~! 🍀🙇 

이번 미션에서는 api 요청을 해서 사용자의 장바구니 데이터를 가져오고 장바구니 페이지를 구성한 후 **리코일을 활용해서 복잡한 클라이언트 상태를 관리해보았습니다! 
저와 페어 모두 리코일을 처음 사용해본 것과 다름이 없어서 리코일의 핵심인 `atom`과 `selector`를 어떻게 구성해갈지에 대해 정말 많이 헤맸던 것 같습니다. 

특히 **무엇을 원자 단위의 상태인 `atom`으로 관리해야할지**에 대해 정말 많은 고민을 했던 것 같습니다. 잘 부탁드립니다!

## 🤔 학습 목표와 관련된 고민

### Recoil을 사용하여 클라이언트 상태를 관리할 수 있다.

이번 미션에서는 전역 상태 관리 라이브러리인 리코일을 사용해서 클라이언트의 상태를 관리해야 했습니다.

우선 서버 데이터의 구성을 확인한 후, 무엇을 클라이언트의 상태로 관리해야할지에 대해서 고민을 했었습니다.  

페어와 논의를 한 후 클라이언트 측에서 변경되고 관리해줘야하는 상태를 

- 상품의 선택 여부
- 상품의 수량 

이 2가지로 정하고 실습 시간에 사용해봤던 `atomFamily`를 활용해보기로 했습니다.

```ts
export const cartItemQuantity = atomFamily<number, number>({
  key: "itemQuantityState",
  default: initialCartItemQuantity,
});

export const selectedCartItems = atomFamily<boolean, number>({
  key: "selectedCartItems",
  default: false,
  effects: (id) => [localStorageEffectForItem(id)],
});
```

동일한 형태(상품 선택 여부, 상품 수량)의 atom을 동적으로 생성할 수 있게 하고, 독립된 상품마다 별도의 atom을 생성할 수 있다는 것에 매력을 느껴 사용해보게 되었습니다. 서버에서 넘겨주는 상품의 고유한 아이디를 활용해서 관리해보았습니다.

그리고 atom을 통해서 만들어지는 파생된 상태를 `selector`를 활용해서 만들어보았습니다. 비동기 데이터 페칭을 할 때도 selector를 활용해보았습니다.

```ts
export const cartItemSelector = selector<CartItem[]>({
  key: "cartItemSelector",
  get: async () => {
    const cartItems = await getCartItems();
    return cartItems;
  },
});
```

그리고,
- 총 주문 금액
- 배송비
- 현재 사용자가 장바구니에 담은 상품 수량 
- (주문 최종 확인 페이지)에서 사용할 사용자가 선택한 상품과, 수량

을 selector를 활용해서 구현했습니다. 

ex) 총 주문 금액 계산
```ts
export const totalOrderPriceSelector = selector({
  key: "totalOrderPriceSelector",
  get: ({ get }) => {
    const cartItemList = get(cartItems);

    const totalPrice = [...cartItemList].reduce((accPrice, currItem) => {
      const currentQuantity = get(cartItemQuantity(currItem.id));
      const isSelected = get(selectedCartItems(currItem.id));

      accPrice += isSelected ? currentQuantity * currItem.product.price : 0;

      return accPrice;
    }, 0);

    return totalPrice;
  },
});
```

### React Testing Library(RTL)를 활용하여 주요 기능에 대한 테스트를 작성할 수 있다.

장바구니 페이지에서 제공하는 주요 기능을 테스트 해야 했습니다.
원래는 UI테스트(+버튼을 클릭하면 리코일로 관리하는 상태가 업데이트 되는)도 진행하려고 했지만, 시간 부족으로 인해 리코일로 관리하는 atom, selector만 테스트하게 되었습니다...😭

- 상품 선택 기능
- 상품 수량 변경 기능, 갯수 변경에 따라서 총 주문 금액이 변경 되는 기능
- 총 주문 금액에 따라서 배송비가 변경되는 기능
- 상품 제거 기능

을 중심으로 테스트를 진행했습니다.

api 요청해서 데이터를 가져오는 것은, 테스트를 할 때마다 실제 api를 호출하는 것은 데이터 동기화와 리소스 관점에서 비효율적인 것이라고 생각해 모킹 데이터를 활용해서 초기에 atom 에 설정해주는 방향으로 테스트를 진행했습니다.
```tsx
const { result } = renderHook(() => useRecoilValue(totalOrderPriceSelector), {
  wrapper: ({ children }) => (
    <RecoilRoot initializeState={initializeState}>{children}</RecoilRoot>
  ),
});
```

## 🤚 질문 

### 낙관적 업데이트 

상품 수량 변경을 하는 경우, 서버에 `patch`요청을 하고 서버의 응답이 정상인 경우 (`response.ok` | 200) 상태를 변경하는 함수를 호출해서 상태를 업데이트 하도록 했습니다.
```
const handleIncreaseQuantity = async () => {
  const canUpdateCardItemQuantity = await patchCartItemQuantity(
    id,
    quantity + 1
  );

  if (canUpdateCardItemQuantity) {
    setQuantity((prevQuantity) => prevQuantity + 1);
  }
};
```
미션을 진행하면서 과연 사용자가 상품 수량 변경 버튼을 클릭할 때마다 api 요청하는 것이 리소스 관점에서 좋은 것인가? 에 대해 생각해보게 되었습니다.  
사용자가 버튼을 클릭했을 때, 낙관적 업데이트로 일단 UI를 변경하고 주문 확인 버튼을 클릭했을 때 api 요청을 한 번에 해서 리소스를 줄이는 방법도 있지 않나?에 대해 생각했지만

- 서버에서 관리하고 있을 재고 데이터를 통해서 주문 가능 수량을 확인해야 하는 문제
- 새로 고침을 했을 때의 문제

위와 같은 문제들로 리소스가 들기는 하지만 서버에 요청을 해서 fresh한 데이터를 유지할 수 있도록 하는 것이 맞다고 생각해 이번 미션에서는 버튼을 클릭할 때마다 patch 요청을 보내는 방향으로 구현했습니다.

🤔 현업에서는 낙관적 업데이트를 어떻게 바라보는지, 실제로 수량 변경과 같은 잦은 api 요청을 유발하는 경우 어떻게 처리를 하는지 궁금합니다!

### atom, selector 분배

이번 미션에서 처음으로 리코일을 제대로 다루다 보니 저와 페어가 설계한 atom, selector의 구조와 분배과 과연 적절한지에 대한 확신이 없어서, 블링에게 의견을 물어보고 싶습니다!

서버 데이터 페칭을 selector로 하고, 장바구니 atom의 기본값을 해당 selctor로 설정했습니다. 그리고, 위에서도 말씀 드렸듯이 개별 상품의 갯수, 선택 여부 관리하기 위해 atomFamily를 활용했었습니다. 
장바구니 atom에 서버에서 보내주는 상품 갯수 정보가 있어 `useRecoilState`를 사용해서 관리할 수 있었을텐데 개별적으로 관리해보기 위해서 atomFamily를 사용하는 것이 과했나? 하는 생각도 들었습니다.

장바구니 미션을 해결하기 위해서 설계한 atom, selector가 블링이 보셨을 때 적절한지, 만약 적절하지 않다면 어떤 부분을 집중적으로 개선해볼 수 있을지에 대한 의견을 물어보고 싶습니다! 🙇‍♂️

2024-05-18 06:13 UTC, hwinkr commented on src/hooks/useUpdateItemQuantity.ts
> +  };
블링의 피드백을 받은 후, 낙관적 업데이트에 대해서 다시 고민하는 시간을 가졌습니다!

블링이 말씀해주신 것 처럼, 네트워크 속도를 Fast 3G로 스로틀링을 건 후 + 버튼을 누르니 업데이트가 늦어지더군요,,😭 그래서 사용자 입장에서는 '어, 왜 수량이 변경 안되지?', '버튼 클릭이 안됐나?' 라는 생각으로 계속해서 버튼을 누르고 **원치 않는 만큼의 수량을 추가할 가능성이 있을 것 같다**는 생각도 했습니다. 

하지만, 상품 수량 데이터는 **항상 서버와 동기화 되어야 하는 예민한 데이터**라는 생각은 변하지 않았던 것 같습니다. 
'**🤔 수량을 변경하는 patch 요청이 항상 성공할 것이라는 보장을 할 수 있을까?**'에 대한 의문이 여전히 해결되지 않고 남았기 때문입니다...ㅎ

예를 들어,

(낙관적 업데이트를 하는 상황에서) 사용자가 수량을 4개에서 10개로 올리는 과정에서 8개부터 10개까지 올리는 patch 요청이 실패했다고 가정해봤습니다.

그리고 나서 사용자가 다른 제품을 추가하고 싶어 뒤로가기를 하고 다시 돌아오거나, 새로고침을 할 경우는 patch 요청이 실패하기 전 데이터인 7개로 표시되므로 사용자가 다시 10개로 올려야 하니 불편함을 줄 수 있다는 생각을 했던 것 같습니다!

또, 사용자가 선택하고 싶은 수량과 서버에서 관리하고 있을 재고 데이터 연동 관점에서도 상품 수량 데이터는 서버 데이터와 항상 동기화가 되야하지 않을까 라는 생각을 했습니다.

![image](https://github.com/woowacourse/react-shopping-cart/assets/68489467/3971527f-7035-41dc-a947-7e96d4092e7b)

상품 수량을 변경하는 요청을 위 이미지 처럼 `변경` 버튼을 클릭했을 때, 한번에 수행 한다면 서버 리소스를 최대한 적게 이용한다는 관점에서는 좋으나, 만약 재고가 부족할 경우 부족하다는 피드백을 '🤔사용자에게 알려주는 시점이 너무 늦어지지는 않을까?'에 대해서도 생각했던 것 같습니다.

따라서, **수량 변경 patch 요청이 항상 성공할 수는 없지 않을까?**, **사용자가 선택한 수량과, 서버의 재고 데이터를 비교한 피드백을 빠르게 알려주면 좋지 않을까**?에 대한 고민을 통해서 
서버에 patch 요청을 하고, 응답에 따라서 상태를 업데이트 하는 방식을 한 번 유지해보기로 했습니다...!

이 결론을 짓고 나서 제가 추가적으로 해결해야 하는 문제는 사용자에게 버튼 수량이 업데이트 되는 중이라는 피드백을 전달해주는 것이였습니다. 만약 사용자가 + 버튼을 눌렀을 경우, 정상적인 네트워크 요청과 UI 업데이트가 되기 전 까지 수량을 보여줘야 하는 영역에 로딩 스피너를 보여주고, 계속해서 버튼을 클릭할 수 없도록 버튼을 잠시 disabled 하게 만드는 방법을 생각해봤습니다! (이 방법이 UX 측면에서 좋은 방법인가에 대한 확신은 없지만, 한 번 이렇게 시도해보려고 합니다!)

### No-Throttling

![Screen-Recording-2024-05-18-at-15 02 11](https://github.com/woowacourse/react-shopping-cart/assets/68489467/0ed4f1b9-2959-47ce-ae6f-750a32d223d6)

### Fast-3G

![Screen-Recording-2024-05-18-at-14 58 17](https://github.com/woowacourse/react-shopping-cart/assets/68489467/6db014ec-aaa7-45b9-af4c-016c354426ac)

Fast-3G 환경에서는 상품 수량이 업데이트 되고 있다는 적절한 피드백을 주고 있는 것 같으나, No-Throttling 환경에서는 오히려 깜빡임 현상처럼 보이네요...ㅎ 그래도 업데이트 되고 있다는 피드백을 바로 전달해주는 것에 의의를 두고 이 방향으로 수정해보도록 하겠습니다!

2024-05-18 06:47 UTC, hwinkr commented on src/components/CartEmpty/CartEmpty.tsx
> +    <>
굳이 `Fragment`가 없어도 되는 경우네요...! 세세한 피드백 감사합니다 ㅎㅎ

2024-05-18 07:04 UTC, hwinkr commented on src/components/PriceInfoBox/PriceInfoBox.tsx
> +      <Price>{price.toLocaleString() + "원"}</Price>
오 이게 더 훨씬 깔끔해보입니다...! 정말 세세하게 봐주시네요 🙇‍♂️🙇‍♂️🙇‍♂️

2024-05-18 07:16 UTC, hwinkr commented on src/components/CartEmpty/CartEmpty.tsx
> +  height:calc(100% - 128px);
부모의 높이를 사용하면 되니, 굳이 계산할 필요가 없을 것 같네요...! 감사합니다 ㅎㅎ

2024-05-18 07:22 UTC, hwinkr commented on src/components/PriceInfoBox/PriceInfoBox.tsx
> +`;
급하게 하느라 파일 분리를 놓친 것 같네요...😭 수정하도록 하겠습니다!

2024-05-18 07:25 UTC, hwinkr commented on src/components/_common/BackButton/BackButton.tsx
![image](https://github.com/woowacourse/react-shopping-cart/assets/68489467/64bb0d1c-5a31-45c0-a69a-6551af57a840)

기본적으로 알파벳 순으로 폴더 이름이 정렬되지만, `_`를 붙여주면 제일 위로 올라오게 됩니다!
공통 컴포넌트를 모아두는 `common`, 레이아웃을 잡아주는 컴포넌트를 모아두는 `layout` 모두 제일 위에 있으면 찾기 쉬울 것 같아서 `_`를 붙이게 되었습니다!

2024-05-18 07:27 UTC, hwinkr commented on src/pages/OrderConfirmPage/OrderConfirmPage.tsx
> +  0;
오타입니다...ㅎ 😅

2024-05-18 07:32 UTC, hwinkr commented on src/pages/OrderConfirmPage/OrderConfirmPage.styles.ts
여기도 분리를 놓쳤었네요...😅

2024-05-18 07:35 UTC, hwinkr commented on src/pages/CartPage/CartPage.tsx
> +        <>
해당 JSX구조에서는 필요가 없겠네요...!

```tsx
<Styled.CartPageLayout>
  {!isEmptyCart ? (
    <>
      <TitleSet
        title="장바구니"
        subTitle={`현재 ${totalItemLength}종류의 상품이 담겨있습니다.`}
      />

      <Styled.CheckBoxWrapper>
        <CheckBox
          isChecked={isAllItemSelected}
          onClick={isAllItemSelected ? unselectAllItem : selectAllItem}
        />
        <Caption text="전체선택" />
      </Styled.CheckBoxWrapper>

      <Suspense fallback={<div>loading....</div>}>
        <ProductList />
      </Suspense>

      <Caption
        asset={() => <MoreInfo />}
        text="총 주문 금액이 100,00원 이상일 경우 무료 배송됩니다."
      />
      <PriceSection />
    </>
  ) : (
    <>
      <TitleSet title="장바구니" />
      <Styled.EmptyCartWrapper>
        <Caption text="장바구니에 담은 상품이 없습니다."></Caption>
      </Styled.EmptyCartWrapper>
    </>
  )}
</Styled.CartPageLayout>;
```

피드백을 반영하면서, JSX 구조를 수정하게 되었습니다!

2024-05-18 07:36 UTC, hwinkr commented on src/recoil/orderInformation.ts
> +    return totalOrderPrice >= 100000 ? 0 : 3000;
상수를 활용해서 의미를 잘 드러내보도록 하겠습니다!

2024-05-18 07:49 UTC, hwinkr commented on src/App.tsx
> +        <Suspense fallback={<div>loading...</div>}>
필요없지만, 한 번 동작 확인차 최상위 컴포넌트에서도 선언 해봤었는데 지운다는 것을 깜빡했네요...😭 수정하도록 하겠습니다!

2024-05-18 13:25 UTC, hwinkr commented on src/recoil/selectedCardItems.ts
> +      const savedValue = localStorage.getItem(SELECTED_ITEM_STORAGE_KEY);
넵 다르게 동작합니다! 

[State Synchronization Example(상태 동기화 예제)](https://recoiljs.org/ko/docs/guides/atom-effects/#state-synchronization-example-%EC%83%81%ED%83%9C-%EB%8F%99%EA%B8%B0%ED%99%94-%EC%98%88%EC%A0%9C)에서 확인할 수 있듯이, effect에서 `setSelf`를 호출하는 것은 그 값으로 atom을 초기화하고 초기 렌더링에 그 값을 사용하게 됩니다. 
```ts
const localStorageEffectForItem =
  (id: number): AtomEffect<boolean> =>
  ({ setSelf, onSet }) => {
    const savedValue = localStorage.getItem(SELECTED_ITEM_STORAGE_KEY);

    if (savedValue) {
      const selectedItems: number[] = JSON.parse(savedValue);
      setSelf(selectedItems.includes(id));
    }

    //...
  };
```
따라서, 해당 `savedValue`의 스코프는 초기 렌더링에 사용됩니다. 

반면, onSet은 atom 값이 변경될 때 즉, 상태를 업데이트 하는 setter 함수가 호출될 때마다 리액트 외부에 있는 시스템과 동기화를 위해서 실행됩니다. 이번 미션의 경우 리액트 외부에 있는 시스템인 **브라우저 저장소인 로컬 스토리지**와 동기화하기 위해서 사용되었습니다. onSet 함수가 실행될 때는 그 시점의 로컬 스토리지의 최신 상태를 참조할 수 있어야 하므로 함수 내부에서 사용될 수 있는 `savedValue` 스코프를 추가로 만들어줘야 했습니다. 

```ts
const localStorageEffectForItem =
  (id: number): AtomEffect<boolean> =>
  ({ setSelf, onSet }) => {
    const savedValue = localStorage.getItem(SELECTED_ITEM_STORAGE_KEY); // 초기 렌더링에는 null

    if (savedValue) {
      const selectedItems: number[] = JSON.parse(savedValue);
      setSelf(selectedItems.includes(id));
    }

    onSet((newValue) => {
      console.log(savedValue); // 상태가 변경되어 호출할 때마다 항상 null을 참조

      const selectedItems: number[] = savedValue ? JSON.parse(savedValue) : [];

      const updatedItems = newValue
        ? [...selectedItems, id]
        : selectedItems.filter((itemId) => itemId !== id);

      localStorage.setItem(
        SELECTED_ITEM_STORAGE_KEY,
        JSON.stringify(updatedItems)
      );
    });
  };
```
따라서, onSet 스코프 외부에 있는 `savedValue`를 참조할 경우 
![Screen Recording 2024-05-18 at 22 23 03](https://github.com/woowacourse/react-shopping-cart/assets/68489467/8bdaf1ed-fe2e-4cd9-9b35-1e745bd96e2d)
`전체 선택`을 클릭해도 마지막 요소만 브라우저 저장소에 반영되므로 스코프를 한 번더 만들어줘야 했습니다!

2024-05-18 13:34 UTC, hwinkr commented on src/apis/index.ts
추상화를 미리 해놓는 것이 확장성을 고려했을 때 더 좋을 것 같습니다! 시도해보겠습니다~!

2024-05-18 14:02 UTC, hwinkr commented on src/pages/CartPage/CartPage.tsx
> +);
네넵 맞습니다! 😊
`<Suspense/>`의 기능을 활용해보고자 사용한 것도 있고, `React.lazy`의 경우 현재 렌더링에 필요한 컴포넌트들만 로드하기 때문에, 초기 렌더링 속도를 개선할 수 있다는 장점도 있는 것 같아요!

2024-05-18 14:38 UTC, hwinkr commented on src/components/_common/Button/Button.tsx
> +  border-radius: ${({ $radiusVariant }) => BUTTON_RADIUS[$radiusVariant]};
확실히 props가 많아지고, 해당 props를 각 스타일 항목별로 따로 사용하니 복잡해보이고 가독성이 떨어진다는 느낌도 드네요...!

```ts
${({ $size, $theme, $width, $radiusVariant }) => css`
  ${BUTTON_SIZE[$size]};
  ${BUTTON_THEME[$theme]};
  border-radius: ${BUTTON_RADIUS[$radiusVariant]};
  width: ${$width === "fixed" ? BUTTON_WIDTH[$size] : BUTTON_WIDTH[$width]};

  &:disabled {
    cursor: not-allowed;
    border: none;
  }
`}
```

이렇게 구조를 변경하니 훨 깔끔해진 것 같아요!! 좋은 방법 추천 감사드립니다 블링! 😊

이번 미션에서 구현한 공통 버튼 컴포넌트는 사실 `react-modules` 미션을 진행할 때, 모달 내부에서 사용했던 버튼 컴포넌트를 참고해서 만들었던 것이었습니다. 

이미 지난 미션이지만 모달 라이브러리에서 구현했던 **재사용할 수 있는 버튼  컴포넌트**에 대해서 추가적인 질문 하나만 해보고 싶습니다!

버튼의 모양과 크기, 색, 휜 정도 등등 버튼으로 만들 수 있는 다앙한 UI 스토리들이 있었고, 만들어야 하는 스토리들이 많아질 때마다 이에 비례하여 props도 많아지고 블링께서 말씀해 주셨던 것 처럼 스타일을 지정하는 방식도 복잡해졌다는 생각을 했었습니다. 

버튼 컴포넌트를 외부에서 호출해서 사용할 때는,
```tsx
<Modal.ModalButton theme="dark" width="fixed" size="full" onClick={onClose}>
  {buttonText}
</Modal.ModalButton>;
```
'버튼 컴포넌트가 그려야하는 UI를 더 선언적으로 표현할 수 있겠구나..! 이러한 이유들로 디자인 시스템이 나왔겠구나!' 하는 생각을 했지만, 한편으로는 위에서도 언급했던 것 처럼 props가 너무 많아지니 재사용을 위해 구현되는 버튼 컴포넌트가 **너무 많은 스타일 책임을 가지게 되는 것은 아닐까**?에 대한 생각도 들었습니다..!

현업에서는 버튼 컴포넌트로 만들어줘야 하는 더 많은 UI 스토리들이 있을 것이라고 생각 되는데요! **재사용 가능한 버튼 컴포넌트**를 만들 때, 변경될 여지가 있는 UI 요소들을 하나의 버튼 컴포넌트에 모두 props으로 내려줘서 재사용 하는지, 아니면 비슷한 UI들을 묶어서 여러개의 버튼 컴포넌트들로 다시 나눠서 사용하는지 여쭤봐도 괜찮을까요?? 🙇‍♂️🙇‍♂️🙇‍♂️

2024-05-18 14:47 UTC, hwinkr commented on src/components/_common/BackButton/BackButton.tsx
> +import BackButtonIcon from "@/assets/back-button.svg?react";
```shell
"vite-plugin-svgr": "4.2.0"
```
해당 라이브러리는 vite 환경에서 SVG 파일을 **리액트 컴포넌트 처럼** 사용할 수 있도록 도와주는 플러그인 역할을 합니다! 

그리고 블링께서 질문 주셨던 url은 SVG 파일을 리액트 컴포넌트로써 import할 수 있도록 해줍니다.  
`"@/assets/back-button.svg?react"`에서 쿼리 스트링인 `?react`는 svg 파일을 리액트 컴포넌트로 변환할 것을 알려주는 역할을 합니다!

2024-05-18 15:28 UTC, hwinkr commented on src/tests/cartPage.test.tsx
파일명을 수정해야할 것 같네요! 피드백 감사드립니다 ㅎㅎ

2024-05-19 01:42 UTC, hwinkr commented
안녕하세요 블링! 피드백 반영 후 다시 리뷰 요청 드립니다. 
처음 배포했던 주소와 재배포 주소는 같습니다! 🍀
남은 주말 잘 보내세요~ 😊🙇‍♂️

2024-05-19 07:14 UTC, uk960214 commented on src/components/ProductItem/ProductItem.tsx
> +const ProductItem = ({ item }: { item: CartItem }) => {
여기에도 prop의 타입을 다른 곳에서처럼 분리해서 관리해주면 좋지 않을까요?

2024-05-19 07:14 UTC, uk960214 commented on src/components/_common/BackButton/BackButton.tsx
> +  return <BackButtonIcon onClick={() => navigate(-1)} />;
컴포넌트가 BackButton인만큼 사용자는 반환되는 컴포넌트가 Button일것이라고 추측할 것 같은데요
지금은 컴포넌트가 사실상 svg라서 1. 접근성 차원에서 적절하지 못하고 2. 다른 버튼과의 사용성이 다르게 느껴지고 3. 예상하지 못한 버그도 날 수 있지 않을까 하는 생각이들었습니다.

해당 아이콘을 버튼으로 래핑하고, 버튼의 디자인은 투명하게 만들되 기능적인 부분들만 버튼에 전달해서 사용하면 어떨까요?

2024-05-19 07:14 UTC, uk960214 commented on src/hooks/useUpdateItemQuantity.ts
> +  };
아하 걱정하신 부분의 정확한 포인트를 인지했습니다. 낙관적 업데이트를 했는데 API 요청이 실패한 케이스에 대해서 고민하신 것 같아요!
하지만 가장 단순하게 생각하면, 낙관적 업데이트를 하고 나서 서버에서 실패 메시지가 오면 바꾸기 전 상태로 돌리면 되지 않을까요?
이 방식이 사용자에게 어색하게 느껴질 수 있다고 생각하시면, 오류가 발생했을 때 사용자에게 '변경에 실패했다'고 메시지를 알리고 롤백을 하는 방법도 있을 것 같구요! 낙관적 업데이트에서 실패하는 경우에 대해서는 다양한 방법으로 대응할 수 있으니 한 번 확인 해보아도 좋을 것 같아요! 
물론 지금의 로딩처리 방법도 틀리지는 않은 것 같아요! 어떤게 사용자의 경험에 더 좋을까 하는 고민을 해보고 최종 선택을 내리면 될 것 같습니다!

2024-05-19 07:15 UTC, uk960214 requested changes
안녕하세요 해리!  빠르게 피드백 잘 반영해주셨네요!
몇 가지 코멘트와 추가적인 피드백도 남겼는데요, 한 번 더 확인 부탁드립니다!

2024-05-20 00:52 UTC, hwinkr commented on src/components/ProductItem/ProductItem.tsx
> +const ProductItem = ({ item }: { item: CartItem }) => {
미리 구조분해 할당으로 분리해주는 것이 가독성 측면, 다른 컴포넌트들과의 통일성 측면에서도 좋은 것 같네요!

2024-05-20 01:13 UTC, hwinkr commented on src/components/_common/BackButton/BackButton.tsx
> +  return <BackButtonIcon onClick={() => navigate(-1)} />;
1, 2는 미션을 진행하면서 생각해보지 못했던 방식이네요! 
이름은 버튼 컴포넌트를 표현하는데, svg를 반환하니 접근성과 사용성 측면에서 모두 좋지 못한 방법을 선택한 것 같습니다! 

한번 개선해 보겠습니다!

2024-05-20 01:46 UTC, hwinkr commented on src/apis/index.ts
> +  return data.content;
추가적으로 공통화 진행해 보겠습니다!

2024-05-20 02:03 UTC, hwinkr commented
> 아하 걱정하신 부분의 정확한 포인트를 인지했습니다. 낙관적 업데이트를 했는데 API 요청이 실패한 케이스에 대해서 고민하신 것 같아요!
하지만 가장 단순하게 생각하면, 낙관적 업데이트를 하고 나서 서버에서 실패 메시지가 오면 바꾸기 전 상태로 돌리면 되지 않을까요?
이 방식이 사용자에게 어색하게 느껴질 수 있다고 생각하시면, 오류가 발생했을 때 사용자에게 '변경에 실패했다'고 메시지를 알리고 롤백을 하는 방법도 있을 것 같구요! 낙관적 업데이트에서 실패하는 경우에 대해서는 다양한 방법으로 대응할 수 있으니 한 번 확인 해보아도 좋을 것 같아요!
물론 지금의 로딩처리 방법도 틀리지는 않은 것 같아요! 어떤게 사용자의 경험에 더 좋을까 하는 고민을 해보고 최종 선택을 내리면 될 것 같습니다!

사용자에게 변경에 실패했다는 피드백을 주는 방법이 괜찮을 것 같아서 피드백을 주고, 이전 상태로 롤백하는 방법을 구현해보았습니다. 피드백을 전달하는 방식은 지금은 alert 함수를 사용해서 간단하게 구현하고 스텝 2에서 시간이 된다면 토스트 메시지도 한 번 구현해보겠습니다!

```ts
const handleIncreaseQuantity = async () => {
  try {
    setQuantity((prevQuantity) => prevQuantity + 1);

    setIsUpdateLoading(true);
    await patchCartItemQuantity(id, quantity + 1);
    setIsUpdateLoading(false);
  } catch (error) {
    setIsUpdateLoading(false);
    setQuantity((prevQuantity) => prevQuantity - 1);

    if (error instanceof Error) {
      alert(error.message);
    }
  }
};
```

2024-05-20 12:02 UTC, uk960214 approved these changes
낙관적 업데이트 관련 수정사항까지 잘 확인했습니다!
1단계는 여기에서 마무리하고 얼른 2단계로 넘어가시죠!
수고 많으셨어요!! 2단계도 기대하고 있겠습니다!

2024-05-20 12:02 UTC, uk960214 commented on src/components/_common/BackButton/BackButton.tsx
> +    </Button>
여기에서는 Icon 말고 Button에 onClick을 달아주면 어떨까요??

2024-05-20 12:02 UTC, merged

2024-05-24 02:52 UTC, llqqssttyy commented on src/recoil/selectedCardItems.ts
> +const localStorageEffectForItem =
effect에 들어갈 함수를 이렇게 타이핑하면 분리할 수 있군요~ 배워갑니다👍

2024-05-24 02:53 UTC, llqqssttyy commented on src/recoil/cartItems.ts
> +export const cartItemSelector = selector<CartItem[]>({
*-Selector라는 네이밍 컨벤션을 일관되게 작성해주셨네욥👍