[1단계 - 장바구니] 아르(홍성진) 미션 제출합니다.
woowacourse/react-shopping-cart pull request #272
Opened 2024-05-16 08:51 UTC by seongjinme

안녕하세요 지그! 아르입니다. 오랜만에 다시 인사드려요 😄 

이번 미션은 소파(@ss0526100)와 함께 진행했습니다. 
저희 모두 React와 Recoil 등의 전역 상태 관리 도구를 모두 레벨2에서 처음 접했어요.
함께 많이 헤매면서 임기응변 식으로 구현한 부분들이 많습니다. 이 부분들은 차차 개선해 나갈게요. 잘 부탁드립니다 🙏

## 배포 주소
https://seongjinme.github.io/react-shopping-cart/

* 미션용 API 서버의 프로토콜(HTTP)과 깃허브 페이지의 프로토콜(HTTPS) 불일치로 인해, 바로 접속하시면 에러가 발생합니다.
* Chrome 기준으로, 아래 첫 번째 이미지와 같이 웹사이트에 대한 설정 화면을 여신 다음, '비보안 콘텐츠' 옵션을 허용해주시면 웹에서 시험해보실 수 있습니다.

<img width="352" alt="image" src="https://github.com/woowacourse/react-shopping-cart/assets/73219583/dbc315d8-75c7-446e-a28e-57144c05715f">

<img width="672" alt="image" src="https://github.com/woowacourse/react-shopping-cart/assets/73219583/07543aa9-9692-401b-a8f2-39dec8e34120">

## 로컬 실행 방법
```Bash
# 실행 환경 구성
npm install

# 로컬 환경에서 실행
npm run dev

# 로컬 환경에서 테스트 실행
npm run test
```

* 로컬에서 실행하실 때 프로젝트 루트 경로에 `.env` 파일이 아래와 같은 포맷으로 필요합니다.

```Bash
VITE_API_URL={url}
VITE_USER_ID={id}
VITE_USER_PASSWORD={password}
```

* 위의 환경변수 파일에 들어갈 값들은 DM으로 보내드리겠습니다. 🙏 

## 주요 컴포넌트 구조
<img width="929" alt="image" src="https://github.com/woowacourse/react-shopping-cart/assets/73219583/0e315da8-e96d-4538-88c9-b6ee81288db0">

## 아쉬웠던 점
* Recoil 첫 경험자로서 장바구니 구현 과정에서 워낙 많이 헤맸던 것 같습니다. 
* 때문에 전반적인 컴포넌트 구조와 고정값 상수화, 공통 로직 추상화에 많은 신경을 쏟지 못했습니다.
* RTL을 이용한 테스트 코드 역시 부분적으로만 작성된 상태입니다. Recoil 상태와 컴포넌트 요소를 불러와 사용하거나 mocking하는 부분이 아직 익숙치 않았고, 때문에 많은 테스트 케이스를 작성하지 못했습니다.

## 궁금한 점
### 비동기 데이터에 대한 효율적인 Atom/Selector 관리법
* API 호출을 통해 받아온 데이터를 Recoil 기반 상태값으로 관리하는 과정에서 특히 많이 헤맸습니다. 상품 데이터를 `CartItem[]` 포맷의 Atom으로 받아온 뒤 커스텀 훅으로 데이터를 set하는 방법을 써보기도 했습니다만, 이 경우엔 커스텀 훅이 적용된 컴포넌트 바깥에서 해당 데이터를 다룰 때 어려움을 겪었습니다.
* 현재는 fetch 받아온 데이터를 selector(`cartItemsState`)로 두고, 해당 selector를 default 값으로 구독하는 Atom(`currentCartItemsState`)을 별도로 두어 관리하는 상태입니다. 이러한 구현법이 실제 Recoil의 의도에 맞는 활용법인지, 조금 더 효율적으로 비동기 데이터를 다룰 방법이 있을지 궁금하여 문의드립니다.

잘 부탁드립니다 🙏

2024-05-17 12:59 UTC, zigsong requested changes
안녕하세요 아르~ 다시 만나 반가워요! 👋 

리뷰어에게도 이번 미션의 난이도가 갑자기 확 올라갔는데, 우선 미션 요구사항 모두 구현하시느라 고생 많으셨습니다 ☺️ 

짧은 시간에도 data fetching과 recoil을 통한 상태관리, 테스트까지 꼼꼼하게 잘 구현해주신 것 같아요. 다만 조금 눈에 띄는 부분들이 있어 코멘트 남겼습니다

> 비동기 데이터에 대한 효율적인 Atom/Selector 관리법

질문주셨는데요, 

> 이 경우엔 커스텀 훅이 적용된 컴포넌트 바깥에서 해당 데이터를 다룰 때 어려움을 겪었습니다.

상태관리의 핵심중 하나는  '여러 컴포넌트에서 동시에 다룰 수 있는 데이터'를 상태로 분리하여 상태의 변경을 시의적절하게 추적하는 것이에요. 어떤 커스텀 훅을 시도하셨는지는 잘 모르겠지만, 서버 데이터를 hook으로 가져와 recoil state로 두는 것은 이번 미션의 핵심은 아니었던 것 같습니다

그리고 

> 이러한 구현법이 실제 Recoil의 의도에 맞는 활용법인지

를 질문주셨는데요, 사실 저를 포함한 많은 리뷰어들이 recoil을 사용해보지 않은 상태라 recoil의 철학이 무엇인지까지 설명드리기엔 한계가 있을 것 같아요 😅 다만 문서를 조금 살펴보고 생각이 든 내용은,  아르가 이번 미션에서 '상태'에 대한 접근을 조금만 다르게 해석해보면 좋을 것 같아요 .

> 현재는 fetch 받아온 데이터를 selector(cartItemsState)로 두고, 해당 selector를 default 값으로 구독하는 Atom(currentCartItemsState)을 별도로 두어 관리하는 상태입니다.

라고 하셨는데, 그러면 생각의 흐름이 
1. fetch해온 데이터를 저장한 selector
2. 해당 selector를 기본값으로 하는 atom

으로 진행돼요. 

그런데 '상태'관리라는 것은 'fetch해온 데이터를 어디다 둘 건지'가 아니라, '무엇을(어떤 값을) 상태로 관리할 건지'에서부터 출발해야 합니다. 즉, 사고의 흐름이

1. atom으로 관리해야 할 상태, 그리고 그 단위가 무엇일지
2. 그 상태는 API에서 가져와야 하므로 selector의 함수를 이용하자

가 되어야 할 것 같습니다.

결국 구현체는 똑같아지는 경우가 많겠지만, 점점 더 큰 앱의 규모에서 상태와 상태가 아닌 것을 구분하는 데 도움이 되면 하는 마음에 리뷰 남깁니다 😊

2024-05-17 12:59 UTC, zigsong commented on src/page/ShoppingCartPage.tsx
> +    </>
근데 여기(`ConfirmButton`)에도 `Suspense`가 있어야 하나요? 👀

2024-05-17 12:59 UTC, zigsong commented on src/components/Header/Header.tsx
> +}
props를 꼭 destructuring해줄 필요 없을 것 같아요~ 

```jsx
export default function Header(props: PropsWithChildren) {
  return <HeaderContainer>{props.children && props.children}</HeaderContainer>;
}
```

그리고 이런 빈 껍데기 `Header`라면 `children`이 optional prop이면 안되지 않을까요?

2024-05-17 12:59 UTC, zigsong commented on src/recoil/atoms.ts
> +});
`atomFamily`로 작성하신 특별한 이유가 있나요~? 

저도 recoil은 잘 모르지만, `atomFamily`는 atom 팩토리 함수를 만들 때 사용하는 것 같아서요

`itemQuantityState`를 그냥 `atom`으로 만들었으면 안되는건지 궁금합니다

2024-05-17 12:59 UTC, zigsong commented on src/components/OrderAmount/OrderAmount.tsx
> +        <img src={InfoIcon} />총 주문 금액이 100,000원 이상일 경우 무료 배송됩니다.
`<img>`에는 `alt` 속성도 있어야 합니당~

2024-05-17 12:59 UTC, zigsong commented on src/components/OrderAmount/OrderAmount.tsx
> +          <Amount>{convertToLocaleAmount(orderAmount)}</Amount>
`{orderAmount.toLocaleString('ko-KR')}원`으로 써도 되지 않을까요~? 

(굳이 `.concat()` 필요없이요! )

2024-05-17 12:59 UTC, zigsong commented on src/recoil/selectors.ts
> +  },
`deliveryFee`나 `totalAmount`의 경우에는 선택된 cart item들의 quantity * price로부터 파생되는 값이므로 별도의 state로 관리하는 게 적절하지 않은 것 같습니다 🙃 

어떻게 생각하시나요?

2024-05-17 12:59 UTC, zigsong commented on src/recoil/selectors.ts
> +      [] as { product: Product; quantity: number }[],
뭔가 로직이 잘못되어서 마지막에 타입 단언이 필요해진 것 같은데요~ 

`cartItems.reduce((arr, item) => ...)`에서 `arr`는 `CartItem` 타입의 값으로, 실제로 배열이 아니지 않나요? `acc`를 쓰려다가 `arr`로 잘못 써서 배열로 착각하고 `arr.push`를 하신 것 같은데요, 제가 이해한 것이 맞다면 다시 예측 가능한 타입으로 작성해주셔야 할 것 같습니다

2024-05-17 12:59 UTC, zigsong commented on .prettierrc
> +  "embeddedLanguageFormatting": "auto",
`embeddedLanguageFormatting` - 검색해도 잘 안 나오는 낯선 속성이네요 🙃

2024-05-17 12:59 UTC, zigsong commented on src/__test__/CartItem.test.ts
> +  },
테스트코드에서 API mocking까지 잘 해주셨네요 :D

2024-05-17 12:59 UTC, zigsong commented on src/__test__/CartItem.test.ts
> +    const { result } = renderHook(() => useRecoilState(itemQuantityState(0)), {
이런 초기값 테스트를 놓치기가 쉬운데 (저도... ㅎㅎ) 꼼꼼히 잘 작성해주신 것 같습니다 !

2024-05-17 12:59 UTC, zigsong commented on src/__test__/itemQuantity.test.ts
> +  it('itemQuantityState의 값은 setter에 의해 변경이 가능해야 한다.', () => {
RTL로 작성하는 테스트는 '사용자 관점'의 동작 테스트로 작성하는 것이 좋아요.

setter의 동작을 확인하는 것이 아니라, 

ex.) `'+' 버튼을 누르면 수량이 ~~ 어떻게 된다.`

와 같은 테스트 명세로 작성하시는 것을 권장드립니다

2024-05-17 12:59 UTC, zigsong commented on src/apis/index.ts
> +  }
`fetch()`의 원천 코드에서 에러를 던지고 있는데, `fetchCartItems()`를 사용하는 곳들에서는 아무런 에러 처리가 되고 있지 않네요 🧐

2024-05-17 12:59 UTC, zigsong commented on src/apis/index.ts
> +    },
요런 반복되는 `header`들의 중복을 제거해볼 수 있을까요?

2024-05-17 12:59 UTC, zigsong commented on src/hooks/useCheckedItemIds.ts
> +
`check`와 `uncheck`의 함수를 나누기보다는, `check`라는 함수 하나만 두고, '선택'할 것인지 '선택 해제'할 것인지는 사용처가 아닌 `check` 함수 내에서 구분해야 합니다! 

지금같은 경우에는 사용처에서 checkbox 클릭 시 항상 이전 상태를 직접 체크해야 하기 때문이죠. `useCheckedItems` hook으로 추상화한 상태를 UI 컴포넌트에서 직접 확인하는 것은 좋은 패턴은 아닙니다

2024-05-17 12:59 UTC, zigsong commented on src/components/PreviousPageButton/PreviousPageButton.tsx
> +  return <Button onClick={onClick} />;
`<button>` 태그의 기본 `type`은 무엇일까요? 👀

2024-05-17 12:59 UTC, zigsong commented on src/components/FooterButton/FooterButton.tsx
> +  children?: undefined;
`children`의 타입이 `undefined`여야 하나요?

2024-05-17 12:59 UTC, zigsong commented on src/page/ConfirmOrderPage.tsx
> +      <FooterButton buttonText="결제하기" disabled />
2단계에서 공개될 예정인가보군요 😲

2024-05-17 12:59 UTC, zigsong commented on src/page/ShoppingCartPage.tsx
> +      totalAmount.state === 'hasValue'
오로지 `hasValue`만을 위해 `useRecoilValueLoadable`를 사용하신 건가요? 

따로 로딩이나 에러 상태에 대한 대응을 해주지 않을 거라면 그냥 `useRecoilValue`를 썼어도 됐을 것 같아요

2024-05-20 19:20 UTC, seongjinme commented on src/constants/endpoints.ts
> +} as const;
아래 첫 번째 커밋을 통해 수정했습니다! 🙏 

* [refactor: 경로 상수명을 복수형(ENDPOINTS)에서 단수형(ENDPOINT)로 변경](https://github.com/woowacourse/react-shopping-cart/pull/272/commits/d17655c5d46154d8ed9a479bc8bc31434721e942)

2024-05-20 19:23 UTC, seongjinme commented on src/page/ShoppingCartPage.tsx
> +    </>
PR을 드릴 당시엔 `ConfirmButton` 요소가 비동기 `selector`에 의존하고 있는 부분이 있어서인지 `Suspense`를 붙여줘야 콘솔에 에러가 뜨지 않았었습니다. 리팩토링 과정에서 관련 로직을 모두 정리하고, 해당 버튼은 공통 요소인 `FooterButton`으로 대체하면서 `Suspense`도 함께 제거해 주었어요. :)

* [refactor: ConfirmButton을 FooterButton으로 대체하고 Suspense 제거](https://github.com/woowacourse/react-shopping-cart/pull/272/commits/e71ef3221bac948b43caa320bfa4c57163b9b66f)

2024-05-20 19:24 UTC, seongjinme commented on src/components/Header/Header.tsx
> +}
말씀대로 불필요한 구조분해 + 잘못된 prop 사용이 섞인 컴포넌트가 되어버렸네요 😓
리팩토링 과정에서 `Header`를 `NavigationBar` 컴포넌트로 바꾸었고, 그 과정에서 위의 내용을 모두 수정하였습니다.

* [refactor: NavigationBar에서 props destructuring 제거](https://github.com/woowacourse/react-shopping-cart/pull/272/commits/426d6c30d4979c3c23adf9e184537279bccb4a3b)

2024-05-20 19:40 UTC, seongjinme commented on src/recoil/atoms.ts
> +});
장바구니에 담겨있는 각각의 상품 별로 주문 수량(`itemQuantity`)의 상태를 관리하고자 했어요. 서버에서 동적으로 생성되는 주문상품별 `id`값에 대응하여 해당 상품의 수량을 편리하게 관리할 방법이 없을까 궁리하다가 `atomFamily`를 도입해 보았습니다.

`atomFamily<number, number>`에서 첫 번째 제네릭 인자는 `atom`의 값의 타입, 두 번째 제네릭 인자는 해당 `atom`을 식별할 매개값의 타입을 의미해요. 요렇게 생성한 `itemQuantityState`라는 `atom`은 실제 필요한 곳에서 `itemQuantityState(cartItemId)` 형태로 불러올 수 있습니다. 덕분에 개별 장바구니 상품을 관리하는 `CartItem` 컴포넌트에서 해당 상품의 주문 수량을 편리하게 가져다 쓸 수 있게 되었어요.

관련하여 제가 참고한 문서는 아래와 같습니다. :)
* https://recoiljs.org/ko/docs/api-reference/utils/atomFamily/
* https://junglast.com/blog/recoil-atomfamily-atom

2024-05-20 19:42 UTC, seongjinme commented on src/components/OrderAmount/OrderAmount.tsx
> +        <img src={InfoIcon} />총 주문 금액이 100,000원 이상일 경우 무료 배송됩니다.
꼼꼼하게 챙겼어야 했는데 놓쳐서 부끄럽네요 🫨 아래 커밋으로 `alt` 속성을 추가했어요. 감사합니다!

* [refactor: 무료 배송 기준 메시지 아이콘 이미지에 alt 속성 추가](https://github.com/woowacourse/react-shopping-cart/pull/272/commits/70739d665054d1a80a57c6d7b2fae22784c2e173)

2024-05-20 19:43 UTC, seongjinme commented on src/components/OrderAmount/OrderAmount.tsx
> +          <Amount>{convertToLocaleAmount(orderAmount)}</Amount>
해당 함수 로직에서 `.concat()`을 제거하고 템플릿 리터럴 방식으로 금액 문구를 출력하도록 수정했습니다 :D

* [refactor: 금액 문자열 표시 로직을 concat 함수에서 템플릿 리터럴 방식으로 수정](https://github.com/woowacourse/react-shopping-cart/pull/272/commits/bcf0a063e408a74c1df5f6f7974485956fbaf6a1)

2024-05-20 20:05 UTC, seongjinme commented on src/recoil/selectors.ts
> +  },
사실... 말씀주신 항목들을 컴포넌트에서 개별적으로 계산시킬 것인지, `selector`로 묶어 관리할 것인지는 페어 프로그래밍 당시부터 꽤 고민했던 부분이었어요. Recoil의 `selector` 자체가 파생 상태를 다루기 위해 만들어진 순수 함수의 개념이기 때문에 위와 같이 활용하는 것도 괜찮다고 생각했거든요. 

지그의 코멘트를 보고 조금 더 숙고하면서, Recoil을 사용하는 환경에서 상태를 분류하는 나름의 기준을 아래와 같이 세워 보았습니다. 😃 

* `atom` : 하나의 'source of truth'를 다루는 기준점으로 사용한다.
* `selector` : 하나 이상의 `atom` 혹은 `selector`에 기반한 파생 상태로서, 상태의 변경에 따라 자동으로 업데이트 되어야 하며 여러 컴포넌트에서 재사용되어야 하는 경우에 사용한다.
* 이밖에 `atom` 혹은 `selector`에 기반한 파생 상태지만 특정 컴포넌트에서만 필요한 경우엔 일반 변수를 활용한다.

위에 열거된 금액 상태들은 다른 컴포넌트에서 재사용되기도 하고, 2단계 미션에서 쿠폰/배송비 옵션이 늘어나면서 로직이 복잡해질 여지가 있어서 일단 남겨두었어요. 다만 위의 기준에 비추어 불필요하다고 판단된 나머지 `atom`, `selector`들은 아래 커밋을 통해 정리하였습니다. 🙏 

* [refactor: 상품 체크 유무를 배열형태로 재정리하고 불필요한 selector, atom 삭제](https://github.com/woowacourse/react-shopping-cart/pull/272/commits/9926aa6d41b65fdf09e78b80787e6b85fb8ced94)

2024-05-20 20:20 UTC, seongjinme commented on src/recoil/selectors.ts
> +      [] as { product: Product; quantity: number }[],
장바구니에서 체크 표시된 상품별 주문 수량을 `{ product: Product; quantity: number }`의 배열 형태로 얻기 위한 코드였는데요. 미션 마감에 쫓기면서 작성하다 보니 말씀대로 로직도 복잡하고 의도를 파악하기 어려운 코드가 되었던 것 같아요. 이번에 대대적으로(?) 리팩토링을 진행하면서 상품 관련 로직을 크게 간소화했고, 그 과정에서 위의 코드는 불필요하게 되어 완전히 삭제했습니다. 😅 

* [refactor: 상품 체크 유무를 배열형태로 재정리하고 불필요한 selector, atom 삭제](https://github.com/woowacourse/react-shopping-cart/pull/272/commits/9926aa6d41b65fdf09e78b80787e6b85fb8ced94)

2024-05-20 20:29 UTC, seongjinme commented on .prettierrc
> +  "embeddedLanguageFormatting": "auto",
[하나의 언어로 쓰인 파일 안에서 다른 언어의 코드가 감지되었을 때 그 코드도 함께 자동으로 포맷팅시켜줄 것인지를 정하는 속성](https://prettier.io/docs/en/options.html#embedded-language-formatting)입니다. `.tsx` 파일 안에서 TypeScript와 HTML 태그를 함께 포맷팅할 때 필요한 옵션이에요. `auto`와 `off`로만 설정 가능하고, 기본값은 `auto`입니다. 

저는 요즘 미션 초기에 `prettier`를 설정할 때마다 [공식 웹사이트의 Playground](https://prettier.io/playground/)에서 여러 실험을 해보고, 가장 취향에 맞는 속성들을 골라서 적용하고 있어요. 그러다 보니 평소에 잘 쓰이지 않는 설정값들도 파일에 함께 포함된 것 같습니다 😅

2024-05-20 20:35 UTC, seongjinme commented on src/__test__/itemQuantity.test.ts
> +  it('itemQuantityState의 값은 setter에 의해 변경이 가능해야 한다.', () => {
"사용자 관점"의 동작 테스트라는 것이 드러나도록 명세를 새로 고쳐 작성했어요. 리팩토링 이후에 변화한 로직들도 반영하여 테스트 코드를 새로 수정했습니다. 코드를 쓰는 당사자의 입장만 반영되기 쉬운 부분이었는데 이렇게 짚어주셔서 감사해요. 🙏 

* [test: 테스트 코드 명세 및 구조 변경](https://github.com/woowacourse/react-shopping-cart/pull/272/commits/a36ebe1b8cc8cbb304bd049bc9bbd2655a109c6f)

2024-05-20 20:47 UTC, seongjinme commented on src/apis/index.ts
> +  }
비동기 코드에 대한 에러 처리를 이번 리팩토링 과정에서 적용했습니다. 개인적으로 가장 헤매기도 하고 애를 먹기도 했던 부분인데요, 그래서 여러 단계에 걸쳐 커밋을 반영했습니다. 단순히 에러에 대한 예외 처리로만 그치지 않고, 에러 상황에 대해 사용자에게 어떻게 안내하면 좋을 것인지를 나름대로 고민해보고 시각화까지 해보는 데에 초점을 두었어요. 이 과정에서 `router`와 `ErrorBoundary`, 에러 처리용 상태 관리와 커스텀 훅까지 익혀볼 수 있는 좋은 경험을 얻었습니다. 🙏 

* [refactor: react-router의 라우팅 설정을 별도 파일로 분리](https://github.com/woowacourse/react-shopping-cart/pull/272/commits/fcb029789e6f2224229ddf58475bbd2ecdaa60f8)
* [refactor: fetch API 코드 추상화 및 리팩토링 적용](https://github.com/woowacourse/react-shopping-cart/pull/272/commits/37dcbcc9e5e30d29a6a9dc89d5f601212f0121df)
* [feat: route 및 fetch 에러에 대한 예외처리 및 에러페이지 이동 로직 구현](https://github.com/woowacourse/react-shopping-cart/pull/272/commits/84ecb0135eeb80fffab73eb2d2fa7ea691c6e820)
* [feat: fetch 오류 발생 시 에러 화면 컴포넌트(ErrorFallback) 출력 기능 구현](https://github.com/woowacourse/react-shopping-cart/pull/272/commits/f7b8517a38bdfd2d1329a50720a188d7dfb067e4)

이렇게 해서 구현된 에러 화면의 예시는 다음과 같습니다. 😅 

<details>
<summary>일반 에러 화면</summary>

<img width="476" alt="image" src="https://github.com/woowacourse/react-shopping-cart/assets/73219583/45bcd96b-f824-41d4-8d05-fbe3d22d4b21">
</details>

<details>
<summary>네트워크 에러 화면</summary>

<img width="476" alt="image" src="https://github.com/woowacourse/react-shopping-cart/assets/73219583/e528f94e-109a-43aa-bbda-f85c6320ad66">
</details>

2024-05-20 20:50 UTC, seongjinme commented on src/apis/index.ts
> +    },
반복되는 `header`들의 중복을 없애고, `fetch` 기능 자체도 함께 추상화하여 분리하면 유용하겠다고 판단하여 아래 커밋 내용과 같은 리팩토링을 진행했어요. 추후에 새로운 URL 경로로 새 API 함수를 만들어야 할 때에도 적은 작업량으로 빠르게 대응할 수 있도록 하는 것을 목표했습니다. 🙏 

* [refactor: fetch API 코드 추상화 및 리팩토링 적용](https://github.com/woowacourse/react-shopping-cart/pull/272/commits/37dcbcc9e5e30d29a6a9dc89d5f601212f0121df)

2024-05-20 21:01 UTC, seongjinme commented on src/hooks/useCheckedItemIds.ts
> +
개인적으로 이번 리팩토링 과정에서 꼭 개선하고 싶었던 부분 중 하나가 장바구니 상품들의 체크박스 관리 로직이었어요. `[{ cartItemId: boolean }, ...]` 형태로 관리되는 데이터 로직도 복잡했고, 말씀대로 개별 함수의 코드에도 아쉬운 부분이 많았어요. 이 문제는 아래의 두 단계를 거쳐 나름대로 해결해 보았습니다.

1. 개별 상품에 대한 체크 유무를 `[cartItemId, ...]` 형태의 `number[]` 타입으로 대체 -> 체크박스 관리 로직 간소화
2. 체크박스 커스텀 훅을 `useCheckedItemIds`에서 `useCheckCartItem`으로 변경하고 내부 함수들의 로직 간소화

현재는 개별 상품에 대한 체크 용도의 함수를 `onCheckCartItem`로 통일한 상태입니다. 다만 인자로 상품 ID값과 boolean값을 여전히 받는 상태이긴 한데요. 이를 어떻게 더 개선할 수 있을지는 계속 고민해 보겠습니다!

* [refactor: 상품 체크 유무를 배열형태로 재정리하고 불필요한 selector, atom 삭제](https://github.com/woowacourse/react-shopping-cart/pull/272/commits/9926aa6d41b65fdf09e78b80787e6b85fb8ced94)
* [refactor: 상품 체크박스 커스텀 훅을 useCheckCartItem로 개편하고 로직을 간소화](https://github.com/woowacourse/react-shopping-cart/pull/272/commits/bfc1881a6840ea284ead33f6ba841758590e7ce4)

2024-05-20 21:03 UTC, seongjinme commented on src/components/PreviousPageButton/PreviousPageButton.tsx
> +  return <Button onClick={onClick} />;
별다른 속성값을 주지 않는다면 `<button>` 태그의 `type`이 `submit`으로 설정됩니다. 이렇게 `type`이 빠진 버튼 요소들이 `<form>`과 함께 쓰였다면 의도하지 않은 오동작이 일어날 수 있었겠네요 😓  꼼꼼하게 살펴주셔서 정말 감사해요. 🙏 

* [refactor: 버튼 요소에 대한 기본 type 설정 추가](https://github.com/woowacourse/react-shopping-cart/pull/272/commits/eed6327d050de9014a670dbc52a1758939ca9c90)

2024-05-20 21:06 UTC, seongjinme commented on src/components/FooterButton/FooterButton.tsx
> +  children?: undefined;
여러모로 불필요한, 그리고 부적합한 설정이었던 것 같습니다... 리뷰 반영 전 리팩토링 과정에서 가장 먼저 수정했습니다. 🙏 

* [refactor: 전체 컴포넌트 구조 개선 및 컴포넌트별 스타일 분리](https://github.com/woowacourse/react-shopping-cart/pull/272/commits/d8448beb42bff79d0baaeb9006693be3ea1bd215)

2024-05-20 21:13 UTC, seongjinme commented on src/page/ShoppingCartPage.tsx
> +      totalAmount.state === 'hasValue'
PR을 올려드릴 당시의 코드 베이스에서는, 위의 값들에 대해 `useRecoilValue`를 썼을 경우 '렌더링되지 않은 컴포넌트에 대한 상태값 변화'와 관련된 에러 메시지가 콘솔에 찍혔습니다. 당시에는 비동기 코드에 기반한 위의 값들을 안전하게 가져다 쓰기 위해 `useRecoilValueLoadable`을 사용했었어요. 다만 `Suspense`가 이미 있는데 굳이 `hasValue`만을 위해 `useRecoilValueLoadable`을 쓰는 것이 올바른 구현법인지에 대해서는 저도 확신이 없는 상태였습니다. 😅 

디버깅 과정에서, 위 코드의 출처인 `ShoppingCartPage`가 라우팅되는 `RouterProvider`를 `Suspense`로 감싸는 해법을 찾게 되었어요. 이러한 방법으로 콘솔 에러를 해결했고, 이에 따라 위의 값들도 `useRecoilValue`로 전환했습니다. :)

* [refactor: useRecoilValueLoadable을 useRecoilValue와 Suspense 조합으로 대체](https://github.com/woowacourse/react-shopping-cart/pull/272/commits/4b0ca33789f25eabf0abb239f9111bd1f03f4b73)

2024-05-21 03:21 UTC, zigsong commented on src/recoil/atoms.ts
> +});
아하 `atomFamily`에 제네릭만 제대로 넘겨주면 동적으로 값을 가져오는 데 있어 유효한 param을 넘겨줄 수 있군요! 

설명 감사합니다 아르 :D 제대로 공부하고 잘 사용하신 것 같네요 👍

2024-05-21 03:22 UTC, zigsong commented on src/recoil/selectors.ts
> +  },
상태를 분류하는 기준과 상태관리 도구를 적절하게 사용하는 방법은 현업 개발자들도 많이 고민하는 부분인데, 아주 멋지게 잘 정리해주셨네요! 

이번처럼 앱 요구사항에 따라 아르만의 기준을 가지고 상태를 적절하게 관리한다면 아주 튼튼하고 유지보수가 편리한 코드를 만드실 수 있을 거예요! 💪

2024-05-21 03:24 UTC, zigsong commented on src/recoil/selectors.ts
> +      [] as { product: Product; quantity: number }[],
코드를 리팩터링하시면서 변수이름들도 훨씬 직관적이고 간결해졌네요 😉

2024-05-21 03:28 UTC, zigsong commented on src/recoil/atoms.ts
> +  default: Promise.resolve(fetchCartItems()),
그런데 이곳은 왜 `Promise.resolve()`를 사용했나요? 그냥 `fetchCartItems`를 넘겨줘도 똑같지 않나요?

2024-05-21 03:28 UTC, zigsong commented on src/apis/index.ts
> +  }
`useFetchError` hook과 에러 화면 시 되돌아갈 버튼까지! 짧은 시간 안에 디테일하게 잘 구현하셨네요 😲

2024-05-21 03:43 UTC, zigsong requested changes
안녕하세요 아르! 몸이 좋지 않으셨다니 🥲 개발만큼이나 중요한게 건강관리이니 더워지는 날씨에 건강 유의하시길 바랄게요! 

그래도 짧은 시간 동안 리뷰를 모두 반영하고 컴포넌트 리팩터링 및 테스트코드도 완벽하게 잘 짜주셔서 놀랍습니다 😲 

충분히 잘해주셨는데, 2단계로 넘어가기 전 확인해야 할 코멘트가 있어 한번만 더 요청 보낼게요. 화이팅이에요! 💪

2024-05-21 03:43 UTC, zigsong commented on .github/workflows/deploy.yaml
> +on:
github workflow까지 작성해주셨네요 :ㅇ

2024-05-21 03:43 UTC, zigsong commented on src/apis/fetchData/fetchData.constants.ts
> +export const ERROR_MESSAGE = {
파일 이름도 `errorMessage` 등으로 바꿔주는 것이 좋을 것 같아요 :D

2024-05-21 03:43 UTC, zigsong commented on src/components/common/CheckBox/CheckBox.tsx
> +const CheckBox = styled.button<CheckBoxProps>(({ isChecked }) => ({
checkbox는 `button` 태그가 아닌 `<input type='checkbox'>`로 마크업한 후 CSS를 통해 스타일링 및 hidden처리 해주셔야 합니다! 2단계에서 같이 수정해주세요 :)

2024-05-21 03:43 UTC, zigsong commented on src/components/shoppingCart/CartItem/CartItem.tsx
> +  const [itemQuantity, setItemQuantity] = useRecoilState(itemQuantityState(cartItemId));
`useRecoilState`를 사용해서 react의 `useState`처럼 사용할 수 있군요 🙃

2024-05-21 03:43 UTC, zigsong commented on src/components/shoppingCart/CartItemContainer/CartItemContainer.tsx
> +  };
요것은 `CartItemContainer`가 아닌 `CartItem`에 있어도 괜찮지 않나용?

2024-05-21 03:43 UTC, zigsong commented on src/components/shoppingCart/QuantityController/QuantityController.tsx
> +  maxQuantity = Infinity,
`Infinity`와 같은 값은 위험할 수 있기 때문에 임의의 값이라도 프론트에서 지정해주는 것이 좋을 것 같습니다!

2024-05-21 03:43 UTC, zigsong commented on src/page/ShoppingCartPage/ShoppingCartPage.tsx
> +      },
이 정보들은 단순 navigation으로 넘겨주기에는 중요한 내용들을 담고 있는데, `ConfirmOrderPage`에서도 `useRecoilValue` 등을 통해서 상태값으로 접근하는 것이 좋지 않을까요? 

\* 이 부분은 2단계로 넘어가기 전 수정 또는 아르의 의견이 필요할 것 같아요!

2024-05-21 04:40 UTC, seongjinme commented on .github/workflows/deploy.yaml
> +on:
애플리케이션 빌드 및 배포 자동화 솔루션에 관심이 있습니다. 그래서 레벨2 미션들부터 Github Actions를 이용해보고 있어요. 별도의 패키지나 플랫폼에 의존하지 않고 언제든 원하는대로 빌드-배포를 한 번에 할 수 있어서 편리한 것 같아요. :)

2024-05-21 06:31 UTC, seongjinme commented on src/recoil/atoms.ts
> +  default: Promise.resolve(fetchCartItems()),
`atom`의 `default`에 비동기 함수를 넘길 경우 해당 Promise가 resolved될 때까지 초기값이 `undefined`로 설정되는 문제를 피하고 싶었어요. 그런데 코드를 다시 살펴보니... `fetchCartItems` 자체가 이미 `Promise<CartItem[]>`를 반환하기 때문에 결과적으로는 `Promise<CartItem[]>`으로 넘어오는 반환값을 Promise로 한 번 더 감싸는 셈이었네요. 

말씀대로 `fetchCartItems`를 `default`로 바로 넘기도록 수정했습니다. 세심하게 살펴주셔서 감사해요 😄 

* [refactor: 장바구니 상품 atom(cartItemsState)의 기본 상태를 간소화](https://github.com/woowacourse/react-shopping-cart/pull/272/commits/2dc6a5ab1cf2c01cd2b033e4f20d44a78212a09d)

2024-05-21 06:38 UTC, seongjinme commented on src/components/common/CheckBox/CheckBox.tsx
> +const CheckBox = styled.button<CheckBoxProps>(({ isChecked }) => ({
의미적으로 '체크박스'의 역할을 하는 요소이니 `button`보다는 `<input type='checkbox'>`로 마크업해야 한다는 말씀에 동의합니다. 피드백 주셨던 다른 내용들 적용하는 김에 바로 적용해 보았어요. 😄 

* [refactor: 체크박스 요소를 button에서 checkbox 타입의 input으로 대체](https://github.com/woowacourse/react-shopping-cart/pull/272/commits/31f4ddedbae129c2392aaacaae5eee58a7599982)

2024-05-21 06:38 UTC, seongjinme commented on src/components/shoppingCart/CartItemContainer/CartItemContainer.tsx
> +  };
비동기 로직을 `CartItemContainer`에 모아두고자 이렇게 작성했었는데요. 살펴보니 개별 상품의 수량을 변경하는 로직은 해당 기능을 가진 `QuantityController` 컴포넌트를 들고 있는 `CartItem`으로 넘겨도 괜찮겠다는 생각이 들었네요 😅 

아래 커밋을 통해 반영하였고, 달라진 로직 구조에 맞춰서 테스트 코드도 수정했습니다!

* [refactor: 상품 수량 변경 로직을 CartItemContainer에서 CartItem으로 이동](https://github.com/woowacourse/react-shopping-cart/pull/272/commits/667a0faea0f2046e280e39005a1a61dba77f9790)
* [test: 장바구니 상품 변경 로직 테스트를 QuantityController로 이동 처리](https://github.com/woowacourse/react-shopping-cart/pull/272/commits/741f19df89dd72d4aafe6c84029ca0c78f251987)

2024-05-21 06:39 UTC, seongjinme commented on src/components/shoppingCart/QuantityController/QuantityController.tsx
> +  maxQuantity = Infinity,
최대 주문 가능 수량을 `100`으로 제한하여 `QuantityController` 컴포넌트를 수정했습니다. :D

* [refactor: QuantityController의 주문 최대 수량을 100으로 설정](https://github.com/woowacourse/react-shopping-cart/pull/272/commits/b0f8bd0f055a6168fbcc1966fbec8aa53b83125e)

2024-05-21 06:44 UTC, seongjinme commented on src/page/ShoppingCartPage/ShoppingCartPage.tsx
> +      },
사용자가 장바구니를 거치지 않고 임의로 `ConfirmOrderPage`로 찾아오는 것을 막는 차원에서 위와 같이 구현했었어요. 하지만 말씀대로 전역적으로 관리되는 상태를 굳이 react-router 통해 넘겨줄 필요가 없다는 말씀에 공감합니다. 마침 오늘 공개된 2단계 미션 내용을 반영하기 위해서라도 위 로직을 고쳐야 하는 상황이었어요.

`ConfirmOrderPage`에서 필요한 주요 상태값은 `useRecoilValue`로 접근하도록 했습니다. 대신 장바구니 페이지에서는 `ConfirmOrderPage`로 넘어갈 때 `isFromCartPage`라는 `boolean` 타입 state를 `navigate`로 넘기도록 했습니다. 사용자가 임의로 주문 확인 페이지에 직접 접근하지 못하게 하면서, 전역 상태관리도 효율적으로 사용하는 효과를 얻어보고자 했어요 🙏 

* [refactor: ConfirmOrderPage가 recoil 상태를 참조하면서 사용자 직접 접근을 방지하도록 수정](https://github.com/woowacourse/react-shopping-cart/pull/272/commits/c7ed727b7668dddd7b207bbd7b8384a0108d4519)

2024-05-21 09:07 UTC, zigsong commented on src/page/ShoppingCartPage/ShoppingCartPage.tsx
> +      },
오오

> 사용자가 임의로 주문 확인 페이지에 직접 접근하지 못하게 하면서, 전역 상태관리도 효율적으로 사용하는 효과

이렇게까지 고민하고 반영해주시다니 아주 멋집니다! 👍

2024-05-21 09:08 UTC, merged