[1단계 - 장바구니 미션] 마루(박규한) 미션 제출합니다.
woowacourse/react-shopping-cart pull request #276
Opened 2024-05-16 08:55 UTC by rbgksqkr

안녕하세요 피터! 만나서 반갑습니다 ㅎㅎ 페어 프로그래밍을 진행하는 시기에 테코톡 발표가 있어서 아쉬운 부분이 여럿 있지만 리팩터링할 때 적극적으로 반영하겠습니다! 

이번 미션에서는 다양한 상태관리를 recoil을 활용하여 처리하는 부분이  핵심이였다고 생각하여 이를 중점으로 고민해보았습니다. recoil 상태관리를 어떻게 리팩터링해야 recoil을 더 활용도 높게 사용하는 것인지, 요구사항이 추가될 경우 어떤 구조가 복잡한 상태관리를 해결할 수 있을지 중점적으로 봐주시면 감사하겠습니다!!

### 실행 방법

현재 배포 링크는 https 인데 서버는 http 이기 때문에 cors 에러가 발생합니다. 그래서 제가 env 파일을 드리고 로컬에서 돌리는 방법이 있고, `브라우저 설정에서 안전하지 않은 컨텐츠를 허용` 하여 확인하는 방법이 있을 것 같습니다! 후자의 방법이 피터가 번거롭지 않다고 판단하여 배포를 진행하였습니다!

배포링크 : https://rbgksqkr.github.io/react-shopping-cart/

## ✅ 구현 사항

> 핵심기능 : 장바구니 화면에서 선택된 상품의 수량 및 총 결제 금액을 확인하고 주문을 확정할 수 있다.
> 
- CartPage
    - Cart : CartPage의 가독성을 높이기 위해 UI 컴포넌트로 각각 분리하였습니다.
        - CartHeaderSection
        - CartMainSection
        - CartFooterSection
    - CartItem : 상품 1개에 대한 데이터 처리를 위해 컴포넌트를 분리하였습니다.
        - CartItemHeaderSection
        - CartItemMainSection
- CartConfirmPage
- recoil
    - atoms
    - selectors

개발 환경 세팅 : 전역 상태 관리를 진행하면서 import문이 많아질 것을 고려하여 절대경로 설정과 eslint에 import문 정렬을 세팅하였습니다.

## 💭 질문 사항

### 전역 상태 관리

서버에서 가져오는 데이터를 모두 atom으로 이용하여 관리하였는데, 전역 상태 관리를 사용하면 모든 데이터를 관리하는지, 아니면 특정 데이터만 관리하는 건지 궁금합니다! 현재 모든 데이터를 atom으로 관리한 이유는 해당 데이터에서 계산할 수 있는 내용을 selector에서 가져와 계산할 수 있었기 때문입니다.
이와 같이 바로 자식의 경우 props로 내려주는 것이 더 간단할 것 같은데, 하위 컴포넌트에서 props로 내려주는 값과 recoil로 가져오는 값, 2개로 관리되는 것 같아서 코드의 가독성이 떨어지는 우려가 있습니다. 이에 대해 어떻게 생각하시는지 궁금합니다!

### RTL 테스트 코드 작성

RTL 테스트 코드를 작성할 때 보통 비동기 코드를 어떻게 처리하는지 궁금합니다. 현재 요구사항을 충족시키기 위해선 비동기 코드를 모킹해야한다고 생각하는데, 원래도 비동기 요청을 하는 경우 모두 모킹을 진행하는지 궁금합니다! 그리고 RTL 테스트 코드에서는 jest와 e2e 테스트 사이의 테스트 코드를 작성해야할 것 같은데, 어떤 기준으로, 어떤 것을 테스트해야하는지 궁금합니다!

2024-05-16 16:40 UTC, iborymagic commented
1).
기본적으로 전역 상태라는 것이, 여러 컴포넌트에서 공유되는 상태이기 때문에 전역으로 관리된다는 것을 고려하여 마루가 한 번 생각해보시는 편이 좋을 것 같습니다. 요 부분에 대해서 직접 생각해보고 정의를 내리고 가야, 나중에 사이즈가 큰 프로젝트에서 여러 상태값들이 와르르 쏟아질 때도 헷갈리지 않을 수 있을 거에요!
참고로 저는 서버에서 가져오는 데이터를 recoil 같은 전역 상태 관리 라이브러리를 사용하여 관리하지는 않고, react-query같은 별도의 라이브러리를 이용하는 편이긴 해요. (recoil을 사용해서 서버 상태를 관리하기도 하던데, 저는 한 번도 해본 적이 없습니다)
추가로, 컴포넌트 내부에서 관리되는 상태값과 recoil에서 관리되는 상태값이 분리되면 가독성이 떨어진다고 생각하시는 이유가 뭘까요? 제가 생각하기에는 오히려 나중에 앱의 사이즈가 커지거나 했을 때, 모든 상태를 전부 전역 상태로 돌리게 되면 어떤 상태가 어디서 업데이트되는지 구분하는 데에만 한 세월이 걸릴 것 같아요!

2-1)
저는 네트워크 상태가 테스트에 영향을 끼치는 걸 방지하기 위해 비동기 요청이 있는 경우는 웬만하면 모킹을 하는 편입니다!

2-2) 
RTL로 무엇을 테스트해야하는지는 RTL 공식문서를 보면 대충 감을 잡으실 수 있을 것 같아요! 컴포넌트의 내부 상태, 내부 메서드, 라이프사이클 메서드, 자식 컴포넌트 등의 세부 구현은 테스트를 하지말라고 되어있으니, 이로 미루어 보았을 때, 세부적인 구현들보다는 특정 컴포넌트에서 사용자가 어떤 상호작용을 했을 때 어떤 결과가 나타나는지를 테스트해보아야 한다는 것을 추론해볼 수 있겠지요.
https://testing-library.com/docs/

2024-05-16 16:40 UTC, iborymagic requested changes
안녕하세요 마루! 장바구니 미션 진행하시느라 고생 많았습니다.
말씀주신 Recoil의 사용도 전반적으로 큰 무리 없이 잘 사용해주신 것 같고, atom도 최소한으로 잘 유지해주시고 계신 것 같아서 관리도 크게 무리가 없어보이네요!
관련해서 이야기 나눠보면 좋을만한 내용들 코멘트로 달아놨습니다.
질문에 대한 답변도 별도의 코멘트로 달아놨으니, 더 이야기나누고 싶은 부분 있으시면 답변 달아주세요. 그리고 리뷰 확인 완료되면 다시 리뷰 요청 주세요~

2024-05-16 16:40 UTC, iborymagic commented on src/components/Cart/CartMainSection.tsx
> +        css={srOnly}
요 srOnly는 무슨 뜻인가용?

2024-05-16 16:40 UTC, iborymagic commented on src/components/CartItem/CartItemHeaderSection.tsx
> +  };
checked 여부같은 값은 아마 어떤 컴포넌트에서든 수정하게 되면 localStorage도 같이 세팅을 해줘야할 것 같아요! 이런 동기화 작업은 atomEffect를 사용해보시는 것도 추천드립니당

2024-05-16 16:40 UTC, iborymagic commented on src/components/CartItem/CartItemMainSection.tsx
> +    await updateItemQuantity(item.id, item.quantity - 1);
이 친구는 방어 로직이 없어도 되는걸까유?

2024-05-16 16:40 UTC, iborymagic commented on src/components/CartItem/CartItemMainSection.tsx
> +            disabled={item.quantity === 1}
오.. 디테일까지 👍 
일부 앱에서는 -를 눌러서 갯수가 0이 되면 장바구니에서 삭제가 되도록 하는 경우도 있더라구요. (그냥 참고용)

2024-05-16 16:40 UTC, iborymagic commented on src/constants/mock.ts
> +export const TOTAL_PRICE_UNDER_100000_DATA = [
테스트하기 편하게 요 목데이터를 처음에 집어넣어주시면 좋을 것 같아요! 링크에 들어갔는데 장바구니에 아무것도 없어서 테스트가 불가능하네요..!

2024-05-18 12:13 UTC, rbgksqkr commented on src/constants/mock.ts
> +export const TOTAL_PRICE_UNDER_100000_DATA = [
[4c5c948](https://github.com/woowacourse/react-shopping-cart/pull/276/commits/4c5c948c6eac246fa80d80149e6977882255bf8e) : 추가 버튼을 구현하여 아이템을 추가하여 테스트하기 용이하도록 수정하였습니다!

2024-05-18 12:17 UTC, rbgksqkr commented on src/components/CartItem/CartItemMainSection.tsx
> +    await updateItemQuantity(item.id, item.quantity - 1);
[62eeace](https://github.com/woowacourse/react-shopping-cart/pull/276/commits/62eeace90c76a1f64f802a1323bb3478e749ce5a) : JSON으로 넘겨주는 응답값이 없어서 처리하지 않았는데 결제 도메인이라는 측면에서 낙관적 업데이트를 하는게 적절하지 않다고 생각하여, 정상적인 status 값일 때 setState하도록 수정하였습니다!

2024-05-18 12:18 UTC, rbgksqkr commented on src/components/CartItem/CartItemHeaderSection.tsx
> +  };
[31c5833](https://github.com/woowacourse/react-shopping-cart/pull/276/commits/31c58330b493221c9fc0caf14bf153d9d7a07e97) : atom이 변경될 때마다 동기화해주는 기능이 있었군요! atomEffect를 활용하여 localStorage와 동기화하는 코드 추가하였습니다!

2024-05-18 12:21 UTC, rbgksqkr commented on src/components/Cart/CartMainSection.tsx
> +        css={srOnly}
ScreenReadOnly 라는 의미로 사용자에게는 input이 보이지 않지만 스크린 리더를 사용하는 사용자에게는 웹 접근성을 제공하는 체크박스입니다! input과 label로 구성되어 있어 텍스트 부분을 눌러도 체크박스의 이벤트를 동작시키기 쉽고, 별도의 이벤트핸들러를 처리해주지 않아도 된다는 점에서 채택하게 되었습니다. 
일반 div태그로 만들고 이벤트 핸들러를 달아 텍스트를 눌렀을 때 전체 선택이 되도록 하는 게 더 직관적일까요??

2024-05-18 12:24 UTC, rbgksqkr commented on src/recoil/cartItems/selectors.ts
> +});
[aa3487f](https://github.com/woowacourse/react-shopping-cart/pull/276/commits/aa3487ff01e5a063ff0e416411177406198d9405) : atom과 같이 selector도 각각 작은 단위로 유지해야 된다고 생각해서, 필요한 곳에서 사용되도록 분리했었습니다. 하지만 대부분 같이 사용되는 데이터고, 불필요하게 2번 순회하게 되므로 같은 종류의 데이터를 하나의 객체로 묶어 사용하는 측에선 구조분해할당으로 반환하도록 구현하였습니다!

2024-05-18 12:25 UTC, rbgksqkr commented on src/recoil/cartItems/selectors.ts
> +    return cartItems >= 100000 ? 0 : 3000;
[f38e0d8](https://github.com/woowacourse/react-shopping-cart/pull/276/commits/f38e0d81e4ddcfe69a85d97bb6aa11f442f589f0), [685f110](https://github.com/woowacourse/react-shopping-cart/pull/276/commits/685f110e313a0dd851f616444d289c331694371e) : 상수 처리 완료하였습니다!

2024-05-18 12:34 UTC, rbgksqkr commented on src/recoil/cartItems/selectors.ts
> +
[4e0367d](https://github.com/woowacourse/react-shopping-cart/pull/276/commits/4e0367db5c13d0816d17a7850a14260ea876fe74) : 디테일한 피드백 감사합니다! 검색해보니 모든 엔트리를 저장하는 게 기본값이라고 하여 최신값만 캐싱하도록 옵션을 수정하였습니다! 

그런데 이와 별도로 모든 recoil 변수가 최신값을 따르는 게 메모리 누수에 적절한 것 아닌가? 생각이 들었습니다. 그래서 모든 값에 캐시 정책을 변경하려고 하려다가 기본값이 모든 엔트리 저장인 이유가 있지 않을까? 라는 생각도 들었습니다. 그래서 일단 fetch하는 비동기 selector 외엔 적용하지 않았는데 어떤 경우에 모든 엔트리를 저장하는 경우가 유용한지 피터의 생각이 궁금합니다. 공식문서에서도 기본값이 변경될 수 있다고 하지만 그 이유에 대해선 잘 나와있지 않아서 여쭤봅니다!

2024-05-18 12:35 UTC, rbgksqkr commented on src/apis/cartItem.ts
> +  });
[3b032a8](https://github.com/woowacourse/react-shopping-cart/pull/276/commits/3b032a81898398c2ef739b01725fa9ca2ceeeb7b) : fetch API 요청에 중복되는 코드를 줄이기 위해 한단계 추상화한 fetcher를 구현하였습니다!

2024-05-18 12:36 UTC, rbgksqkr commented on src/apis/cartItem.ts
> +};
[62eeace](https://github.com/woowacourse/react-shopping-cart/pull/276/commits/62eeace90c76a1f64f802a1323bb3478e749ce5a) : 아래 코멘트대로 API 요청을 완료하고 status값을 확인 후 setState하는 걸로 수정하였습니다!

2024-05-18 12:47 UTC, rbgksqkr commented
안녕하세요 피터! 리뷰가 많은 도움이 되어서 코드가 꽤 변경사항이 있습니다 ㅎㅎ 코멘트에도 별도로 남겼지만 요약하면 다음과 같습니다.

- 비동기 로직을 selector 로 관리하며, cachePolicy_UNSTABLE을 `most-recent` 로 두어 최근 값만 캐싱
- fetcher 라는 fetch API 빌더 함수 구현
- 결제 도메인이라는 것을 고려하여 낙관적 업데이트를 없애고 API 요청이 완료된 후 업데이트
- 도메인 관련 상수화 및 css 상수화
- API 반환값을 모킹하여 RTL 컴포넌트 테스트 코드 작성
- atomEffect를 활용하여 localStorage와 동기화
- Suspense와 ErrorBondary를 적용하여 API 비동기 로직 UX와 안정성 개선
- 중복해서 계산하는 같은 종류의 selector 로직들을 하나로 묶어 한번에 계산 후 객체로 관리
- 테스트를 용이하게 하기 위해 add button 추가

### RTL 테스트 코드

RTL 테스트 코드 작성 시 요소를 타겟하는데 어려움이 있어 사용자 행동에 대한 테스트 코드 작성을 하지 못했습니다. 수량이 변경된 상태, 체크 박스가 체크된 상태값을 확인하기 위해 screen.getByText를 사용하였는데 css명과 겹치게 되고, CartItem의 경우 같은 태그가 여러개 생기다보니 오류가 지속적으로 발생하여 제대로 테스트되지 않았습니다. 그래서 CartItem과 같이 같은 컴포넌트가 나열될 때 어떤식으로 테스트 코드를 작성해야 할지 여쭤보고 싶습니다!

### atomFamily 적용 기준

현재 cartId와 체크 여부를 atomFamily로 사용하고 있고, 상태를 유지하기 위해 이 값을 로컬 스토리지에 저장하고 있습니다. 하지만 이럴 경우 수량(quantity)을 변경할 때 수량을 포함한 모든 정보를 담고 있는 atom을 setState해야해서  모든 데이터가 리렌더링 됩니다. 그래서 atomFamily를 사용하여 quantity까지 관리할 경우 변경된 아이템만 변경되어 리렌더링의 이점이 있습니다.

그럼에도 이 방식을 선택한 이유는 개수까지  atomFamily로 관리할 경우 기존 atom의 값은 서버에서 불러온 시점의 데이터가 남고, atomFamily의 개수와 일치하지 않기 때문이였습니다. 그래서 클라이언트에서만 관리되는 체크상태만 atomFamily로 구현했었는데 이에 대한 피터의 생각이 궁금합니다!

2024-05-20 02:15 UTC, iborymagic commented on src/recoil/cartItems/selectors.ts
> +
사실 저도 고민을 해봤던 부분인데, 요즘은 메모리 사이즈에 대한 걱정이 크지 않기도 하니 모든 결과를 캐싱해놓으면 그만큼 계산을 피할 수 있다는 점에서 성능을 끌어올리는 데에는 좋겠다 정도로 생각했던 것 같습니다.
특정한 경우를 생각해보라고 한다면 계산 비용이 높은 경우에 효과적일 수 있겠고, 결과값의 경우의 수가 적으면 캐싱하는 데에 필요한 메모리가 적을테니 그것도 고려해볼만 하겠네요.

2024-05-20 02:17 UTC, iborymagic commented on src/components/Cart/CartMainSection.tsx
> +        css={srOnly}
네이밍 뜻이 궁금해서 여쭤본 것이었습니다!

2024-05-20 02:41 UTC, iborymagic commented
1. 사실 질문을 정확하게 이해하지는 못했는데, 체크박스때문에 고민이신거라고 한다면 태그에 test-id나 aria-label 같은거를
품목의 id나 이름을 넣어서 자세하게 만들어준 다음 screen.getByTestId 혹은 getByLabelText 같은걸 사용해주면 되지 않을까요?

2. 저는 좋다고 생각해요. 서버 데이터와 클라 상태값의 싱크 문제로 인해서 현재 방식을 선택하신 걸로 알아들었는데, 그래서 저도 사실 recoil을 서버 데이터를 다루는 데에 쓰진 않았습니다. 주로 react-query 같은 별도의 도구를 사용하거나 했던 것 같아요.

2024-05-20 02:46 UTC, iborymagic approved these changes
안녕하세요 마루! 1단계 미션 마무리하시느라 고생 많았습니다.
제가 리뷰드린 것보다 더 많이 적극적으로 수정해주셔서 아주 재미있게 코드를 잘 읽었습니다. 배포해주신 사이트는 수정해주신 후에 갑자기 에러가 발생해서 접속이 안되는데, 나중에 여유가 되신다면 한 번 고쳐주시면 직접 들어가서 수정사항들을 확인해보도록 하겠습니다.
질문 주신 내용은 별도의 코멘트도 달아놨으니 확인해주세요.
고생 많으셨고, 다음 미션도 화이팅하세요!

2024-05-20 02:46 UTC, merged

2024-05-24 02:32 UTC, lurgi reviewed
마루 테스트코드 너무 잘짜십니다 👍  깔끔하게 짜셔서 배울점이 많았어요!!

2024-05-24 02:32 UTC, lurgi commented on src/pages/cartItem.test.tsx
> +}));
모듈 모킹 한 수 배웁니다 👍

2024-05-24 02:32 UTC, lurgi commented on src/pages/cartItem.test.tsx
> +    // 모킹된 데이터 반환값 설정
주석이 너무 좋아요~

2024-05-24 02:32 UTC, lurgi commented on src/pages/cartItem.test.tsx
> +    await waitFor(() => expect(screen.getAllByRole('button', { name: /삭제/i }).length).toBe(1));
제품이 사라지는 것을 확인하는 코드인 것 같은데, 그 기준이 삭제버튼인 이유가 궁금하네요! 아이템이 사라지는 것을 확인하려면 명시적으로 아이템을 기준으로 테스트를 짜야된다고 생각이 들었어요!

2024-05-24 02:32 UTC, lurgi commented on src/recoil/cartItems/selectors.test.ts
> +      ${TOTAL_PRICE_OVER_100000_DATA}  | ${10}
이렇게 작성할 수 있군요!!

2024-05-24 02:32 UTC, lurgi commented on src/recoil/cartItems/selectors.test.ts
> +    `('구매한 상품의 총 금액($TOTAL_PRICE)을 계산한다.', ({ data, TOTAL_PRICE }) => {
10만원이 넘을경우 배송비가 없고, 넘지 않을 경우 배송비를 포함하는 경우를 테스트하는 경우 맞을까요? 명세만 보고는 잘 모르겠어요!