[1단계 - 장바구니 미션] 시모(심호림) 미션 제출합니다.
woowacourse/react-shopping-cart pull request #278
Opened 2024-05-16 08:55 UTC by simorimi

안녕하세요 케빈! 만나서 반갑습니다. 저는 시모라고합니다!

이번 미션을 진행하면서 느낀 점은 시간이 많이 촉박했네요. 석가탄신일이라고 달리 놀고 한 것 없이 평소처럼 시간을 쓰고하였지만, 미션이 이번 레벨 들어서는 가장 시간이 오래 걸렸고 어려웠던 것 같습니다! 그러다 보니 완성도 면에서 많이 부족하다고 스스로도 많이 느껴지네요. 부족한 점들에 대해 서술해보자면,

- 테스트

: RTL 테스트를 진행하지 못하였습니다. 파일을 만들고 진행하려고 하였으나, 

```tsx
src/api/index.ts:1:25 - error TS1343: The 'import.meta' meta-property is only allowed when the '--module' option is 'es2020', 'es2022', 'esnext', 'system', 'node16', or 'nodenext'.

    1 export const BASE_URL = import.meta.env.VITE_API_URL;
```

와 같은 오류가 계속 발생하였고 해당 오류를 해결해보기위하여 stackOverFlow나 gpt 또 이러한 문제를 해결한 크루들의 의견들을 하나씩 반영해보았으나 결국에는 해결하지 못하였습니다. 촉박했던 시간에 이러한 오류까지 겹쳐 결국 테스트 코드를 작성하지 못하였습니다..

- 상수화

: 한글이나 숫자들에 대한 상수화를 하지 못했습니다. 나중에 리팩토링하자는 마음으로 일단 남겨두고 나머지 기능 구현에 힘을 쏟았지만, 기능 구현은 성공하였으나 테스트 구현 과정에서 오류가 발생하여 해당 부분을 수정하지 못하였네요. 추후 최우선적으로 수정하겠습니다.

- recoil

: 평소 useState를 이용하는 것과 달리 이번에는 recoil을 이용하여 전역 상태의 개념을 배워볼 수 있었습니다. Atom이나 Selector 개념에 대해서 준이 제공한 학습 자료를 익히며 이번 미션에서 적용해보던 중 api 호출에 대해서 selector를 이용하는 부분에서 어려움을 겪었습니다. 특히 delete나 adjust의 경우 cardId를 동적으로 받아서 해결해야하다보니 selector를 이용하기가 더욱 어렵더라고요. 또한 selector를 이용하다보니 atom과는 달리 렌더링 과정에서도 차이를 보였습니다. 

```tsx
export const CartItemsSelector = selector({
  key: 'cartItemStateSelector',
  get: async ({ get }) => {
    get(CartItemsState);
    const cartItems = await fetchCartItems();
    return cartItems;
  },
});

export const CartItemsState = atom<CartItem[]>({
  key: 'cartItemsState',
  default: [],
});

// 본 코드
const updateCartItem = useSetRecoilState(CartItemsState);
  const cartItems = useRecoilValue(CartItemsSelector);
  
  const handleDeleteCartItem = async (cartItemId: number) => {
    try {
      await removeCartItem(cartItemId);
      updateCartItem([]);
    } catch (error) {
      console.error('Failed to remove cart item:', error);
    }
  };
```

그러다보니 삭제 이후 반영이 되지 않는 문제로 해당 코드처럼 updateCartItem를 이용하여 해당 부분을 호출함을 통해 해당 코드와 연결되어있는 CartItemsSelector

2024-05-17 08:28 UTC, JeongBin0227 commented
> PR 질문사항

recoil 로 동적인 부분을 다루는것을 atom과 selector를 어떻게 사용하는지가 중요하다고 생각합니다.
비동기 API 호출을 처리하는 selector를 정의하고, 이를 통해 데이터를 가져오고, 데이터 변경(예: 삭제, 수정 등)을 처리하는 부분은 atom과 함께 관리하는 것이 적합해요. 

시모의 코드를 예로 들자면

```
xport const cartItemsState = atom({
  key: 'cartItemsState',
  default: selector({
    key: 'cartItemsState/default',
    get: async () => {
      const cartItems = await fetchCartItems();
      return cartItems;
    },
  }),
});
```
Atom 및 Selector 정의하고

```
export const fetchCartItemsSelector = selector({
  key: 'fetchCartItemsSelector',
  get: async ({ get }) => {
    const cartItems = await fetchCartItems();
    return cartItems;
  },
});
```
API 호출을 위한 Selector 를 두어 사용하는것이 좋습니다.

혹시 이해가 안된다면 다시 질문해주세요~

2024-05-17 08:35 UTC, JeongBin0227 requested changes
안녕하세요 시모~

시모가 완성도가 떨어진다고 하셨지만, 개인적으로 전체적인 코드가 깔끔했다고 생각합니다. 다만 반복되는 코드가 많았는데 이부분만 고치면 될거 같아요. 시모가 고민인 부분을 코멘트로 남겨놨으니 한번 읽어보시고 이해가 안되는게 있으면 다시 말해주세요!

미션하느라 고생하셨습니다 💯

2024-05-17 08:35 UTC, JeongBin0227 commented on src/components/ItemList/Item.tsx
> +                alt="-"
alt 도 동일하게 
```
alt={cartItem.quantity === 1 ? '삭제' : '-'
```
이런식으로 해주면 어떨까요

2024-05-17 08:35 UTC, JeongBin0227 commented on src/api/shoppingCart.ts
> +};
코드가 반복되는데
```
const getAuthHeaders = () => {
  const token = generateBasicToken(USER_ID, USER_PASSWORD);
  return {
    Authorization: token,
    'Content-Type': 'application/json',
  };
};
```
이렇게 만들어서 같이 활용하면 어떨까요

2024-05-17 08:35 UTC, JeongBin0227 commented on src/recoil/selectedCardItems.ts
> +});
중복된 코드가 많아보여서 이런식의 공통 함수를 뽑아내면 앞으로 잘 활용될수 있을거 같아요

```
const calculateTotal = (selectedCartItems: CartItem[]) => {
  const totalCartItemQuantity = selectedCartItems.reduce(
    (total, cartItem) => total + cartItem.quantity,
    0,
  );

  const totalOrderAmount = selectedCartItems.reduce(
    (total, cartItem) => total + cartItem.product.price * cartItem.quantity,
    0,
  );

  const shippingFee = totalOrderAmount >= 100000 || totalOrderAmount === 0 ? 0 : 3000;
  const totalPaymentAmount = totalOrderAmount + shippingFee;

  return { totalCartItemQuantity, totalOrderAmount, shippingFee, totalPaymentAmount };
};
```

2024-05-18 14:53 UTC, simorimi commented on src/components/ItemList/Item.tsx
> +                alt="-"
그렇네요! 심지어 다른 곳에는 해당 부분이 적용되어있으나 이 부분만 빠진 것으로 보아 통일성에서도 아쉽네요. 꼼꼼한 피드백 감사합니다!

2024-05-20 05:44 UTC, simorimi commented on src/components/OrderButton/OrderButton.tsx
> +      {label}
기존에 저의 기준은 react node의 경우 너무 받을 수 있는 타입 범위가 넓어지다보니 좀 지양했었습니다. 그런데 orderButton이나 header의 경우 텍스트를 받을 수도 있지만, 실제 이미지가 들어갈 수도 있을 것이라는 생각에 좀 더 유연하게 하는 것이 확장성에 훨씬 도움이 되겠다는 생각이 드네요. 지금까지 reactNode를 전혀 사용하지 않으려고 하였으나 이번 피드백 덕분에 어느정도의 범위까지 해야겠다는 기준이 듭니다 좋은 피드백 감사합니다!:)

2024-05-20 15:02 UTC, simorimi commented
기존의 로직이 삭제나 수량 변경 버튼 클릭시 새로고침이 되는 로직이였습니다. 이 부분이 우리가 흔히 생각하는 어플의 움직임과는 많이 다르다는 생각이 들더라고요. 그래서 어떻게 할까 고민하던중 케빈이 알려준 방향성으로 피드백 반영해보았습니다. fetch를 진행하지만, 보여주는 화면에 대해서는 atom으로 관리하는 것이 set을 호출할때 관련된 부분에 대해서만 렌더링을 재진행하여 원하는 그림을 부드럽게 보여줄 수 있겠다는 생각이 들었습니다. 그래서 원하는 방향으로 잘 수정할 수 있었습니다! 좋은 피드백 감사합니다!

2024-05-20 16:15 UTC, simorimi commented on src/recoil/selectedCardItems.ts
> +});
해당 selectedCartItems를 selector로 관리해주어 반복되는 로직을 뽑아냈습니다! 추가로 calculator가 너무 많은 일을 한다는 생각에 각 상태들을 분리하였습니다! 코드를 짤 당시 마감시간에 쫓기다보니 아무래도 이렇게 반복되는 로직 및 많은 일을 하는 로직들이 포함되어있었던 것 같습니다! 좋은 피드백 감사합니다!:)

2024-05-20 16:20 UTC, simorimi commented on src/recoil/selectedCardItems.ts
> +});
recoilPersist의 경우 Atom의 상태를 영속적으로 저장하는 역할을 합니다! 특히 여기에서의 경우 localStorage에 atom을 저장하는 것을 의미합니다. 영속적으로 저장을 원하는 곳에 `effects_UNSTABLE: [persistAtom]` 해당 property를 추가하면 됩니다!

2024-05-21 06:09 UTC, simorimi commented on src/test/CartItemsCaculatorSelector.test.ts
> +// });
아닙니다 두 파일 모두 같은 이유로 실패한 테스트입니다! 해당 파일에서 api요청을 하지 않는데도 불구하고 api요청에 관련한 문제가 뜨더라고요. 지금 예상으로는 애초에 기존의 데이터 자체가 api 업데이트한 데이터를 계속 들고와서 그런 것이 아닌가라는 의문을 가지고 있습니다. 현재 수정한 로직에 대해서는 atom으로 따로 관리하기에 테스트가 가능하지 않을까라는 생각이 듭니다.

2024-05-21 06:22 UTC, simorimi commented on src/components/Header/Header.tsx
> +    </Styled.Header>
props가 줄어드니 훨씬 깔끔한 느낌이 듭니다. 심지어 step2에서 확장성을 고려했을 때 useLocation의 pathname의 값이 바뀔 때 switch 문을 이용한다면 훨씬 수정하기에도 간편할 것 같다는 생각 또한 드네요! 좋은 피드백 감사합니다 :)

2024-05-21 08:22 UTC, simorimi commented on src/components/OrderButton/OrderButton.tsx
> +      {label}
추가로 해당 부분 또한 label을 받기보다 apptitle과 동일하게 path에 따라 설정하면 훨씬 깔끔한 코드가 될 것 같아 수정해보았습니다! 갈수록 제가 봐도 가독성이 좋아지고 있어서 기분이 좋네요 좋은 피드백 감사합니다!:)

2024-05-21 08:33 UTC, simorimi commented on src/App.tsx
> +    </ErrorBoundary>
전체가 loading이 뜨기보다는 해당하는 부분에 뜨는 것이 UI 적으로도 훨씬 이쁘다는 생각이 듭니다. Header의 경우는 비동기 처리와 무관하기에 Header를 제외한 나머지 즉 content와 orderButton를 suspense로 감싸는 방향으로 수정하였습니다. 그리고 이렇게 감싼 다음 이전에는 ShoppingCart와 OrderConfirmation 에서 상태를 관리하던 것에서 suspense안에서의 비동기 호출을 위하여 content와 orderButton 각각에 필요한 것들을 옮기도록 수정하였습니다. 이렇게 옮긴 것이 역할의 분리 측면에서도 좋다는 생각이 드네요! 좋은 피드백 감사합니다 :)

2024-05-21 13:08 UTC, simorimi commented on src/api/shoppingCart.ts
> +};
여기에서 더 나아가 response에 대한 로직도 반복됨을 느꼈습니다. 이 부분을 어떻게 줄이면 좋을지 고민하다가 제가 생각해낸 해답은 payload 유무에 따라 fetch하는 함수를 구현해주면 로직의 반복없이 쉽게 사용할 수 있을 것이라는 생각이 들었습니다. 현재는 delete, get, patch만 있지만 추후 put이나 post가 추가된다면 해당 로직을 반복하여 사용하기 쉬울 것이라 생각하여 다음과 같은 방법으로 구현해보았습니다! 좋은 피드백 감사합니다! :)

2024-05-21 13:10 UTC, simorimi commented on src/test/CartItemsCaculatorSelector.test.ts
> +// });
열심히 수정해보았는데 일단 우선에 테스트를 제외하고 수정한 부분 먼저 보내드리겠습니다! 테스트의 경우 step2의 메인이 되는 부분이기에 step1 메인 코드들에 대해 먼저 보내드리고 step2 구현과 더불어 테스트 코드에 대한 작업을 하고있겠습니다! 피드백 반영이 늦어져서 죄송합니다 케빈!

2024-05-22 09:23 UTC, simorimi commented on src/test/CartItemsCaculatorSelector.test.ts
> +// });
테스트 코드 또한 마무리 다 했습니다! 참고해보시면 될 것 같습니다!!

2024-05-22 12:50 UTC, JeongBin0227 approved these changes
안녕하세요 시모!

수정해주신 부분 모두 확인했습니다 👍 피드백이 좀더 있었는데 시간이 너무 늦어져서 이 부분은 2단계에서 달겠습니다!

미션하느라 고생많으셨어요~ 2단계에서 만나요!!

2024-05-22 12:50 UTC, merged

2024-05-24 02:37 UTC, anttiey reviewed
안녕하세요, 시모! 파슬리입니다 🌱

Recoil 상태를 정말 잘 다루시네요. 저희는 `atomFamily` 사용하다가 스트레스만 얻고 포기했는데 이런 방식으로 관리할 수 있는지 몰랐습니다. 코드 보면서 많은 인사이트 얻어 갑니다 👍👍👍

2024-05-24 02:37 UTC, anttiey commented on src/recoil/selectors.ts
> +    return get(cartItemsState).length;
> 단순 궁금증 💭

배열의 요소 개수와 같은 간단한 계산도 셀렉터로 관리해 준 이유가 있으신가요? 저의 경우 간단한 계산은 사용처에서 직접 해도 충분하다고 생각해서 전역 상태로 두지 않았는데요. 시모의 `셀렉터로 관리하는 값` 을 정하는 기준이 궁금합니다.

2024-05-24 02:37 UTC, anttiey commented on src/components/OrderButton/OrderButton.tsx
> +  const isOrderable = hasSomeCartItem && isSomeCartItemSelected;
해당 상태도 selectedCartItems 여부를 확인하는 용도라면 selectedCartItemsCountSelector 개수로도 판단할 수 있지 않나요? `isSomeCartItemSelected` 상태를 추가로 생성한 이유가 있나요?

2024-05-24 02:37 UTC, anttiey commented on src/components/CartItems/CartItems.tsx
> +    isAllCartItemSelectedSelectorFamily(cartItemIds),
해당 상태는 cartItemsCountSelector 값과 selectedCartItemsCountSelector 값을 비교하여 판단할 수 있을 것 같은데 `isAllCartItemSelectedSelectorFamily` 상태를 추가로 생성한 이유가 있나요? `selectorFamily` 로 관리하는 게 오히려 복잡한 로직처럼 보여서요.

2024-05-24 02:37 UTC, anttiey commented on src/components/CartItems/CartItems.tsx
> +    isAllCartItemSelectedSelectorFamily(cartItemIds),
위와 같이 관리하면 굳이 `handleSelectedAll` 로 상태를 직접 바꿔 줄 필요도 없을 것 같아요.

2024-05-24 02:37 UTC, anttiey commented on src/components/CartItems/CartItem.tsx
> +  const adjustCartItemQuantity = (adjustedQuantity: number) => {
`cartItems` 를 관리하는 로직을 커스텀 훅으로 분리해서 도메인 로직과 UI 로직을 분리할 수 있을 것 같아요 🧐

2024-05-24 02:57 UTC, ImxYJL reviewed
간단하게 코멘트 남겼습니다~!

2024-05-24 02:57 UTC, ImxYJL commented on src/recoil/atoms.ts
> +export const isCartItemSelectedState = atomFamily<boolean, number>({
저와 달리 atomFamily를 사용하셨는데, 단일 atom을 객체 혹은 배열 형태로 사용하는 것과 비교했을 때 확실한 이점이 있어 사용하신 것인지 아니면 데이터 의미상 단일 atom보다는 atomFamily를 사용하는 게 더 낫다고 생각하신 건지 궁금합니다.

2024-05-24 02:57 UTC, ImxYJL commented on src/recoil/selectors.ts
> +    return get(cartItemsState).length;
전역으로 사용하는 상태에서 파생된 값은 전부 셀렉터로 관리하시는 건가요?