[1단계 - 장바구니 미션] 수야(최영수) 미션 제출합니다.
woowacourse/react-shopping-cart pull request #281
Opened 2024-05-16 08:56 UTC by cys4585

안녕하세요 피터! 만나서 반갑습니다. 수야입니다 :)

## 앱 실행 방법

```bash
npm install
npm run dev
```

---

## 장바구니 미션

이번 미션은 API를 호출하여 장바구니 상품 데이터를 불러오고,
이 데이터를 기반으로 Recoil을 사용해서 클라이언트 상태를 관리하는 미션이었어요!
API로 처리할 수 없는 데이터(상품 선택 여부 데이터 저장)의 경우에는 Session Storage를 통해 관리했습니다! 

---

## 집중한 부분

무엇보다도, Recoil을 통해 상태를 관리하는 데 집중했어요. 처음 사용해보는 도구이고, 상태 관리에 대한 지식이 부족해 우여곡절이 있었지만, 최종적으로 페어와 함께 스스로는 만족할만한 상태 관리 구조를 만들었다고 생각해요. atom을 기반 상태로 두고, 여기서 파생되는 상태를 selector로 정의해 관리하고 있어요. 상태와 파생 상태의 자세한 구조는 아래와 같아요.

### 상태
1. API를 통해 장바구니 상품 데이터를 불러오고, 이를 atom으로 보관해요. (`cartItemsSelector` → `rawCartItemsState`)
2. 세션 스토리지를 통해 선택된 장바구니 상품 데이터를 불러오고, 이를 atom으로 보관해요. (`selectedCartItemIdsSelector` → `selectedCartItemIdsState`)

### 파생 상태 (depth 1)
1. 장바구니 상품 데이터를 Component에서 편하게 사용하기 위해 `rawCartItemsState`, `selectedCartItemIdsState`을 취합하는 상태(`cartItemsState`)를 만들어요.
2. `rawCartItemsState`를 기반으로, 장바구니의 담긴 상품의 종류 수를 계산하는 상태(`uniqueCartItemsCountState`)를 만들어요.
3. `selectedCartItemIdsState`를 기반으로, 선택된 상품의 종류 수를 계산하는 상태(`selectedUniqueCartItemsCountState`)를 만들어요.

### 파생 상태 (depth 2)
1. 장바구니 상품 데이터(`cartItemsState`)를 기반으로, 선택된 장바구니 상품들의 총 개수를 계산하는 상태(`selectedCartItemsCountState`)를 만들어요.
2. 장바구니 상품 데이터(`cartItemsState`)를 기반으로, 주문 금액을 계산하는 상태(`orderAmountState`)를 만들어요.

### 파생 상태 (depth 3)
1. 주문 금액(`orderAmountState`)을 기반으로, 배송비를 계산하는 상태(`deliveryCostState`)를 만들어요.

### 파생 상태 (depth 4)
1. 주문 금액(`orderAmountState`), 배송비(`deliveryCostState`)를 기반으로, 총 결제 금액을 계산하는 상태(`totalOrderAmountState`)를 만들어요.

---

## 어려움을 느낀 부분

### recoil
UI를 작성하기 전에 미션 요구 사항과 Figma 디자인 시안을 보면서 상태 구조를 먼저 작성해보고 시작을 했어요. 여기서 많은 어려움이 있었는데요.
1. atom과 selector 중 언제 어떤 녀석을 써야 할 지에 대한 판단 기준이 없어서 많이 헤맸어요. 
2. 비동기 데이터를 atom으로 어떻게 관리할 수 있을지 고민을 많이 했어요.
3. 요구 사항 분석을 완벽하게 하지 못해, 다시 설계해야 했습니다. (장바구니에 담긴 상품 종류 수, 장바구니에 담긴 상품 중 선택된 상품 종류 수를 별도로 계산해야 함을 놓쳤어요.)
4. 미리 설계한 상태들의 이름이 길고, 관심사에 따라 분리하지 않고 atom.ts/selector.ts로 관리하여 기능 개발 단계에서 계속 언제 어떤 상태를 써야 할 지를 되돌아보느라고 애를 먹었어요. (관심사에 따라 분리하고, 최대한 이름을 짧게 하기 위해 노력했습니다.)

### test (recoil, api, session storage)

---

## 질문

1. 페어와 함께 이번 미션을 진행하면서 체감한 selector의 역할에 대해서 정의해 봤습니다(atom/selector의 파생 상태(의존), 비동기 데이터 패칭). 잘 사용하고 체감한 것일지, 또 다른 사용처가 있을지 
2. atomFamily을 어떻게 사용해야 할지 아직 와 닿지 않아요. 지금 요구 사항에서 어떤 데이터를 atomFamily로 사용해보는 것을 고려해볼 수 있을까요?
3. "장바구니에 담긴 상품"을 의미하는 데이터 타입과, 장바구니에 담긴 상품 UI를 표현하는 컴포넌트의 이름이 모두 `CartItem`인 문제를 마주했었어요. 컴포넌트 네임에 `-View`를 붙여서 회피했었는데, 각각 어떻게 정의하면 좋았을지 피터의 조언을 요청 드립니다!
5. Recoil 상태 변경, 외부 시스템 처리(api, storage)를 `useCartItemControl` 훅이 담당하고 있어요. 요구 사항을 잘 만족하고 있고, UI로부터 관심사를 잘 분리했다고 생각을 합니다. 이 부분에 대해서 질문이나 지적, 조언이 많으면 좋겠어요! 제대로 처리하는 다른 방법이 있을지 궁금해요!

2024-05-18 01:56 UTC, iborymagic commented
1. 적절하게 역할을 정의하셔서 잘 사용해주신 것 같아요. 근데 한 가지, selector로 fetch를 한 후에 한 번 더 atom에 넣어주는 이유가 궁금하네요! (코멘트에도 달아놨습니다)

2. atomFamily는 제가 알기로는 비슷한 유형의 데이터를 관리하되, 서로의 리렌더링에 영향을 주고싶지 않을 때 사용하는 것으로 알고 있어요. 예를 들면, 지금 배열로 관리하고 있는 장바구니의 각 품목을 atomFamily로 관리할 수 있을 것 같아요.

3. 요런건 그냥 본인만의, 혹은 팀의 컨벤션을 만들어놓고 거기에 따라 관리하면 될 것 같아요! 저는 아마 데이터에 `CartItemData` 같은 이름을 붙여주지 않았을까 싶네요.

4. 흠, 글쎄요. storage 관련된 로직도 effect로 잘 처리해주고 계시고, 이 정도면 충분히 잘 활용하고 계신 것 같아요. recoil에 대해서 깊이 파고들어가기보다는 어떤 걸 전역 상태로 관리할지와 같은 부분에 대해 고민해보면 좋을 것 같네요! 
(recoil 자체가 어느정도 Meta에서 방치하고 있는 라이브러리이기도 하고..)
그리고 요 부분은 궁금하면 직접 공식문서를 찾아보는 연습을 하는게 수야에게 더 도움이 되지 않을까 싶습니다.

2024-05-18 02:00 UTC, iborymagic requested changes
안녕하세요 수야! 장바구니 미션 진행하시느라 고생 많았습니다.
PR에 내용들을 이미지와 함께 깔끔하게 잘 정리해주셔서 내용을 파악하기가 편했어요.
또, recoil 상태에 대해 도식화를 진행한 것, 컨벤션을 별도의 파일로 정리해둔 것 등 인상깊은 부분들이 많았던 것 같습니다.
함께 이야기 나눠보면 좋을 것 같은 부분들에 대해 코멘트 달아놓았으니, 확인 완료되면 다시 리뷰 요청 보내주세요~

2024-05-18 02:00 UTC, iborymagic commented on docs/RULE.md
> +   2. 비동기 데이터 패칭
컨벤션을 정해놓고 작업하는거 좋네요! 👍 (selector의 용도가 두 가지인 것 같아요 ㅎㅎ)

2024-05-18 02:00 UTC, iborymagic commented on src/api/cartItems.ts
> +}
에러 처리도 꼼꼼하네요 👍

2024-05-18 02:00 UTC, iborymagic commented on src/api/cartItems.ts
> +  });
요 fetch 로직에 반복되는 부분이 많아보여요. 요런건 별도의 builder 함수로 빼낼 수도 있겠네요!

2024-05-18 02:00 UTC, iborymagic commented on src/components/CartAmount.tsx
> +          총 주문 금액이 100,000원 이상일 경우 무료 배송됩니다.
요런 금액은 정책에 따라 달라질 수 있기도 하고, 여러 곳에서 안내문구로 사용될 여지가 있어보여요! 상수화해두면 관리하기가 편하겠네요.

2024-05-18 02:00 UTC, iborymagic commented on src/components/CartItemView.tsx
> +            <S.CountButton onClick={handleIncreaseButtonClick}>+</S.CountButton>
useCartItemControl에 방어 로직이 있긴 하지만, quantity가 1일 때는 - 버튼을 더 못누르도록 disabled를 시켜주는 것도 UX를 개선시키는 방법 중 하나일 것 같아요.

2024-05-18 02:00 UTC, iborymagic commented on src/pages/CartPage.tsx
> +      <Suspense fallback={<div>Loading...</div>}>
Suspense까지 사용해주셨네요! 이왕 사용하는 김에, `Loading...`만 뜨더라도 전체 레이아웃은 유지되도록 스타일링을 해주면 CLS(Cumulative Layout Shift)를 방지할 수 있을 것 같아요.

2024-05-18 02:00 UTC, iborymagic commented on src/recoil/uniqueCartItemsCount.ts
> +});
사실, 개인적으로는 이런 지나치게 간단한 값까지 전역상태로 관리해야하나 싶은 생각은 있습니다. 나중에 앱이 커지면 언제 어디서 어떤 상태가 사용돼야하는지 찾기도 힘들어지고, 기존에 선언돼있던 상태를 못찾고 비슷한 상태를 또 만들기도 하고.. 그런 상황이 있을 수 있어서 전역 상태는 최대한 간결하게 유지하는게 좋다고 생각해요.

2024-05-18 02:00 UTC, iborymagic commented on src/hooks/useCartItemControl.test.ts
> +    it("1. patch api 요청 2. 상태 변경", async () => {
명세를 좀 더 자세하게 적어주면 테스트를 파악하기가 더 편할 것 같아요.

2024-05-18 11:41 UTC, cys4585 commented on src/recoil/rawCartItems.ts
> +});
서버에서 받아온 데이터를 클라이언트 상태로 바꿔서 관리하고자 했어요! 사용자와의 상호작용에 의해 **상태를 클라이언트 단에서 변경**할 수 있도록 atom으로 관리했습니다!

지금 앱에 보이는 데이터는, 최초 접속 시에만 서버로부터 데이터를 fetching해오고, 이후에 데이터 변형은 모두 클라이언트 단에서 실행됩니다. 물론 서버에 제거, 수량 변경 API 요청을 보내고 **정상 응답이 와야 클라이언트 단에서 상태를 바꾸긴** 하지만, **실제 데이터가 아니기**에 이게 문제로 인식이 되네요…

2024-05-18 11:54 UTC, cys4585 commented on src/utils/sessionStorage.ts
> +};
브라우저가 닫히면 장바구니의 **선택 값들이 초기화**돼야 한다고 판단했습니다! 판단 이유는 아래와 같아요.
  1. **꼭 기억**해야 하는 데이터였다면 **서버에서 관리**를 했을 것이다.
  2. **UX 관점**: 서비스 이용 시나리오 상상
      - 장바구니 페이지에서 사용자가 몇몇 상품들은 선택하고, 다른 어떤 상품들은 선택하지 않는다. → 브라우저를 닫는다. → 한참 뒤에 장바구니 페이지에 다시 왔을 때, 옛날에 결제를 하기 위해 선택했던 그 **흔적이 남아있지 않는 것**이 자연스럽다. 사용자 입장에서 **결제를 위한 생각과 행동의 맥락이 끊겨**있을 것이다.
  3. 요구 사항 기준으로, **새로 고침을 했을 때** 선택한 상품 상태가 **유지**되는 것이 중요했다. 브라우저를 닫았을 때도 상태가 유지돼야 한다는 요구 사항은 없다.

2024-05-18 12:08 UTC, cys4585 commented on src/api/cartItems.ts
> +}
아핫... 고백하자면 사실 페어의 코파일럿 기능을 적극적으로 활용했어요. 코드 작성을 할 때부터 '에러 처리 꼼꼼하게 해야지'하고 의식하고 작성됐다기 보단, 코파일럿이 이렇게 제안해줬을 때 '오 맞네!'하고 반영했습니다.

굳이 이 말씀을 드린 이유는 AI 기술의 발전 속도가 정말 급진적이라고 느껴지는 요즘, 개발자로서 또는 20~30대 직장인으로서 AI를 어떻게 받아들이고 사용해야 할 지에 대한 피터의 의견을 여쭐 수 있는 기회라 생각했습니다!

우선 저는 이 AI를 받아들이지 않고 배척하면 도태될 것이라 생각해요. PC가 보급된 후 excel과 같은 office용 툴들이 등장했을 때도 그 활용 여부에 따라 기회를 얻기도, 실직을 하기도 했을 거라 생각합니다. 같은 논리로 근미래에는 AI를 능숙하게 다룰 줄 아는 사람일수록 퍼포먼스가 뛰어날 거라 생각해요. 
하나 불안한 점은 이미 디테일을 아는 사람, 경험해본 사람(ex: n년차 개발자)들에게는 도움이 될 것이라 확신하는데, 디테일을 배우고 있는 단계에 있는 사람들은 어떤 태도를 취해야 할 지 잘 모르겠다는 것입니다. 

이와 관련된 피터의 생각, 또는 현업 개발자 시장에서 어떤 분위기인지 궁금해요!

2024-05-18 16:10 UTC, cys4585 commented on src/pages/CartPage.tsx
> +      <Suspense fallback={<div>Loading...</div>}>
데이터 로딩 시 레이아웃 유지되도록 Skeleton을 구현해봤습니다! 각 컴포넌트의 합성 컴포넌트로 `-.Skeleton`을 주입해줬어요!!

2024-05-18 16:19 UTC, cys4585 commented on src/api/cartItems.ts
> +  });
피터의 조언에 따라 fetch 요청을 처리하고 에러 시 핸들링 해주는 함수를 별도로 분리해봤습니다!! 이런 방향을 의도하신 게 맞으신지, 여기서 어떻게 더 개선해보면 좋을지 궁금해요!

2024-05-18 16:21 UTC, cys4585 commented on src/recoil/uniqueCartItemsCount.ts
> +});
앗 그렇네요!!! 그저 배열의 길이만 계산하면 되는데 굳이 파생 상태로 뒀었네요! ㅎㅎㅎ 파일 자체를 삭제해버리고 사용처에서 `length`를 계산해서 사용하도록 수정하니, 파일이 줄어서 확실히 파악이 잘 되는 것 같아요.

2024-05-20 13:17 UTC, iborymagic commented on src/api/cartItems.ts
> +  });
충분히 잘 분리해주신 것 같아요!

2024-05-20 13:26 UTC, iborymagic commented on src/api/cartItems.ts
> +}
허허.. 개인적으로는 너무 섣부르게 걱정할 필요가 있을까 싶네요~ 사실 프로덕트라는게 코드로만 이루어진 게 아니다보니, AI가 계속 발전하더라도 개발자들의 영역은 분명히 존재할거라고 생각합니다. 발전이 워낙 빠르다보니 AI가 언제 어느정도까지 커버할 수 있을지 알 수는 없지만, 지금 시점에서는 너무 걱정할 필요는 없다고 생각하는 편입니다~

2024-05-20 13:33 UTC, iborymagic approved these changes
안녕하세요 수야! 장바구니 미션 1단계 마무리하시느라 고생 많았습니다.
제가 말씀드린 것보다 몇 단계 더 나아가서 반영해주신 부분도 있고, 
그렇지 않더라도 의도대로 리뷰를 잘 반영해주신 것 같아서 미션은 여기에서 머지해도 될 것 같습니다.
질문 주신 부분들에 대해서는 코멘트로 답변 달아놓았어요.
고생 많으셨고, 다음 미션도 화이팅하세요!

2024-05-20 13:33 UTC, merged

2024-05-21 06:45 UTC, cys4585 commented on src/recoil/rawCartItems.ts
> +});
피터! 좋은 말씀 감사합니다!
서버에서 데이터를 받아와서 상태로 관리하고 있긴 하지만, 이번 미션에서는 이 서버 상태 동기화를 잘 처리하는 것 보다는 클라이언트 단의 상태를 기준으로 파생 상태를 잘 관리하는 데 집중해봐야 겠네요!!

2024-05-24 02:36 UTC, llqqssttyy commented on src/recoil/rawCartItems.ts
> +export const rawCartItemsState = atom<RawCartItem[]>({
`rawCartIemsState`라는 이름에서 변경되지 않는, 원본 데이터라는 느낌이 들어요. 그런데 atom은 변경이 가능한 상태고, 해당 값을 atom으로 만든 이유도 변경을 위한 것인 것 같아요! 수야가 raw라는 단어를 붙인 의도를 여쭤봐도 될까요?

2024-05-24 02:47 UTC, llqqssttyy commented on src/recoil/cartAmount.ts
> +export const orderAmountState = selector({
selector 구조가 깔끔하네용👍