[2단계 - 장바구니 미션] 라이언(박한영) 미션 제출합니다
woowacourse/react-shopping-cart pull request #285
Opened 2024-05-23 18:26 UTC by Parkhanyoung

안녕하세요 호프 그동안 잘 지내셨나요? 다시 만나 뵙게 되어 반갑습니다! 🙂
step1 때도 호프 덕분에 많이 배울 수 있었습니다 🙇🏻‍♂️
그럼 이번 리뷰도 잘 부탁드립니다!

-----

## 실행 방법

### 프로덕션
[배포 링크 바로가기](https://parkhanyoung.github.io/react-shopping-cart/dist/)

### 로컬
루트 디렉토리 기준으로 아래의 명령어를 실행해 주세요.

```
npm install
// 로컬 실행
npm run dev
// 테스트 실행
npm run test
```

## 구조
컴포넌트와 커스텀 훅의 개략적인 구조를 표현해봤습니다!
<img width="700" alt="스크린샷 2024-05-24 오전 2 54 06" src="https://github.com/woowacourse/react-shopping-cart/assets/80797824/afe229dd-a8b8-4ce2-b480-cc3bb9b4306b">
<img width="1114" alt="스크린샷 2024-05-24 오전 3 08 48" src="https://github.com/woowacourse/react-shopping-cart/assets/80797824/303a9d43-0d51-4b08-8122-8756c3609c45">

## 질문
**1. 효과적인 디렉토리 구조**
미션의 요구사항이 복잡해지면서 파일들의 위치가 헷갈리는 일이 많아졌습니다. 나름대로 고민하며 응집도가 좋은 형태로 모아두려고 노력했습니다. 그런데 관련 파일들을 한 곳에 모아두려고 하다 보니 디렉토리의 수가 많아지고 depth가 깊어지기도 했습니다. 호프가 보시기에는 디렉토리 구조가 괜찮았는지, 유지보수성을 높이기 위해 현재의 디렉토리 구조를 어떤 식으로 개선해볼 수 있을지 질문 드리고 싶습니다!

**2. 테스트 케이스 보완**
아직까지 어디서부터 어디까지, 그리고 얼마나 디테일하게 테스트해야 효과적일지 감을 잘 못잡고 있는 것 같습니다. 🥲
커스텀 훅에 대한 테스트를 작성하려 했는데 의존성이 많아 대부분의 로직을 모킹해야 했습니다. 그래서 커스텀 훅에 대한 테스트는 작성하지 않고, 중요 비즈니스 로직과 관련된 유틸 함수에 대해서만 테스트 케이스를 작성하게 됐습니다. 그런데 이 정도의 테스트 케이스만으로 다양한 쿠폰 적용 시나리오들을 충분히 커버하지 못했다는 생각이 들기도 했습니다. 하지만 테스트를 추가하고 싶어도 어떤 테스트를 더 작성해야 유의미할지 감이 잡히지 않았습니다. 호프는 어떤 테스트가 추가로 작성될 필요가 있었다고 생각하셨는지 궁금합니다! 그리고 유의미한 테스트 케이스를 작성하기 위한 호프만의 사고 방식이나 노하우를 공유해주신다면 큰 도움이 될 것 같습니다!

리뷰를 위해 긴 코드와 긴 글 읽어주셔서 감사드립니다! 🙇🏻‍♂️

2024-05-23 18:53 UTC, Parkhanyoung commented on src/hooks/useCouponsDiscountCalculator/index.ts
> +    return Math.max(...possibleDiscounts);
[참고] 가장 큰 할인액을 적용해야 하는 요구 조건에 따르기 위해, 가능한 모든 경우의 수에 대해서 계산한 후 그 중 가장 큰 할인액을 반환합니다.

2024-05-23 18:53 UTC, Parkhanyoung commented on src/hooks/useCouponsDiscountCalculator/useCouponDiscountCalculator.ts
> +
**[질문] 위 로직을 else if 대신 더 깔끔하게 처리할 수 있는 방법이 있을까요?**
쿠폰 별 할인액 계산 방법과 계산에 필요한 정보가 각기 달라, else if 문을 이용하여 처리했습니다. 그런데 else if 문이 많으니 가독성이 그리 좋지 않다고 느껴졌습니다. 혹시 호프에게 이 로직의 가독성을 개선하기 위한 아이디어가 있는지 궁금합니다!

2024-05-25 17:15 UTC, moonheekim0118 requested changes
안녕하세요 라이언~ 이번 단계도 고생하셨어요 👏 빠르게 내주셨는데..제가 늦어서 죄송해요 😭 🙏 양해해주셔서 정말 감사합니다 ( _ _ )

> RawCoupon은 전역 상태(Selector)로, 쿠폰 선택 정보는 지역 상태로 처리

전역 상태와 지역상태를 나누는 기준을 명확하게 정립해주셨군요 👏 👏 저도 라이언의 선택에 동의합니다.
다만, 코멘트에도 남겨드렸다싶이 '쿠폰 적용으로 인해 발생한 할인 금액'의 상태는, 다른 주문 데이터와 함께 전역으로 관리되어야하지 않을까~생각했습니다. isRemoteDeliveryArea는 전역상태일 필요가 없을 것 같구요. 🙂 코멘트 참고해주세용 ㅎㅎ

> 1. 커스텀 훅과 전역 상태 사용의 적절성

라이언의 말씀대로, 쿠폰 및 주문이라는 복잡한 요구사항에 대응하기 위해서는 어쩔 수 없이 상태 흐름이 복잡해지기 마련이지요. 하지만 우려해주신 것 과 다르게 제가 라이언의 코드를 읽으면서 많이 복잡하다라고 느끼진 않았습니다. 훅도 역할별로 적절한 단위로 잘 분리해주셨고요, 전역상태 관련해서는 남겨드린 코멘트 외에는 괜찮아보입니다.

유지보수성을 위해서 더 개선할 부분은, 한번 쿠폰이나 금액 관련 요구사항들이 바뀌어도 잘 대응될까?를 상상해봐주시고, 이에 따라 대응될 수 있도록 개선해봐주셔도 좋을 것 같네요ㅎㅎ실제로 업무 하다보면 요구사항이 고도화 되는 경우가 많거든요.

1. 쿠폰의 종류가 추가 된다면
2. 최대 쿠폰 선택가능 개수가 변경된다면
3. 쿠폰 적용 불가능한 상품이 생긴다면
4. 배송비가 각각 부과되는 상품이 생긴다면


>  유지보수하기 용이한 디렉토리 구조

co-location을 선택하셨군요 ㅎㅎ저는 개인적으로 라이언이 해주신 방법을 선호합니다. 말씀해주신대로 응집도가 높아지기도 하고, 코드 파악하기가 더 수월해서요. 해당 목적이라면 depth 가 깊어지는건 크게 문제가 되지 않을 것 같습니다. 
아무래도 코드가 늘어나게 되면 어쩔 수 없이 폴더들도 많아지는건 숙명인 것 같아요.


> 테스트 케이스 보완

라이언이 말씀주신대로, 다른 로직에 의존성이 많은 훅이라면 유틸함수들만 테스트해줘도 좋을 것 같아요. 그게 아닌 경우는 `useToggleList` 라는 훅인데, 요 훅은 훅테스트를 따로 추가해주면 좋을 것 같아요. 다른건 유틸함수 테스트만으로 충분해보입니다.

또한 `훅에 외부 유틸함수 사용밖에 없다` -> 이러면 훅으로 만들 필요가 있나!? 라고 의심해봐주셔도 좋을 것 같아요.

제가 생각하기에 유의미한 테스트 대상은..간단하게 **해당 프로그램의 개발자가 직접 짠 코드**라고 생각합니다. 즉 제가 생각하기에 유의미 하지 않은 테스트는 1. 외부라이브러리 메서드에 대한 테스트랑, 2. 자바스크립트 기본 메서드만 사용하는 함수에 대한 테스트 일 것 같아요.

물론 내가 직접 짠 코드가 대부분인데 외부 의존성도 있다 -> 이러면 모킹을 해야겠지요 ㅎㅎ

---

그럼 고생하셨어요 라이언~ 코멘트 확인하고 다시 요청해주세요 🙂

2024-05-25 17:15 UTC, moonheekim0118 commented on src/components/common/domain/CartAmount.tsx
요 폴더 이름의 domain 의 의미는 뭘까요 ? 혹시 도메인 관련 컴포넌트를 묶어두고 싶으신거라면
해당 도메인명을 폴더 이름에 써주시는 것도 좋을 것 같아요ㅎㅎ

2024-05-26 06:10 UTC, Parkhanyoung commented on package.json
> +    "js-combinatorics": "^2.1.2",
복수의 쿠폰 적용 시 최대 할인액을 적용하기 위해 순열을 이용했습니다!
가능한 쿠폰 적용 시나리오를 순열로 모두 구한 뒤, 그 중 최대값을 이용하는 방식입니다.
이때 순열을 구하는 유틸함수를 직접 만드는 대신 패키지를 이용했습니다.
미션 중에는 계산 로직보다는 비즈니스 로직에 대해 고민하는 데 집중하기 위해서 패키지를 이용하는 게 낫다고 판단했습니다!

2024-05-26 06:31 UTC, Parkhanyoung commented on src/components/CheckoutPage/CheckoutContent.tsx
> +  const location = useLocation() as { state: CheckoutPageState };
제가 미리 설명드렸어야 했던 부분을 빠뜨렸네요 🥲 잘 짚어주셔서 감사합니다, 호프! 🙂

이번 미션의 기획에서는 결제 시 결제 내용 데이터가 데이터베이스에 저장되지 않았습니다. 하지만 실제 운영되는 프로덕트에서는 결제 수행 시 결제 내용 데이터가 데이터베이스에 저장될 것이라 생각했습니다. 그리고 이런 checkout 페이지에서는 그 결제 내용 데이터를 서버로부터 받아와 보여주는 방식이 될 것이라 예상했습니다. 그래서 이번 미션에서는 location.state를 서버 데이터라고 가정하고 처리했습니다.

location.state를 이용하지 않으면, 쿼리 스트링이나 전역 상태를 이용해야 할 것 같은데, 그러한 방식은 실제의 처리와는 거리가 있는 방식이라고 판단하여 이 방식을 최종적으로 택했습니다.

다시 한 번 피드백 주셔서 감사합니다! 혹시 제 답에 대해 다른 의견이 있으시다면 편히 공유해주시면 감사하겠습니다 🫡

2024-05-26 07:24 UTC, Parkhanyoung commented on src/hooks/useCouponsDiscountCalculator/discountCalculators/index.ts
> +};
좋은 지점을 짚어주셔서 감사합니다! 🙂

호프가 짚어주신 대로 함수의 로직만 본다면 해당 함수가 불필요하게 느껴지는 것 같습니다. 이러한 함수 분리가 오버 엔지니어링처럼 보일 수 있지만 유지보수성을 고려할 때 장기적으로는 더 나을 수 있겠다고 판단했습니다. 세부적인 이유는 아래와 같습니다!

1. **가독성을 위해 표현의 일관성을 유지** - freeShipping, fixedDiscount와 같이 간단한 할인 로직을 함수로 분리하지 않았을 때와 함수로 분리했을 때 useCouponDiscountCalculator의 로직은 아래와 같이 표현될 것입니다.
```ts
// 💡 함수로 분리하지 않았을 때
    if (isFixedDiscountCoupon(coupon)) {
      return coupon.discount;
    } else if (isPercentageDiscountCoupon(coupon)) {
      return calculatePercentageDiscountAmount(coupon, currentDiscountedOrderAmount);
    } else if (isBuyXGetYCoupon(coupon)) {
      return calculateBuyXGetYDiscountAmount(coupon, cartItems);
    } else if (isFreeShippingCoupon(coupon)) {
      return shippingCost
    }
```

```ts
// 💡 함수로 분리했을 때
    if (isFixedDiscountCoupon(coupon)) {
      return calculateFixedDiscountAmount(coupon);
    } else if (isPercentageDiscountCoupon(coupon)) {
      return calculatePercentageDiscountAmount(coupon, currentDiscountedOrderAmount);
    } else if (isBuyXGetYCoupon(coupon)) {
      return calculateBuyXGetYDiscountAmount(coupon, cartItems);
    } else if (isFreeShippingCoupon(coupon)) {
      return calculateFreeShippingDiscountAmount(shippingCost);
    }
```
물론 내용 면에서는 차이가 없지만 표현적인 일관성이 저해되어 읽어나가는 데 방해가 될 수 있을 것이라 생각했습니다. 사소한 부분일 수도 있지만, 표현의 일관성을 유지하여 예측 가능한 형태로 만들어 코드를 읽는 사람이 읽을 때의 리듬을 잃지 않도록 하는 게 중요하다고 생각했습니다!

2. **로직의 의미를 명확히 나타내기 위함** - 이 부분 역시 사소한 차이지만, 함수로 분리하는 게 로직의 의미를 조금 더 명확히 나타낸다고 생각했습니다.
```ts
// 💡 함수로 두지 않았을 때
return shippingCost
// ✅ 의미: 배송비를 반환한다.

// 💡 함수로 두었을때
return calculateFreeShippingDiscountAmount(shippingCost)

const calculateFreeShippingDiscountAmount = (shippingCost: number): number => {
  return shippingCost;
};
// ✅ 의미: 무료 배송 할인에 따라 계산한다. 무료 배송 할인의 정책은 배송비를 그대로 반환하는 것이다.
```

3. **이후의 수정에 유연하게 대처하기 위해**: 별도의 함수로 분리해두면 이후의 수정 사항이 발생했을 때 유연하게 대처하기 쉬워질 것이라 생각했습니다. 예를 들면 고정 할인이나 배송비 할에 추가 조건이 생길 경우, 해당 함수에 그 내용을 반영할 수 있습니다.

답변을 작성하다 보니 가볍게 던져주신 질문에 길게 답하게 됐네요 😅 그만큼 저에게도 고민이 됐던 부분이었기 때문인 것 같습니다 😄 혹시 다른 의견이 있으시다면 공유해 주시면 재밌게 이야기해볼 수 있을 것 같습니다!

2024-05-26 08:27 UTC, Parkhanyoung commented on src/components/PaymentPage/CouponModal/CouponList.tsx
> +    coupons.filter(({ isSelected }) => isSelected).length >= MAX_SELECTABLE_COUPON_COUNT;
앗 그렇네요! useCoupons 훅의 책임의 관심사가 맞는 것 같습니다!
수정 완료했습니다! [38d9aba](https://github.com/woowacourse/react-shopping-cart/pull/285/commits/38d9aba4bdbe02401122ede0182ede1411a969c4)

2024-05-26 08:47 UTC, Parkhanyoung commented on src/hooks/useCouponSelectabilityChecker/index.ts
> +  };
호프가 이야기해주신 두 가지 생각에 모두 공감했습니다!
커스텀 훅이 반환하는 함수에 이름을 붙여주고, 반환값이 하나여도 객체 형태로 반환하도록 수정했습니다! [3fb1610](https://github.com/woowacourse/react-shopping-cart/pull/285/commits/3fb1610e54ae80999e02db6add23281ebcae93de)

2024-05-26 08:48 UTC, Parkhanyoung commented on src/hooks/useCoupons/index.ts
다 호프가 좋은 피드백을 많이 남겨주신 덕분입니다 👍🏻

2024-05-26 08:48 UTC, Parkhanyoung commented on src/hooks/useCoupons/index.ts
다 호프가 좋은 조언들을 많이 해주신 덕분입니다 👍🏻

2024-05-26 11:20 UTC, Parkhanyoung commented on src/hooks/useCoupons/index.ts
> +  const totalPayAmount = totalOrderAmount - discountAmount;
고민했던 부분인데 코멘트 남겨주셔서 감사합니다 👍🏻

**discountAmount 및 totalPayAmount를 전역 상태로 만들지 않았던 이유**
앞서 말씀드렸던 바와 같이 전역 상태와 지역 상태를 구분하는 가장 큰 기준점은 '여러 페이지에서 사용되는지' 여부였습니다. 그런데 현재 discountAmount 및 totalPayAmount는 PaymentPage에서만 사용되고 있습니다. 그렇기에 지역 상태로 충분하다고 판단했습니다. 더불어, discountAmount, totalPayAmount는 지역 상태인 쿠폰 선택 정보(selectedCouponIds)에 의존하고 있는데, 이를 전역 상태로 관리할 경우, 쿠폰 선택 정보와 할인 금액 상태 간의 일관성이 깨지는 문제가 발생할 수 있을 것 같습니다. 예를 들면 결제하기 페이지에서 다른 페이지로 전환했을 때 지역 상태인 쿠폰 선택 정보는 초기화되지만, 할인 금액은 유지되는 문제가 발생할 수 있을 것 같습니다. 이렇듯 페이지 전환 시 상태를 초기화해야 한다는 점에서도 전역 상태로 만들지 않는 게 맞다고 판단했습니다.

호프는 이러한 의견에 대해 어떻게 생각하시는지, 혹은 discountAmount나 totalPayAmount가 전역 상태로 관리되어야 하는 이유가 무엇이라고 생각하시는지 여쭙고 싶습니다! 🙂

2024-05-26 11:56 UTC, Parkhanyoung commented on src/hooks/useToggleList.ts
> +type UseToggleListReturn<T> = [Array<T>, ToggleItem<T>];
네 Set 타입을 이용하는 방식으로 수정했습니다! [69fda74](https://github.com/woowacourse/react-shopping-cart/pull/285/commits/69fda74bc0000d407ff2477aa6c333d31c8648b6)

2024-05-26 12:01 UTC, Parkhanyoung commented on src/pages/CheckoutPage.tsx
> +  const onReturnToCartButtonClick = () => navigate(ROUTE_PATH.cart);
on-** 그리고 handle-** 사이에 의미 차이는 없다고 생각합니다. 그래서 둘 중 어떤 것이든 통일해서 사용하기만 한다면 문제가 없을 것 같습니다!
그런데 제 코드를 돌아보니 둘을 혼용하고 있더라구요 😅 그래서 더 간결한 on-** 형태로 수정완료했습니다! [9175f88](https://github.com/woowacourse/react-shopping-cart/pull/285/commits/9175f88ea6966c6939575cf9de285628d62ef9a7)

2024-05-26 12:32 UTC, Parkhanyoung commented on src/types/rawCoupon.ts
> +type TimeString = string;
오 이런 타입도 있었군요! 알려주셔서 감사합니다 🙇🏻‍♂️
DateString, TimeString에 적용해봤는데 처음 사용해본 거라 맞게 적용한지 모르겠네요 😂 [ad06eca](https://github.com/woowacourse/react-shopping-cart/pull/285/commits/ad06eca1293fc4bef3ece3a47983bc642ba6013f)

2024-05-26 12:45 UTC, Parkhanyoung commented on src/constants/couponDiscountType.ts
> +export type FreeShipping = typeof COUPON_DISCOUNT_TYPE.freeShipping;
그렇네요! 타입 선언들은 types에 포함시키는 게 맞는 것 같습니다. 쿠폰 할인 유형 타입들은 types에 별도의 파일로 분리했습니다! [e93ef9a](https://github.com/woowacourse/react-shopping-cart/pull/285/commits/e93ef9a58d1f3c684145843756315af956a92451)

2024-05-26 12:50 UTC, Parkhanyoung commented on src/hooks/useCouponSelectabilityChecker/isCouponSelectable/isCouponSelectable.test.ts
> +  it("모든 조건을 충족했을 때 선택 가능으로 판정한다.", () => {
어떤 조건인지 자세히 적어주었습니다! 👍🏻 [f1bfa7f](https://github.com/woowacourse/react-shopping-cart/pull/285/commits/f1bfa7f6f8445554c817be7c8446f749c1c17384)

2024-05-26 13:03 UTC, Parkhanyoung commented on src/hooks/useCouponsDiscountCalculator/discountCalculators/discountCalculators.test.ts
> +    });
세심하게 짚어주셔서 감사합니다! 🙂

앞서 [calculateFreeShippingDiscountAmount를 함수로 분리했던 이유](https://github.com/woowacourse/react-shopping-cart/pull/285#discussion_r1615075771)와 유사한 이유로 이 테스트 케이스도 존재하고 있습니다.
1. **코드 일관성:** 모든 할인 계산 함수에 대해 테스트를 작성하여 테스트 코드의 일관성을 유지하고자 했습니다.
2. **미래의 변화에 대비:** 배송비 할인 함수 로직이 변경될 때, 테스트를 통해 변경 사항이 올바르게 작동하는지 확인할 수 있을 것 같습니다.
3. **명세의 기능:** 테스트에는 기능의 정상 동작 확인뿐만 아니라 명세의 기능도 있다고 생각합니다. 이 테스트는 함수의 의도와 기대되는 동작을 문서화하여 코드에 대한 명확한 스펙을 제공하는 역할도 하리라 생각합니다.

이러한 이유들로 현재의 테스트가 단순하더라도 유용한 측면이 있다고 생각합니다.

2024-05-26 13:22 UTC, Parkhanyoung commented on src/components/common/domain/CartAmount.tsx
호프 말씀대로 도메인명을 폴더 이름에 써주는 게 더 명확하게 표현되는 것 같습니다!
감사합니다. 수정 완료했습니다! 🙂

2024-05-26 13:52 UTC, Parkhanyoung commented on src/recoil/isRemoteDeliveryArea.ts
> cartAmount 라는 selector에서 배송비 계산 시, 의존해야하는 상태가 있어야해서 추가된걸까요?

네 맞습니다 🥲 selector에서 배송비 계산 시, 산간 지역 여부에 따른 배송비 책정을 하기 위해서 의존해야 하는 상태가 있어야 하기 때문에 추가했습니다.

> 과연 isRemoteDeliverayArea 라는 값이 전역적으로 공유되어야하는 상태일까요~?

호프 말씀대로 전역으로 공유되어야 하는 상태는 아니라고 생각합니다! 산간 지역 여부 설정 및 그에 따른 배송비 변경은 결제 페이지에서만 이루어지기 때문에 꼭 전역적으로 공유되어야 하는 상태는 아니라고 생각합니다. 다만 selector인 CartAmount에서 배송비를 관리하고 있기 때문에 이 selector가 참조하기 위해서는 전역 상태가 되어야 하기 때문에 전역 상태로 두게 되었습니다.

> 아예 selector 에 set 메서드를 사용해보시는건 어떠세용?

아직 감을 못 잡았는데, 혹시 이 방법에 대해서 조금 더 구체적으로 설명해주실 수 있나요~?

2024-05-26 14:29 UTC, Parkhanyoung commented
이번 리뷰에서도 좋은 피드백과 질문들을 던져 주셔서 감사합니다!
호프 덕분에 중요한 지점에 대해서 다시 한 번 고민해 볼 수 있었습니다. 🙂

> useToggleList 라는 훅인데, 요 훅은 훅테스트를 따로 추가해주면 좋을 것 같아요.

useToggleSet(기존의 useToggleList)에 대한 테스트도 추가 완료했습니다! [ae6a2ee](https://github.com/woowacourse/react-shopping-cart/pull/285/commits/ae6a2ee2d3bd6f9c18ab60792bb53d1ad97f0030)

2024-05-27 08:19 UTC, woowapark reviewed
첫 PR이라 구경왔다가 본문에 남겨두신 고민거리들이 눈에 띄어서 몇 가지 코멘트 남겨두고 갑니다 :)     
제 코멘트는 모두 참고만 해주시고 반영은 하지 않으셔도 되고요.       
혹시 궁금하거나 이야기 나누고 싶은 부분이 있으시다면 편하게 알려주세요.     
리뷰 자체는 호프와 소통하시는 것들이 마무리 되는대로 정리해주시면 됩니다! 🙂     
미션 마무리 화이팅~💪💪💪

2024-05-27 08:19 UTC, woowapark commented on src/hooks/useCoupons/index.ts
> +};
요기에서 사용하는 별도의 함수들을 충분히 잘 테스트해주셨는데요 🙂     
그래도 한 단계 더 고민해본다면 실제로 컴포넌트에서 사용되는 것은 그것들을 조합한 이 useCoupons 훅일테니,      
Recoil에 특정 쿠폰들과 장바구니 선택 상품들을 세팅한 상태에서      
-> 특정 쿠폰을 선택하는 액션이 일어났을 때        
-> 의도한 대로 할인값이 잘 계산되어 리턴되는지        
를 검증해두어야 컴포넌트에서는 다른 검증 없이 안전하게 사용할 수 있다고 보장할 수 있을 것 같아요.            
훅에서 해당 유틸 함수들을 사용하지 않는 방식으로 개선한다면 검증된 줄 알았던 로직이 어느새 다시 깨질 수도 있으니까요.

2024-05-27 08:19 UTC, woowapark commented on src/hooks/useCouponsDiscountCalculator/useCouponDiscountCalculator.ts
> +
(맹목적인 패턴 적용이 이제는 안될 거라는 믿음 하에...ㅋㅋㅋㅋㅋ)        
만약 더 복잡해지는 경우(각 쿠폰에 할인 규칙이 추가되거나, 새로운 쿠폰이 다양하게 추가되거나 등등)에 이 훅에서는 '할인 정책을 적용한다'는 책임만 가져가고,     
실제 '할인 정책의 규칙'은 별도로 관리하는 것이 좋겠다 필요성이 생긴다면       
전략 패턴과 같은 방식을 고려해볼 수는 있을 것 같습니다.        
후순위의 학습 키워드로 참고만 해보시라고 남겨두어요 ㅎ-ㅎ

2024-05-27 15:08 UTC, Parkhanyoung commented on src/components/PaymentPage/ShippingDetail.tsx
> +  const { shippingCost } = useRecoilValue(cartAmountState);
좋은 조언 감사드립니다! 🫡 너무 맞는 이야기밖에 없네요! 의존하고 있는 항목들이 꼭 직접적으로 알아야하는 항목인지 점검해보면, 올바른 구조인지를 점검해볼 수 있을 것 같습니다. 여기서는 컴포넌트와 recoil 상태를 매개할 수 있는 레이어로서 커스텀 훅을 두는 게 좋겠네요! 머지된 이후에 꼭 반영해보도록 하겠습니다!

추가로, 한 가지 질문이 있습니다. 공원이 언급해주신 세 가지 항목에 대해 크게 공감을 했는데요. 한편으로, '그렇다면 컴포넌트에서 recoil 상태를 하나라도 이용한다면, 모두 별도의 커스텀 훅으로 래핑해서 사용해야 할까'라는 궁금증이 생겼습니다. 그렇게 되면 커스텀 훅의 종류가 급격히 늘어나 혼동을 유발할 수 있을 것 같아서요! 이런 맥락에서 컴포넌트와 전역 상태 간의 매개를 담당하는 중간 레이어를 두기 위해 커스텀 훅을 만드는 게 유일한 방법일지 궁금합니다.

2024-05-27 15:17 UTC, Parkhanyoung commented on src/hooks/useCouponListDiscountCalculator/discountCalculators/discountCalculators.test.ts
> +    });
테스트에서는 간결함보다 명확한 서술이 더 중요할 수 있겠군요! 앞으로 테스트 코드 짤 때는 조금 장황해지더라도, 명확히 서술하는 데 방점을 두는 게 좋겠네요! 좋은 피드백 감사드립니다!

그런데 혹시 이 테스트 코드에 코멘트를 남겨주신 건, ```TEST_COUPON.buy2Get1```을 사용하고 있기 때문일까요? 이런 부분을 반복적이더라도 매번 명시적으로 적어주는 게 좋다는 의미이실까요? 🤔

2024-05-27 15:22 UTC, Parkhanyoung commented on src/hooks/useCouponSelectabilityChecker/isCouponSelectable/isCouponSelectable.test.ts
> +    };
공원이 적어주신 방식이 훨씬 직관적으로 어떤 부분을 테스트하는지 알아보기 좋네요!

> 혹은 쿠폰 생성을 위한 함수를 만들거나, 쿠폰을 class로 만들어서 활용해볼 수도 있고요.

이렇게 테스트를 위해 별도의 함수나 클래스를 만들어볼 생각은 못했네요! 공원의 코멘트를 보고 테스트 코드도 프로덕션 코드 못지 않게 유지보수성에 신경을 써주는 게 중요하다고 느꼈습니다!

2024-05-27 15:26 UTC, Parkhanyoung commented on src/utils/math/getPermutations.ts
> +};
> 우선 미션에서는 명시된 것 외에는 서드파티 라이브러리를 안쓰는 것이 기본입니다!ㅋㅋ

앗 그렇군요. 의도치 않게 반항을 했네요,, 죄송합니다 🥲

> 필요할 때에는 적절히 주석으로 설명을 적어두는 것도 좋은 방식입니다

어느샌가부터 무의식적으로 주석은 지양하는 게 좋다는 잘못된 믿음을 가졌던 것 같습니다. 앞으로 코드만으로 파악하기 어려운 부분에는 주석을 적절히 활용해보도록 하겠습니다! ✍🏻

2024-05-27 15:28 UTC, Parkhanyoung commented on src/utils/domain/determineShippingCost/determineShippingCost.test.ts
>  });
넵 맞는 말씀입니다! 안 그래도 유틸 함수에 두는 게 조금 꺼림직했는데, 앞으로는 별도의 디렉토리로 분리하겠습니다 👍🏻

2024-05-27 15:42 UTC, Parkhanyoung commented on src/api/coupons.ts
> +};
> Raw라는 것도 어디 기준에서 raw인지에 대해 이해가 필요할 수 있을 것 같아서요

이 부분이 크게 공감됐습니다! Response라는 단어가 서버에서 받아온 데이터라는 점을 더 명확히 나타낼 수 있을 것 같습니다!

> 지금은 쿠폰 목록을 불러오는 데에 실패하면 전체 앱을 사용할 수 없는 것으로 보이는데요

에러 관련한 고민을 깊게 못해봤었는데 잘 짚어주셔서 감사합니다 공원 🙂

현재 Suspense와 ErrorBoundary를 사용하고 있는데요. 이 둘을 함께 사용하니, 비동기 로직에 대해서도 ErrorBoundary를 통해 에러를 핸들링할 수 있었습니다. 또한 여기 api 로직 내에서 try catch문을 사용하여 에러를 잡아버리면 오히려 ErrorBoundary에서 에러가 잡히지 않게 되어 문제가 될 수 있겠다는 생각이 들기도 합니다.

혹시 공원은 이런 점을 고려하더라도 api 로직에서 에러 핸들링이 필요하다고 생각하시는 것일지, 필요하다면 어떤 형태로 핸들링하는 게 좋다고 생각하시는지 여쭙고 싶습니다!

2024-05-27 15:46 UTC, Parkhanyoung commented on src/components/CheckoutPage/CheckoutContent.tsx
> +  const location = useLocation() as { state: CheckoutPageState };
공원의 말씀을 듣고 생각해보니, 일단 주어진 요구 사항에만 충실하는 것이 더 큰 도움이 될 수도 있을 것 같네요 🙂 좋은 지점을 짚어주셔서 감사합니다! 당장의 요구 사항에 맞게 구현하는 방식으로 수정해보겠습니다!

2024-05-28 07:11 UTC, moonheekim0118 commented on src/components/CheckoutPage/CheckoutContent.tsx
> +  const location = useLocation() as { state: CheckoutPageState };
오오 👍 라이언의 의도 넘 좋습니다 👍 👍 
다만 공원의 말씀처럼 현재 요구사항 내에서 해결해보시는 것도 도움 될 것 같아요ㅎㅎ

2024-05-28 07:35 UTC, moonheekim0118 commented on src/pages/CheckoutPage.tsx
> +  const onReturnToCartButtonClick = () => navigate(ROUTE_PATH.cart);
의미의 차이점은 없지만 , 저는 아래와 같은 규칙을 가지고 개발해왔어요ㅎㅎ하지만 요건 프로젝트마다 컨벤션에 따라 달라질 것 같으니, 그냥 참고해주세요 :) 

- `on-**` : 이벤트 대상에 부착 될 때 사용 / on-** 이라는 이름 자체가, '** 이벤트가 트리거 될 때' 라는 의미를 가지고 있으므로 
- `handle-**` : 이벤트 대상에 부착 될 함수를 선언할 때 사용 / handle-** 이라는 이름 자체가, '** 이벤트 처리'라는 의미를 가지고 있으므로

따라서 저는 prop에 있는 이벤트 처리 함수는 on-** 의 네이밍을 따르고, 
해당 함수를 선언할 때에는 handle-** 의 네이밍을 따랐어요 ㅎㅎ

```

const handleClick =() => { }

<CartButton
    onClick={handleClick}
/>
```
요런 식으로 사용햇습니다ㅋㅋ

2024-05-28 07:35 UTC, moonheekim0118 commented on src/hooks/useCoupons/index.ts
> +  const totalPayAmount = totalOrderAmount - discountAmount;
아하, 저는 일단 1번의 배경(서버상태로 간주)을 모르는 상태에서 해당 상태들이 여러 페이지 내에서 참조되어야 한다고 생각했어요. ㅎㅎ 

> 상태 일관성 유지

좋은 고민을 해주셨네요 👍 👍  라이언이 해주신 고민과 고민 해결 방법에 대해서 깊게 동의합니다 :) 
라이언만의 기준을 잡고, 좋은 선택을 내려주셨군요ㅎㅎ

저는 단순히 할인 금액 같은 경우는 페이지가 변경 될 때 reset 시켜주면 되지 않을까?하고 생각하긴 했어요, 다만 그렇다면 각 페이지별로 이런 로직을 알고 있어야하는게 단점이겠네요 🥲

다만 현재 방법은, location 으로 데이터를 내려주지 않는다면, 어떻게 해결하실지도 궁금하네요 ㅎㅎ

2024-05-28 07:35 UTC, moonheekim0118 commented on src/types/rawCoupon.ts
> +type TimeString = string;
👏 👏

2024-05-28 07:35 UTC, moonheekim0118 commented on src/hooks/useCouponsDiscountCalculator/discountCalculators/index.ts
> +};
오호 이런 배경이 있으셨군요? 자세하게 설명해주셔서 감사합니다.

라이언이 말씀해주신것에 깊게 공감이 갑니다. 특히나 로직의 의미를 더 명확히 나타낼 수 있다는 점에요. ㅎㅎ
다만, 이럴 경우에 주석 등으로 해당 함수의 목적을 설명해주시면 좋을 것 같아요 :) 
해당 코드를 처음보거나, 할인 정책을 잘 모르는 사람이 봤을 때는 calculateFreeShippingDiscountAmount -> 요 함수의 이름과 내부 로직이 불일치 하는 것 처럼 느껴져서요.(이름은 calculate 인데 아무 연산도 안하네..!? 😮 )

특히나 이렇게 정책이 복잡할 경우, 즉 코드 외적인 것에 대한 배경 설명이 필요 할 경우 주석을 잘 활용해주시면 아주 좋습니다ㅎㅎ

2024-05-28 07:35 UTC, moonheekim0118 commented on src/hooks/useCouponsDiscountCalculator/discountCalculators/discountCalculators.test.ts
> +    });
기준이 있으시다면 좋습니다 👍 👍 설명감사해요.

2024-05-28 07:56 UTC, moonheekim0118 commented on src/api/coupons.ts
> +};
공원은 아니지만,,저의 의견을 한번 말씀드려보자면 🤭 ..

> 현재 Suspense와 ErrorBoundary를 사용하고 있는데요. 이 둘을 함께 사용하니, 비동기 로직에 대해서도 ErrorBoundary를 통해 에러를 핸들링할 수 있었습니다. 그래서 api 로직 내에서의 에러 핸들링은 불필요하다고 판단했습니다.

- 에러바운더리가 걸려있으니 라이언 말씀대로 에러처리는 될 텐데요! 다만, 실제로 에러바운더리까지 에러가 전파되기 전에, 서버로부터 응답받은 에러에 대한 가공이 필요하거나, 에러에 대한 후속 처리가 필요한 경우도 있을 것 같아요. (예를들어 하나의 페이지에서 a,b,c api 요청을 할 때, a 가 실패할 시 b,c 요청을 하지 않아야한다..라는 처리 등) 이럴 때에 대비하여 api 레이어에서 에러 처리를 해주면 좋겠지요!?

> api 로직 내에서 try catch문을 사용하여 에러를 잡아버리면 오히려 ErrorBoundary에서 에러가 잡히지 않게 되어 문제가 될 수 있겠다는 생각이 들기도 합니다. 

- catch 절에서 에러를 한번 더 throw 하면 되지 않나요? 👀 만약 요게 안된다면 왜 안되는지도 고민해보셔도 좋겠네용ㅎㅎ

2024-05-28 07:59 UTC, moonheekim0118 requested changes
라이언~ 개선해주시느라 고생 많으셨습니다 👏 👏 _(제가 요즘 건강 이슈로 인해.. 상습적으로 늦어서 정말 죄송합니다. 😭 🔫 )_

너무 잘 개선해주셔서, 추가로 코멘트 남길 부분은 없었어요ㅎㅎ라이언이 남겨주신 질문에 대해서 답변해드린게 전부이긴 한데요,
공원이 남겨주신 코멘트 및 제가 남겨드린 코멘트에 대해서 더 이야기 나눠보거나, 개선해보고 싶으신 부분이 있으실 것 같아서 일단 한번 더 rc 할게요!
(혹시나 머지를 원하시면 편하게 디엠주세요.)

그럼 고생하셨습니다 🦁

2024-05-28 15:50 UTC, Parkhanyoung commented on src/hooks/useCouponListDiscountCalculator/discountCalculators/discountCalculators.test.ts
> +import {
수정 완료했습니다. 🙂 원래는 프로덕션 코드와 테스트 코드가 섞여 있으니 헷갈렸는데, 별도의 디렉토리로 분리하니 확실히 원하는 파일을 찾기 쉬워진 것 같습니다! 다만, 하나의 디렉토리에 모든 테스트 코드를 몰아넣기보다는 관련된 프로덕션 코드와 가까이에 위치시키는 게 낫겠다고 판단하여, 관련된 프로덕션 코드의 디렉터리의 하위 디렉토리로 두어보았습니다.
(ex. hooks/useToggleSet/\__test__\)

커밋 링크: [146de56](https://github.com/woowacourse/react-shopping-cart/pull/285/commits/146de56f812743417b8851ea29aa850841427bf8)

2024-05-28 15:54 UTC, Parkhanyoung commented on src/utils/domain/determineShippingCost/determineShippingCost.test.ts
>  });
분리 완료했습니다! [8032ff9](https://github.com/woowacourse/react-shopping-cart/pull/285/commits/8032ff9d6a3d2544dee07df78255a4ef187a08b9)

2024-05-28 16:04 UTC, Parkhanyoung commented
호프, 공원 마지막까지 좋은 리뷰로 도움을 주셔서 너무 감사드립니다! 🙇🏻‍♂️
두 분의 피드백과 조언이 정말 큰 도움이 되었습니다! 앞으로도 조언 주신 내용 잊지 않도록 하겠습니다.

호프 건강이 안 좋으셨군요 😢 얼른 낫길 기도하겠습니다 🍀 (제가 코드 리뷰로 호프를 더 고생시킨 것 같긴 하네요 ㅠ)
컨디션도 안 좋으신데 끝까지 열심히 봐주셔서 다시 한 번 감사드려요 🫡

### 3차 리뷰 요청 반영/수정 사항

| 번호 | 커밋 메시지 | 커밋 링크 |
| --- | ----------- | -------- |
| 1 | RawCoupon 네이밍을 CouponResponse로 수정 | [0b33266](https://github.com/woowacourse/react-shopping-cart/pull/285/commits/0b33266ac4d995372a0e5fa17a7c1a5e5c7a5e97) |
| 2 | CheckoutPage에서 주문 정보 표시를 위해 쿼리 스트링을 이용하는 방식 적용 | [66e0ce7](https://github.com/woowacourse/react-shopping-cart/pull/285/commits/66e0ce745dba14a84fcf8b14a71a00f735a13a6e) |
| 3 | 할인 계산 로직을 간략히 설명하는 주석 추가 | [72543d7](https://github.com/woowacourse/react-shopping-cart/pull/285/commits/72543d79b1d33502550f83e0b1f8b7821e67bf99) |
| 4 | utils와 domain 디렉토리를 분리 | [8032ff9](https://github.com/woowacourse/react-shopping-cart/pull/285/commits/8032ff9d6a3d2544dee07df78255a4ef187a08b9) |
| 5 | test 관련 파일을 \_\_test\_\_ 디렉토리로 분리 | [146de56](https://github.com/woowacourse/react-shopping-cart/pull/285/commits/146de56f812743417b8851ea29aa850841427bf8) |
| 6 | 중간 레이어로 커스텀 훅을 두어 컴포넌트의 리코일에 대한 직접적인 의존성을 제거 | [8b020fe](https://github.com/woowacourse/react-shopping-cart/pull/285/commits/8b020fe3a7be71c3e7f49066b3084a48588cfdf1) |


(관련된 코멘트에 답글로도 남겨두었으니 참고해 주세요)

2024-05-28 16:18 UTC, woowapark commented on src/api/coupons.ts
> +};
우선 코드 구현 이야기로 가기 전에,       
어떤 에러가 발생할 수 있는지와 그 에러가 발생했을 때 사용자에게는 어떤 UI를 제공해주어야 할 지에 대해 생각해보는 게 도움이 될 수도 있을 것 같아요 :)         
어디에서 어떤 식으로 핸들링하는 것이 좋을 지는 요구 사항에 따라 다른 선택을 할 수도 있다고 생각합니다.        
실제로 서비스마다 에러가 발생했을 때 보여주는 UI나 메세지 등이 조금씩 다를 거에요.        
평소에 사용하던 서비스에서 뭔가 문제가 발생했을 때 / 네트워크가 느릴 때 / 가끔씩 서버 에러가 발생했을 때 / 로그인 안된 상태에서 권한이 필요한 무언가를 할 때 등등 여러 상황에서 어떤 식의 UX를 제공해주고 있는지 발견해보는 것도 재밌을 것 같네요 
마침 새로운 미션이 더 고민해보기 좋은 미션인 것 같으니ㅋㅋ 구현해보시면서 더 고민해보시는 걸 추천해봅니당

2024-05-30 04:30 UTC, moonheekim0118 approved these changes
안녕하세요 라이언~! 다른 미션으로도 바쁘실텐데 끝까지 끈기있게 반영해주셔서 감사합니다 🙇 
덕분에 저도 많이 배워갔어요ㅎㅎ

그럼 이번 미션은 여기서 마무리할게요 :) 고생하셨어요. 다음 미션도 파이팅입니다 👍 👍 👍

2024-05-30 04:30 UTC, merged