[2단계 - 장바구니 미션] 버건디(전태헌) 미션 제출합니다.
woowacourse/react-shopping-cart pull request #286
Opened 2024-05-24 05:56 UTC by brgndyy

## [배포링크](https://brgndyy.github.io/react-shopping-cart/dist/)

---

안녕하세요 브콜 ! step2로 다시 찾아 뵙게 되었습니다.

> ❗️ step1과 마찬가지로 사이트 설정 -> 안전하지 않은 콘텐츠 -> 허용을 해주시면 배포 사이트 확인이 가능합니다 ❗️

이번 미션이 개인적으로 제일 재밌기도 했고, 생각해볼수 있는 부분이 많았던 미션이어서 많이 배워가는 중인데요!

많이 부족한 코드이지만, 놓치고 있는 부분 말씀 주시면 성장하는데에 큰 도움 될거 같습니다  🙇

이번 미션을 진행하면서 가장 크게 배우고 느꼈던 부분은 **전역 상태 관리 레이어** 인데요. 

해당 부분 및 그 외 여쭤보고 싶은 질문들 코멘트로 남겨놓겠습니다. 

이번 step2도 잘부탁드립니다!

2024-05-24 06:00 UTC, brgndyy commented on src/services/test/calculateDiscountPrice.test.ts
이번에 돈 계산 관련된 로직이 많다보니, 테스트 코드의 유용함을 많이 느낄 수 있었습니다! 

그래서 테스트 코드도 각 케이스 별로 나눠서 짜보았는데요.

한번 봐주시면 감사하겠습니다 🙇

여기서 궁금한점은, 브콜은 현업 생활 하시면서 테스트 코드를 많이 짜시나요 ?

사실 현재 우테코에서 배워가는 과정에 있다보니 테스트 코드를 짜는게 당연히 큰 도움되고 얻어갈수 있는 부분이 크다고 생각하는데요.

아무래도 현업에서는 시간이 굉장히 촉박하다보니 테스트 코드를 도입하는거 자체가 큰 비용이 되지 않을까 ?

만약에 초기부터 테스트 코드 문화가 잡혀있지 않다면, 중간에 도입하기엔 굉장히 어려운 문화 아닐까 생각이 들었습니다.

아직 현업에 임해보지 못해서 드는 추상적인 걱정일수도 있는데, 현업에 실제로 계신 브콜께 한번 여쭈어 보고 싶습니다!

2024-05-24 06:00 UTC, brgndyy commented on src/store/couponStates.ts
## 서버상태의 초기 셋팅 레이어

저번 장바구니 아이템도 그렇고, 이번에 쿠폰도 그렇고 서버에서 받아온 상태를 아톰에 넣어주기 전에,

1. 초기에 fetch를 통해 데이터를 받아온다.
2. 포맷팅 레이어를 두어서 필요한 프로퍼티들을 추가해준다.

의 흐름을 가지고 있습니다. 

이번에도 쿠폰을 받아올때, 현재 장바구니에 담은 아이템들의 총 가격, 갯수들을 기반으로

`isAvailable` => 초기에 disabled로 해줄것인가 말것인가? 
`isChecked` => 체크표시가 되어있는가 아닌가 ? 

같은 클라이언트측에서 필요한 프로퍼티들을 추가해주고 있는데요!

이렇게 하면, 전 관리가 필요한 상태 들이 응집성 있게 되어서 상태추적에 용이하다고 생각했습니다.

결국 이 상태는 근본 atom이 되어서, 그 후에 파생 상태들 또한 쉽게 만들어줄수 있다고 판단했구요! 


<img width="572" alt="스크린샷 2024-05-24 오전 8 11 50" src="https://github.com/woowacourse/react-shopping-cart/assets/109535991/89fbf952-06eb-4446-ad6d-2eafa61f69f2">


사진으로는 이렇게 나타낼수 있을거 같은데요.

근데  

>disabled나 checked 값은 클라이언트에서 다루어야하는 상태인데, 서버상태에 해당 프로퍼티들을 넣어주는것이 옳은가? 

과도한 리렌더링을 유발하는거 아닌가 ? 

에 대한 의구심도 들었습니다.

제가 놓치고 있는 부분이나 더 생각해보아야할 점이 있다면 말씀주시면 감사하겠습니다!

2024-05-24 06:00 UTC, brgndyy commented on src/store/custom/useManager.ts
## - 복잡한 타입 선언

step1 때는 recoil 자체를 처음 써보다보니 일단 되는대로 구현을 했었습니다. 

물론 지금도 당연히 recoil과 친한건 아니지만, 기능 구현이 다 되어있는 상태에서 코드를 살펴보니 너무 하드코딩 느낌으로 파생상태들을 선언해주고 이를 무지성으로 사용하고 있다는 느낌이 들었어요!

그래서 이를 한곳에서 관리해주는 레이어를 하나 더 만들어보았는데요! 

`useManager`가 리코일의 selector, action, state를  한곳에 모아주는 역할을 하고 이를 필요한 도메인 별로 `useCartManager`, `useCouponManager`, `useShippingManager`로 나누어보았습니다.

다만, 이 `useMananger` 코드 내부애서 타입들이 any로 대부분 선언이 되어있어서 상태값들을 불러올때 타입추론이 안되는 상황이에요 🥲

<img width="503" alt="스크린샷 2024-05-24 오전 8 29 00" src="https://github.com/woowacourse/react-shopping-cart/assets/109535991/4ed51c5e-b011-4d98-add3-4b0760acabff">


이런식으로 사용하는곳에서 직접 타입지정을 해주어야하는데요.

타입스크립트가 익숙치 않아서, 중앙 관리자 역할(useManager)의 타입이 동적으로 결정될수 있도록 하고 싶은데 아직 감조차 잡히지 않아 이는 구현을 하지 못한 상태입니다.

이번에 이를 구현해보면서 들었던 궁금증인데요. 

현업에서는 타입스크립트의 기능들을 어느정도로 활용할까요?

이 `useManager`에서 사용 된 타입들도 직관적으로 한번에 이해가 되는 타입이 아니라서 따로 공부해볼 예정인데요!

현업에서 이런식의 복잡한 타입 관리? 같은걸 많이 하는 편인가요 ?

단순히 받아오는 api에 대한 타입선언을 넘어서서, 복잡한 타입선언을 해주는 경우는 언제인지, 많은 경우가 그러는지 여쭙고 싶어요!

2024-05-24 06:02 UTC, brgndyy commented on src/pages/checkout/CheckoutPage.tsx
> +        장바구니로 돌아가기
PR을 올린후에 추가적으로 장바구니에 담았던 제품들이 초기화 되어야한다는 추가 요구사항을 받았는데요! 

리뷰 받은 후에 수정사항 반영해보면서 추가적으로 구현해보도록 하겠습니다

2024-05-25 17:18 UTC, Tanney-102 requested changes
안녕하세요 버건디!
두번째 단계도 고생 많으셨습니다!
작성해주신 useManager훅과 질문주신 내용들 위주로 보려고 했어요! 또 추가로 신경쓰시면 좋을 내용들 코멘트 남겨두었으니 확인부탁드립니다!

2024-05-25 17:18 UTC, Tanney-102 commented on src/services/calculateDiscount.ts
> +      return (calculator as FixedDiscountCalculator)(coupon);
discountCalculators를 Record타입이 아니라 interface로 타이핑했으면 as를 안써도 됐을 것 같습니다!

2024-05-25 17:18 UTC, Tanney-102 commented on src/pages/cart/components/Cart.tsx
> +    <CartContext.Provider value={{ allCartItems: totalCartItems }}>
지금보니 드는 의문인데 왜 context를 써야하나요? recoil 상태를 그냥 가져다쓰면되지 않나요?

2024-05-26 23:18 UTC, brgndyy commented on src/store/custom/useManager.ts
> +    ...createUseRecoilStates(states || {}),
value와 setter 만으로도 상태들을 모두 관리해줄순 있겠지만, `[state, setState]`의 형태로 관리해주는 것이 훨씬 더 간편해서! 라고 말씀드릴수 있을거 같습니다.

예를 들어서 

```ts
  const { individualCartItemQuantity } = useCartManager();
  const [productQuantity, setProductQuantity] = individualCartItemQuantity(id);
```

각각의 아이템 수량을 관리해주는 경우 useRecoilState를 사용해서 관리해주는 것이 가독성 면에서도 훨씬 좋다고 판단했습니다.

하지만 단순히 setter만 사용해야하거나, value 만 사용해야하는경우,

예를 들어서, 쿠폰을 적용시켰다가 뒤로가기 페이지를 눌렀을때는 쿠폰을 초기화 해주는 setter 함수만 필요한데요.

```ts
  const { initializeCouponStates } = useCouponManager();

  const handleBackButtonClick = () => {
    initializeCouponStates();
    navigate(PAGE_ROUTES.CART);
  };

```

이런식으로 필요한 함수만 골라와서 사용할수 있는것이 더 가독성 면에서 좋다고 판단하여 value, setter, states 각각 나눠서 분리해주었습니다!

2024-05-26 23:18 UTC, brgndyy commented on src/store/custom/useManager.ts
> +  };
질문을 제가 정확히 이해하지 못했는데요..! 

>지금 구조로는 A 상태만 사용하는 컴포넌트에서 { A, B } = useManager() 이런식으로 모든 상태를 다 구독해야할 것 같아요.

라고 말씀 주신 부분에서 A 상태만 필요한 상태에서 B 상태까지 구독해야하는 경우가 어떤건지 이해하지 못했습니다 🥲

현재 커스텀 훅내에서 필요한 값들만 불러와서 사용하고 있는 중이라고 생각하고 있습니다만, 제가 놓치고 있는 부분이 있을까요 ? 

리렌더링 같은 경우, 현재 아예 베이스 아톰를 중심으로 isChecked나 isAvaliable 같은 프로퍼티도 추가해주어서 관리해주다보니 리렌더링이 발생하는것이 맞습니다! (이 부분은 Single Source Of Truth을 근거로 한번 이렇게 하나의 출처에서 관리되도록 해본것인데요. 불필요한 리렌더링이 유발 된다. 라는 단점이 동시에 존재할수 밖에 없었습니다..! 🥲)

2024-05-28 15:41 UTC, Tanney-102 commented on src/store/custom/useManager.ts
> +    ...createUseRecoilStates(states || {}),
이유가 명확해서 좋네요 👍

2024-05-30 00:46 UTC, brgndyy commented on src/store/custom/useManager.ts
> +  };
사실 처음에 예상했던건 브콜이 말씀 주셨던것처럼, 셀렉터로 선언해주면 필요한 부분만 리렌더링 될것이다! 였습니다.

그래서 처음에 checkedId 같이 필요한 부분을 따로 셀렉터로 선언해서 관리해주어야할거라고 생각했는데요.

하지만 리액트 데브툴로 확인해보니 체크 상태만 변경 되더라도 전체가 리렌더링 되더라구요..! 

그래서 일단 전체 상태로 관리해주어도 괜찮을 것이다. 라고 예상하고 코드를 짰었는데, 그게 오히려 제가 잘못 파악하고 있던거였습니다..🥲 (다른 크루원들은 필요한 부분만 리렌더링 된다고 하더라구요)

수정하게 된다면 코드 자체가 좀 많이 바뀔수밖에 없는 지금 상황에선 계속 아쉬움이 남는 부분입니다...

2024-05-30 00:46 UTC, brgndyy commented on src/store/couponStates.ts
> 관심사의 분리 차원에서 순수한 모델과 메타 데이터의 성격을 가지고 있는 정보들을 분리 

좋은 말씀 감사합니다! 

한번 수정해보도록 하겠습니다 🙇

2024-05-31 18:27 UTC, Tanney-102 commented on src/store/custom/useManager.ts
> +  };
데브툴 하이라이트로 확인하셨나요? 요새도 있는 버그인지 모르겠는데 context같은 거 쓸 때 실제로 렌더가 안되는데 깜박거리는 경우도 가끔 있더라구요. 실제 컴포넌트가 호출되는지를 확인하시는 게 가장 정확합니다. 아쉽지만 배운 게 있으셨으리라 믿습니다!

2024-05-31 18:29 UTC, Tanney-102 approved these changes
안녕하세요 버건디~ 마지막까지 정말 고생 많으셨습니다.
이번 미션의 아쉬움을 거름 삼아 상태관리 라이브러리들을 더욱 폭 넓은 관점으로 바라보게 되시기를 바라며 이만 마무리하겠습니다!!

2024-05-31 18:29 UTC, merged