[2단계 - 장바구니 미션] 소파(차승하) 미션 제출합니다.
woowacourse/react-shopping-cart pull request #291
Opened 2024-05-24 16:50 UTC by ss0526100

## [배포](https://ss0526100.github.io/react-shopping-cart/)

안녕하세요 케빈 다시 만나게 되어서 반갑습니다.

스텝 2를 진행하면서 테스트 코드에 시간을 많이 할애할 듯 하여 일단 우선적으로 최소한의 테스트코드를 작성한 후 리뷰 요청드립니다.

추후에 테스트 코드를 추가하도록 하겠습니다..!

아쉬운 점과 궁금한 점, 리뷰하시면서 아시면 도움 될 내용들을 정리해 보았습니다.

그럼 잘부탁드려요!

## 아쉽거나 어려웠던 점

- 컴포넌트와 페이지가 많아짐에 따라 파일 구조를 설정하는 것이 어려웠습니다.
- 페이지를 명명할 때 어떤 식으로 명명할 지 몰라 lastPage와 같은 이름을 사용하였습니다.
- 유사한 ui를 가진 컴포넌트들을 하나로 합칠 수 있었을 것 같다는 아쉬움이 들었습니다.
-  모달창에서 쿠폰이 선택된 상태로 만료기간이 지난 경우 선택된 쿠폰을 해제할 수 없었습니다. 추가적인 코드 작업이 필요해 보입니다.

2024-05-25 16:29 UTC, JeongBin0227 commented
궁금한점이 있는데, 같은 상품인데 왜 분리되어 있는지 알수있을까요?
![image](https://github.com/woowacourse/react-shopping-cart/assets/45503248/b2910eae-6f0d-43b4-8d4e-a5435fa0d047)

2024-05-25 16:33 UTC, JeongBin0227 commented
UX) 사용 가능한 쿠폰을 제일 상단에 보여주면 어떨까요?
![image](https://github.com/woowacourse/react-shopping-cart/assets/45503248/328690b2-569b-4228-b59a-facaa1fc9e63)

2024-05-25 16:38 UTC, JeongBin0227 commented
> 컴포넌트와 페이지가 많아짐에 따라 파일 구조를 설정하는 것이 어려웠습니다.

흠 이건 제가 사용하는 방법인데, 저는 기능이나 도메인에 따라 파일을 구조화하거나, 컴포넌트 유형별로 구조를 나누는 편입니다. 예를 들어, 기능이나 도메인을 기준으로 하면 모든 사용자 관련 컴포넌트는 features/user 폴더에, 모든 주문 관련 컴포넌트는 features/order 폴더에 넣을 거 같아요. 아니면 컴포넌트를 기준으로 하면 공통 컴포넌트, 페이지 컴포넌트, 레이아웃 컴포넌트 등으로 나눌 수 있습니다. 예를 들어, components/common, components/pages, components/layouts와 같은 구조를 가질 수 있어요

2024-05-25 16:39 UTC, JeongBin0227 commented
> 페이지를 명명할 때 어떤 식으로 명명할 지 몰라 lastPage와 같은 이름을 사용하였습니다.

개인적으로 last page 는 명확히 어떤 의미인지 파악하기 어렵고 나중에 페이지가 추가되면 실제로 last page가 아닐수 있어 목적이나 기능을 명확히 하는 이름이 좋습니다. ConfirmationPage 가 될수도 있고 PaymentPage가 될수도 있을거 같아요

2024-05-25 16:40 UTC, JeongBin0227 commented
> 유사한 ui를 가진 컴포넌트들을 하나로 합칠 수 있었을 것 같다는 아쉬움이 들었습니다.

이부분은 전부다 바꾸는게 어렵다면 기준을 잡고 몇가지만 먼저 시도해봐도 좋을거 같아요

2024-05-25 16:45 UTC, JeongBin0227 requested changes
안녕하세요 소파!

2단계 미션도 빠르게 제출해주셔서 감사합니다 👍 덕분에 여유롭게 볼수 있었습니다 1단계 미션에서 구조화를 잘해주신덕분에 어느 폴더에 어떤파일이 위치할지 쉽게 파악할수 있었습니다. 소파가 남긴 고민들이나 결과물 및 코드를 보고 코멘트 몇개 드렸으니 읽어보시면 좋을거 같아요~

2단계 미션도 고생하셨습니다~ 💯

2024-05-25 16:45 UTC, JeongBin0227 commented on src/utils/checkIsAvailableCoupon.ts
> +  if (coupon.discountType === 'percentage') return checkIsAvailablePercentageCoupon(coupon);
흠.. 이런 로직은 취향차이이긴 한데, 이런 로직은 어떠신가요?
```
  const checkers = {
    fixed: isAvailableFixedCoupon,
    buyXgetY: isAvailableBuyXgetYCoupon,
    freeShipping: isAvailableFreeShippingCoupon,
    percentage: isAvailablePercentageCoupon
  };

  const checker = checkers[coupon.discountType];

  if (!checker) return false;

  return checker(coupon, itemAmount, deliveryFee, nowMinutes);
```

2024-05-25 16:45 UTC, JeongBin0227 commented on src/utils/checkIsAvailableCoupon.ts
> +  const nowMinutes = getNowMinutes();
이렇게 현재 시간을 함수에서 다시 생성하면 테스트 환경에서 현재 시간을 조작하기 어렵게 만듭니다.
외부에서 주입받도록 변경하면 어떨까요?

```
export default function checkIsAvailableCoupon(
  coupon: Coupon,
  items: CartItem[],
  deliveryFee: number,
  nowMinutes = getNowMinutes(),  
)
```
이렇게요!

2024-05-25 16:45 UTC, JeongBin0227 commented on src/type.d.ts
> +export interface FixedDiscountCoupon extends CouponBase {
저는 개인적으로 이럴경우, 쿠폰 타입을 정의할 때, 현재의 스키마에 의존하지 않고 좀 더 범용적이고 확장 가능한 방식으로 정의하는 것이 어떨까 생각됩니다. 이렇게 하면 스키마가 변경되더라도 타입 정의와 비즈니스 로직에 큰 영향을 미치지 않습니다.

2024-05-25 16:45 UTC, JeongBin0227 commented on src/App.tsx
> +import ShoppingCartPage from './page/ShoppingCartPage/ShoppingCartPage';
혹시 동적 임포트를 사용하는것을 들어보셨나요?
이건 그렇게 중요한건 아닌데 참고차 이런것도 있구나~ 라는 느낌으로 가볍게 봐주시면 될거같아요

```
// 동적 임포트를 사용하여 코드 스플리팅
const OrderConfirmationPage = lazy(() => import('./page/OrderConfirmationPage/OrderConfirmationPage'));
const OrderLastPage = lazy(() => import('./page/OrderLastPage/OrderLastPage'));
const ShoppingCartPage = lazy(() => import('./page/ShoppingCartPage/ShoppingCartPage'));
```

2024-05-25 16:45 UTC, JeongBin0227 commented on src/hooks/useCoupons.ts
> +  const MAX_COUPON_NUMBER = 2;
상수는 매번 랜더링 될때마다 재선언 되니 제일 상단에 적어도 될거같아요

2024-05-25 16:45 UTC, JeongBin0227 commented on src/page/OrderConfirmationPage/CartAmountWithCoupon/CartAmountWithCoupon.tsx
> +        <img src={InfoIcon} />총 주문 금액이 100,000원 이상일 경우 무료 배송됩니다.
100,000 은 비지니스에 따라 변경될수도 있으니 상수로 관리하는것도 좋아보여요

2024-05-25 16:45 UTC, JeongBin0227 commented on src/page/OrderConfirmationPage/CouponItem/CouponItem.tsx
> +};
getFromToMinuteKoKR 때문에 해당 파일이 무척 복잡하게 느껴지는거 같아요
따로 파일을 뺄수도 있고, 
```
const getFromToMinuteKoKR = (fromMinute: number, toMinute: number) => {
  const formatTime = (minute: number) => {
    const isAM = minute < 12 * 60;
    const hour = Math.floor(minute / 60) % 12 || 12;
    const restMinute = minute % 60;
    const period = isAM ? '오전' : '오후';
    const minuteString = restMinute > 0 ? ` ${restMinute}분` : '';
    return `${period} ${hour}시${minuteString}`;
  };

  const from = formatTime(fromMinute);
  const to = formatTime(toMinute);
  const adjustedTo = from.includes('오전') !== to.includes('오전') ? `${to.includes('오전') ? '오전' : '오후'} ${to}` : to;

  return { from, to: adjustedTo };
};
```
같은 파일에서 써야한다면 이렇게 줄여볼수도 있을거 같아요

2024-05-26 16:45 UTC, ss0526100 commented on src/App.tsx
> +import ShoppingCartPage from './page/ShoppingCartPage/ShoppingCartPage';
케빈의 코멘트를 읽고 React.lazy에 대해 찾아보았습니다.

지금은 작은 프로젝트라 import시 큰 부담이 없어 적용하지 않아도 괜찮겠지만, 나중에 프로젝트가 커지면 유용할 것 같다는 생각이 들었습니다!

알려주셔서 감사합니다!!

2024-05-26 17:01 UTC, ss0526100 reviewed
코멘트 주신 내용+테스트 구현해서 다시 리뷰 요청드립니다!! 미션 진행 관련 내용 코멘트 남겨놓았습니다! 참고하시면 좋을 것 같아요!!

2024-05-29 11:03 UTC, ss0526100 commented
안녕하세요 케빈 늦어서 죄송합니다. 부족했던 부분을 추가해보았습니다.

> 차라리 유틸함수로 빼면 어떨까 생각됩니다. 해당 컴포넌트 뿐만 아니라 다른 곳에서도 사용할수있는 범용적인 함수같아요

이와 같은 케빈의 코멘트를 보고 직접 분리해보고, 상수화를 해보는 등 리팩토링을 진행해보았는데요.

너무 코드가 장황해지는 것 같다는 생각이 들었습니다. 그래서 일단 커밋을 진행하지 않고 이대로 두었습니다. 어짜피 이 부분을 사용한다면, 계산하는 부분이 꼭 필요할 것 같다는 생각도 들고요...! 

리뷰 감사했습니다...!

2024-05-31 01:41 UTC, JeongBin0227 approved these changes
안녕하세요 소파!~

수정해주신 코드 모두 확인하였습니다. 혹시나 제가 놓친 코멘트가 있으면 확인해주세요~

다른 미션 진행중이실텐데 고생하셨습니다 다음 미션도 화이팅입니다 💯

2024-05-31 01:41 UTC, merged