[2단계 - 장바구니 미션] 낙타(송재석) 미션 제출합니다.
woowacourse/react-shopping-cart pull request #294
Opened 2024-05-25 06:27 UTC by Largopie

> 배포 주소 : https://largopie.github.io/react-shopping-cart
> 로컬 실행
> ```
> npm run dev
>```

안녕하세요 하루! 🐫 잘 지내셨나요! ㅎㅎ
DM으로 질문했었는데도 빠르게 답변 남겨주셔서 너무 감사드립니다 :) 👍

이번에 신경쓴 부분은 쿠폰 로직을 어떻게 동작하게 할 지에 대해서 많은 고민이 있었던 것 같아요.
step2 시작 전 [실습](https://github.com/woowacourse/react-basecamp/tree/main/coupons)을 진행하면서 어떻게 쿠폰 로직을 사용할 수 있을지 직접 구현해보기도 했는데, 정확하게 감이 오지 않는 느낌이더라구요 🥲

그래서 처음에는 막연하게 해당 실습내용을 바탕으로 훅 로직을 비슷하게 작성했었습니다.

그러다가 문득 기존에 `selector`를 이용해서 구현했기 때문에, `selector`로 구현하면 `get`, `set`을 이용하기에도 좋은 점이 많아서 `selector`를 기반으로 쿠폰로직을 대부분 만들어 나갔습니다!

`selector`로 사용하지 않아도 된다고 판단되었던 부분들은 `util`함수로 분리하게 되었어요!
그리고 실습 내용을 바탕으로 **TDD로 구현**을 해보게 되었는데,

- 즉각적으로 구현한 부분을 피드백을 받을 수 있다는 점
- 각 역할별로 관심사를 분리해서 구현할 수 있다는 점

에서 좋은 점을 많이 느꼈던 것 같습니다!

## 🎫 쿠폰 적용 로직 설명
다음은 쿠폰 로직에 대한 간단한 설명입니다!

### selectedCoupons

- 실시간 선택된 쿠폰
- 체크를 누를 때 마다 selectedCoupons에 적용 조건이 반영됨

### fixedSelectedCoupons

선택 확정된 쿠폰

- 적용 버튼을 눌렀을 때, selectedCoupons의 쿠폰이 fixedSelectedCoupons로 세팅됨

### calculateTotalDiscountAmountSelector

- selectorFamily
    - fixed: boolean
- fixed가 true일 때, fixedSelectedCoupons의 할인률을 가져옴
- fixed가 false일 때, selectedCoupons의 할인률을 가져옴

### 중복 쿠폰 적용 시

**조합을 이용**해서 모든 순서의 배열을 받아온 후, 값을 계산하고 가장 할인률이 높은 인자를 선택하는 방식

## 🐫 추가 반영 사항 및 질문

### 🤔 버튼 label 삭제

버튼의 라벨을 중복적으로 사용한다는 리뷰를 받고 다시 한 번 버튼에 대해서 고민을 해보았습니다.
저의 의견으로는 버튼을 보통적으로 구현하는 경우는 2가지로 나뉠 것 같습니다.

1. 텍스트 ⇒ 텍스트 자체로 의미 파악 가능
2. 이미지 ⇒ `alt` 속성에 버튼이라는 것을 명시

이와 같은 방식을 사용한다면 `label`이 있을 필요가 없지 않을까 하는 생각에 `label`을 삭제하게 되었습니다.

### 🤔 h1태그는 어떻게 사용해야할까?

`SHOP`에 `h1` 태그를 사용할지, 각 카테고리별 제목에 `h1` 태그를 사용할지 고민했습니다. 여러 사이트를 참고한 결과, 사이트마다 사용하는 방식이 달랐습니다.

- `카카오페이` → 로고에 h1 없음, 각 기능에 h1태그 부착(ex. [송금](https://www.kakaopay.com/services/life/money_transfer), [보도자료](https://www.kakaopay.com/news/pr), [공지사항](https://www.kakaopay.com/news/notice) 등)
- `무신사` → 로고에 h1 있음
    - 마이페이지와 같은 부분에도 h1태그 장착 되어 있음 -> (이 때, 왜 한 페이지에 h1태그가 두개가 있는지 궁금증이 생겼습니다.. ㅠ)
  <img width="309" alt="Untitled" src="https://github.com/woowacourse/react-shopping-cart/assets/106071687/e215b8fe-cdc5-4177-897c-2e782a915b51">
- `29cm` → 로고에 h1 없음. h1태그를 못찾았음.
- `worksout` → 로고에 h1 있음, [CARHARTT WIP](https://worksout.com/collections/carharttwip)에 접속하면 CHARHARTT WIP도 h1
- `coupang` → 로고에 h1 있음, 각 카테고리 별 주제에도 h1 있음(ex. [남성 패션](https://www.coupang.com/np/categories/187069))

하루는 이 부분에 대해 어떻게 생각하시나요?

## 🍀 이 부분을 중점적으로 리뷰받고 싶어요!

- 쿠폰 로직에 대한 개선 사항
- 각 역할별로 관심사를 분리하여 구현한 부분이 잘 되어있는지

아무래도 이번 미션이 쿠폰 적용에 관련되어있는 미션이다 보니, 쿠폰 로직 쪽에서의 개선 방법, 그리고 각 역할별로 분리가 잘 되어있는지를 중점적으로 리뷰 받고 싶습니다 :)

이번 STEP2도 잘 부탁드려요~ 🐫🐫🐫

2024-05-25 06:55 UTC, 365kim commented
미춋따 대박

<img width="186" alt="image" src="https://github.com/woowacourse/react-shopping-cart/assets/60066472/1ca18369-940c-4afe-87d5-3f51afa6d4a3">

2024-05-25 13:22 UTC, 365kim commented on src/recoil/coupon/atom.ts
> +});
`selectedCouponsState ` 이 상태를 컴포넌트 내부의 상태(React.useState)가 아니라 전역 상태 atom으로 구성해주신 이유가 궁금합니당 :)

2024-05-25 13:25 UTC, 365kim commented on src/components/common/Title.tsx
> +  return <h1 css={title}>{children}</h1>;
> SHOP에 h1 태그를 사용할지, 각 카테고리별 제목에 h1 태그를 사용할지 고민했습니다. 여러 사이트를 참고한 결과, 사이트마다 사용하는 방식이 달랐습니다. (중략) 하루는 이 부분에 대해 어떻게 생각하시나요?

낙타의 생각을 먼저 듣고싶습니다! 낙타는 어떤 결론을 내리셨는지 궁금해요 :)

2024-05-25 13:28 UTC, 365kim commented on src/components/CartItem/CartItemHeaderSection.tsx
> +      </button>
👍

2024-05-25 13:28 UTC, 365kim commented on src/components/CartItem/CartItemHeaderSection.tsx
>          labelHidden={true}
간단하게 이렇게 써도 좋겠슴니닷

```suggestion
        labelHidden
```

2024-05-25 13:40 UTC, 365kim commented on src/recoil/cartItems/atoms.ts
> +import { atom, atomFamily } from 'recoil';
> src/recoil/cartItems/atoms.ts

상황을 가정해, recoil에서 zotai로 마이그레이션 하게 되어 디렉토리 이름 변경이 필요해진다면, 변경사항에 recoil 하위 모든 파일이 잡힐 것 같습니다. 디렉토리 이름에는 'recoil'이라는 도구 이름이 드러나지 않도록 하면 어떨까요? (globalState 정도로...?)

2024-05-25 13:40 UTC, 365kim commented on src/utils/validations.test.ts
> +      const expiredCoupon: Coupon = {
네이밍 좋네용 👍

2024-05-25 13:41 UTC, 365kim commented on src/utils/validations.ts
> +  return true;
이렇게 써볼 수 있을까요?

```suggestion
  return now >= startTime && now <= endTime
```

2024-05-25 13:44 UTC, 365kim commented on src/recoil/coupon/selector.test.tsx
> +        expect(result.current).toBeDefined();
> 해당 쿠폰을 반환한다.

'반환값이 정의되었다'는 것보다 더 구체적으로 해당 쿠폰이 제대로 반환되었는지를 검증해볼 수 있을까요?

2024-05-25 13:45 UTC, 365kim commented on README.md
> +  - [x] 테스트
중간중간에 바로 문서 업데이트해주시는 것 좋네용 👍

2024-05-25 13:51 UTC, 365kim commented on src/types/coupon.ts
> +}
Coupon 타입을 discountType에 따라 Union으로 정의해볼 수 있을까요? 예를 들어 discountType이 fixed일 때는 `discount`가 optional이 아니라 required 속성인 것을 반영하는 식으로요 :)

2024-05-25 13:54 UTC, 365kim commented on src/utils/format.ts
> +};
오 포맷팅 유틸함수는 단위테스트를 작성해봐도 좋을 것 같아요 (시간적 여유가 없다면 후순위로 미뤄주셔도 좋아요)

2024-05-25 13:57 UTC, 365kim commented on src/utils/format.ts
> +export const dateFormat = (targetDate: Date) => {
<img width="380" alt="image" src="https://github.com/woowacourse/react-shopping-cart/assets/60066472/99058815-b664-4425-bc20-b392ea7c935f">


유틸함수의 반환값을 주석만 보고 빠르게 예상할 수 있도록 작성해도 좋겠습니다.

```suggestion
/** @returns '2024년 5월 1일' 꼴로 포맷 */
export const dateFormat = (targetDate: Date) => {
```

2024-05-25 13:58 UTC, 365kim commented on src/components/Coupon/CouponItem.tsx
> +              최소 주문 금액 : {coupon.minimumAmount.toLocaleString('ko-KR')}원
```suggestion
              최소 주문 금액: {coupon.minimumAmount.toLocaleString('ko-KR')}원
```

2024-05-25 14:01 UTC, 365kim commented on src/components/Coupon/CouponItem.tsx
> +      if (selectedCoupons.includes(coupon.code))
단순 궁금) `else if() {}`가 아니라 `else { if() }` 로 의도해주신 구문일까용 ?

2024-05-25 14:06 UTC, 365kim commented on src/components/Coupon/CouponItem.tsx
> +    coupon.discountType === 'freeShipping' && orderTotalPrice >= MINIMUM_FREE_SHIPPING_AMOUNT;
`isShippingFreeCouponDisabled` 도 `isCouponApplicable`를 계산하는 곳에서 판단해줄 수 있을까요?

2024-05-25 14:11 UTC, 365kim commented on README.md
> +![주문확인 컴포넌트 구조화](https://github.com/woowacourse/react-shopping-cart/assets/106071687/2f10b8af-dbba-47c1-b01b-1550e6e7c505)
👍

2024-05-25 14:17 UTC, 365kim commented on src/recoil/coupon/selector.test.tsx
> +    it('쿠폰이 유효하지 않다면, "false"를 반환한다.', () => {
quantity가 3 이상인 아이템이 없다면 Buy 2 get 1 free 쿠폰을 사용할 수 없다는 테스트도 추가해볼 수 있을까요?

2024-05-25 14:22 UTC, 365kim commented on src/layouts/GeneralLayout.tsx
> +      </button>
너무 잘썼습니다 감사합니다 👏👏👏👏👏


https://github.com/woowacourse/react-shopping-cart/assets/60066472/51fe5b22-f5b3-4445-bef9-73f4ec0c7674

2024-05-25 14:22 UTC, 365kim commented on src/layouts/GeneralLayout.tsx
> +export default function GeneralLayout() {
사소한데 `GlobalLayout`이라는 이름을 추천드려봅니다 (지금도 좋습니다)

2024-05-25 14:26 UTC, 365kim commented on src/components/CartConfirm/OrderResult.tsx
> +        <Receipt description="쿠폰 할인 금액" price={-totalDiscountAmount} />
0원일 때 - 부호를 표시하지 않도록 처리되면 더 좋을 것 같습니다 :)

<img width="383" alt="image" src="https://github.com/woowacourse/react-shopping-cart/assets/60066472/49ff9d9b-7985-4424-b4b2-42200c38582a">

2024-05-25 14:32 UTC, 365kim commented on src/mocks/coupons.ts
> +export const INVALID_BOGO_COUPON: Coupon = {
'유효하지 않다'는 의미는 꼭 만료기간이 아니어도 적용될 수 있으니, `INVALID`대신에 `EXPIRED_`로 구체화해서 네이밍하면 어떨까요?  `isCouponValid` 이라는 함수도 `isStillValid`, `isStillActive`, `isNotExpired` 등으로 더 구체화해주셔도 좋을 것 같아용

2024-05-25 14:35 UTC, 365kim commented on src/components/Cart/CartProducts/AllChecked.tsx
> +        labelHidden={false}
이 prop은 기본값을 false로 두고, optional 프롭으로 해도 좋겠습니당

2024-05-25 14:49 UTC, 365kim commented on src/recoil/coupon/selector.ts
> +          if (!isCouponApplicable) return 0;
오 `selectedCoupons`이면서 `!isCouponApplicable`인 경우는 언제일까요?

2024-05-25 15:00 UTC, 365kim requested changes
낙타, 안녕하세요 :) 
2단계 작업 잘봤습니다

충격 감동 실화) 만들어주신 장바구니 아이템 추가버튼 너무 잘썼습니다 🥹 1단계 마지막 코멘트도 반영해주시고, 작업 중간중간에도 적극적으로 리팩토링 진행해주신 것으로 확인했어요 💯 각 컴포넌트를 적절한 크기로 잘 나누어 구현해주셔서 자연스레 관심사가 잘 분리되어보이며, 쿠폰 로직도 잘 구현해주신 것으로 확인했습니다. 소소한 코멘트를 남기긴했지만 전반적으로 완성도 있게 잘 구현해주신 것 같아요 👍 

코멘트 확인해보시고 반영 완료되시면 리뷰 재요청 부탁드릴게요
수고하셨습니다 👏👏👏

2024-05-26 08:08 UTC, Largopie reviewed
안녕하세요 하루!! 반영 사항 빠르게 반영 완료했습니다 :) 

질문 주셨던 내용은 모두 코멘트에 답변 남겨두었습니다!!
추가적인 코멘트 얼마든지 남겨도 환영 환영입니다!! 🚀🐫🚀🐫

변경 사항이 하나 추가적으로 있다면,
피그마 디자인 시안의 모달의 크기는 382px인데, 기존에 만들었던 모달 컴포넌트 라이브러리에는 'small', 'medium', 'large' 세가지 속성밖에 존재하지 않아서, 숫자를 입력하면 px로 반영될 수 있도록 수정해서 반영했습니다 :)

늘 그렇듯 잘 부탁드립니다 :)

2024-05-26 08:08 UTC, Largopie commented on src/components/Cart/CartProducts/AllChecked.tsx
> +        labelHidden={false}
좋은 것 같습니다!! 필요할 때만 true를 해주면 되겠네요!! 🐫

2024-05-26 14:22 UTC, 365kim commented on src/components/CartConfirm/OrderResult.tsx
> +        <Receipt description="쿠폰 할인 금액" price={-totalDiscountAmount} />
오호 확실히 이 라인은 할인금액 라인이구나 하는 인지를 할 수 있겠군요.👍

제 개인적으로 경험해보지 못한 표기법이라서 제안드려보았어요. 수학에서 -0과 0을 구분하기도 하고요. 이것은 기획의 영역으로 보여서 그냥 넘어가주셔도 좋겠습니다.

2024-05-26 14:25 UTC, 365kim commented on src/components/Coupon/CouponItem.tsx
> +      if (selectedCoupons.includes(coupon.code))
아하, 이렇게 쓰는 것은 처음봐서 궁금해서 질문드렸어요. 복잡한 코드가 아니라 코드 파악에 어려움은 없었찌만, 뒤에 다른 코드를 추가해주실 계획이 있으시려나 하는 생각도 살짝 들었습니다. 🤔

2024-05-26 14:32 UTC, 365kim commented on src/components/common/Title.tsx
> +  return <h1 css={title}>{children}</h1>;
좋은 결론이라고 생각합니다 👍

이미 여러 사례를 보며 느끼셨겠지만, 어느 부분에서 웹 표준을 준수하지 못하는 사례도 종종 볼 수 있습니다. 표준을 잘 준수한 경우는 참조를 하고, 표준에 어긋난 경우는 어떤 점에서 개선해볼 수 있을지 고민해보는 정도로 마무리하면 좋을 것 같네요 :)

2024-05-27 02:10 UTC, Largopie commented on src/components/Coupon/CouponItem.tsx
> +      if (selectedCoupons.includes(coupon.code))
아하 확실히 그렇게 느껴질 수도 있을 것 같네요!

생각해보니, 쿠폰은 체크 해제할 때, 선택되지 않았을 리가 없으니, 이렇게 if문을 제거해주어도 괜찮겠네요..!


```suggestion
    } else {
      setSelectedCoupons(selectedCoupons.filter((code) => coupon.code !== code));
```

2024-05-27 02:10 UTC, Largopie commented on src/components/common/Title.tsx
> +  return <h1 css={title}>{children}</h1>;
단순 궁금) 하루가 생각하시기에 웹 표준을 준수하는 이유는 개발자의 가독성 및 생산성 향상의 측면이 클까요, 사용자의 관점(seo, 스크린리더 등)에서 가져가는 이점이 클까요?

웹 표준이 지켜지지 않은 여러 사이트들도 굉장히 많고, 나름대로 사용자가 사용하는데 큰 영향이 없어보여서 갑자기 궁금증이 생겼습니다 :) 🐫

2024-05-27 02:10 UTC, Largopie commented on src/utils/format.ts
> +export const dateFormat = (targetDate: Date) => {
> 유틸함수의 반환값을 주석만 보고 빠르게 예상할 수 있도록 작성해도 좋겠습니다.

이럴 때 활용해주어도 직관적으로 파악하는데 많은 도움이될 것 같네요!! 감사합니다 :)

2024-05-27 14:06 UTC, 365kim commented on src/utils/format.ts
> +/** @returns 시간을 '오전 11시 12분 13초'의 형태로 포맷 */
👍

<img width="395" alt="image" src="https://github.com/woowacourse/react-shopping-cart/assets/60066472/98a33635-613b-483f-9fb2-71c37a144e49">

2024-05-27 14:07 UTC, 365kim commented on src/utils/validations.ts
> +export const isCouponActive = (coupon: Coupon) => {
바뀐 이름 좋네용 :) 반영 감사합니다 ☺️

2024-05-27 14:08 UTC, 365kim commented on src/layouts/GeneralLayout.tsx
> +export default function GeneralLayout() {
Chat GPT 를 매우 잘 활용하시네용 👏

2024-05-27 14:32 UTC, Largopie commented on src/components/CartItem/CartItemHeaderSection.tsx
>          labelHidden={true}
이런 방법을 몰랐네요...! 👍 바로 반영했습니다 :)
읽고 나서 해당 코멘트 위치를 못찾아서 답변을 못남겼네요 ㅠㅜ

2024-05-27 14:37 UTC, 365kim commented on src/components/common/Title.tsx
> +  return <h1 css={title}>{children}</h1>;
제 생각에는 말씀해주신 측면 모두 중요해 보입니다.

스펙을 동일하게 이해하고 개발한다면 자연스럽게 코드 가독성에도 도움이 되겠습니다. SEO에도 매우x10 큰 영향을 미치지요.

그런데 잘 지켜지지 않은 사례들을 보면 '굳이' 라는 생각이 들 수도 있을 것 같아요. 저도 아래 사실을 알기 전까지는 그렇게 생각했던 것 같습니다.

2007년 장애인차별금지법 제정 후, 웹에서 제공하는 전자정보를 장애 환경에 상관없이 동등한 수준으로 제공해야 한다는 법이 시행되었습니다. 국가에서 웹접근성지침(KWCAG)을 발표하기도 했습니다.

누군가에게 너무나 당연한 것이, 또 누군가에게는 당연하지 않은 것이 될 수 있지요.
모두에게 당연한 환경을 제공하는 것은, 법으로 제정되어야 할 만큼 어려운 일이었나봅니다.

저는 웹 표준을 준수하는 것은 필수이지, 선택이라고 생각하지 않습니다.

2024-05-27 15:12 UTC, Largopie commented on src/components/common/Title.tsx
> +  return <h1 css={title}>{children}</h1>;
하루가 집중적으로 label, 스크린리더에 대해서 깊게 고민해주시고 답변을 달아주는 이유가 있었네요..
정말 감사합니다. 하루 리뷰 덕분에 웹 표준 준수에 대해서 앞으로도 지속적으로 고민하고 잘 지킬 수 있도록 개선해나갈 수 있을 것 같아요!

🐫🐫🐫🐫🐫

2024-05-27 15:12 UTC, Largopie commented on README.md
> +  - [x] 테스트
✌️

2024-05-27 15:22 UTC, merged