[2단계 - 장바구니 미션] 파란(안영훈) 미션 제출합니다.
woowacourse/react-shopping-cart pull request #301
Opened 2024-05-25 17:26 UTC by greetings1012

step2도 잘 부탁드립니다, 카일!

# 🚀 프로젝트 실행 방법

.env 파일을 파일 최상위에 저장
npm i
npm run dev

.env 파일은 슬랙 DM으로 드릴게요!

또한 장바구니 상품 추가를 프로젝트 내에서 할 수 없어요 🥲
장바구니가 비었을 때 DM 보내주시면 최대한 빠르게 다시 채워넣도록 할게요!

## 배포 링크

[vercel 배포 링크](https://react-shopping-cart-mu-one.vercel.app/)
이전처럼 사이트 들어간 후 주소창 왼쪽의 설정 버튼 -> 사이트 설정에서 안전하지 않은 콘텐츠를 허용해주시면 감사하겠습니다!

## 🧪 테스트 확인

npm run test

## 😄 신경 쓴 부분

카일이 1단계 때

> atoms, selectors 두 레이어로만 나누게 되면, 모든 리코일 상태가 이 두 파일에만 선언될텐데 이렇게 되면 파일이 금방 비대해지지 않을까요? 상태를 모아둔 파일도 긴밀한 관계를 가진 상태끼리 분류해두면 어떨까요?

라고 피드백 주신 부분을 고심했어요.
결과적으로 recoil 폴더를 따로 생성해 그 안에서 관심사별로 폴더를 분리해 구현하는 구조를 선택했습니다!

또한 쿠폰과 배송비를 계산하는 로직을 커스텀 훅으로 구현해 분리했어요.

각 훅과 아톰, 셀렉터도 가능한 모든 케이스를 테스트하도록 설계하려고 노력했습니다!

## 😭 놓친 부분

추가된 요구사항 중

> 결제하기 버튼을 누를 때 /orders api를 사용한다.
> 결제 금액 확인 페이지로 이동 후, 다시 장바구니로 돌아오면 장바구니에서 주문한 상품은 사라진다.
> 장바구니로 돌아왔을 때 모든 선택 상태는 초기화한다.
> 쿠폰은 사라지지 않습니다.

이 있어 어디에서 선택 상태를 초기화할 지를 많이 고민했는데, 주소창에 직접 링크를 수정해 이동하는 경우까지 고려하다보니 코드가 조금 복잡해진 것 같아요.
코드에 다시 정확한 부분과 그에 따른 질문을 달아놓을게요!

## 🌲 파일 구조

📦src
 ┣ 📂apis
 ┃ ┗ 📜index.ts
 ┣ 📂assets
 ┃ ┣ 📂images
 ┃ ┃ ┣ 📂CheckIcon
 ┃ ┃ ┃ ┣ 📜CheckedIcon.svg
 ┃ ┃ ┃ ┗ 📜UncheckedIcon.svg
 ┃ ┃ ┣ 📜EmptyCart.png
 ┃ ┃ ┣ 📜InfoIcon.svg
 ┃ ┃ ┣ 📜LeftArrow.svg
 ┃ ┃ ┣ 📜MainLogo.svg
 ┃ ┃ ┣ 📜MinusIcon.svg
 ┃ ┃ ┗ 📜PlusIcon.svg
 ┃ ┗ 📜index.ts
 ┣ 📂components
 ┃ ┣ 📂Button
 ┃ ┃ ┣ 📂CheckButton
 ┃ ┃ ┃ ┣ 📜CheckButton.style.tsx
 ┃ ┃ ┃ ┗ 📜CheckButton.tsx
 ┃ ┃ ┣ 📂ShowModalButton
 ┃ ┃ ┃ ┣ 📜ShowModalButton.style.tsx
 ┃ ┃ ┃ ┗ 📜ShowModalButton.tsx
 ┃ ┃ ┗ 📂SubmitButton
 ┃ ┃ ┃ ┣ 📜SubmitButton.style.tsx
 ┃ ┃ ┃ ┗ 📜SubmitButton.tsx
 ┃ ┣ 📂Container
 ┃ ┃ ┣ 📂CartItemContainer
 ┃ ┃ ┃ ┣ 📜CartItemContainer.style.tsx
 ┃ ┃ ┃ ┗ 📜CartItemContainer.tsx
 ┃ ┃ ┣ 📂CouponContainer
 ┃ ┃ ┃ ┣ 📜CouponContainer.style.tsx
 ┃ ┃ ┃ ┗ 📜CouponContainer.tsx
 ┃ ┃ ┣ 📂DeliveryInfoContainer
 ┃ ┃ ┃ ┣ 📜DeliveryInfoContainer.style.tsx
 ┃ ┃ ┃ ┗ 📜DeliveryInfoContainer.tsx
 ┃ ┃ ┣ 📂NotificationContainer
 ┃ ┃ ┃ ┣ 📜NotificationContainer.style.tsx
 ┃ ┃ ┃ ┗ 📜NotificationContainer.tsx
 ┃ ┃ ┣ 📂PriceContainer
 ┃ ┃ ┃ ┣ 📜PriceContainer.style.tsx
 ┃ ┃ ┃ ┗ 📜PriceContainer.tsx
 ┃ ┃ ┣ 📂QuantityContainer
 ┃ ┃ ┃ ┣ 📜QuantityContainer.style.tsx
 ┃ ┃ ┃ ┗ 📜QuantityContainer.tsx
 ┃ ┃ ┣ 📂TitleContainer
 ┃ ┃ ┃ ┣ 📜TitleContainer.style.tsx
 ┃ ┃ ┃ ┗ 📜TitleContainer.tsx
 ┃ ┃ ┗ 📂TotalPriceContainer
 ┃ ┃ ┃ ┣ 📜TotalPriceContainer.style.tsx
 ┃ ┃ ┃ ┗ 📜TotalPriceContainer.tsx
 ┃ ┣ 📂Header
 ┃ ┃ ┣ 📜Header.style.tsx
 ┃ ┃ ┗ 📜Header.tsx
 ┃ ┗ 📂List
 ┃ ┃ ┣ 📂CartItemList
 ┃ ┃ ┃ ┣ 📜CartItemList.style.tsx
 ┃ ┃ ┃ ┗ 📜CartItemList.tsx
 ┃ ┃ ┣ 📂CouponList
 ┃ ┃ ┃ ┣ 📜CouponList.style.tsx
 ┃ ┃ ┃ ┗ 📜CouponList.tsx
 ┃ ┃ ┗ 📂DeliveryInfoList
 ┃ ┃ ┃ ┣ 📜DeliveryInfoList.style.tsx
 ┃ ┃ ┃ ┗ 📜DeliveryInfoList.tsx
 ┣ 📂constants
 ┃ ┣ 📜DELIVERY_INFOS.ts
 ┃ ┣ 📜MESSAGES.ts
 ┃ ┗ 📜PATHS.ts
 ┣ 📂hooks
 ┃ ┣ 📜useCalculateCouponDiscount.test.tsx
 ┃ ┣ 📜useCalculateCouponDiscount.ts
 ┃ ┣ 📜useCalculateDeliveryFee.test.tsx
 ┃ ┣ 📜useCalculateDeliveryFee.ts
 ┃ ┣ 📜useCouponCheck.test.tsx
 ┃ ┣ 📜useCouponCheck.ts
 ┃ ┣ 📜useToggleModal.test.ts
 ┃ ┗ 📜useToggleModal.ts
 ┣ 📂mockData
 ┃ ┣ 📜cartItemListMockData.ts
 ┃ ┣ 📜couponListMockData.ts
 ┃ ┗ 📜selectedDeliveryListMockData.ts
 ┣ 📂modals
 ┃ ┗ 📂ApplyCouponModal
 ┃ ┃ ┣ 📜ApplyCouponModal.style.tsx
 ┃ ┃ ┗ 📜ApplyCouponModal.tsx
 ┣ 📂pages
 ┃ ┣ 📂ErrorPage
 ┃ ┃ ┣ 📜ErrorPage.style.tsx
 ┃ ┃ ┗ 📜ErrorPage.tsx
 ┃ ┣ 📂OrderConfirmPage
 ┃ ┃ ┣ 📜OrderConfirmPage.style.tsx
 ┃ ┃ ┗ 📜OrderConfirmPage.tsx
 ┃ ┣ 📂PaymentConfirmPage
 ┃ ┃ ┣ 📜PaymentConfirmPage.style.tsx
 ┃ ┃ ┗ 📜PaymentConfirmPage.tsx
 ┃ ┗ 📂ShoppingCartPage
 ┃ ┃ ┣ 📜ShoppingCartPage.style.tsx
 ┃ ┃ ┗ 📜ShoppingCartPage.tsx
 ┣ 📂recoil
 ┃ ┣ 📂ApplyCouponModal
 ┃ ┃ ┗ 📂atoms
 ┃ ┃ ┃ ┣ 📜applyCouponModalState.test.ts
 ┃ ┃ ┃ ┗ 📜applyCouponModalState.ts
 ┃ ┣ 📂CartItem
 ┃ ┃ ┣ 📂atoms
 ┃ ┃ ┃ ┣ 📜selectedCartItemListState.test.ts
 ┃ ┃ ┃ ┣ 📜selectedCartItemListState.ts
 ┃ ┃ ┃ ┣ 📜selectedCartItemTotalPriceState.test.ts
 ┃ ┃ ┃ ┗ 📜selectedCartItemTotalPriceState.ts
 ┃ ┃ ┗ 📂selectors
 ┃ ┃ ┃ ┣ 📜selectedCartItemListSelector.test.ts
 ┃ ┃ ┃ ┣ 📜selectedCartItemListSelector.ts
 ┃ ┃ ┃ ┣ 📜selectedCartItemListTotalCountSelector.test.ts
 ┃ ┃ ┃ ┣ 📜selectedCartItemListTotalCountSelector.ts
 ┃ ┃ ┃ ┣ 📜selectedCartItemListTotalPriceSelector.test.ts
 ┃ ┃ ┃ ┗ 📜selectedCartItemListTotalPriceSelector.ts
 ┃ ┣ 📂Coupon
 ┃ ┃ ┣ 📂atoms
 ┃ ┃ ┃ ┣ 📜selectedCouponListState.test.ts
 ┃ ┃ ┃ ┣ 📜selectedCouponListState.ts
 ┃ ┃ ┃ ┣ 📜selectedCouponTotalDicsountState.test.ts
 ┃ ┃ ┃ ┗ 📜selectedCouponTotalDiscountState.ts
 ┃ ┃ ┗ 📂selectors
 ┃ ┃ ┃ ┣ 📜selectedCouponListSelector.test.ts
 ┃ ┃ ┃ ┗ 📜selectedCouponListSelector.ts
 ┃ ┣ 📂DeliveryFee
 ┃ ┃ ┗ 📂atoms
 ┃ ┃ ┃ ┣ 📜deleveryFeeState.test.ts
 ┃ ┃ ┃ ┗ 📜deliveryFeeState.ts
 ┃ ┗ 📂DeliveryInfo
 ┃ ┃ ┣ 📂atoms
 ┃ ┃ ┃ ┣ 📜selectedDeliveryInfoListState.test.ts
 ┃ ┃ ┃ ┗ 📜selectedDeliveryInfoListState.ts
 ┃ ┃ ┗ 📂selectors
 ┃ ┃ ┃ ┣ 📜selectedDeliveryInfoListSelector.test.ts
 ┃ ┃ ┃ ┗ 📜selectedDeliveryInfoListSelector.ts
 ┣ 📂styles
 ┃ ┣ 📜Global.style.tsx
 ┃ ┗ 📜theme.ts
 ┣ 📂types
 ┃ ┣ 📜CartItem.type.ts
 ┃ ┣ 📜Coupon.type.ts
 ┃ ┣ 📜DeliveryInfo.type.ts
 ┃ ┣ 📜Error.type.ts
 ┃ ┗ 📜Product.type.ts
 ┣ 📂utils
 ┃ ┣ 📜auth.ts
 ┃ ┗ 📜formatStrings.ts
 ┣ 📜App.tsx
 ┣ 📜index.css
 ┣ 📜main.tsx
 ┗ 📜vite-env.d.ts

2024-05-25 17:40 UTC, greetings1012 commented on src/pages/ShoppingCartPage/ShoppingCartPage.tsx
> +
선택된 상품 목록을 초기화하기 위해 useEffect를 사용해 cartItemList에 없는 항목이 selectedItemList에 있으면 그 항목을 제거하는 메서드를 구현했어요.
하지만 이 방법은 cartItemList, selectedItemList, setSelectedItemList 세 가지에 의존성을 두고 있어 제가 의도한 것보다 수행되는 횟수가 많고, 화면의 재렌더링을 유발해 다시 모든 데이터들을 처음부터 가져와 성능 저하가 일어날 것 같아요.

2024-05-26 09:34 UTC, igy95 requested changes
안녕하세요 파란~ 주말에도 고생 많으시네요 😀 리뷰 남겨두었으니 코멘트 확인 부탁드리고 질문 주신 부분에 대한 답변도 달아두었으니 핑퐁 이어나가면 좋을 것 같습니다 ㅎㅎ

2024-05-26 09:34 UTC, igy95 commented on src/recoil/ApplyCouponModal/atoms/applyCouponModalState.ts
> +export const applyCouponModalState = atom<boolean>({
boolean type의 상태는 `is-*` prefix를 붙이는 게 어떨까요?

2024-05-26 09:34 UTC, igy95 commented on src/pages/ShoppingCartPage/ShoppingCartPage.tsx
> +
현재 말씀 주신 내용만으로는 어떤 코멘트를 드려야 할지 감이 잘 오질 않습니다 🥲 각각의 상태가 어떤 역할이고 페이지 진입시 상태를 초기화할 때 분기 처리가 필요한 이유 등 기획적인 면에 대한 설명이 보충되어야 할 것 같아요. 그래야 코드 적으로 어떻게 처리할 수 있을지 고민해볼 수 있을 듯 합니다.

만일 기획 사항과 구현 방식이 크게 이질적이지 않다면, 현재 걸어둔 의존성은 크게 문제 없다고 생각합니다.

2024-05-26 09:34 UTC, igy95 commented on src/pages/OrderConfirmPage/OrderConfirmPage.tsx
> +  const isOpen = useRecoilValue(applyCouponModalState);
`applyCouponModalState`는 단순히 모달을 열기 위한 상태로 보이는데, 이것을 전역적으로 관리해야하는 이유가 있을까요?

2024-05-26 09:34 UTC, igy95 commented on src/modals/ApplyCouponModal/ApplyCouponModal.tsx
> +        <NotificationContainer content={`쿠폰은 최대 2개까지 사용할 수 있습니다.`} />
상수 처리 필요하지 않을까요!

2024-05-26 09:34 UTC, igy95 commented on src/modals/ApplyCouponModal/ApplyCouponModal.tsx
> +        <Modal.CancelButton content={`선택된 쿠폰이 없습니다`} onClick={() => {}} />
`onClick`이 비어있는 이유가 있을까요?

2024-05-26 09:34 UTC, igy95 commented on src/hooks/useCalculateDeliveryFee.ts
> +    }, 3000);
`3000`은 무얼 의미하는 값인가요?

2024-05-26 09:34 UTC, igy95 commented on src/constants/DELIVERY_INFOS.ts
> +};
데이터를 선언할 때는 타입 단언보다는 명시적 선언을 권장드립니다. 또한 이 데이터가 추가 배송료가 붙는 지역에 대한 정보를 가진 데이터임을 알 수 있도록 이름의 구체화가 좀 더 필요하지 않을까 싶습니다. 

```suggestion
export const DELIVERY_INFOS: Record<string, DeliveryInfo> = {
  ISLANDS_AND_MOUNTAINS: { title: '제주도 및 도서 산간 지역', surcharge: 3000 } ,
};
```

2024-05-26 09:34 UTC, igy95 commented on src/hooks/useCalculateCouponDiscount.ts
> +    switch (coupon.discountType) {
`coupon.discountType`은 서버에서 정한 스펙인가요? 맞다면 `discountType`에 대한 별도의 타입 선언을 추가하여 각 타입이 의미하는 바를 주석으로 달아두면 좋을 것 같아요!

2024-05-26 09:34 UTC, igy95 commented on src/App.tsx
> +      errorElement: <ErrorPage error={CART_ITEM_ERROR_MESSAGE.FETCH_CART_ITEMS} />,
어떠한 에러 페이지에서 특정 에러 타입만 발생할 것이라는 걸 어떻게 보장할 수 있을까요?

2024-05-26 09:34 UTC, igy95 commented on src/components/Container/CartItemContainer/CartItemContainer.tsx
> +  const [isSelected, setIsSelected] = useRecoilState(selectedCartItemListSelector(item));
상태를 제공하는 쪽의 이름과 반환받은 상태를 선언한 쪽의 이름이 매칭되질 않는 듯 합니다. 그리고 이 상태를 전역으로 두어야했던 이유도 궁금하네요!

2024-05-26 09:34 UTC, igy95 commented on src/pages/ShoppingCartPage/ShoppingCartPage.tsx
> +
+ 추가 코멘트

>결제하기 버튼을 누를 때 /orders api를 사용한다.
>결제 금액 확인 페이지로 이동 후, 다시 장바구니로 돌아오면 장바구니에서 주문한 상품은 사라진다.
>장바구니로 돌아왔을 때 모든 선택 상태는 초기화한다.
>쿠폰은 사라지지 않습니다.

혹시 본문에 써주신 이 기획이 맞다면, 장바구니에서 주문한 상품 초기화 로직은 결제 금액 확인 페이지에서 /orders api 호출 시점에 진행 후 링크 이동을 해주면 되지 않을까요?

2024-05-27 08:46 UTC, greetings1012 commented on src/types/Error.type.ts
지금과 같이 types를 한 곳에 몰아 선언한 구조에서는 굳이 types라고 따로 명시할 필요가 없겠네요!
수정했습니다 😄

2024-05-27 08:49 UTC, greetings1012 commented on src/types/Error.type.ts
> +export type ErrorType = keyof typeof CART_ITEM_ERROR_MESSAGE;
step1 때 카트에 대해서만 구현하다 보니 상수명을 CART_ITEM_ERROR_MESSAGE로 지어놓고 바꾸는 것을 잊고 있었네요... 수정했습니다!

2024-05-27 08:52 UTC, greetings1012 commented on src/recoil/ApplyCouponModal/atoms/applyCouponModalState.ts
> +export const applyCouponModalState = atom<boolean>({
수정했습니다!

2024-05-27 08:53 UTC, greetings1012 commented on src/pages/OrderConfirmPage/OrderConfirmPage.tsx
> +  const isOpen = useRecoilValue(applyCouponModalState);
같은 모달을 주문 확인 페이지 이외의 다른 페이지에서도 열 수 있도록 하는 구조를 연습해보고 싶어 Recoil을 통해 관리해 보았어요!

2024-05-27 13:52 UTC, greetings1012 commented on src/modals/ApplyCouponModal/ApplyCouponModal.tsx
> +        <Modal.CancelButton content={`선택된 쿠폰이 없습니다`} onClick={() => {}} />
테스트를 위해 이것저것 넣어보다가 지우는 걸 깜빡했네요...
지웠습니다! 😊

2024-05-27 13:56 UTC, greetings1012 commented on src/hooks/useCalculateDeliveryFee.ts
> +    }, 3000);
기본 배송비를 뜻하는 숫자인데, 상수 처리가 필요해 보이네요!
상수 처리했습니다!

2024-05-27 14:13 UTC, greetings1012 commented on src/constants/DELIVERY_INFOS.ts
> +};
타입 선언보다는 단언이 타입 추적과 확인에 훨씬 도움이 되겠네요 😄
타입을 단언해 주었습니다!

상수 이름의 경우에는, 추가 배송비가 붙는 지역 외에도 퀵 배송, (대형 가전 혹은 가구의 경우에는) 방문 설치 등 조금 더 다양한 조건이 붙을 수 있다고 생각해 DELIVERY_INFOS라는 다소 포괄적인 이름을 붙였어요!

이를 고려해 미션 요구사항에서는 제주도 및 도서산간의 조건 하나밖에 없었지만 일부러 객체 모음으로 만들어 관리할 수 있게 구현하기도 했습니다.

2024-05-27 15:18 UTC, greetings1012 commented on src/App.tsx
> +      errorElement: <ErrorPage error={CART_ITEM_ERROR_MESSAGE.FETCH_CART_ITEMS} />,
router의 errorElement가 페이지를 로드할 때에 일어나는 에러만 핸들링하는 것인 줄 알았는데, 
다시 찾아보니 페이지 안에서 일어나는 모든(내부에서 핸들링되지 않은) 에러를 핸들링하는 것이었군요!

각 페이지에서 개별적으로 핸들링되지 않은 에러가 일어났음을 포괄적으로 명시하도록 코드를 수정했습니다! 😀

2024-05-27 15:40 UTC, greetings1012 commented on src/hooks/useCalculateCouponDiscount.ts
> +    switch (coupon.discountType) {
확실히 이름만으로 명확하게 알 수 없는 서버에서 제공하는 값에 대한 정보는 주석으로 달아주는 것이 좋겠네요!

다만 type로 선언하니 값을 불러올 수 없어 const로 선언 후 사용하는 곳에서 불러오게 되었는데,
type라는 이름이 붙어 있음에도 const로 선언하는 것이 옳은 방향일까요?

2024-05-27 15:53 UTC, greetings1012 commented on src/modals/ApplyCouponModal/ApplyCouponModal.tsx
> +        <NotificationContainer content={`쿠폰은 최대 2개까지 사용할 수 있습니다.`} />
최대 쿠폰 개수를 상수처리 해 주었습니다!

Modal의 style의 경우에는 이전 미션에서 제가 만든 Modal 패키지를 사용해 모달을 구현하는 것이 요구사항이었는데,
이전 미션의 모달 요구사항을 유지하면서 이번 미션의 디자인을 강제로 맞추기 위해서 추가한 값이에요.
혹시 이 부분도 상수화가 필요할까요?

2024-05-27 16:22 UTC, greetings1012 commented on src/components/Container/CartItemContainer/CartItemContainer.tsx
> +  const [isSelected, setIsSelected] = useRecoilState(selectedCartItemListSelector(item));
다시 코드를 찬찬히 훑어보니 전혀 전역으로 관리할 필요가 없는 상태였네요!
다음부터는 구현을 완료한 후 필요없는 state를 다시 한번 확인하는 습관을 들이도록 할게요 🥲
만약 전역으로 관리했어야 하는 상태였어도 이름이 isSelectedCartItemSelector 등 boolean값을 전달한다는 것을 밝혔어야 할 것 같아요.

메서드만 따로 hook으로 분리해서 구현했습니다!

2024-05-27 17:12 UTC, greetings1012 commented on src/pages/ShoppingCartPage/ShoppingCartPage.tsx
> +
코멘트가 정말 도움이 많이 되었습니다 😭
제가 처음에 질문드리려고 했던 부분은 

> 결제를 완료한 시점에서 /orders api 호출로 선택된 상품들은 장바구니 목록에서 제거되는데,
> 아직 selectedItemListState에서는 선택된 상품의 배열이 남아있어 제거해야 해요.
> 하지만 결제 금액 페이지에서 selectedItemListState에 종속되는 상품 종류 값, 상품 개수 값, 총 금액 등이 있어
> 주문 확인 페이지에서 결제 금액 확인 페이지로 넘어가는 순간 selectedItemListState를 제거하면 오류가 발생했어요.
> 그래서 어떠한 경로로든 처음 창, 즉 장바구니 창으로 이동하게 되면 selectedItemListState를 초기화하도록 구현했는데,
> 이러한 방식은 이상한 위치에서 억지로 초기화하기 위해 useState를 사용하는 것 같아 의구심이 들었어요.

위와 같은 내용이었어요! 최대한 자세히 풀어 설명드리려고 노력했는데, 의도가 잘 전달되었으면 좋겠어요 😂

이 내용을 계속 고민하던 중, 카일이 추가 코멘트로 남겨주신 부분을 보고 문득 아래와 같은 생각이 들었어요.

> 미션 뿐만 아니라 정말 결제가 되는 서비스를 운영한다고 해도
> 실제로 결제할 항목 정보가 서버로 전송되는 때는 /orders api를 호출하는 시점인데,
> 굳이 결제 금액 페이지에서까지 selectedItemListState를 통해서 정보를 불러올 필요가 있을까?
> 그냥 값 자체만 전달해 주어도 괜찮지 않을까?

그래서 라우터의 state를 넘겨주는 기능을 이용해 값 자체만 결제 금액 확인 페이지로 넘겨주었고, 
selectedItemListState는  /orders api 호출 시점에 바로 초기화시켜 주었습니다!

이렇게 했더니 질문드린 부분에 대한 메서드 자체가 필요 없어지고, 그에 따른 여러 부가적인 값과 함수들도 사라져
결과적으로 코드를 훨씬 깔끔하게 리팩터링 할 수 있었어요.

[refactor: PaymentConfirmPage가 recoil에 의존하지 않도록 구현](https://github.com/woowacourse/react-shopping-cart/pull/301/commits/ecff694c38ece40a08e7b1bd8d1f111a2f7159a5)
위 커밋을 참고해주시면 좋을 것 같아요 😁

카일의 조언 덕분에 훨씬 깔끔한 코드가 되어 기분이 좋아요! 다시 한번 감사합니다 😊

2024-05-28 11:19 UTC, igy95 commented on src/pages/ShoppingCartPage/ShoppingCartPage.tsx
> +
도움이 되었다니 다행입니다 ㅎㅎ 스스로 답을 찾아가신 듯하여 보기 좋네요

2024-05-28 11:23 UTC, igy95 commented on src/pages/OrderConfirmPage/OrderConfirmPage.tsx
> +  const isOpen = useRecoilValue(applyCouponModalState);
넵, 훈련 차원이라면 크게 막을 필요는 없다고 생각합니다. 다만 코드를 작성해보시면서 '현업이라면 어떻게 코드를 관리해야할까?'에 대한 측면도 고려해보시면 좋을 듯 해요. 전역 상태는 말 그대로 여러 컴포넌트에서 동일한 상태를 바라봐야하는 니즈가 있을 때 두는 상태인데, 모달을 열고 닫는 것은 사실 각각의 컴포넌트에서 지역 상태로 관리해도 크게 무리가 없는 상태입니다. 따라서 이러한 상태도 전역으로 끌어올리게 되면, 오히려 전역 상태가 비대해질 수 있는 우려도 무시할 수는 없을 것 같아요.

2024-05-28 11:24 UTC, igy95 commented on src/modals/ApplyCouponModal/ApplyCouponModal.tsx
> +        <NotificationContainer content={`쿠폰은 최대 2개까지 사용할 수 있습니다.`} />
오 아뇨, 이쪽에서 확인해보니 그렇게 오해할 수도 있었겠네요. 제가 의도한 부분은 쿠폰 개수에 한해서였습니다!

2024-05-28 11:26 UTC, igy95 commented on src/constants/DELIVERY_INFOS.ts
> +};
> 타입 선언보다는 단언이 타입 추적과 확인에 훨씬 도움이 되겠네요 😄 타입을 단언해 주었습니다!

제가 말씀 드린 의도는 반대입니다 ㅎㅎ 사실 이 맥락에서는 단언, 선언 둘 다 상관 없지만 잘못 추론되는 타입을 강제 변환하는 목적이 아닌 구현체에 타입을 부여하는 목적에서는 타입 선언이 좀 더 적절할 듯 하여 드린 말씀입니다.

2024-05-28 11:28 UTC, igy95 commented on src/hooks/useCalculateCouponDiscount.ts
> +    switch (coupon.discountType) {
type 자체를 값으로 사용할 수는 없기 때문에 어떠한 데이터에 대해 타입, 값을 모두 사용하고 싶다면 enum 혹은 typeof 연산자로 대응해볼 수 있을 것 같아요.

2024-05-28 11:31 UTC, igy95 commented on src/components/Container/CartItemContainer/CartItemContainer.tsx
> +  const [isSelected, setIsSelected] = useRecoilState(selectedCartItemListSelector(item));
모든 상태를 되도록 전역으로 관리하는 것만이 정답은 아닙니다. 전역 상태는 여러 컴포넌트에서 접근 가능하다는 이점이 있지만, 이를 바꿔 말하면 하나의 컴포넌트에서만 사용되는 경우에 오히려 지역성을 떨어트려 상태와 컴포넌트 간 관계 파악이 어려우며 다른 곳에서 수정 가능하다는 단점이 있을 것 같아요. 따라서 어떠한 상태를 선언할 때 상태가 사용되는 목적을 잘 고려해보시면 좋겠습니다.

2024-05-28 11:31 UTC, igy95 approved these changes
안녕하세요 파란, 코멘트에 대해 답변 달아두었으니 확인 부탁드립니다 ㅎㅎ 미션을 빨리 끝내신 만큼, 남은 기간 동안 찬찬히 학습하신 부분에 대해 정리해보면 좋겠네요! 마지막까지 고생 많으셨습니다 👍

2024-05-28 11:32 UTC, merged