[2단계 - 장바구니 미션] 시모(심호림) 미션 제출합니다.
woowacourse/react-shopping-cart pull request #308
Opened 2024-05-26 13:58 UTC by simorimi

안녕하세요 케빈! 오랜만입니다 하하. 
주말 잘 보내셨나요? 다른 리뷰어의 코드리뷰를 하시느라 주말에도 힘드실 것 같습니다!  
지난번 step1이 가장 늦게 merge가 되어서 사실 이번 step2에 대한 걱정이 많았습니다. 특히나 먼저 하고있는 크루들이 다들 생각할 거리들이 너무 많다며 고민이 많아 보이는 모습들을 보고서는 제 때 제출할 수 있을가에 대한 걱정이 많았네요. 그래도 결국에는 여유를 가지고 이렇게 제출할 수 있어서 많이 기쁩니다. 이번주 주말 상관없이 꽤나 열심히 달려왔는데 개운하게 미션을 마무리 할 수 있어 행복하네요! 그러면 이번 미션을 진행하면서 생각해 본 것들에 대해서 말 전해보겠습니다.

## 📍 step.2 학습 목표
- 복잡한 '파생' 상태 관리
- RTL 테스트 고도화

## 복잡한 '파생' 상태 관리
- 이번 미션의 핵심 두가지가 바로 학습 목표에서 말하는 `파생 상태 관리`와 `RTL 테스트`인데 저의 생각에는 두 목표를 통해 전달하고자 하는 메시지는 동일하다는 생각이 들더군요. `역할의 분리를 잘해서 테스트하기 좋은 상태를 만들어라!` 라고 해석하였습니다. 특히나 basecamp에서 tdd로 미션을 진행하는 모습을 권유하는 것을 보고서는 더욱 확신을 했었네요. 그렇다면 저는 이러한 의도에 잘 하였는가라면 그래도 스스로는 꽤나 만족스럽다고 말 할 수 있겠네요. 쿠폰 할인들 각각에 대한 파생 상태를 가지기도 하며 id에 따라 각 할인 금액만큼을 반환하는 상태 그리고 선택된 쿠폰들을 통해 총 할인 금액을 계산해주는 상태 등 세세하게 분리하려고 노력하였습니다. 그 결과 테스트 코드를 작성하는데에도 크게 어렵지 않았으며 쿠폰 할인을 계산해주는 로직을 작성하는데에도 괜찮았습니다! useCouponApplicability 코드 또한 간결해서 스스로 만족스러웠습니다. 스스로는 만족스럽기는 하나 케빈의 피드백 또한 무척이나 궁금해지네요! 

## RTL 테스트 고도화
- 처음에 validator 부분을 작성할 때는 tdd로 구현하였으나 뒤에 useCouponApplicability 부분부터는 결국 기존의 방식대로 회귀하였네요. 이 부분에 대해서는 아쉬웠으나 시간에 대한 압박이 있다보니 이렇게 된 것 같습니다. 그래도 단위별로 세세하게 역할을 분리하고 해당 역할 하나씩에 대한 테스트를 구현하는 목표는 가까워진 것 같아 좋았네요. 

- 중간에 오류를 만나서 당황하기도 하였는데요. fetch로 불러오는 값에 대해서는 테스트를 할 수 없었던 부분이었습니다. 그래서 중간에 coupons에 대한 상태를 selector에서 atom으로 수정을 해줌에 따라 coupons를 좀 더 유연하게 mock data를 집어넣을 수 있게 하였습니다. 처음에는 coupons의 경우 값을 set하는 경우가 없기에 selector로 구현하였었는데요. test 시 데이터를 초기화 하고 원하는 데이터를 테스트를 하기위해서는 해당 부분에 대해서 set이 가능한 atom으로의 변경이 필요하였습니다. 처음에 이러한 과정을 거치면서 들었던 생각은 테스트를 위한 코드를 작성하는 것이 아닌가라는 생각도 들더라고요. 그래도 확장성을 생각한다면 (예를 들어, 쿠폰이 삭제 되거나 추가되는 경우 새로고침이 아니라 자연스럽게 렌더링을 하려고 한다면) 이러한 방향성으로 가는 것도 나쁘지 않겠다는 생각이 들었습니다!

지난번 좋은 피드백 해주셔서 감사했습니다! 이번에도 코드리뷰를 통해 대화 나눠봅시다. 감사합니다! :)

2024-05-27 13:12 UTC, JeongBin0227 commented
> 이번 미션의 핵심 두가지가 바로 학습 목표에서 말하는 파생 상태 관리와 RTL 테스트인데 저의 생각에는 두 목표를 통해 전달하고자 하는 메시지는 동일하다는 생각이 들더군요. 역할의 분리를 잘해서 테스트하기 좋은 상태를 만들어라! 라고 해석하였습니다. 특히나 basecamp에서 tdd로 미션을 진행하는 모습을 권유하는 것을 보고서는 더욱 확신을 했었네요. 그렇다면 저는 이러한 의도에 잘 하였는가라면 그래도 스스로는 꽤나 만족스럽다고 말 할 수 있겠네요. 쿠폰 할인들 각각에 대한 파생 상태를 가지기도 하며 id에 따라 각 할인 금액만큼을 반환하는 상태 그리고 선택된 쿠폰들을 통해 총 할인 금액을 계산해주는 상태 등 세세하게 분리하려고 노력하였습니다. 그 결과 테스트 코드를 작성하는데에도 크게 어렵지 않았으며 쿠폰 할인을 계산해주는 로직을 작성하는데에도 괜찮았습니다! useCouponApplicability 코드 또한 간결해서 스스로 만족스러웠습니다. 스스로는 만족스럽기는 하나 케빈의 피드백 또한 무척이나 궁금해지네요!

useCouponApplicability 코드를 봤을땐, 쿠폰 적용 가능 여부를 결정하는 로직을 validateCouponApplicability 함수로 분리하여 역할을 잘 나누고 있는거 같아요 👍 그러다 보니 자연스럽게 테스트도 더쉽고 명확하게 가능했다고 생각합니다.

그치만 아쉬운점이 몇가지 있어서 이부분은 코드에 따로 남기겠습니다.

2024-05-27 13:31 UTC, JeongBin0227 commented
> 중간에 오류를 만나서 당황하기도 하였는데요. fetch로 불러오는 값에 대해서는 테스트를 할 수 없었던 부분이었습니다. 그래서 중간에 coupons에 대한 상태를 selector에서 atom으로 수정을 해줌에 따라 coupons를 좀 더 유연하게 mock data를 집어넣을 수 있게 하였습니다. 처음에는 coupons의 경우 값을 set하는 경우가 없기에 selector로 구현하였었는데요. test 시 데이터를 초기화 하고 원하는 데이터를 테스트를 하기위해서는 해당 부분에 대해서 set이 가능한 atom으로의 변경이 필요하였습니다. 처음에 이러한 과정을 거치면서 들었던 생각은 테스트를 위한 코드를 작성하는 것이 아닌가라는 생각도 들더라고요. 그래도 확장성을 생각한다면 (예를 들어, 쿠폰이 삭제 되거나 추가되는 경우 새로고침이 아니라 자연스럽게 렌더링을 하려고 한다면) 이러한 방향성으로 가는 것도 나쁘지 않겠다는 생각이 들었습니다!

coupons 상태를 selector에서 atom으로 변경한 것은 좋은 결정인거 같아요. 왜냐하면 테스트 환경에서 더 쉽게 초기화하고 원하는 데이터로 커스터함하기 쉬우니까요. 처음에 다들 테스트를 위한 코드를 작성한다고 많이 생각하는데 결국 테스트 하기 쉬운 코드가 좋은 코드이고 많은 역할을 하지 않게 잘 나눈 함수라고 생각합니다.
추가로 테스트 환경을 설정할 때, 가능한 한 실제 환경과 유사하게 구성하는 것이 좋습니다. 테스트 목적이기도 하고 이를 통해 예상치 못한 버그를 미리 발견할 수 있어요. 그리고 fetch 요청과 같은 비동기 작업을 테스트할 때는 msw(Mock Service Worker)와 같은 도구를 사용하여 네트워크 요청을 모킹하는 것도 좋은 방법입니당

2024-05-27 13:43 UTC, JeongBin0227 requested changes
안녕하세요! 시모!

시모의 우려와는 달리 너무 잘 작성해주셔서 감사합니다! 시모가 빨리 제출해주셔서 여유롭게 확인했습니다 👍 시모의 고민포인트와 미션에 맞추어 1차 리뷰는 달았습니다! 드린 코멘트에 대해서 이해안되는 부분있으면 편하게 다시 질문주세요~

2단계 미션하느라 고생많으셨어요~ 💯

2024-05-27 13:43 UTC, JeongBin0227 commented on src/hooks/useCouponApplicability.ts
> +  }, [selectedCoupons]);
여기 의존성 기준이 있을까요? selectedCoupons 만 해놔서 궁금합니다.

2024-05-27 13:43 UTC, JeongBin0227 commented on src/hooks/useCouponApplicability.ts
> +  }, [selectedCoupons]);
setIsCouponApplicable 여러번 호출했는데, 이런식으로도 바꿀수 있겠네요.

```
useEffect(() => {
    let applicable = validateCouponApplicability(coupon, totalOrderAmount);

    if (coupon.code === 'BOGO' && applicableBOGOCartItems.length === 0) {
      applicable = false;
    }

    if (selectedCoupons.length === 2 && !selectedCoupons.includes(coupon)) {
      applicable = false;
    }

    setIsCouponApplicable(applicable);
  }, [selectedCoupons]);
```

2024-05-27 13:43 UTC, JeongBin0227 commented on src/hooks/useCouponApplicability.ts
> +  }, [selectedCoupons]);
되도록 매직 넘버는 상수화 해주는게 좋아요

2024-05-27 13:43 UTC, JeongBin0227 commented on src/test/useCouponApplicability.test.tsx
> +});
전체적으로 각 테스트가 무엇을 검증하는지 명확하게 설명되어 있어서 좋은거 같아요

2024-05-27 13:43 UTC, JeongBin0227 commented on src/test/useCouponApplicability.test.tsx
> +});
상태 초기화도 신경을 많이 쓰셨는지, RecoilRoot의 initializeState를 사용하여 초기 상태를 설정하는 방식이 좋고, 각각의 상태를 모킹 데이터로 설정하여 테스트가 독립적으로 동작하도록 보장하도록 의도하신거 라면 👍 
beforeAll과 afterAll을 통해 타이머를 관리하는 점도 좋네요~

2024-05-27 13:43 UTC, JeongBin0227 commented on src/test/useCouponApplicability.test.tsx
> +});
쿠폰 코드가 유효하지 않은 경우의 테스트도 있었으면 더 좋을거 같아요

2024-05-27 13:43 UTC, JeongBin0227 commented on src/api/fetch.ts
> +};
fetchWithPayload 와 fetchWithoutPayload 의 Props 가 달라서 fetchWithoutPayload 를 구분시켜주면 더 좋을거 같아요.

2024-05-27 13:43 UTC, JeongBin0227 commented on src/components/ApplyingCouponModal/ApplyingCouponModal.tsx
> +      <>
요 Fragment는 필요없어 보이네요

2024-05-27 13:43 UTC, JeongBin0227 commented on src/components/ApplyingCouponModal/ApplyingCouponModal.tsx
> +export default ApplyingCouponModal;
이 정도는 괜찮을 수 있지만, 파일이 커진다면 Modal 내의 BackDrop, Container, Header, Content, ButtonContainer, Button 등을 별도의 컴포넌트로 분리해도 좋겠네여

2024-05-30 13:55 UTC, simorimi commented on src/components/ApplyingCouponModal/ApplyingCouponModal.tsx
> +export default ApplyingCouponModal;
아무래도 선언적으로 코드를 짜는 것이 의미 전달(가독성)에 더 도움이 될 것 같군요! 좋은 피드백 감사합니다! 궁금한게 있는데 그렇다면 해당 코드의 경우 module을 작성할 때 호출의 편리성을 위해서 modal 합성컴포넌트를 통해서 작성했습니다. 그렇다면 만약 이렇게 각 컴포넌트로 분리한다면 해당 컴포넌트 마다 modal을 호출한 다음 . 접근법으로 필요한 부분에 대해서 접근하나요? 아니면 modla module을 작성할 때 태초에 합성 컴포넌트 보다는 각각을 분리해서 호출하는 방향이 훨씬 나을까요? 개인적인 생각에는 전부 modal을 호출하는 것이 조금 어색한 느낌이 들어서 질문을 드립니다!

2024-05-30 14:10 UTC, simorimi commented on src/api/fetch.ts
> +};
해당 props를 구분시켜주면 더 좋을 것 같다는 의견으로 보이는데 혹시 맞을까요?  payload를 optional로 쓰지 않고 각각의 props를 분리해달라는 의견으로 보입니다! 아마 without payload의 경우 payload를 전혀 받을 일이 없기에 그렇게 말씀 주신걸로 보이는데 맞을까요? 해당 피드백 반영했습니다!

2024-05-30 14:59 UTC, simorimi commented on src/hooks/useCouponApplicability.ts
> +  }, [selectedCoupons]);
1) 의존성의 기준이라기보다는 제가 의도한 바는 최초의 경우 selectedcoupons 이전의 것들에 대해서 유효성을 검증하고 selectedCoupons가 변화할 떄 맨 마지막 것 까지 작동하도록 의도했습니다. 사실 코드의 경우 불필요한 작업을 줄이는 것이 최선이나 코드를 짧게 하고자 이렇게 의도했습니다! 현재 코드를 
```
 useEffect(() => {
    setIsCouponApplicable(
      validateCouponApplicability(coupon, totalOrderAmount),
    );

    const inapplicableBogo =
      applicableBOGOCartItems.length === CONDITION.noneApplicableBOGO;

    if (coupon.code === 'BOGO' && inapplicableBogo) {
      setIsCouponApplicable(() => false);
    }
  }, []);

  useEffect(() => {
    if (
      selectedCoupons.length === CONDITION.maxSelectedCoupons &&
      !selectedCoupons.includes(coupon)
    ) {
      setIsCouponApplicable(() => false);
    }
  }, [selectedCoupons]);
```
부분과 같이 명확하게 동작하도록 수정해보았습니다! 좋은 피드백 감사합니다 :)
2) 이 과정을 밟으면서 let 을 사용하는 것에 대해서 경계하는 것을 익히 들어왔던지라 이 방법에 대해서는 제쳐두고 고려를 했던 것 같습니다. 해당 코드의 경우 let이 크게 예측이 불가능한 범위도 아니라고는 생각하는데 케빈의 경우는 let을 사용하는 것이 set을 통해 렌더링을 반복하는 것 보다 낫다고 생각하셨던 것인지 의도가 궁금합니다! 아마 이러한 피드백을 주신 이유가 set을 하는 경우 해당 상태와 관련된 것들이 제 랜더링 되기에 불필요한 랜더링을 줄이기위하여 이렇게 주신 것으로 의도가 보입니다! 
3) 이 부분에 대해서 제가 놓쳤군요! 해당 부분에 대해서 직관적으로 의미전달이 힘들어 보이네요 좋은 피드백 감사합니다 :)

2024-05-31 01:44 UTC, JeongBin0227 commented on src/api/fetch.ts
> +};
네 맞습니다 의도대로 잘해주신거 같아요!

2024-05-31 01:51 UTC, JeongBin0227 commented on src/components/ApplyingCouponModal/ApplyingCouponModal.tsx
> +export default ApplyingCouponModal;
합성 컴포넌트를 사용하는 것과 각각의 컴포넌트를 개별적으로 호출하는 것 모두 장단점이 있다고 생각합니다 

간단하게 합성 컴포넌트 사용은 재사용성이 좋고, 어떤 컴포넌트 어떤 역할을 하는지 분명하다고 생각하고 묘듈화가 잘되어있어 쉽게 조합하고 더 복잡한 UI를 만들수 있다고 생각해요. 하지만 컴포넌트 간의 의존성이 증가하여 수정사항이 생기면 변경사항이 많아질수도 있어요. 개별 컴포넌트를 사용하면 컴포넌트가 단순하게 됩니다 그러다 보니 독립성은 커지지만, 코드 중복이나, 커스텀 면에서 확장성이 떨어진다고 생각해요
여기서 결국 중요한건 각 컴포넌트가 하나의 책임만 가지도록 즉, 단일 책임 원칙을 따르도록 설계하는것이 가장 중요합니당

제가 너무 장황하게 얘기했는데 정리하면
합성 컴포넌트는 복잡한 UI나 로직을 캡슐화하여 재사용성을 높이고, 코드의 중복을 줄이는 데 유용하고, 개별 컴포넌트는 단일 책임 원칙을 쉽게 지킬수 있어서, 각 컴포넌트가 독립적으로 동작하도록 설계할 때 유용합니다.

이런 측면에서 모달은 확장성이 좋아야하고 복잡한 UI라고 생각해서 합성 컴포넌트를 제안드렸습니다

2024-06-03 05:13 UTC, merged