[2단계 - 장바구니 미션] 제이드(전세영) 미션 제출합니다.
woowacourse/react-shopping-cart pull request #323
Opened 2024-05-27 08:55 UTC by skiende74

안녕하세요 브콜 !
이번에 장바구니 미션 2단계를 완료하여 제출합니다.

이번에 테스트를 RTL에서 snapshot방식으로 바꾸었습니다.
recoil 공식문서에서 안내하고 있는 방식인 점과
renderHook으로 렌더할 필요 없이 jest(node) 환경에서 테스트가 가능해 좋다고 판단하였습니다.

카트의 상태구현은 크게 바뀐 건 없지만, snapshot방식으로 테스트를 새로작성하는 김에
다시 처음부터 구현하였습니다. 약간 간결해졌다고 생각합니다.

### 신경쓴 것
recoil의 selector는 잘 활용한다면, 커스텀훅을 대체할 수 있다고 생각하였습니다.
그래서 이번 미션은 모두 selector를 활용하여 로직을 구현하였습니다.
그 외 view에 존재할만한 로직들도 전부 selector로 구현하고, view에서는 가져다 쓰는 방향으로만 하였습니다.

### step1때 하던 것

2024-05-28 17:24 UTC, Tanney-102 requested changes
안녕하세요 제이드~
두번째 미션까지 진행하느라 고생많으셨습니다!
selector를 아주 촘촘하게 작성해주셨네요.
도메인에 따라 잘 나눠 작성해주셔서 상태 설계를 이해하기 좋았습니다!
apiClient 관련 에러처리도 반영해주셔서 좋네요 👍 
몇가지 코멘트 달아두었으니 확인 부탁드려요!

2024-05-28 17:24 UTC, Tanney-102 commented on src/types/Coupon.ts
> +type DateType = `${number}-${number}-${number}`;
👍

2024-05-28 17:24 UTC, Tanney-102 commented on src/recoil/orderSummaryState.ts
> +});
selector를 깔쌈하게 잘 쓰시네요 💯

2024-05-28 17:24 UTC, Tanney-102 commented on src/recoil/coupon/validateCouponApplicability.ts
> +  expirationDate: (coupon, get) => new Date(coupon.expirationDate) >= new Date(),
테스트 용이성 측면에서도 그렇고 재사용 측면에서도 현재 시간을 의마하는 Date 객체는 인자로 전달받으면 어떨까요?
유틸성이 강할 수록 이러한 사이드 이펙트는 밖으로 빼는 것이 좋습니다.

2024-05-28 17:24 UTC, Tanney-102 commented on src/recoil/coupon/couponState.ts
> +      get(fetchCouponListSelector).find((coupon) => coupon.id === id),
select 할 때마다 순회하는 것도 뭐 나쁘지는 않지만 id기반의 조회가 필요하다면 애초에 객체형태로 상태를 관리해도 좋을 것 같아요.

```ts
{ [coupon.id]: coupon }
```

2024-05-28 17:24 UTC, Tanney-102 commented on src/recoil/cartItemState.ts
> +  },
cart item을 선택했는지 여부까지 전역으로 관리되어야 하나요~?

2024-05-28 17:24 UTC, Tanney-102 commented on src/pages/OrderConfirmationPage.tsx
> +    onConfirm: () => {},
여기 함수들은 추가될 예정인가요?

2024-05-28 17:24 UTC, Tanney-102 commented on src/pages/CartPage.tsx
> +  addCartItem(21);
오 이친구들은 무엇을 위한 함수 호출인가요? 매번 페이지가 렌더될 때마다 호출되어도 괜찮은가요?

2024-06-02 15:05 UTC, skiende74 commented on src/pages/CartPage.tsx
> +  addCartItem(21);
테스트하시기 좋게 카트아이템추가하고 뺀다는 게, 
빼고 나서 미처 커밋하지 못했네요....ㅎㅎ

2024-06-02 15:06 UTC, skiende74 commented on src/recoil/orderSummaryState.ts
> +});
감사합니다 :)

2024-06-02 15:39 UTC, skiende74 commented on src/api/apiClient.ts
> +      return await apiClient._fetchWithThrow(endpoint, requestInit);
저도 airbnb 코드스타일을 통해  'no-return-await'룰을 알게 되어 사용하다, 
ESLint v8.46(10개월전) 부터 deprecated rule이 되어 사용하지 않게 되었습니다 !

룰의 기존의도는 await로 인해 microtask를 대기하지않고,
Promise를 그냥 반환하는 것으로 성능 손해를 방지하는 것이었지만,

[no-return-await 공식문서](https://eslint.org/docs/latest/rules/no-return-await)
에 따르면, 
이제는 return await 변수명; 을 사용하여도 JS엔진에서 항상 최적화가 작동하여 
return문에 붙은 await 프로미스는 대기하지 않고 즉시 반환하게되어
성능상의 차이가 발생하지 않는다고 합니다.

그래서 둘을 자세히 조사하고 비교해본 결과,
return await할 때 에러가 발생할 경우의 디버깅에 유리하다고 생각되어 사용하게되었습니다.

![image](https://github.com/woowacourse/react-shopping-cart/assets/86130706/19dfaea7-676a-4adb-b1bd-710e8b298c98)

위처럼 foo내부에서 bar()를 리턴할때
bar내부에서 에러가 발생할 경우
return await bar(); 한 경우는 foo와 bar 모두가 에러 스택트레이스에 등장하지만
return bar(); 한 경우는 bar만 에러 스택트레이스에 등장해
디버깅에 용이하다는 의견이 많았습니다.

또, return await를 붙여주게되면
bar가 async함수라는 것을 명시적으로 알려주는 셈이 되어,
그 점을 장점으로 꼽는 의견도 있었는데, 그 부분도 공감을 하여 사용하게 되었습니다.

2024-06-03 06:43 UTC, skiende74 commented on src/recoil/coupon/validateCouponApplicability.ts
> +  expirationDate: (coupon, get) => new Date(coupon.expirationDate) >= new Date(),
테스트 용이성 측면에서 그런 의존성을 뺴주는 게 확실히 좋은 것 같습니다.

2024-06-03 06:55 UTC, skiende74 commented on src/pages/CartPage.tsx
> +  addCartItem(21);
useDefaultCartItem으로 분리해놓고, 필요할때만 호출하게끔 변경하였습니다. :)

2024-06-03 06:55 UTC, skiende74 commented on src/pages/OrderConfirmationPage.tsx
> +    onConfirm: () => {},
추가하려 하다가 미처 추가를하지못했네요ㅎㅎ

2024-06-03 07:56 UTC, skiende74 commented on src/recoil/cartItemState.ts
> +  },
선택된 아이템이 바뀔경우,
전체금액, 쿠폰할인금액 등 모든 파생상태가 다시 계산되어야 하는데,
이 파생상태는 선택된 아이템들을 기준으로 계산을 해야하기때문에
카트아이템을 선택했는지여부를 전역으로 관리해줬던 것 같습니다.

cartItems 상태에 속성으로 isChecked를 넣어줘도되지만,
cartItems는 최고조상 아톰이라,
작은아톰(체크여부)을 하나 더만들어서 수정해야 재계산이 적어질 것이라 생각하였습니다.

혹시 질문의도를 제가 정확히 파악한 게 맞을까요?

2024-06-03 09:06 UTC, skiende74 commented on src/api/apiClient.ts
> +      return await apiClient._fetchWithThrow(endpoint, requestInit);
둘의 차이에 대해 자세히 조사/비교해보고 나름의 결론을 내려보았는데,
덜 조사한 것이나 잘못조사한 부분이 없을까요?

2024-06-04 15:33 UTC, Tanney-102 commented on src/api/apiClient.ts
> +      return await apiClient._fetchWithThrow(endpoint, requestInit);
캬 대박이네요 👍  리뷰는 제가 받아야겠네요~ 한 수 배워갑니다!

2024-06-04 15:36 UTC, Tanney-102 commented on src/recoil/cartItemState.ts
> +  },
네넵 다른 파생 상태에 영향을 주는 거라면 납득이 가네요

2024-06-04 15:37 UTC, Tanney-102 approved these changes
안녕하세요 제이드!
뭔가 리뷰하러 왔다가 제가 잔뜩 배우고 가는 것 같네요~ 👍 
끝까지 고생 많으셨습니다!

2024-06-04 15:37 UTC, merged