[2단계 - 장바구니 미션] 파노(전환오) 미션 제출합니다.
woowacourse/react-shopping-cart pull request #41
Opened 2021-05-24 14:52 UTC by jho2301

안녕하세요 수호님!
장바구니 2단계  과제로 PR 드립니다.

리뷰 받을 수 있는 날이 얼마 안 남아서 많이 아쉽습니다!
마지막 지하철미션은 제 페어가 수호님께 리뷰매칭되어서 끝까지 리뷰받을 수 있을 것 같습니다ㅎㅎㅎ

마지막까지 잘 부탁드립니다!

## 사용 기술 스택

## 기능 구현 목록

## 주안점, 중점적으로 리뷰받고 싶은 부분

 
## 웹 VSCode 환경

https://github.surf/jho2301/react-shopping-cart/tree/step2

## 데모

과제 데모: 
스토리북: 

## 시연

## 디렉토리 구조

```

```

2021-05-28 13:37 UTC, wow9144 requested changes
새롭게 시도하시고 변경하신 부분들도 무난하게 잘 하신것 같습니다. 👍 
세부 피드백 확인해보시고 고민하시던 에러처리 부분과 함께 커밋해주시면 좋을 것 같습니다.

2021-05-28 13:37 UTC, wow9144 commented on src/hooks/useFetch.ts
> +  const doFetch = async () => {
동사형을 만들기 위해 억지로 앞에 do를 붙일 필요는 없습니다.
fetch 라고 해도 충분히 의미 전달이 됩니다.
좋은 코드를 작성하는데 도움을 주는 책들의 `네이밍`편을 보면 대부분 나오는 내용이기도 합니다.

2021-05-28 13:37 UTC, wow9144 commented on src/states/slices/cart/thunk.ts
> +  async ({ userName, cartId }: { userName: string; cartId: CartId }, thunkAPI) => {
`: { userName: string; cartId: CartId }`
가능하면 이렇게 인라인으로 일회성 타입을 선언하는것은 지양하는게 좋습니다.
변경이 생길 때 이쪽 저쪽을 다 변경해야 하고 중복적으로 선언될 여지도 많습니다.
당장 이곳 한 번만 이렇게 사용된다면 개인적으로는 이렇게 해도 무방하다고 생각하지만 코드의 변화에 즉각적으로 반응하여 따라 바뀔 수 없기 때문에 이번 한번만 사용되고 지워질 코드가 아니라 지속적으로 관리되어야 하는 코드라면 필연적으로 더러운 코드로 남아 수정을 유발하게 만드는 코드가 됩니다.

2021-05-28 13:37 UTC, wow9144 commented on src/states/slices/cart/slice.ts
> +export const cartSlice = createSlice({
아쉽지만 RTK 에 대해서는 제가 도움이 될 만한 깊은 조언을 드리기는 어려울 것 같습니다.
리덕스와 리덕스를 중심으로 한 고구마 줄기 같은 모든 라이브러리들을 프로덕션에 다 써보고 리덕스는 버리기로 결정을 했던 시점이 RTK가 나오기 전이라....RTK는 문서만 봤고 실무에 써본적은 없습니다.

저라면 PayloadAction의 제너릭 타입을 인라인 리터럴로 하지 않고 따로 빼서 별도 선언하는 정도로 했을 것 같습니다.

2021-06-10 10:01 UTC, jho2301 commented on src/components/OrderConfirm/OrderConfirmSection/index.tsx
> +          <OrderConfirmListItem key={item.cart_id} item={item} />
camelize라는게 있네요..! 
바로 적용해보겠습니다..

2021-06-10 10:33 UTC, jho2301 commented on src/components/ProductList/ProductCard/index.tsx
> +interface Props extends Product {
제가 봐도 이상하네요 ㅎㅎ..
바로 고쳤습니다!

2021-06-10 10:34 UTC, jho2301 commented on src/components/OrderConfirm/OrderConfirmSection/index.tsx
> +          <OrderConfirmListItem key={item.cart_id} item={item} />
수정커밋: 0342d5a

2021-06-10 10:49 UTC, jho2301 commented on src/hooks/useFetch.ts
> +  const doFetch = async () => {
고민이 있었던 부분입니다..! 
당시에는 fetch 내장함수와 구분을 하려고 해당 네이밍을 하였습니다.
해당 스코프에선 내장함수를 사용하지 않으니 이름을 은닉해도 좋을까요?

2021-06-10 10:52 UTC, jho2301 commented on src/hooks/useFetch.ts
> +  const doFetch = async () => {
두 개의 아쉬움?을 해소하는 fetchData라는 이름으로 변경해보았습니다!
수정커밋:  fecf07d

2021-06-10 11:06 UTC, jho2301 commented on src/states/slices/cart/thunk.ts
> +  async ({ userName, cartId }: { userName: string; cartId: CartId }, thunkAPI) => {
![image](https://user-images.githubusercontent.com/44419181/121513539-ea64b000-ca25-11eb-97a2-03c4c5c8d3e4.png)
[레퍼런스](https://redux-toolkit.js.org/api/createAsyncThunk#payloadcreator)
당시에 RTK 썽크함수가 2개이상의 인자는 객체로 전달하게끔해서, 함수 인자를 위한 객체타입으로, 일회성으로 써줬던 것 같습니다. (두 번째 인자가 thunkAPI라서..ㅜ)
각 함수의 인자 타이핑을 위한 객체타입이라, 타입을 따로 만든다면 재활용이 어려울 것 같다고 생각합니다. 어떻게 생각하시는지 궁금합니다. .

2021-06-10 11:28 UTC, jho2301 commented on src/states/slices/cart/slice.ts
> +export const cartSlice = createSlice({
혹시 여쭤봐도 된다면 어떤 라이브러리를 사용하고 계신지 궁금합니다!

2021-06-10 14:02 UTC, jho2301 commented on src/hooks/useCart.ts
> +    throw new Error(NETWORK_ERROR);
에러처리만 더 수정하고 리뷰요청드릴 수 있도록하겠습니다 ㅜㅜ 엄청 늦어져서 죄송해요

2021-06-11 10:42 UTC, jho2301 commented on src/hooks/useCart.ts
> +    throw new Error(NETWORK_ERROR);
API요청의 에러처리 위치를 APIClient로 잡았고, useFetch 사용하는 코드 고쳐서 각각 에러바운더리 설정해줘봤습니다. `react-error-boundary`라이브러리 적용해봤습니다..!
수정커밋 : cd98d2, 60d721

2021-06-11 10:59 UTC, jho2301 commented on src/hooks/useCart.ts
> +    throw new Error(NETWORK_ERROR);
아 잘못 이해하고 있었네요 다시 수정하겠습니다

2021-06-11 11:21 UTC, jho2301 commented on src/hooks/useCart.ts
> +    throw new Error(NETWORK_ERROR);
훅을 사용하는 컴포넌트에서 에러 체크하고, 에러바운더리에서 어떤 에러인지 알 수 있도록 에러코드를 throw하는게 더 좋을 것 같습니다. 다시 수정하겠습니다ㅎㅎ..
(백엔드 개발자랑 에러코드를 받도록 합의하는 과정을 거쳤다면, 커스텀훅 내부에서 에러 throw해도 무방할 것도 같습니다. 그러면 훅을 사용하는 컴포넌트에선 에러 관련 로직이 없어도 될 것 같아요)

2021-06-12 15:03 UTC, jho2301 commented on src/hooks/useCart.ts
> +    throw new Error(NETWORK_ERROR);
한 에러바운더리에서 분기처리할 정도로 에러의 경우수가 많지 않아서 일괄적으로 처리했습니다.
장바구니 관련 동작은 스낵바로 에러를 띄웠습니다.
GET을 해오는 동작, 주문시 오류는 중요성을 고려해서 에러바운더리를 이용해서 에러화면을 나타냈습니다.

수정커밋: 79e3c7a

2021-06-12 15:08 UTC, jho2301 commented on src/hooks/useCart.ts
> +    throw new Error(NETWORK_ERROR);
한 에러바운더리에서 분기처리할 정도로 에러의 경우수가 많지 않아서 일괄적으로 처리했습니다.
장바구니 관련 동작은 스낵바로 에러를 띄웠습니다.
GET을 해오는 동작, 주문시 오류는 중요성을 고려해서 에러바운더리를 이용해서 에러화면을 나타냈습니다.

2021-06-13 01:52 UTC, jho2301 commented on src/hooks/useCart.ts
> +    throw new Error(NETWORK_ERROR);
![image](https://user-images.githubusercontent.com/44419181/121792783-0e95dc00-cc34-11eb-8103-631d25a87460.png)
1. APIClient에서 response 상태코드 200번대 외 번호를 에러로 throw합니다.

![image](https://user-images.githubusercontent.com/44419181/121792840-adbad380-cc34-11eb-90a2-2126facdddb8.png)
2. useFetch나 thunk함수에서 catch해서 에러 state에 저장합니다.

![image](https://user-images.githubusercontent.com/44419181/121792862-fd010400-cc34-11eb-8368-553acd471c14.png)
3. useCart에서는 커스텀훅 내에서 에러처리하도록 했습니다

![image](https://user-images.githubusercontent.com/44419181/121792872-228e0d80-cc35-11eb-9b21-722cdbd7b859.png)
4. useFetch는 유틸성이 커서 사용하는 컴포넌트가 받아서 처리하도록 의도했습니다.

![image](https://user-images.githubusercontent.com/44419181/121792905-5e28d780-cc35-11eb-9894-e17e229b19fa.png)
5. get 이외의 동작도 useFetch가 수행할 수 있도록 수정했습니다

2021-06-18 14:47 UTC, wow9144 commented on src/states/slices/cart/slice.ts
> +export const cartSlice = createSlice({
mobX 도 써보고 최근에는 recoil 도 써봤습니다만 저는 recoil이 가장 좋은 것 같습니다.

2021-06-18 15:58 UTC, wow9144 approved these changes
바꾸신 부분에 대해 의도를 잘 전달하기 위해 캡쳐까지 해가면서 설명해주셔서 좋았습니다. :)
크게 손을 봐야 할 부분이 있긴한데 이번 미션에서 요구되는 부분은 아닌것 같고 다른 부분들은 다 좋아서 머지하고자 합니다.
손을 봐야 하는 부분은 익셉션 처리를 정적 언어에서는 어떻게 처리 하는지를 먼저 보시면 좋을 것 같고, 그에 비해 타입스크립트로 익셉션 처리하는데에는 어떤 한계점이 있는지 그 한계를 보완하기 위해 어떤 기법을 도입해야 하는지 같이 고민하셔야 하는 부분입니다.
코멘트에 말씀드렸다시피, 스프링을 쓰는 어플리케이션에서 클라이언트의 요청에 대해 여러 익셉션이 나는 상황일 때 코드가 어떻게 전개 되어 익셉션을 처리하는지를 먼저 보시면 큰 도움이 될 것 같습니다.

수고 많으셨습니다. 👍

2021-06-18 15:58 UTC, wow9144 commented on src/components/OrderList/OrderItemListSections/OrderItemListSection/OrderListItem/index.tsx
> +  handleLinkToProductDetail: () => void;
OrderListItem 컴포넌트의 Props 로 handleLinkToProductDetail 라는 네이밍은 너무 구체적이기 때문에 적절하지 않은것 같습니다.
OrderListItemCard 가 클릭 되었을 때 실행될 함수인데 외부에서 받은 함수가 실행 될뿐이고 그 함수가 실행되면 productDetail 로 링크 이동을 하는지, 팝업을 띄워서 디테일을 보여주는지는 이 컴포넌트의 관심사가 아닙니다.
확인해보지 않아도 productDetail 로 이동시키는 코드가 전달된 함수 안에 들어있겠지만, 그 코드가 바뀐다면(팝업을 띄운다든지) 그 본래 함수의 이름도 바뀌어야 할 것이고 그 함수가 바뀌면 이곳의 인터페이스도 바뀌고 컴포넌트 내의 코드도 바뀌고....
이처럼 구체적인것에 의존하면 코드 변화의 여파가 큽니다.
추상에 의존하도록 Props 인터페이스에서부터 좀 더 추상화된 이름을 쓰는 것이 좋겠습니다.
또한 사용자쪽의 변화에 의해 구현부가 바뀌게 되면 안됩니다.
인터페이스가 바뀌면 이 인터페이스에 의존하는 쪽(props를 전달하는쪽)이 바뀌어야 하는것이지, 사용자측의 코드가 바뀐다고 하여 의존하고 있던 인터페이스가 변경되는 일이 발생한다면 애초부터 인터페이스에 의존을 하는게 아니라 구현부에 인터페이스를 짜맞춘 것 이었을것입니다.

2021-06-18 15:58 UTC, wow9144 commented on src/states/slices/cart/thunk.ts
> +let currentCalledRequest = '';
error의 타입을 구분하기 위한 방법으로, 이것은 좋은 선택은 아닌것 같습니다.
함수 스코프 밖에 존재하는 이런 전역적인 변수에 값을 바꿔가며 특정 함수가 값을 사용하게 하는것은 코드가 동기적으로 실행됨을 보장 할 때 부분적으로 사용 가능 할 수도 있으나 비동기적인 작업에 이렇게 쓰면 확정적 버그로 봐도 무리가 없습니다.
서버에 요청하는 성공케이스일 때 변수에 값을 쓰는데(write) 그 값을 사용하는건 에러가 났을 때 사용을 하기 때문에 비동기 요청이 동시 다발적으로 일어나고 응답은 순차적이지 않다면 잘못된 동작을 하게 될 것 같습니다.
 
또한
`const { functionName } = error as FetchError;`
error 객체에서 functionName 을 뽑아내는 코드 자체도 이상합니다 -_-;;
functionName을 뽑아내는 것도 이상하고 뽑아낸걸 분기치는것도 이상합니다 --;;
협업하고 있는 백엔드 개발자에게 클라이언트의 요청을 처리하다 발생한 익셉션을 어떻게 처리하는지 물어보시고 스프링에서 그런 처리를 어떻게 하는지 코드를 보여달라고 하시면 큰 도움이 되실 것 같습니다.
그 방법을 들고 와서 적용하시려고 하면 도움이 되실거고 javascript의 catch 에서는 오직 Error로 타입이 정해져 있으므로 에러에 대한 익셉션 인터페이스를 만들어 catch 구문에서 익셉션 구현체들을 분기 치는식으로 하면 됩니다.
쉽지 않을 수 있으니 이건 나중에 천천히 시도 해보시면 좋을 것 같습니다.

2021-06-18 15:58 UTC, merged

2021-06-22 07:46 UTC, jho2301 commented
# 학습로그

## Redux

## Redux Thunk

## Redux Toolkit


## msw

## rtl

## error boundary

## Suspense Component

## TTFB

## as const