[2단계 - 장바구니 미션] 동동(김동희) 미션 제출합니다.
woowacourse/react-shopping-cart pull request #44
Opened 2021-06-01 13:23 UTC by bigsaigon333

# [2단계 - 장바구니 미션] 동동(김동희) 미션 제출합니다. 

@ysm0622 님 안녕하세요.  동동 :weight_lifting_man: 입니다. 

장바구니 미션 2단계 PR 제출하오니 리뷰 부탁드립니다! 

## 1.  [:fire: 데모사이트 :fire: ](https://bigsaigon333.github.io/react-shopping-cart/)

## 2. [:airplane: VSCODE  in web :airplane: ](https://github1s.com/bigsaigon333/react-shopping-cart/tree/step2)

## 3. 구현한 기능 목록 - 2단계
- [x] 제공 받은 API로 Endpoint와 Schema 변경
- [x] 상품 상세 페이지 구현
- [x] 반응형 레이아웃 적용
- [x] 디렉토리명 변경 (도메인명 > list > listItem)
- [x] 각 listItem이 store를 구독하도록 변경(리렌더링 최소화)

## 4. 고민한 점
- useSelector hook을 사용하는 각각의 컴포넌트가 store를 subscribe 한다는 것을 인지하지 못하고, 이곳 저곳에서 useSelector를 사용하여 상태의 일부분만 바뀌어도 전체 page가 리렌더링되고 있었습니다. 
이를 `react-redux` 의 `shallowEqual` 과 각 state의 `id 배열`을 잘 활용하여, 변화가 있는 컴포넌트만 렌더링되도록 하였습니다. 
- 비동기 로직 실행시의 상태(idle, pending, succeed, failed)를 각 state의 status로 관리하였으나, 이를 UI에 반영하지는 못하였습니다. 지하철 노선도 미션시에 status 와 useEffect, useSelector 가 섞여서 react rendering flow를 좇아가기가 너무 어려웠습니다.. 이에 loading을 나타내는 spinner 표시는 이번 미션에서는 배제하였습니다...
- 반응형 레이아웃을 적용하였습니다. breakpoint 는 아래와 같이 나누었습니다. 
  - SMALL: "640px",
  - MEDIUM: "768px",
  -  LARGE: "1024px",
제 휴대폰(iPhone XR) 에서는 원하는 대로 잘 표시가 되는데, 다른 폰에서는 어떨지 모르겠습니다... 
CSS cross-browsing 이 생각보다 쉽지 않았습니다.. cross-browsing 의 어려움에 대해 살짝 맛본듯한 느낌입니다 ㅎㅎ

2021-06-02 13:20 UTC, ysm0622 requested changes
장바구니에 있는 물품을 구매하고나면 장바구니가 비워져야할것같아요! 👍 

코드가 전체적으로 깔끔하고 일관성있어서 좋네요! 👍 

고생하셨어요! 👏 👏 👏

2021-06-02 13:20 UTC, ysm0622 commented on src/App.jsx
> +      <BrowserRouter basename={process.env.PUBLIC_URL}>
환경변수는 `const PUBLIC_URL = process.env.PUBLIC_URL` 처럼 상수로 따로 분리해서 관리하면 좋습니다! 👍

2021-06-02 13:20 UTC, ysm0622 commented on src/assets/shopping-cart.svg
> +</g>
오잉 이건 뭘까요 ㅋㅋ

2021-06-03 14:29 UTC, bigsaigon333 commented on src/assets/shopping-cart.svg
> +</g>
앗 불필요한 `<g>` 가 들어가 있었네요.. free vector 를 제공하는 사이트에서 다운받아서 아무 생각없이 사용했습니다 :crying_cat_face: 

MDN에 따르면 svg의 `<g>`는 HTML의 `<div>`와 같이 컨테이너 역할을 수행하나,  해당 svg 파일에서는 불필요하다가 판단되어 삭제하였습니다!

짚어주셔서 감사합니다~! 

참고자료) 
https://developer.mozilla.org/en-US/docs/Web/SVG/Element/g

2021-06-03 14:37 UTC, bigsaigon333 commented on src/App.jsx
> +      <BrowserRouter basename={process.env.PUBLIC_URL}>
process.env, 환경변수 자체가 상수인데, 별도로 상수화를 해야할까? 를 잠시 고민했습니다. 

고민 끝에 다음과 같은 이유로, `src/constants/env.js` 를 만들어 `export const { PUBLIC_URL } = process.env; ` 와 같이 상수화하였습니다!

1. 상수를 사용하는 파일 입장에서는 해당 상수가 환경변수인지 JS파일의 상수인지를 모르게 하는게 좋겠다.
2. 환경변수에서 파생된 상수를 환경변수와 같이 export 시킬 수 있다.

```jsx
const NODE_ENV = process.env.NODE_ENV;

const PUBLIC_URL = NODE_ENV === "development" ? "/" : process.env.PUBLIC_URL;

export {NODE_ENV, PUBLIC_URL};
```

2021-06-03 15:23 UTC, bigsaigon333 commented on src/assets/shopping-cart.svg
> +</g>
관련 커밋입니다: https://github.com/woowacourse/react-shopping-cart/pull/44/commits/fdbaa8220dfa6d310bd09e2bc222863aebfc8244

2021-06-03 15:23 UTC, bigsaigon333 commented on src/App.jsx
> +      <BrowserRouter basename={process.env.PUBLIC_URL}>
관련 커밋입니다: https://github.com/woowacourse/react-shopping-cart/pull/44/commits/fc971af783a92fa8b6dea9e6c2109a35c28e3988

2021-06-03 15:28 UTC, bigsaigon333 commented on src/App.jsx
> +    dispatch(fetchOrders());
메인페이지에서 물품 정보뿐만이 아니라 장바구니 정보가 필요하여서 물품 정보와 장바구니 정보를 fetch 하여야 하는데, 
그냥 주문목록 정보도 같이 fetch 해버릴까... 라는 생각으로 접근하였습니다..

주문목록 정보는 주문목록 페이지로 이동하지 않는 이상 불필요하므로, 주문목록 페이지(`src/pages/Order/Order.jsx`)에서 fetch 하는 것으로 수정하였습니다! :smile: 

관련 커밋입니다: https://github.com/woowacourse/react-shopping-cart/pull/44/commits/8d7f8c91355986009029418543506f78cb4a9dfa

2021-06-03 15:28 UTC, bigsaigon333 commented
> 장바구니에 있는 물품을 구매하고나면 장바구니가 비워져야할것같아요! 

앗 당연히 확인을 하고 리뷰 요청을 드렸어야 했는데, 부끄럽습니다 :crying_cat_face: 

해당 부분 수정하였습니다~! 

관련 커밋입니다: https://github.com/woowacourse/react-shopping-cart/pull/44/commits/caf02df2a44fc5b824b799a3d4bf8a35c09d99bd

2021-06-04 14:45 UTC, ysm0622 approved these changes
피드백 잘 반영해주셔서 감사해요! 👍 

고생하셨어요!!! 👏 👏 👏 👏 👏 👏 👏

2021-06-04 14:45 UTC, merged