[2단계 - 장바구니 미션] 브랜(서지환) 미션 제출합니다. (작성중 입니다)
woowacourse/react-shopping-cart pull request #47
Opened 2021-06-03 12:09 UTC by seojihwan

2021-06-08 13:40 UTC, HyeonaKwon requested changes
안녕하세요 브랜님! 
몇개 안되지만 코멘트 확인해주세요~ 고생하셨습니다!

2021-06-08 13:40 UTC, HyeonaKwon commented on src/hooks/useCart.ts
> +      cart.reduce((acc: CheckedList, { cartId }) => {
요런건 .reduce() 를 사용하는 건 아닌 것 같네요!  
그냥 checked 로 채워진 배열이 필요한 것 같은데 새로운 배열을 생성하는건 어떨까요?
```javascript
setCheckedList([...Array(cart.length)].fill(checked));
```

2021-06-08 13:40 UTC, HyeonaKwon commented on src/hooks/useCart.ts
> +        acc[cartId] = 1;
여기도 마찬가지입니당!

2021-06-08 13:40 UTC, HyeonaKwon commented on src/hooks/useCart.ts
> +  const onClickSubmitButton = () => {
UI 이벤트 핸들러까지 custom hook 에 포함되어야하는 이유가 무엇일까요??

2021-06-08 13:40 UTC, HyeonaKwon commented on src/pages/ProductList/index.tsx
> +        <p>requestErrorMessage</p>
조금 더 사용자 친화적 UI 었으면 좋았겠네요 :)

2021-06-08 13:44 UTC, HyeonaKwon commented
음 로딩은 도메인별로 hook 이 있고, 그 훅에서 loading 을 관리해도 될 것 같아요!
그러면 api 호출이 완료될 때까지 loading 값을 관리해주고 컴포넌트가 가져다 사용해도 편할 것 같네요!
그리고 로딩이 보여지는 시간이 짧긴 하지만, api 의 응답이 언제나 빠르다는 보장은 없기 때문에 로딩을 보여주는 건 사용자에게 친절한 ui가 됩니다 :)

2021-06-08 13:46 UTC, HyeonaKwon commented
아 그리고 브랜님! 장바구니에서 같은 상품들은 그룹핑되면 좋겠네요!  
장바구니에 넣을 때마다 다른 상품처럼 새로 아이템이 들어가네요 😭

2021-06-10 05:42 UTC, seojihwan commented on src/hooks/useCart.ts
> +        acc[cartId] = 1;
카트에 담긴 아이템을 조회하면 카트id, 상품id,이름, 상품, 이미지 url형태인 Object가 배열로 담겨옵니다!
이 정보는 전역스토어에 저장되고 CartPage에서 useSelect를 통해 가져옵니다.

하지만 카트에 담긴 아이템의 갯수나, 체크상태를 확인하기 위해서는 지역상태가 또 필요합니다. (서버에 저장되지않음)
이 지역상태를 배열로 갖는다면, [{cartId: '1', count: 5, isChecked: false}, ...] 이러형태로 갖을 수 있을 것 같은데요. 매번 cartId를 통해 타겟인 cartItem을 찾아가야합니다. ( 화면에 그려주기 위해 자신의 id에 해당하는 정보를 찾아야함 )

카트정보를 찾아가는데 있어서 각각 O(n)의 시간복잡도가 발생하고... n개의 상품이면 O(n^2)의 시간복잡도가 발생할 것 같습니다. 

현재에는 객체를 생성하기위해 reduce를 사용해주고 있는데요. 이에 대해서는 어떻게 생각하시는지 궁금합니다.

cartId의 형태
[{  
  cartId: string;
  productId: string;
  name: string;
  price: number;
  imageUrl: string;
}, {... }]

2021-06-10 06:01 UTC, seojihwan commented on src/hooks/useCart.ts
> +  const onClickSubmitButton = () => {
훅의 네이밍이나 기능을 보았을 때에도, Submit에 대한 이벤트 핸들러를 직접 만들어 주기 보다는 컴포넌트에서 상태만 전달받고 사용하는 것이 더 좋아보이네요! 

이 코드는 지하철 노선도 미션코드이지만.. 아래 코드에 대해서도 UI 이벤트 핸들러( input change 이벤트에 대한 핸들러 )가 custom hook에 포함된 것이 올바르지 않은것인지 궁금합니다. (아직 피드백을 받지 못해서... ㅎㅎ 부탁드립니다)
```ts
import { useState } from "react";

type Validator = (value: string) => void | never;

const useInput = (validator: Validator) => {
  const [inputValue, setInputValue] = useState("");
  const [errorMessage, setErrorMessage] = useState<string | null>(null);

  const validate = (value: string) => {
    try {
      validator(value);

      setErrorMessage(null);
    } catch (error) {
      setErrorMessage(error.message);
    }
  };

  const setValueOnChange: React.ChangeEventHandler<HTMLInputElement> = ({
    target,
  }) => {
    const { value } = target;

    setInputValue(value);

    validate(value);
  };

  return {
    inputValue,
    errorMessage,
    setValueOnChange,
    setInputValue,
  };
};

export default useInput;

```

2021-06-10 06:04 UTC, seojihwan commented
장바구니에 여러번 담게되면 백엔드 API상, Product Id가 같아도 Cart Id가 다른 형태로 데이터가 전달되는데요!
이런 경우에는 장바구니 담기를 막거나, 프론트에서 데이터를 한번 가공하는 것이 좋을까요?

2021-06-11 02:30 UTC, HyeonaKwon commented on src/hooks/useCart.ts
> +        acc[cartId] = 1;
아.. orderCountList 라고 해서 배열인 줄 알았는데 객체군요.. 요것부터 이상해보이네요! 😭. 변수명에서 자료구조를 빼는게 좋겠네요

2021-06-11 02:40 UTC, HyeonaKwon commented on src/hooks/useCart.ts
> +  const onClickSubmitButton = () => {
비즈니스 로직이 아니라 history.push 까지 custom hook 이 가져가야 하는 생각이 드네요. 게다가 cart 도 export 해주고 있으니 충분히 컴포넌트에서 수행할 수 있을것으로 보이구요!
위의 코드에서는 내부 로직을 수행하는 것으로 보이는데요, 그래도 validate 를 export 하고 핸들러는 컴포넌트에 있는건 어떨까요?

2021-06-11 02:42 UTC, HyeonaKwon commented
보통은 장바구니 상품의 수량만 업데이트하는 api 가 존재할텐데요, 그런 api 가 없다면 애초에 장바구니에 담지않는건 어떨까요! 사용자 입장에서는 버그라고 생각이 드는데요!

2021-06-21 14:58 UTC, seojihwan commented
# [테스트] 
## 내용
- [테스트해야하는 이유와 테스트 비교](https://www.notion.so/3-806caf6360f0417c89d00385beac3390)
# [리덕스 사가]
## 내용
- [리덕스 사가를 이용한 이유](https://www.notion.so/3-806caf6360f0417c89d00385beac3390)

2021-06-24 08:05 UTC, seojihwan commented
좀 많이 늦었지만 😅피드백 반영해보았습니다~

|수정 내용|커밋|
|:-:|:-:|
|핸들러 컴포넌트 페이지로 이동|f254cfb7715919eb547dc2a07c9e912422cda62a|
|중복된 상품 카트에서 필터링|3f7ea56e976fa4ba54fac89f7eae9884a9965ad2|
|자료구조 네이밍 제거|1e1771133f63caabd21d069e93bdadf84b3e44b8|

2021-06-25 01:28 UTC, HyeonaKwon approved these changes
브랜님! 수정해주신 사항 잘 봤습니다 ㅎㅎ 장바구니에서 중복된 상품을 필터링할 때 사용자에게 알림도 있으면 더 좋았겠단 생각이 들었어요~

미션 수행하느라 고생하셨습니다!

2021-06-25 01:28 UTC, merged