[2단계 - 장바구니 미션] 그루밍(강민경)
woowacourse/react-shopping-cart pull request #51
Opened 2021-06-05 17:37 UTC by ddongule

안녕하세요!!!!!
드디어.. 장바구니 미션 2를 들고온 그루밍입니다!!!!!!!
미션들이 많이 밀려있어 미션 2를 제출하기까지 굉장히 오래걸렸네요.. 죄송합니다😱😱ㅠㅠ..
2단계에서는 기존 1단계에서 만들었던 mock data를 사용하지 않고, 
새로 받은 API를 연동해 기존 앱과 연동했는데요!
API가 생각했던 방향과 조금 달라 헤매기도 했습니다 끄흑..ㅠㅠ
비동기로 데이터를 받고, 전역 State로 관리하면서 
1단계에서 어색했던 Redux와 조금 더 친해지는 시간을 가질 수 있었던 것 같습니다. 하하하!!!
혹시 잘못 사용하고 있는 부분이 있다면 마구마구 알려주세횻!!!!!!!
서론이 길어졌네욧..!!! 2단계 미션도 잘 부탁드립니다아!!!!! 🥺🧡🥺🧡🥺
감사합니다앗!!!

## [👉데모 페이지👈](https://ddongule-shopping-cart.netlify.app/)

## 🧪 구현한 기능 및 테스트
### ✨✨ 공통 요구사항 및 필수 요구사항
- [x] 작성 가능한 단위의 테스트를 직접 선정하여 진행 (테스트 도구 선택 자율) 
- [x] 제공 받은 API로 Endpoint와 Schema 변경
- [x] 상품 상세 페이지

### ✨✨ 공통 요구사항 및 필수 요구사항
- [x] 주문 상세
- [x] [주문 목록 페이지] 페이징 적용
   ![order-details](https://user-images.githubusercontent.com/26598561/120896269-cd159780-c65b-11eb-8d94-4ae5893d9d8b.gif)
- [x] [상품 상세 페이지] 흐름을 고려한 맞춤 큐레이팅 상품 추천 기능
   ![detailpage](https://user-images.githubusercontent.com/26598561/120896198-75772c00-c65b-11eb-9e10-d33c5743a38c.gif)
- [x] 사용자를 위한 로딩 환경 개선
- [x] 반응형 레이아웃 구현
   ![meedia](https://user-images.githubusercontent.com/26598561/120896532-f84cb680-c65c-11eb-92cf-a9cf480b3d7c.gif)

- [x] 링크(/order-payments) 를 통한 결제 페이지 접근 불가 → [확인 링크](https://ddongule-shopping-cart.netlify.app/order-payment)
- [x] 브라우저 새로고침시 모든 상태 유지

## 📁 폴더 구조
```
├── App.js
├── assets
│   ├── image
│   │   ├── baemini.png
│   │   ├── loading.gif
│   │   ├── noImage.jpeg
│   │   └── tung.png
│   └── svg
│       ├── Cart.js
│       ├── Check.js
│       ├── TrashCan.js
│       └── index.js
├── components
│   ├── @common
│   │   ├── Button
│   │   │   ├── index.js
│   │   │   ├── index.stories.js
│   │   │   └── index.styles.js
│   │   ├── CheckBox
│   │   │   ├── index.js
│   │   │   ├── index.stories.js
│   │   │   └── index.styles.js
│   │   ├── Image
│   │   │   ├── index.js
│   │   │   └── index.styles.js
│   │   ├── Loading
│   │   │   ├── index.js
│   │   │   └── index.styles.js
│   │   ├── PageHeader
│   │   │   ├── index.js
│   │   │   ├── index.stories.js
│   │   │   └── index.styles.js
│   │   ├── PageWrapper
│   │   │   ├── index.js
│   │   │   └── index.styles.js
│   │   ├── RightAddon
│   │   │   ├── index.js
│   │   │   └── index.styles.js
│   │   └── TextWithLine
│   │       ├── index.js
│   │       └── index.styles.js
│   ├── CompletedOrderList
│   │   ├── index.js
│   │   ├── index.stories.js
│   │   └── index.styles.js
│   ├── ErrorBoundary
│   │   └── index.js
│   ├── NavBar
│   │   ├── index.js
│   │   ├── index.stories.js
│   │   └── index.styles.js
│   ├── OrderItem
│   │   ├── index.js
│   │   ├── index.stories.js
│   │   └── index.styles.js
│   ├── PaymentSheet
│   │   ├── index.js
│   │   ├── index.stories.js
│   │   └── index.styles.js
│   ├── ProductDetail
│   │   ├── index.js
│   │   ├── index.stories.js
│   │   └── index.styles.js
│   ├── ProductItem
│   │   ├── index.js
│   │   ├── index.stories.js
│   │   └── index.styles.js
│   ├── QuantityInput
│   │   ├── index.js
│   │   ├── index.stories.js
│   │   └── index.styles.js
│   ├── ShoppingItem
│   │   ├── index.js
│   │   ├── index.stories.js
│   │   └── index.styles.js
│   ├── index.js
│   └── pages
│       ├── CompletedOrder
│       │   ├── index.js
│       │   ├── index.stories.js
│       │   └── index.styles.js
│       ├── Details
│       │   ├── index.js
│       │   └── index.styles.js
│       ├── OrderDetails
│       │   ├── index.js
│       │   └── index.styles.js
│       ├── OrderPayment
│       │   ├── index.js
│       │   ├── index.stories.js
│       │   └── index.styles.js
│       ├── Products
│       │   ├── index.js
│       │   ├── index.stories.js
│       │   └── index.styles.js
│       └── ShoppingCart
│           ├── index.js
│           ├── index.stories.js
│           └── index.styles.js
├── constants
│   └── index.js
├── global.styles.js
├── hooks
│   ├── useCarts.js
│   ├── useLoading.js
│   ├── useOrder.js
│   ├── usePagination.js
│   ├── useProducts.js
│   └── useRandom.js
├── index.js
├── reducers
│   ├── cart.js
│   ├── index.js
│   ├── loading.js
│   ├── location.js
│   ├── order.js
│   └── products.js
├── service
│   ├── carts.js
│   ├── loading.js
│   ├── order.js
│   └── products.js
├── store.js
└── utils
    └── index.js
```

## 📝 느낀점
- 장바구니 미션 1단계에서 API가 어떻게 올 지 예상해 어느정도 설계를 하고 들어갔는데, 막상 실제 API를 받아보니 예상과 벗어나있어 API와 맞닿아있는 코드를 고치면서 꽤나 고생했습니다. 물론 계획된 미션이기는 했지만, 앞으로 백엔드 분들과 협업을 할 때에도 충분히 논의를 하고 개발에 들어가야겠다고 생각했습니다. 만약 서로가 원하는 부분을 제대로 이해하지 않고 개발한다면 정말 힘들어질 수도 있을 것 같다고 느꼈습니다 ㅠㅅ ㅠ 
- Redux를 사용하면서 Redux와 붙어있는 다양한 라이브러리들을 알게되었는데, 당연한 이야기지만 편리하다고 막 사용하지 않고 이해하면서 사용해야 함을 느꼈습니다. 매번 생각을 하기는 하지만, 막상 개발을 하면서 구현에 급급한 제 자신을 볼 수 있었습니다. 반성해야겠씁니다!! 

## 🧐 궁금한 점 && 더 봐주셨으면 좋겠다고 생각하는 부분!
#### Logic 분리
- 각 페이지 컴포넌트가 점점 길어지기도 하고 컴포넌트에서 가지고 있는 정보가 점점 많아지는 것 같아 custom hook으로 로직들을 분리했습니다! custom hook 자체도 처음 사용해보고 로직 분리도 익숙하지 않은 편이라, 각 역할에 맞게 잘 분리했는지는 아직 확신이 없습니다..!!.!! ㅠㅠ 😭 😭 
  Reducer의 경우에도 마찬가지로 저번에는 페이지를 구현하면서 하나의 reducer에 모든 내용을 집어넣었었는데, 각 내용들이 한 데 뒤섞여 보기가 어렵기도 하고, 각 페이지에 따라 분리하는게 더 맞는 방향이라고 판단해 분리했습니다! 
   그래서.. reducer나 hook들의 역할 분리나.. 내부 로직들이 잘 만들어져 있는지 살펴봐주신다면... 더 좋을 것 같습니다!! 호호홋..!!!! 

    저는 데이터를 API에서 가져오거나 업데이트 시켜주는 부분은 service로, 나머지 로직은 hook에 넣어놓았습니다!!! 제가 아직 Layer를 나누고 또 로직을 분리하는 경험이 많지 않아 갈팡질팡하고 있읍니다..🥲 🥲 
혹시 이런 분리를 할 때에 어떤 부분을 가장 생각하면서 해야하는지 팁을 조금 주실 수 있을까효..?! 

    물론 정답은 없겠지만, 지금 제가 뭔가 logical하게 생각해서 코드를 분리하는 것이 아니라 `가독성이 떨어지네?! 한 번 분리해봐야겠다!` → `그럼 API 통신 부분은 따로 빼볼까?` → `여기는 재사용할 수 있을 것 같으니까 다르게 한 번 빼볼까?`→ ... 이런 식으로 코드 분리가 진행되고 있어서 불안한 마음에 한 번 여쭈어봅니다아..!!! ㅠㅅ ㅠ 따흐흑

2021-06-06 11:52 UTC, JaeYeopHan requested changes
수고하셨어요! 👏 👏 👏 

---

- 전역 상태가 무엇인지, 다시 한번 생각해보면 좋을 것 같아요.
- redux는 왜 사용하는지, side effect는 어디에서 처리해야 하는지도 같이 고민해보면 좋을 것 같습니다.
- hooks의 분리도 컴포넌트 분리와 마찬가지로 도메인과 관련이 있는 것과 관련이 없는 것으로 나누고 도메인과 관련이 있다면 어떤 특정 도메인과 관련이 있어서 분리해야 하는지 고민해봐도 좋을 것 같아요~ (모든 로직이 hooks로 다뤄져야 할 필요도 없다고 생각합니다 ㅎㅎ)

2021-06-06 11:52 UTC, JaeYeopHan commented on src/hooks/useCarts.js
> +    dispatch({
1. 전체 toggle 하는 것과 하나의 아이템만 toggle하는 것 같이 있는데 분리해서 작성하면 더 좋을 것 같네요 ㅎㅎ (왜일지도 함께 고민해보면 좋을 것 같습니다~)
2. 이 UI 상태가 redux에서 관리되어야 하는 상태값일까요? 👀

2021-06-06 11:52 UTC, JaeYeopHan commented on src/hooks/useLoading.js
> +const useLoading = () => {
fake loading인 것 같은데 이것이 필요했다면 왜 필요했는지 고민해봐도 좋을 것 같아요~

2021-06-06 11:52 UTC, JaeYeopHan commented on src/hooks/useProducts.js
> +  const updateProductURL = () =>
routing하는게 redux action을 통해 dispatch 되어야 하는 걸까요? 👀

2021-06-06 11:52 UTC, JaeYeopHan commented on src/components/@common/Button/index.js
> +const Button = ({
button의 기본 attributes를 받지 않으면 재사용이 어렵지 않을까요?

2021-06-06 11:52 UTC, JaeYeopHan commented on src/components/@common/RightAddon/index.js
> +const RightAddon = ({ onIncreaseQuantity, onDecreaseQuantity }) => (
네이밍보고 어떤 역할을 하는지 전혀 알 수가 없을 것 같아요!

2021-06-06 11:52 UTC, JaeYeopHan commented on src/components/ErrorBoundary/index.js
> +  componentDidCatch(error, errorInfo) {
console.error만 해주면 사용자는 에러인지 아닌지 알 길이 없어 보여요!

2021-06-06 11:52 UTC, JaeYeopHan commented on src/hooks/useRandom.js
> +  const randomProducts = (data, length) => {
이름은 useRandom이라서 도메인 로직과 전혀 상관없을 것 같은데, products라는 도메인을 알고 있네요!

2021-06-06 11:52 UTC, JaeYeopHan commented on src/hooks/usePagination.js
> +  const [page, setPage] = useState(1);
초기값이 무조건 1이어야 할까요?  usePagination 사용하는 곳에서부터 지정하도록 하면 어떨까요?

2021-06-06 11:52 UTC, JaeYeopHan commented on src/hooks/usePagination.js
> +  const pageLength = data => Math.ceil(data.length / 5);
5개 이상으로 자르고 싶을 땐 이 페이지네이션 기능을 사용할 수 없을 것 같은데요?! 👀

2021-06-06 11:52 UTC, JaeYeopHan commented on src/hooks/usePagination.js
> +  const pageLength = data => Math.ceil(data.length / 5);
이름은 상수처럼 보이는데 함수라서 사용하는 입장에서 혼동이 있지 않을까요?

2021-06-06 11:52 UTC, JaeYeopHan commented on src/hooks/usePagination.js
> +    page,
이 hooks를 사용하는 입장에서 index와 page가 무엇인지 알려면 이 내부 구현을 전부 봐야할 것 같은데, 어떻게 생각하시나요?

2021-06-07 12:29 UTC, ddongule commented on src/hooks/useLoading.js
> +const useLoading = () => {
앗 맞습니다 처음에 fake로 로딩 구현하고 나중에 api 통신 후 로딩 뜨도록 바꿔야지 해놓고 까먹었나봅니다 ㅠㅅ ㅠ!! 학 이놈의 정신!!!!!!!!!! 🥲🥲 fake loading을 실제 API 통신이 되어야 뜨도록 변경했습니다! 

해당 커밋은 [`e50cc99`](https://github.com/woowacourse/react-shopping-cart/pull/51/commits/e50cc99e598e5262d4c7ff1b66b8dcac0a1b02b9)에 올려두었습니다!!

덧붙여 만약 fake loading이 필요하다면.. 사용자가 이 앱을 사용하면서 느끼는 즐거움(?!) 정도 때문일 것 같은데, 실제로 변경한 데이터가 반영이 되지 않는데 이렇게 fake loading을 하게되면 결국 사용자는 앱을 사용하면서 더 큰 불편함을 느낄 것 같아 사용하지 않는 것이 더 좋을 것 같습니다!

2021-06-07 12:45 UTC, ddongule commented on src/components/@common/Button/index.js
> +const Button = ({
헉 나름대로 Button의 기본 attributes 중 type, disabled, onClick 등을 받고 있어서 재사용이 잘 될 것이라고 생각했었는데, 다른 요소들을 고려하지 못한 방법이었네요!!! 
가만생각해보니 이런 실수들을 자주 하고 있는 것 같아서 다음부터는 더 신경써야겠습니다..🥲 반성하겠읍니다 또흐흑😱

해당 커밋은 [`dda28af`](https://github.com/woowacourse/react-shopping-cart/pull/51/commits/dda28af84af33b0d0017e9b8bbe3035ed4249d5c)에 올려두었습니다!!

2021-06-07 13:07 UTC, ddongule commented on src/components/@common/RightAddon/index.js
> +const RightAddon = ({ onIncreaseQuantity, onDecreaseQuantity }) => (
어헛 쓸 때에는 그렇게 생각하지 못했는데, 다시 보니 이 코드를 처음 보는 사람에게는 불편한 네이밍이라는 생각이 들었습니다! 조금 더 명확한 네이밍인 ChangeQuantityAddon으로 변경했습니다 !!  🥳 🥳

요 내용은 [`0fd5e55`](https://github.com/woowacourse/react-shopping-cart/pull/51/commits/0fd5e555c1e4bdaefa74e5c58b506cd42dc207f3)에 반영되어 있습니다!

2021-06-07 14:02 UTC, ddongule commented on src/hooks/useProducts.js
> +  const updateProductURL = () =>
오오 요 부분은 어떤 페이지로 가야할 지 Routing을 담당하는 부분은 아니고, 
**결제 페이지**가 **장바구니**를 거치지 않고 접근이 가능하게 되면 안될 것 같아서, 미리 url(https://ddongule-shopping-cart.netlify.app/order-payment에 바로 접근)을 통한 사용자의 접근을 막아주려고 만들어놓은 State 입니다!

장바구니 → 주문/결제 - (결제완료) → 주문목록 (요 flow를 보장해주려고 만들어놓은 State이라고 볼 수 있습니다!)

원래는 `useLocation`, `useHistory` 등 route 에 대한 hook들을 사용해보려고 했는데, 제가 찾아보기로는 이전 url을 저장하지 않고 보통 현재의 url만 저장하고 있는 것 같아서.. (제가 못 찾은 걸 수도 있습니다 허헛 ㅠㅠ🥲🥲) 사용하지 못했습니다!!! 

그래서 부득이하게 전역 state로 사용자가 어떤 페이지에 접근할 때 그 url을 저장하고, 사용자가 order-payments 페이지에 올 때마다 valid한 route를 통해 왔는지 검증해주었습니다! 

혹시 이렇게 State를 사용해 page url을 검증하는 것보다 더 효과적인 방법이 있을까요? 
추천해주실 만한 방법이 있으시다면.... 살짝 힌트를 주실 수 있을까요? 다시 한 번 반영해보겠습니다앗!!

2021-06-07 16:03 UTC, ddongule commented on src/hooks/usePagination.js
> +  const pageLength = data => Math.ceil(data.length / 5);
헉 맞습니다! 구현하기에 급급해 hook의 사용성을 더 고려하지 못했네요 ㅠㅠ😭 조금 더 사용성을 고려했어야 하는데.. 부끄럽습니다 하핫
hook을 사용하는 사람으로 하여금 원하는 만큼의 페이지를 보여줄 수 있게 할 수 있도록 코드를 수정했습니다! 

그리고 네이밍 부분도 반영했습니다! 제가 생각해도 진짜 함수이름같지 않은 이름이었네요.... 왜 이렇게 작성했을까요 과거의 제자신. . . . 🥲 🥲 🥲 

요 커밋에 [`37f1868`](https://github.com/woowacourse/react-shopping-cart/pull/51/commits/37f1868acb764a23a76a88f674f51a404fc4b9b5
)에 반영되어 있습니다!

2021-06-07 16:25 UTC, ddongule commented on src/hooks/useRandom.js
> +  const randomProducts = (data, length) => {
헉 그러네요!!!! Random Products를 위한 hook 인데, 이렇게 useRandom이라고 쓰니까, Products 도메인과 관련되어있는지 모르겠네요...... 세상에 앞으로 네이밍에 더 신경을 써야겠습니다!! ㅠㅠㅠㅠ 🥺 🥲 
해당 커밋은  [`17486bf `](https://github.com/woowacourse/react-shopping-cart/pull/51/commits/17486bfe5d2ec7c5c15120088217091f35dbc8a2)에 반영되어 있습니다!

2021-06-07 16:54 UTC, ddongule commented on src/hooks/usePagination.js
> +  const [page, setPage] = useState(1);
아하 당연히 1페이지부터 시작한다고 생각했는데, 제 생각에 편견이 있었다는걸 깨달았습니다!! 아악!! 🌟🌟🎉🎉
사용하는 곳에서 지정할 수 있도록 코드 변경했습니다!  

요 커밋은  [`96b3be `](https://github.com/woowacourse/react-shopping-cart/pull/51/commits/96b3be3b13331a62f38f5fb1cbd0a48ee72b985c)에 반영됐습니다!

2021-06-07 17:15 UTC, ddongule commented on src/hooks/usePagination.js
> +    page,
오오.. 저도 그렇게 생각합니다!!!!!!!!!!!!!!!!! 
일반적으로 사용하는 네이밍이라고 생각해 사용했는데, 오히려 너무 일반적인 느낌이라 사용자 입장에서는 이 변수가 어떤 데이터를 담고있는지에 대해 유추할 때에 불편할 수 있을 것 같습니다! 🥲 🥲
page는 firstPage로, index는 pageIndex로 변경해 조금 더 구체적으로 변수가 어떤 데이터를 담고있는지 설명했습니다! ㅎㅎ

해당 커밋은 [`33384a6`]( https://github.com/woowacourse/react-shopping-cart/pull/51/commits/33384a6fc2dc0ccc729799201423a0ba38d607a9)입니다!!

2021-06-08 01:44 UTC, ddongule commented on src/hooks/useCarts.js
> +    dispatch({
헉 처음에 toggleOneCheckBox, toggleAllCheckBox로 나누어서 구현하려다가, 결국 같은 toggle이라는 행동을 하는 것 같아서 하나로 합쳐서 만든 것이었는데, 생각해보니 dispatch에서는 서로 타입으로 만들어서 각기 다른 로직을 수행하게 해놓고 하나의 함수에서 분기처리로 이걸 나눴다는 점에서 일관성이 없었네요!!!
전체를 check하는 것과 하나를 check 하는 행동 자체도 같은 행동이라고 볼 수 없기도 해서 분리하는 편이 더 좋아보입니다! 오오옦 고민했었던 부분인데 다시 한 번 짚어주셔서 생각이 정리가 조금 된 것 같습니당!!!!! 감사합니다!! 🥺🥺🥺

그리고 이 부분을 redux로 관리하게 된 이유는요!! 
장바구니에 담긴 상품들을 가져오는 `GET` API를 호출할 때, 상품의 수량인`quantity`와 상품이 선택되었는지 여부를 나타내는`isChecked` 값이 들어오지 않습니다.ㅠㅠ
그래서 저는 장바구니에 들어온 상품들을 `GET`하는 API를 호출하면서, 내부 State로 저장을 할 때에 `quantity`와 `isChecked` 값을 함께 저장해서 사용했습니다! 호호홋..!!

- `quantity`의 경우에는 상품을 결제할 때, Navigation Bar, 상세 상품 목록 등 다양한 곳에서 사용되는 부분이라 전역 State로 관리하는 부분이 합당하다고 생각했습니다! 
- `isChecked`의 경우에는 ShoppingCart에서만 주로 쓰이고 있지만, 나중에 사용자가 장바구니에 다양한 상품을 담아두고 선택된 몇가지만 사려고 저장해놓고 다시 나갔다가 들어왔을 때 이렇게 isChecked 값을 전역 상태값으로 저장해두면 본인이 선택한 상품의 checked 상태까지 저장되어있어 조금 더 사용하기 편할 것이라고 생각했습니다! 지역적으로 사용하면 이런 부분이 불가능할 것이라고 생각이 되는데, 혹시 제가 생각하지 못하는 어떤 부분이 있을까요? 

헉 세상에 그런데 이 피드백을 통해 제가 전반적으로 Redux를 사용하게되면서 상태를 편리하게 사용하다보니 지역적으로 쓰일 수 있는 작은 State들 까지도 큰 고민 없이 전역상태로 관리하고 있다는 것을 깨달았습니다..! 🌟 다음부터는 어떤 앱을 만들어 전역 상태관리를 할 때에 이런 부분도 꼭 고려해서 앱을 설계해야겠다는 생각이 들었읍니다.. 😱😱 하악!!

2021-06-08 03:12 UTC, ddongule commented on src/components/ErrorBoundary/index.js
> +  componentDidCatch(error, errorInfo) {
헉쓰쓰 에러바운더리에서 `getDerivedStateFromError`는 오류가 발생하면 error상태를 업데이트해서 에러화면 띄워주는 역할, 그리고 `componentDidCatch`는 서버에 에러 로그를 전송하는 등의 사이드이펙트를 만들어주는 역할로 알고있어서, `componentDidCatch`에는 콘솔만 띄울 수 있도록 해놓았숩니다! 
몇번 확인해본 결과, 에러가 나면 에러 화면 자체는 그래도 잘 보여지고 있는 것 같은데, 혹시 제가 에러처리를 잘못 사용하고있는 부분이나 놓치고 있는 부분이 있다면 살짝 알려주실 수 있을까효..? ㅠㅅ ㅠ
에러처리를 많이 해보지 않아 저의 부족한 식견으로는 어느 부분이 잘못되었는지 눈에 띄지 않고 있습니다.. 
🥲 🥲 🥲 많이 해보다 보면 조금 보일까요..? ㅠㅠㅠㅠ

예전에 주셨던 [React에서 선언적으로 비동기 다루기
](https://jbee.io/react/error-declarative-handling-1/)도 보았는데 제가 잘 이해를 하지 못한 탓인지.. ㅠㅠㅠㅠ 아직 에러를 처리하는 방법이 너무 방대하고 어려워보입니다 따흐흐흑,,,,, 
살짝 힌트를 알려주시면 다시 한 번 고쳐보겠읍니다! 😱 😱

2021-06-09 02:05 UTC, JaeYeopHan commented on src/hooks/useCarts.js
> +    dispatch({
서버에서 받은 데이터가 과연 redux에 있어야 하는가도 고민해보시면 좋을 것 같네요!ㅎㅎ

2021-06-09 02:06 UTC, JaeYeopHan commented on src/hooks/useProducts.js
> +  const updateProductURL = () =>
음 router guard를 만들어주신 것 같아요! 구현 방법은 여러 방법이 있어서 살펴보셔도 좋을 것 같아요!

2021-06-09 02:07 UTC, JaeYeopHan commented on src/components/ErrorBoundary/index.js
> +  componentDidCatch(error, errorInfo) {
> error상태를 업데이트해서 에러화면 띄워주는 역할

제가 이 부분을 못봤나보네욯ㅎㅎ

2021-06-09 02:08 UTC, JaeYeopHan approved these changes
수고하셨습니다! 👏 👏 👏 
질문주신 부분에 대해서 코멘트 추가했어요!!

2021-06-09 02:08 UTC, merged

2021-06-22 08:20 UTC, ddongule commented
# 🍯 그루밍의 학습로그
## 🐝 [Redux] - 3

### 내용
- 전역 상태를 관리하는 Tool이다. 
- Action Type에 따라 Reducer를 호출해 State를 변경할 수 있다. 
- State가 자주 업데이트 되는 큰 어플리케이션을 만들 때 사용하면 좋다.
- Action을 호출하면 Action Store는 Store의 변화가 감지하고 View를 업데이트한다.

## 🐝 [Flux Design Pattern] - 3

### 내용
- Model View Controller 구조의 단점(양방향 데이터 바인딩의 단점, 모델의 변화에 따라 바로바로 시스템이 복잡해질 수록 예측 불가능한 상황들이 생기고, 데이터가 꼬여버릴 수 있다는 것)을 보완할 목적으로 개발됨
- 단방향 데이터 방식의 디자인 패턴이다. 
- 아래와 같은 구조를 가진다.
  ![](https://taeny.dev/static/8ef687083384d183ff57c029daa5a6c4/9f82e/flux.png)
  - Dispatcher - Flux의 데이터 흐름을 관리한다.
  - Store - 데이터(상태)를 저장한다.
  - View - Store의 변화를 감지하고 View를 업데이트 한다.

- Redux는 이런 Flux 패턴에 영감을 받아 개발되었는데, Redux는 Dispatcher라는 개념이 존재하지 않고, Single Store만이 존재한다. Redux는 Flux 패턴을 조금 더 쉽고 정돈된 형태로 쓸 수 있게 해준다.

## 🐝 [Local Storage, Session Storage, Redux Persist] - 3

### 내용
- Local Storage vs Session Storage
  - SessionStorage는 현재 사용하는 Tab이 닫히기 전까지 데이터가 유지된다.(새로고침해도 유지) 같은 페이지라도 다른 탭에 있으면 다른 곳에 저장된다.   
  - LocalStorage는 유저가 브라우저 캐시를 지우거나 직접 데이터를 Clear하기 전까지 데이터가 유지된다. 

- Redux Persist는 이러한 State 캐싱을 쉽게 사용할 수 있게 해준다.

### 링크
- https://medium.com/@jsh901220/react%EC%97%90-redux-%EC%A0%81%EC%9A%A9%ED%95%98%EA%B8%B0-a8e6efd745c9