[2단계 - 장바구니 미션] 체프(심문성) 미션 제출합니다
woowacourse/react-shopping-cart pull request #53
Opened 2021-06-08 06:41 UTC by Puterism

### [🚀 데모 페이지](https://puterism.github.io/react-shopping-cart/)

2단계 제출이 많이 늦어졌습니다... 죄송합니다 😭 
이번 리뷰도 잘 부탁드립니다 :)

## 2️⃣ 2단계에서 변경한 것들
- `redux-toolkit`을 적용하였습니다.
- 상품 상세 페이지를 구현했습니다.
- 전체적으로 기존 데이터를 이미 가지고 있거나 로드했던 상태라면, 그 데이터를 먼저 보여준 뒤, 최신 데이터를 fetch해와서 표시해주는 식으로 변경했습니다. 이 방법을 통해, 로딩 스피너를 띄우는 상황을 많이 줄일 수 있었습니다.
  - 이를 위해 장바구니 뿐만 아니라, 상품 데이터 및 주문 관련 로직도 모두 Redux 전역 상태에 두고 구현했습니다.
- 커스텀 훅으로 적극적으로 적용해보았습니다.
  - 지난 1단계 피드백 때 커스텀 훅을 우선 막 써보라는 피드백을 주신 덕분에, 커스텀 훅이 어떤 식으로 동작하고, 어떤 레이어에 있는지 감을 잡을 수 있었습니다. 커스텀 훅을 통해 컴포넌트 내부에 있는 비즈니스 로직이나 중복 사용될 수 있는 로직을 분리할 수 있었습니다.

## ✋ 리뷰해주실 때
- 위 내용들에 대해서 적용된 부분을 주로 살펴봐주시고 이에 관련하여 추가적인 피드백이 있으시거나, 이외의 부분에 주시고 싶으신 피드백이 있다면 부탁드립니다!
- `redux-toolkit`에 대한 내용은 제외해주셔도 괜찮습니다

## 🎸 기타
- 지금까지 좋은 리뷰 남겨주셔서 감사드리고, 점심 식사 때도 생각해볼 만한 주제와 이야기를 해주셔서 정말로 많이 감사드립니다 😄

2021-06-29 02:26 UTC, Vallista requested changes
안녕하세요 체프!
누락이 되어 있었는지 몰랐네요 ㅠㅠ 호딱 리뷰 했습니다!

## 전체적인 코드 리뷰

1. `COLOR.GRAY[900]` 처럼 배열을 써서 사용하는게 왜 더 좋은지? 모르겠어요. `COLOR.GRAY_900`이 더 좋지 않나요? COLOR.GRAY[900]을 하려면 일단, GRAY를 친 다음, [을 쳐서 그 안에있는 900을 알아와야 하는 3가지 단계가 있다면, GRAY_900은 G만 쳐도 연관된 정보가 다 나오기 때문에 훨씬 이득입니다. (코딩 단계에서요) 또한, vs code 상에서 해당 16진수 코드가 무엇인지 한 눈에 볼 수도 있구요.

2. 라우팅쪽에 중복되는 패턴이 보이는데 이 부분도 개선을 할 수 있을 것으로 보입니다!

3. React.ReactNode와 React.ReactElement 두 가지의 차이가 무엇일까요? 그리고 반환 형태의 고정이 필요하다면, parameter와 return type을 따로따로 정해주는 것보다, React.VFC를 쓰는게 더 좋겠습니다 :)

4. useAxios등에 any 타입을 써서 data 추론이 제대로 안될 것으로 보여요~ 예시를 드렸으니 해당 예시를 보시고 타입추론이 가능하도록 구현해주세요~

5. 지금 hooks의 레이어가 제대로 정돈된 것으로 보이지가 않습니다! useCart와 useCartPage 요 두 개는 합쳐도 될 것 같아요~ 페이지 단위로 함께 사용하고, API만 분리를 해서 지역적으로 사용되어야 한다면 useAxios 콜을 통해 처리를 하던. 그렇게 하는 방식이 좀 더 깔끔해보이긴 하네요~

2021-06-29 02:26 UTC, Vallista commented on src/hooks/useCartPage.ts
> +const useCartPage = () => {
오... 카트 페이지와 대응되는 1:1 훅이 또 따로 있군요..?

제가 보기에는 useCart와 useCartPage를 병합하고, API레이어를 따로 추출하는게 맞는 것 같아요.
지금 동일한 작업을 두 가지의 훅이 하는걸로 보이는데요~

2021-06-29 02:26 UTC, Vallista commented on src/hooks/useImageFallback.ts
> +  const [imageUrl, setImageUrl] = useState(defaultImageUrl);
오 내부에선 뭐 하는게 없군요? onload등의 캐싱등을 해주면 더 좋겠습니다~

2021-06-29 02:26 UTC, Vallista commented on src/pages/ProductDetailPage/ProductDetailPage.tsx
> +  const { id }: { id?: string } = useParams();
useParams 에 해당되는 type이 react-router-dom에 있지 않을까유?

2021-06-29 02:26 UTC, Vallista commented on src/slices/cartSlice.ts
> +export const GET_CART_ITEMS = 'cartItems/GET_CART_ITEMS' as const;
먼가 as const 타입으로 맹글어주는 함수를 만들면 좋겠네요.

```tsx
interface StringLiteral<T> {
    readonly target: T
}

function createStringLiteral<T>(target: T): StringLiteral<T>['target'] {
    return target as StringLiteral<T>['target']
}

const GET_CART_ITEMS = createStringLiteral('cartItems/GET_CART_ITEMS')
const ADD_CARD_ITEM = createStringLiteral('cartItems/ADD_CARD_ITEM')
const DELETE_ITEM = createStringLiteral('cartItems/DELETE_ITEM')
const DELETE_CHECKED_ITEMS = createStringLiteral('cartItems/DELETE_CHECKED_ITEMS')
const UPDATE_QUANTITY = createStringLiteral('cartItems/UPDATE_QUANTITY')
const CHECK_CART_ITEM = createStringLiteral('cartItems/CHECK_CART_ITEM')
const CHECK_ALL_CART_ITEMS = createStringLiteral('cartItems/CHECK_ALL_CART_ITEMS')
```

어? 뭔가 더 길어진 것 같네...

2021-06-30 10:24 UTC, Puterism commented on src/App.styles.ts
> +    darkBrown: COLOR.BROWN[300],
이렇게 관련 데이터까지 묶어서 레이어를 나누어야 한다고만 생각했었는데 코딩 단계를 생각하지 못했네요...
확실히 `GRAY_900`의 형태일 때가 개발할 때 좀 더 편하겠네요! 피드백 감사드립니다!

2021-06-30 10:33 UTC, Puterism commented on src/Routes.tsx
> +      <Route exact path="/products">
**✋ 질문 있습니다!**

배열 내의 객체들도 반복되는 형태이고, `Route` 또한 여러 라인에 걸쳐서 반복되는 형태로 작성되는데, 특별하게 배열로 관리했을 때의 이점이 잘 느껴지지 않습니다. `exact`와 같이 별도의 prop을 내려주어야 하는 상황일 때 배열 내의 객체에서 관리하게 된다면 별도로 조건부 렌더링까지 해주는 코드가 필요해지니 좀 더 손이 많이 가는 형태가 아닌가?하는 생각이 듭니다.

저는 `Route`라는 컴포넌트가 직접 작성된 형태가 좀 더 관리하기 좋은 형태라고 생각하는데, `Route` 데이터를 배열로 만들어서 관리할 때의 특별한 이점이 있을까요?

2021-06-30 11:18 UTC, Puterism commented on src/api.ts
> +  if (response.data instanceof Array || response.data instanceof Object) {
**✋ 질문 있습니다!**

`Array.isArray()`가 더 명시적이고 좋은 방법이 아닌가...?하는 생각에 `instanceof`와 `Array.isArray()`의 차이점에 대해서 찾아보았습니다.

`Array.isArray()`와 `instanceof Array`는 각각 다르게 동작하는데,
```js
const array = { __proto__: Array.prototype };
array instanceof Array; // true
Array.isArray(array); // false 
```
위와 같이 `Array.isArray`와 다르게 객체의 프로토타입을 확인하는 `instanceof`의 경우 `array` 객체의 프로토타입을 `Array.prototype`으로 정의해두었을 때, true로 판단하는 문제가 발생한다는 것을 알 수 있었습니다.

발리스타님은 어떤 면에서 `Array.isArray()`를 쓰지 않고도 좋은 처리 방법이라고 생각하셨는지 궁금합니다!

2021-06-30 11:32 UTC, Puterism commented on src/components/units/CartItem/CartItem.tsx
>  const CartItem = (props: IProps): ReactElement => {
`ReactElement`는 `React.createElement`가 호출되었을 때 리턴되는 객체의 타입이며 `type`과 `props`와 `key` 속성을 갖습니다.
`ReactNode`는 `ReactElement`의 superset이며 현재 컴포넌트의 하위에 렌더될 수 있는 컴포넌트의 타입입니다. 타입 정의를 찾아보니 다음과 같았습니다.
```ts
type ReactNode = ReactChild | ReactFragment | ReactPortal | boolean | null | undefined;
```

2021-06-30 11:33 UTC, Puterism commented on src/components/shared/Button/Button.styles.ts
>    font-size: ${({ size }) => sizeTable[size || T.ButtonSize.REGULAR].fontSize};
앗, 이 부분은 하나로 묶어줄 수 있겠네요! 피드백 감사드립니다!

2021-06-30 11:57 UTC, Puterism commented on src/pages/ProductDetailPage/ProductDetailPage.tsx
> +  const { id }: { id?: string } = useParams();
```js
const { id } = useParams<{ id?: string }>();
```
위와 같이 제너릭으로 넣어줄 수 있었군요... 피드백 감사드립니다!

2021-06-30 12:02 UTC, Puterism commented on src/slices/cartSlice.ts
> +export const GET_CART_ITEMS = 'cartItems/GET_CART_ITEMS' as const;
**✋ 질문 있습니다**

`as const`를 이용한 const assertion보다 작성해 주신 코드와 같이 별도로 만들어 준 `readonly` 타입을 wrap 해주어야 하는 특별한 이유가 있나요?
`as const` 라는 문법 자체가 바뀔 일은 없을 것 같고...
`as const`를 통해 `readonly`가 되는 것보다 해당 문자열 그 자체가 타입이 되는 방식에 어떤 문제가 있는 걸까요...?

2021-07-01 00:06 UTC, Puterism commented on src/hooks/useAxios.ts
> +  data: any | any[] | null;
axios response data에는 어떤 타입의 데이터가 올 지 전혀 알 수 없기 때문에 이와 같이 지정해줘야 한다는 생각을 했었습니다. 하지만 data에 대한 타입 지정을 any로 해주기 때문에 어디에나 할당할 수 있다는 점에서, 컴파일 타임에서 오류를 막을 수 있는 타입 지정의 이점이 사라지겠네요. 너무 짧은 생각이었네요 ㅠㅠ
Axios response의 타입 정의를 살펴보니 제너릭으로 지정해줄 수 있게 되어있다는 것을 알았습니다. 해당 부분도 같이 참고해서 다시 만들어보겠습니다. 피드백 감사드립니다!
```ts
export interface AxiosResponse<T = any>  {
  data: T;
  status: number;
  statusText: string;
  headers: any;
  config: AxiosRequestConfig;
  request?: any;
}
```

2021-07-01 10:47 UTC, Puterism commented on src/components/units/ProductItem/ProductItem.tsx
> +import useImageFallback from '../../../hooks/useImageFallback';
저도 공감합니다!
다른 폴더들에 관해서도 경로 축약을 할 수 있는 설정을 적용해서 수정해보겠습니다!

2021-07-01 11:07 UTC, Puterism commented on src/hooks/useCart.ts
> +const useCart = (): {
`useCart`는 장바구니 리스트의 데이터들을 불러오거나 추가하는 함수를 제공하는 역할을 하고 있습니다. 장바구니의 데이터들만 조회하고 추가하는 데 사용하는 다른 페이지에서 사용하는 중입니다.
https://github.com/woowacourse/react-shopping-cart/blob/1ad1d7a94e1f067dec603e2cb80742824de723f2/src/pages/OrderListPage/OrderListPage.tsx#L11

`useCart`는 `useAxios`를 사용하지 않고 Redux의 액션 디스패치 함수의 로직을 사용합니다. `useCart`에서 `data`나 `error`, `status`를 받지는 않고 Redux를 통해 데이터를 받아와서 반환하는 역할을 하고 있습니다.

2021-07-01 12:39 UTC, Puterism commented on src/hooks/useCart.ts
> +  const onAdd = async (productId: T.Product['productId']) => {
> 계속 보니 T.Product['productId'] 가 반복되네요~ 해당 부분을 단독 Type으로 때낼 수 있겠어요

반복해서 사용하는 타입에 대해 별도의 타입으로 떼어낼 수도 있겠네요!

> onAdd는 실행하는 함수이므로, on- 이 아니지 않을까요?

이벤트 핸들러 함수가 아니니 `on` prefix와는 맞지 않겠네요

피드백 감사드립니다!

2021-07-01 14:35 UTC, Puterism commented on src/hooks/useCartPage.ts
> +const useCartPage = () => {
`useCart`와 `useCartPage`가 각각 하는 역할은 다음과 같습니다.

장바구니 페이지에서만 사용하는 로직이 있고, 장바구니 페이지 뿐만 아니라 다른 페이지에서도 장바구니에 물건을 추가하는 기능이 있어서, 장바구니 데이터들을 활용하는 로직들은 `useCart`로, 장바구니 페이지에서만 사용되는 로직은 `useCartPage` 에 넣어두었습니다.

페이지 컴포넌트의 로직을 커스텀 훅으로 분리하는 과정에서 어떻게 하면 적절하게 재사용할 수 있을지 고민한 결과, 이렇게 페이지 컴포넌트에 종속되는 `useCartPage`, 그리고 다른 곳에서도 재사용될 수 있는 장바구니 관련 로직인 `useCart` 이렇게 두 가지로 나누게 되었습니다.

그렇다면 결국 페이지에 종속되고 재사용하지 못하더라도 컴포넌트 로직을 커스텀 훅으로 분리할 이유가 있는가? 에 대한 고민도 있었는데요.
일단 모든 로직을 커스텀 훅으로 넣어보자!하는 개인적인 시도도 있었고,
비대해지는 함수 컴포넌트 내의 로직을 어느 정도 다른 곳으로 분리할 수 있었다는 이점이 있었다고 생각합니다.

그럼에도 불구하고 현재 이 커스텀 훅의 구조에서 느껴지는 위화감은 지울 수가 없네요...

만약 두 커스텀 훅을 병합하게 된다면 다른 곳에서 사용하고 있는 장바구니 관련 로직을 중복해서 작성하게 될 것 같은데, 이와 관련해서도 어떻게 생각하시는지 궁금합니다!

2021-07-02 12:22 UTC, Puterism commented on src/pages/ProductDetailPage/ProductDetailPage.tsx
> +  const { id }: { id?: string } = useParams();
03ea113 에서 반영하였습니다!

2021-07-02 12:22 UTC, Puterism commented on src/components/units/ProductItem/ProductItem.tsx
> +import useImageFallback from '../../../hooks/useImageFallback';
03ea113 에서 반영하였습니다!

2021-07-02 12:22 UTC, Puterism commented on src/components/shared/Button/Button.styles.ts
>    font-size: ${({ size }) => sizeTable[size || T.ButtonSize.REGULAR].fontSize};
03ea113 에서 반영하였습니다!

2021-07-02 12:22 UTC, Puterism commented on src/App.styles.ts
> +    darkBrown: COLOR.BROWN[300],
03ea113 에서 반영하였습니다!

2021-07-02 12:31 UTC, Puterism commented on src/hooks/useCart.ts
> +  const onAdd = async (productId: T.Product['productId']) => {
cb235d3 에서 반영하였습니다!

2021-07-02 14:00 UTC, Puterism commented on src/hooks/useAxios.ts
> +  data: any | any[] | null;
>any?!?!?
제대로 타입 설정을 하는건 안될까유? 아니면 generic

10a6663 에서 반영하였습니다!

2021-07-02 15:01 UTC, Puterism commented on src/hooks/useAxios.ts
> +  data: any | any[] | null;
> 요런 형태로 API 레이어를 분리하고, axios는 그쪽에서 처리하도록 합시다요~
hooks에서는 해당 API를 래핑하여 사용 할 수 있도록~

`useProduct`라는 단일 상품 데이터를 가져오는 커스텀 훅을 새로 작성해서 적용해보았습니다!
651991c 에서 반영하였습니다!

2021-07-02 15:06 UTC, Puterism commented on src/hooks/useAxios.ts
> +  data: any | any[] | null;
해명할 거리가 한 가지 있어서 추가로 코멘트 남깁니다. (사실 변명에 가깝지만 ㅠㅠ)

651991c 에서 `useAxios`에 `errorMessage`를 같이 리턴해주도록 구현했는데요.

현재 서버에서는 유효하지 않은 요청을 보냈을 때의 에러 메시지가 body에 담겨져서 response가 오는 형태입니다.

`useAxios`를 최대한 범용적으로 만들고 싶었고, 에러 상황일 때 data가 에러 메시지임을 알 수 있게끔 타입 정의도 잘 해주고 싶었습니다. 하지만 string과 `Product` 타입과 계속 충돌이 일어나 잘 되지 않았습니다...

유효하지 않은 요청일 때 body에 에러 메시지가 오는 상황에서 `response.data`의 타입 정의에 대해서 개인적으로 좀 더 고민해보고자 합니다.

2021-07-02 18:43 UTC, Puterism commented on src/hooks/useImageFallback.ts
> +  const [imageUrl, setImageUrl] = useState(defaultImageUrl);
`useImageFallback`은 이미지의 링크를 불러오지 못하는 상품 아이템이 있어서, 이미지를 로드하지 못한다면 대체 이미지로 보여주게끔 처리하고 싶어서 작성한 훅입니다.

대체 이미지를 보여줄 때도 또 다시 로드가 발생하기 때문에 해당 이미지를 미리 캐싱해주면 더 좋겠네요! 피드백 감사드립니다!

2021-07-03 04:55 UTC, Puterism commented on src/components/units/CartItem/CartItem.tsx
> +      <Styled.Image src={currentImageUrl} alt={name} onError={onImageLoadError} />
https://github.com/realdennis/img-suspense
이 라이브러리의 컨셉과 비슷한 느낌일까요?

2021-07-03 10:56 UTC, merged

2021-07-05 02:45 UTC, Vallista commented on src/Routes.tsx
> +      <Route exact path="/products">
1. 일단 조건부 렌더링을 하지 않도록 코딩할 수 있습니다~
2. 애초에 Routes.tsx 는 정확한 역할을 하는 친구일까요? 렌더링을 별도로 분리해야할 만큼 최적화/도메인 분리가 필요한 파일일까요? 제가 보기에는 아닙니다. 그 이유는 Routes.tsx는 렌더링을 별도로 돌릴 만큼 큰 도메인 데이터를 갖고있지도 않고, 최적화 측면에서도 전혀 의미가 없습니다. 그렇기 때문에 configure 파일 + component의 중앙화 정도만 해주는데요~ 이 역할을 해줌으로써 렌더링이 왜 필요한가요? ㅇ-ㅇ?? 단순히 배열 + 개체 형태로 이루어져 있고, 그 데이터를 바이패스 받아 index.tsx에서 렌더링만 굴려주면 될 것으로 보입니다.

2021-07-05 02:48 UTC, Vallista commented on src/api.ts
> +  if (response.data instanceof Array || response.data instanceof Object) {
```
const array = { __proto__: Array.prototype };
array instanceof Array; // true
Array.isArray(array); // false 
```

이게 왜 문제인지 모르겠어요. ts를 쓰면 애초에 prototype에 직접 접근해서 수정할 문제가 없을텐데요!?
instanceof 를 사용하는 것은 ts의 기본적인 동작 (인스턴스 타입 - 힙 메모리에 할당된 객체 타입을 비교)이기 때문에
꼼수 혹은 어쩔수 없는 패턴을 사용한 프로토타입 체이닝이 아닌이상, instanceof 는 문제 없어보입니다~

2021-07-05 02:49 UTC, Vallista commented on src/components/units/CartItem/CartItem.tsx
>  const CartItem = (props: IProps): ReactElement => {
그렇다면 React.ReactElement를 넣는게 맞는걸까요 React.ReactNode를 넣는게 맞는걸까요?

2021-07-05 02:50 UTC, Vallista commented on src/components/units/CartItem/CartItem.tsx
> +      <Styled.Image src={currentImageUrl} alt={name} onError={onImageLoadError} />
넹 ErrorBoundary 예시가 적절하네여

2021-07-05 02:52 UTC, Vallista commented on src/hooks/useAxios.ts
> +  data: any | any[] | null;
DTO에 대해서 한 번 공부해보세요~

성공와 실패에 대한 타입 인터페이스는 별도의 레이어에서 관리되어야 하며, 명확해야합니다!
errorMessage가 아니라 error 그 자체를 generic으로 두어서 타입을 반환하는건 어떨까요?

2021-07-05 02:53 UTC, Vallista commented on src/hooks/useCart.ts
> +const useCart = (): {
오. API가 두 방법으로 호출되는군요... 그럼 RTK의 RTK query를 쓰는게 더 나았을텐데용~?

2021-07-05 02:53 UTC, Vallista commented on src/hooks/useCart.ts
> +const useCart = (): {
기술적 선택이 잘못된 것으로 보입니다..

2021-07-05 02:54 UTC, Vallista commented on src/hooks/useCart.ts
> +const useCart = (): {
😱

2021-07-05 02:57 UTC, Vallista commented on src/hooks/useCartPage.ts
> +const useCartPage = () => {
ㅋㅋ 지금 구조의 위화감은 제가 보기에

hooks/useCart 와 hooks/useCartPage 가 같은 위상에 있어서 그런것 같아요 ㅋㅋ
그래서, 해당 부분을 page에 1:1 매칭되는 레이어와 공용으로 사용될 수 있는 레이어를 분리하는게 좋겠습니다.

hooks/business
hooks/common

정도로 나눠서 common에는 공통으로, business에는 1:1에 매칭되는 레이어로 구분

2021-07-05 02:57 UTC, Vallista commented on src/hooks/useCartPage.ts
> +const useCartPage = () => {
사실 지금 시도는 괜찮다고 생각해여 ㅋㅋ 다만 레이어에 대해서 한 번 생각해보시라는 의미로 피드백을 드린 것이었습니다

2021-07-05 02:58 UTC, Vallista commented
@Puterism 피드백 달았씸다