[1단계 - 장바구니]록바(김상록) 미션 제출합니다.
woowacourse/react-shopping-cart pull request #85
Opened 2022-05-12 08:38 UTC by lokba

2022-05-14 09:23 UTC, EungyuCho requested changes
록바님 처음 뵙네요! 잘 부탁드려요 😃 

바로 질문으로 들어갈게요~ 1, 3, 4번 질문은 아래 코멘트에서 답변을 드렸어요!
> 적절하게 상속이 이루어졌는지 궁금하다.

우선 버튼의 경우 굳이?.. 상속해야할까 생각이 들었고 추가로 적어주신 Flex 예시가 코드에 없어서 이해하기 힘드네요 😭 

> 재사용이 많지 않은데 이렇게 나누는 것이 적절한지 궁금하다.

사실 최상위 StyledButton은 border, background, cursor를 설정해주는 것 외에 별도로 역할을 하고있지 않아서 그대로 사용할 수도 없는 형태라.. 재사용을 하고싶으시다면 별도로 style을 다시 입히지 않고 사용할 수 있게 공용 컴포넌트로 만들어봅시다~ [참고](https://chakra-ui.com/docs/components/form/button)

> 상속 vs Props로 스타일을 변경하기 두 가지 방식이 어떤 상황에 적절한지 궁금합니다.

상속: 컴포넌트들에서 공통적으로 사용하는 동일한 속성이 있을 때 동일한 속성 기준으로 다시 상속을 고려해본다.
Props: 재사용을 패턴화 할 수 있을때 사용한다. (theme이라거나 size 등 조건에 따라 여러 스타일이 변경될 때)
질문을 보고 생각해봤는데 딱 이정도 기준을 잡고가는 것 같아요 🤔 

코드 잘 봤어요 록바님~

디렉터리 위계를 맞추려는 고민까지 하시다니.. 👍 
코드도 선언적으로 작성하려고 노력하신게 보여서 좋았어요.
전체적으로 깔끔하다는 느낌을 많이 받았어요.

코멘트를 달았으니 확인부탁드릴게요!
고생하셨습니다 🙂

2022-05-16 04:58 UTC, lokba commented on src/components/common/Styled/index.jsx
> +`;
이런!!! 막판에 해당 컴포넌트를 추가했는데, 실수를 해버렸네요. 

첨부해주신 사이트 너무 좋네요!! 재사용성을 위한 컴포넌트에 대한 좋은 예시들이 많네요 👍 

해당 사이트 참고하면서, Flex 컴포넌트를 구현했습니다.
```jsx
const Flex = styled.div`
  ${({
    direction = 'row',
    wrap = 'nowrap',
    justify = 'normal',
    align = 'normal',
    gap = '0',
  }) => css`
    display: flex;
    flex-direction: ${direction};
    flex-wrap: ${wrap};
    justify-content: ${justify};
    align-items: ${align};
    gap: ${gap};
  `}
`;

```
기존의 방식보다 재사용성이 높을 것으로 보이고, 확장을 하고 싶으면 props로 얼마든지 가능할 수 있다는 것이 장점인 것 같습니다.

[커밋 링크](https://github.com/woowacourse/react-shopping-cart/pull/85/commits/0766291361d2296443b5507ab96662570ce36795)

2022-05-16 05:00 UTC, lokba commented on src/index.js
> +loadProductList();
> 일반적인 프로덕트 상황을 가정하고 미션을 진행하는 것이 좋다고 생각한다.

저도 아사님의 생각에 공감합니다. 😎
기존 방식을 생각하고 경험해봤다는 것에 의미를 두고, 
일반적인 프로덕트 상황으로 변경하였습니다. 

[커밋 링크](https://github.com/woowacourse/react-shopping-cart/pull/85/commits/a2afad0e474d9af48354090377132888e60b8f09

2022-05-16 05:04 UTC, lokba commented on src/App.jsx
> +          <Route path="/react-shopping-cart/product/:id" element={<ProductDetail />} />
page라고 하면, 전체적인 컨텐츠를 다 포함하고 있어야 한다고 생각하여
`ProductList`로 폴더 네이밍을 지었는데요.



> 내부 컨텐츠의 네이밍이 `page`가 안될 이유는 없다.

아사님의 생각이 저의 생각을 뒤집어 주셨습니다.
라우팅으로 매칭되는 컴포넌트들은 `page`폴더 하위에 배치했습니다. 


[커밋 링크](https://github.com/woowacourse/react-shopping-cart/pull/85/commits/a2b8c69fb19ac7b9d238a2f306a836dd88d0ca09)

2022-05-16 05:09 UTC, lokba commented on src/App.jsx
> +          <Route path="/react-shopping-cart/product/:id" element={<ProductDetail />} />
`Outlet`라는 친구 적용해봤습니다. 
들어만 봤지...적용해 본적이 없는데요. 굉장히 좋은 친구네요ㅎㅎ 

[커밋 링크](https://github.com/woowacourse/react-shopping-cart/pull/85/commits/a71c21920c55c1d55b186b252330071494546f75)

2022-05-16 05:17 UTC, lokba commented on src/components/Product/index.jsx
> +  Price: styled.p``,
맞습니다!! 
어떻게 생각하실지 모르겠지만, 저는 통일성을 추구하는 개발자입니다. 😇

2022-05-16 05:18 UTC, lokba commented on src/components/Product/index.jsx
> +          <Styled.Price>{price} 원</Styled.Price>
감사합니다. 당연한 디테일인데, 놓치고 있었네요.
금액과 관련된 부분은 `toLocaleString` 적용했습니다. 🎯

2022-05-16 05:25 UTC, lokba commented on src/components/Product/index.jsx
> +        <img src={thumbnail} alt="thumbnail" />
아사님~ 궁금한게 있는데요. 😎

저는 현재 코드 리뷰 스터디를 진행하고 있는데요. 
해당 스터디는 크루원들의 코드 리뷰를 보면서, 의미있는 내용을 정리하는 스터디입니다.

이전부터, 아사님이 공유해주시는 블로그나 레퍼런스가 상황에 굉장히 적절하다고 생각했는데요.
관련된 블로그나 레퍼런스는 어디에 기록을 하시는건가요?✍️

2022-05-16 05:27 UTC, lokba commented on src/components/ProductList/index.jsx
> +        <Styled.EmptyMessage>상품 목록이 존재하지 않습니다.</Styled.EmptyMessage>
리덕스에서 사용되는 각각의 reducer에서 initialState에  `isLoading` 필드를 추가했습니다.

- 리덕스에 상태가 저장되기 전 : `isLoading : true`
- 리덕스에 상태가 저장된 경우 : `isLoading : false`

위와 같이 변경하였고, 로딩 중 상태에 `LoadingSpinner` 컴포넌트를 렌더하게 보완하였습니다.

2022-05-16 05:34 UTC, lokba commented on src/components/common/Button/Button.stories.jsx
> +};
필요가 있다고 생각합니다.

해당 스토리는 아주 단순한 스타일링 된 `button` 컴포넌트인데요.

제가 필요있다고 생각하는 이유를 적어보겠습니다.

제가 생각하는 스토리북은 테스트 코드를 작성하는 이유와 비슷하다고 생각합니다.
제가 생각하는 테스트 코드를 작성하는 이유 중 하나는 테스트 코드 자체가 usecase에 대한 명세로 사용될 수 있기 때문입니다.
스토리북도 마찬가지라고 생각합니다.
새로운 개발자가 프로젝트에 투입된다고 하였을 때, 가장 편하게 UI를 볼 수 있는 것은 스토리북이라고 생각합니다.
아주 간단한 스타일링 된 `button` 컴포넌트가 포함되어있다면 
`해당 프로덕트의  Default Button UI는 이렇게 생겼구나`라고 알 수 있다고 생각합니다.

2022-05-16 05:37 UTC, lokba commented on src/components/common/Header/index.jsx
> +const Styled = {
찬성합니다. 🏎🏎🏎
저도 해당 폴더를 딱 들어갔을때, 기대하는 코드는 해당 컴포넌트 코드라고 생각합니다.

[커밋 링크](https://github.com/woowacourse/react-shopping-cart/pull/85/commits/cb40ab605cce32ffc245dbb4cdd98480e34ce374)

2022-05-16 05:39 UTC, lokba commented on src/components/common/Header/index.jsx
> +    </Styled.Wrapper>
감사합니다. 오랜만에 칭찬을 받는 것 같네요.😎

2022-05-16 05:42 UTC, lokba commented on src/components/common/Styled/index.jsx
> +  background: #73675c;
이전에 @자스민 크루원의 피드백에서 봤습니다.

도메인이 들어간 color 이름보다,
tailwind 사이트와 같이 작성하면 이해하기도 쉽고 활용도 또한 넓다고 생각이 듭니다. 
`ThemeProvider` 사용해서 수정하였습니다.🎯

[커밋 링크](https://github.com/woowacourse/react-shopping-cart/pull/85/commits/be34e69b28f0fd51d4e6e5a51d48afb9b4a2c7b3)

2022-05-16 05:44 UTC, lokba commented on src/components/ProductList/index.jsx
> +const ProductList = () => {
> `page/ProductList/UniqueProductComponent/index.js `

이렇게도 생각할 수 있군요. 간직하고 있겠습니다. 적절한 상황이 온다면 적용해보겠습니다.

page 폴더 만들어서 수정 완료했습니다. 🎯

2022-05-16 05:47 UTC, lokba commented on src/components/common/Button/index.jsx
> +};
아주 좋습니다. 😈(리뷰가 굉장히 매콤하네요ㅋㅋ)
수정 완료했습니다. 🏎🏎🏎

2022-05-16 08:44 UTC, lokba commented
안녕하세요 아사님! 주말 잘 보내셨나요? 

저는 주말동안 학교 과제도 하고, 영화도 보고, 나름대로 휴식을 좀 취한 것 같네요.
아사님도 좋은 주말 보내셨길 바랍니다. 😎😎😎

질 좋은 코멘트를 주셔서, 많은 도움이 되었습니다. 
아사님이 코멘트 달아주신 부분은 모든 부분 반영했습니다.

추가적으로 개선한 사항은 아래와 같습니다.

### 1. 전반적인 디렉토리 재배치 
`구조만 보더라도, 해당 폴더에 어떤 내용이 담겨있는지 알 수 있는가?`의 관점에서
기존에 문제가 있던 폴더를 나누고, 전반적으로 재배치 시켰습니다.

<br>

### 2. 에러 처리
잘못된 API를 호출하게 되면, Not-Found 페이지로 리다이렉팅 하였습니다.
```jsx
loadProductList()
      .then((res) => dispatch(setProductList(res)))
      .catch(() => navigate('/react-shopping-cart/notFound'));
```

<br>

### 3. 리덕스 상태 존재 시, API 미호출 및 액션 미호출
```jsx
useEffect(() => {
    if (isLoaded) return;

    dispatch(startProductList());
    loadProductList()
      .then((res) => dispatch(setProductList(res)))
      .catch(() => navigate('/react-shopping-cart/notFound'));
  }, []);
```

위와 같이 함으로써, 불필요한 통신을 최소화하였습니다.

<br>

2022-05-16 12:20 UTC, EungyuCho commented on src/App.jsx
> +          <Route path="/react-shopping-cart/product/:id" element={<ProductDetail />} />
> es6가 처음 도입되었을 때도, 그때의 개발자도 이와 같이 느꼈겠죠?? 🤔

그럴 것 같아요 🙂 
커뮤니티에서 다양한 논의를 통해 업그레이드 되니 니즈들을 최대한 반영해주는 것 같아요. (~~항상 그렇진 않지만요 ㅜㅜ~~)

2022-05-16 12:21 UTC, EungyuCho commented on src/components/Product/index.jsx
> +  Price: styled.p``,
스타일 컨벤션이라면야... 🤔  
근데 저도 비슷한 병 있어요 ㅋㅋㅋㅋ...

2022-05-16 12:23 UTC, EungyuCho commented on src/components/Product/index.jsx
> +        <img src={thumbnail} alt="thumbnail" />
어.. 음...
정말 자주보는 블로그 같은 경우 북마크에 저장해뒀는데 그렇게 많진 않아요.

해당 상황에 보충하면 좋겠다 싶은 내용이 있으면 구글링으로 관련 레퍼런스를 드립니다  😎 (~~산지직송이 최고~~)

2022-05-16 12:42 UTC, EungyuCho commented on src/components/common/Button/Button.stories.jsx
> +};
맞아요 문서화 목적으로 컴포넌트를 storybook에 최대한 올리는건 동감합니다 🙂 

저도 storybook을 최대한 활용하는데 동의하지만 작성해주신 Button 컴포넌트가 단순하다보니 굳이 문서화를 할 필요가 있었을지 의문이 들었었어요.

아무래도 컴포넌트에 대한 문서화를 할 때 스타일링을 이래저래 바꿔보면서 어떤 형태가 될 지 유추가 되는 컴포넌트가 있어야 usecase를 보고 디자인대로 바로 사용할 수 있다고 생각하는데 해당 Button컴포넌트는 결국 직접 하나부터 끝까지 커스텀해야하는 형태라... storybook에 올리기에는 애매했다고 생각했었어요 😅 

록바님의 생각에도 동의합니다! 위 의견은 제 주관적 의견이니 참고만 해주세요 🤩

2022-05-16 13:11 UTC, EungyuCho requested changes
반영하느라 고생하셨어요 록바님! 👏 

> 저는 주말동안 학교 과제도 하고, 영화도 보고, 나름대로 휴식을 좀 취한 것 같네요. 아사님도 좋은 주말 보내셨길 바랍니다. 😎😎😎


저도 잘 보냈어요! 코딩을하고 코딩을하고 코딩을 했습니다  😎😎😎

본론으로 들어가서 

> CardButton, CardDetailButton를 어디에 둘지 고민을 많이 하였습니다.

케이스 바이 케이스인 것 같은데요~
개인 프로젝트라면 코드라인 길이에 따라 결정할 것 같아요. 200줄 넘어가면 관리하기가 힘들어져서 그때마다 부랴부랴 분리하곤 하는데요.
지금 생각해보면 분리하는편이 더 낫겠네요 💦
 
얼마나 길어질지 모르니 파일 구조 일관성을 위해 분리하는편이 좋다고 생각됩니다~ 4~500줄이 된 index파일에 개의치 않으신다면 그냥 가져가셔도 무방할 것 같아요 😆 

위에 예시는 같은 위계의 컴포넌트이고 만약 해당 컴포넌트 내부에 있는 별도 컴포넌트라면 코멘트에서 보신 것 처럼 해당 컴포넌트 파일이 있는 위치에서 폴더로 하위 컴포넌트를 생성하는 방향을 꼭 고려해주셨으면 좋겠어요 (이거 나중에 컴포넌트 찾기 진짜 어려워요 😭 )

여튼 코멘트로 조금 더 괴롭혀드리고 싶었지만... 잘 짜주셨네요 😢 
Step2를 기대해주세요! 다음 스텝에 뵐게요!

2022-05-16 13:11 UTC, merged

2022-05-17 02:44 UTC, lokba commented on src/components/common/Button/Button.stories.jsx
> +};
감사합니다~ 아사님의 의견 도움이 되었습니다.
아무래도 storybook이 미숙해서, 그렇게 생각할 수도 있겠네요ㅎㅎ

2022-05-17 02:45 UTC, lokba commented on .storybook/preview.js
> +};
하하~ storybook에서 에러처리는 신경 못썼네요ㅠㅠ
step2에서 반영하겠습니다~~ 🏎🏎🏎