[1단계 - 장바구니] 하리(이아현) 미션 제출합니다.
woowacourse/react-shopping-cart pull request #89
Opened 2022-05-12 08:41 UTC by LAH1203

월터님 안녕하세요! 만나뵙게 되어 반갑습니다 😄

#### [데모 페이지](https://lah1203.github.io/react-shopping-cart/)

<br>

### 필수 요구사항

- [x] Redux를 활용한 상태 관리
- [x] REQUIREMENTS.md에 요구 사항 도출
- [x] Mock Data 활용 (Schema 설계까지)
  - [x] JSON Server
- [x] 상품 목록 페이지

<br>

### 선택 요구사항

*추가적으로 구현한 것들만 적어보았습니다 🌸*

- [x] 상품 상세 페이지
- [x] 상품 호버링 애니메이션

<br>

사실 구현해보고 싶은 것들은 많았는데, 이번에 여러 것들(개념, 오류 등)을 찾아 헤매는데 시간을 많이 써버려서 시간이 부족했습니다 😅 2단계 때 필수 구현 사항을 모두 마친 후에 시간이 남는다면 추가해보려고 합니다 !

<br>
<hr>

```
📦src
 ┣ 📂actions
 ┃ ┗ 📜actions.ts
 ┣ 📂components
 ┃ ┣ 📂Layout
 ┃ ┃ ┗ 📂Header
 ┃ ┃ ┃ ┣ 📜Header.tsx
 ┃ ┃ ┃ ┗ 📜RightMenu.tsx
 ┃ ┣ 📂Logo
 ┃ ┃ ┗ 📜Logo.tsx
 ┃ ┣ 📂PlainLink
 ┃ ┃ ┗ 📜PlainLink.tsx
 ┃ ┣ 📂ProductCard
 ┃ ┃ ┗ 📜ProductCard.tsx
 ┃ ┗ 📂ProductCardGrid
 ┃ ┃ ┗ 📜ProductCardGrid.tsx
 ┣ 📂configs
 ┃ ┗ 📜api.ts
 ┣ 📂pages
 ┃ ┣ 📂MainPage
 ┃ ┃ ┗ 📜MainPage.tsx
 ┃ ┣ 📂NotFoundPage
 ┃ ┃ ┗ 📜NotFoundPage.tsx
 ┃ ┗ 📂ProductPage
 ┃ ┃ ┗ 📜ProductPage.tsx
 ┣ 📂reducers
 ┃ ┗ 📜index.ts
 ┣ 📂styles
 ┃ ┣ 📜GlobalStyle.ts
 ┃ ┗ 📜theme.ts
 ┣ 📜App.tsx
 ┣ 📜index.tsx
 ┗ 📜types.ts
```

이번 미션에는 `redux`, `react-redux`, `redux-thunk`, `redux-promise`를 사용하여 redux를 미션에 도입해봤고, 그 안에서 서버에 데이터를 요청하는 부분은 `axios`를 사용하였습니다. 또, 기본적인 스타일링은 `styled-components`, `styled-reset`을 사용하여 global 스타일, 테마 등을 지정해주었습니다.

<br>

## 질문

이번에 redux를 이런 식으로 사용해본 것은 처음이라 이와 관련해서 괜찮은건지, 아니면 어떻게 짜는게 좋은지, 명확하지 않은 의문들이 좀 많아요 😭 괜찮으시다면 이 부분을 자세히 피드백 주셨으면 좋겠습니다 🙏

- (ex) `actions.ts`에서 action들을 미리 선언하여 사용해봤는데, 이런 식으로 promise를 payload로 전달해줘도 괜찮은 것인지
- (ex) 지금 redux store에는 불러온 상품 목록, 클릭한 상품 정보를 저장하는데 이 정보들을 state가 아닌 redux에 저장해서 사용하는게 맞는지

<br>

그럼 이번 미션 잘 부탁드립니다 ! 감사합니다 😊

2022-05-13 09:41 UTC, inwalter99 commented
안녕하세요. 리뷰어 월터입니다.
다름이 아니라 리뷰가 조금 늦어질 것 같아 미리 양해의 말씀을 드리려고 왔습니다 🥲 
개인적인 사정이 있어서 시간을 못내고 있습니다 ㅜ.ㅜ 리뷰를 어느정돈 해놨는데 아직 부족해서,,, 늦어도 48시간 전에는 리뷰드리도록 할게요!
그전까지 추가로 반영할 게 있으시면 반영부탁드립니다!

2022-05-14 09:12 UTC, inwalter99 requested changes
코드 잘 봤습니다. 기다려주셔서 감사합니다 하리님 8ㅅ8
코드와 컴포넌트 등은 전반적으로 잘 작성된 것 같습니다! 잘 읽었습니다!
다만 `redux-promise-middleware` 를 사용했음에도 다른 상태(로딩, 에러 등)을 다루지 못한 것은 아쉽습니다 🥲 이 부분이 구현되면 좋겠습니다!

추가로 api 패칭 등 좀 더 다양한 부분은 2단계가면 리뷰를 더 드릴 수 있을 것 같아요!
지금까진 대부분 좋습니다ㅎㅎ 드린 코멘트들 확인부탁드릴게요!

질문 주신 부분은 따로 코멘트 드리겠습니다.
고생하셨습니다!

2022-05-14 09:13 UTC, inwalter99 commented
> actions.ts에서 action들을 미리 선언하여 사용해봤는데, 이런 식으로 promise를 payload로 전달해줘도 괜찮은 것인지
`actions.ts에서 action들을 미리 선언하여 사용해봤는데` 랑 뒤의 말이 이어지는 질문일까요?
**redux-promise-middleware** 를 사용하려면 `promise를` `payload`로 전달해줘야하는 걸로 이해를 했습니다!
 `actions.ts에서 action들을 미리 선언하여 사용해봤는데` 은 어떤 질문이신지 좀 더 자세하게 설명 부탁드릴 수 있을까요?

2022-05-14 09:16 UTC, inwalter99 commented
> 지금 redux store에는 불러온 상품 목록, 클릭한 상품 정보를 저장하는데 이 정보들을 state가 아닌 redux에 저장해서 사용하는게 맞는지

`store` !== `state` 가 아니라 `state` 를 전역으로 접근할 수 있도록 저장하는 곳(?)이 `store` 인데용
`상품 목록`, `클릭한 상품 정보` 등을 각 컴포넌트의 상태로 들고 있을지, 전역적으로 들고 있을지에 대한 질문으로 이해하면 될까요?
그러면 다시 페이먼츠 미션으로 돌아가서 [context api 가 나오게된 배경, 목적](https://reactjs.org/docs/context.html#:~:text=Context%20provides%20a%20way%20to%20share%20values%20like%20these%20between%20components%20without%20having%20to%20explicitly%20pass%20a%20prop%20through%20every%20level%20of%20the%20tree.) 등을 이해해보면 좋을 것 같아요. redux 는 전역적인 상태저장소 외에도 다른 문제를 해결하기 위해 나온 것이지만 질문 주신 부분은 위의 링크로 어느정도 답을 드릴 수 있을 것 같습니다!

2022-05-15 06:32 UTC, LAH1203 commented on src/App.tsx
> +          <Route path="/product/:id" element={<ProductPage />} />
앗 넵! 상수화시켜보겠습니다 👍
https://github.com/woowacourse/react-shopping-cart/pull/89/commits/3aacae5720bd8863da6a4f3b9b18837a5ba44255 https://github.com/woowacourse/react-shopping-cart/pull/89/commits/daa8be89caa267e88150acc50ef3698a959fab85

2022-05-15 06:32 UTC, LAH1203 commented on src/components/ProductCard/ProductCard.tsx
> +import { Product } from '../../types';
헉 이런 방법이 있었다니.. @_@
정리하고 나니까 깔끔해서 너무 좋네요! 감사합니다 😆 https://github.com/woowacourse/react-shopping-cart/pull/89/commits/f55cdfc3fb24f423b8da191a51d70bc05959f860

2022-05-15 06:32 UTC, LAH1203 commented on src/components/PlainLink/PlainLink.tsx
> +function PlainLink({ to, disabled = false, children }: Props) {
이 부분도 페어를 하면서 중간에 살짝 의견 차이가 났던 부분인데요.
저는 기존의 'react-router-dom'의 Link를 다른 이름으로 가져와서 저희가 가공해서 내보내는 컴포넌트의 이름은 `Link`를 유지하길 바랐고, 페어는 저와 반대로 가져오는 것은 이름을 그대로 유지하고 만드는 컴포넌트의 이름을 다른 것으로 만들기를 원했습니다.
결론적으로 컴포넌트 이름을 바꾸기로 결정이 났지만, 저도 역시 이질감이 없는 `Link`라는 이름이 좋은 것 같아요 ㅎㅎ 컴포넌트의 이름을 PlainLink → Link로 변경해주도록 하겠습니다 😊 https://github.com/woowacourse/react-shopping-cart/pull/89/commits/9a55f1558a717e00b5fe0017b11e1c1d901d0587

2022-05-15 06:32 UTC, LAH1203 commented on src/components/PlainLink/PlainLink.tsx
> +  }
막판에 이것저것 구현하고 정리하느라 이 부분을 빼먹어버렸네요 😅
바로 수정하였습니다 ! https://github.com/woowacourse/react-shopping-cart/pull/89/commits/fb352e730e2ebff9cf59c630e1ba52c919dd6e81 알려주셔서 감사합니다 👍

2022-05-15 06:32 UTC, LAH1203 commented on src/components/ProductCard/ProductCard.tsx
> +);
네! 저도 분리를 하는게 맞다고 생각하는 쪽입니다 :) 우선 쓰이는 두 곳에서 width, height, fill이 다르기 때문에 그 부분을 인자로 받아 svg를 반환하도록 만들어주었습니다 https://github.com/woowacourse/react-shopping-cart/pull/89/commits/6effdecba6c3a7e47319fe7460a3a5ed6cf5119c

근데 아무래도 인자를 받아서 그에 따라 그려주는 것이다보니 컴포넌트 같이 변했다는 생각도 들어서 기존에 svg 파일 등을 넣어놓던 assets 폴더에 그대로 놔둬도 되는걸까? 살짝 의문도 들고 궁금해지기도 하네요 ! 혹시 이에 대해서도 이렇게 만들 경우 컴포넌트와 애셋 중 어느 성격에 좀 더 가까울지, 의견을 주실 수 있을까요? 🤔

2022-05-15 06:32 UTC, LAH1203 commented on src/components/ProductCard/ProductCard.tsx
> +          <p>{price?.toLocaleString('ko-KR')} 원</p>
> `product` 타입이 `Product`가 아닌 `Partial<Product>`인 이유
- 우선은 저희가 `Product` 타입에 넣은 값들을 모두 productCard에서 사용하는 것이 아니다보니 이에 대해 하나하나 설정해주는 방법밖엔 없었어요! 근데 Product 타입은 후에 다른 기능 추가 시 다른 곳에서도 충분히 사용될 가능성이 있으므로 범용성 있게 하나로 빼서 사용하는 편이 좋겠다고 생각했습니다. 그럼 Omit이나 Pick 같은 것을 사용하면 되지 않느냐, 라는 의견도 있었는데 우선은 간단히 Partial을 쓰자고 페어분이 제안해주셔서 이렇게 적용하게 되었습니다.
- 저는 사실 아직 'Partial보다는 Omit이나 Pick이 맞지 않을까?'란 생각이 살짝 남아있기는 한데, 월터님은 어떻게 생각하시나요? 반드시 들어올 데이터는 명확하게 명시를 해주는 편이 나을까요?

> `price`가 넘어오지 않을 경우
- 정상적인 경우에는 넘어오지 않을 때는 없습니다 😅 Partial로 설정해주다보니 price가 undefined가 될 경우가 있어서 옵셔널 체이닝을 적용해주었는데요, 만약 Omit이나 Pick을 적용해준다면 이는 필요없을 것 같습니다 😣

2022-05-15 06:32 UTC, LAH1203 commented on src/index.tsx
> +);
헉 넵! 정리하였습니다 👍 https://github.com/woowacourse/react-shopping-cart/pull/89/commits/a1c19f9b400495ac1034b610ffd3a9238bf4cdc6
추가적으로, 원래 src 하위에 위치하던 `actions`와 `reducers` 폴더도 redux와 관련된 것들이기에 따로 관리하는 편이 오히려 불편하다는 생각이 들어, 새롭게 만들어준 store와 같이 redux 폴더 내에 정리해주었습니다 🙂

2022-05-15 06:32 UTC, LAH1203 commented on src/pages/MainPage/MainPage.tsx
> +  }, [dispatch]);
지금은 데이터가 적어서 상관은 없지만, 만약 나중에 데이터가 많아진다면 이를 그려주는 과정에서 초기에 레이아웃이 깨지지 않도록 해주는 것이 좋다고 생각해서 `useEffect` 대신 `useLayoutEffect`를 사용해보았는데요. 반대로 동기적으로 실행되므로 데이터를 모두 가져올 때까지 사용자가 기다려야 한다는 단점도 있는 것 같네요 😢
월터님은 주로 이런 상황에서 어떤 방식을 사용하시나요?

2022-05-15 06:33 UTC, LAH1203 commented on src/components/ProductCardGrid/ProductCardGrid.tsx
> +function ProductCardGrid({ productList }: Props) {
모든 상품 정보 (메인 페이지) https://github.com/woowacourse/react-shopping-cart/pull/89/commits/ba9237175c68802b56dd36847b5aa3a88b4a84eb
상품 상세 정보 https://github.com/woowacourse/react-shopping-cart/pull/89/commits/7965e277e23272042b6a53d8e5fa79ff4b175c98

각각의 api에 요청하는 동작에 현재 진행 상황 (loading, complete, error) 을 추가해보았습니다. 각각 진행, 성공, 실패 여부에 따라 상황이 달라지며, 이를 사용하여 사용자에게 로딩중인지, 정보 가져오기에 실패했는지 등의 예외 상황을 보여주도록 만들어봤습니다. (현재는 피드백을 반영하는게 우선이므로 우선 텍스트로 해봤는데, 나중에 2단계 구현 후 수정해볼 예정입니다 😊)
추가적으로, 말씀해주신 productList가 비어있을 경우에도 텍스트로 예외 상황을 보여주도록 추가하였습니다 ! thunk를 처음 사용해봐서 많이 헤맸네요 😅 혹시 이상하게 사용하거나 잘못 적용한 부분이 있다면 알려주세요 !

2022-05-15 06:33 UTC, LAH1203 commented
> actions.ts에서 action들을 미리 선언하여 사용해봤는데 랑 뒤의 말이 이어지는 질문일까요?
> redux-promise-middleware 를 사용하려면 promise를 payload로 전달해줘야하는 걸로 이해를 했습니다!
> actions.ts에서 action들을 미리 선언하여 사용해봤는데 은 어떤 질문이신지 좀 더 자세하게 설명 부탁드릴 수 있을까요?

- 앗 actions를 파일로 나눠서 promise를 적용해본게 처음이라 낯설어서, 이렇게 사용하는게 맞는 것인지 혹은 사용하는데 더 좋은 방법이 있을지 등이 궁금했습니다 😅
- 우선은 위에서 언급해주신 thunk를 만들어 사용하니 `redux-promise-middleware`의 사용 목적이 좀 퇴색되는 것 같아서, promise 부분은 빼주었습니다 :)

2022-05-15 22:45 UTC, inwalter99 commented on src/components/PlainLink/PlainLink.tsx
> +function PlainLink({ to, disabled = false, children }: Props) {
ㅋㅋ포인트는 `react-router-dom의 <Link /> 를 대체해 사용할 거라면` 입니다! 저는 `기존 라이브러리의 어떤 컴포넌트`를 커스텀하고 무조건 이걸 사용하게끔 하고 싶다면, 린트룰을 만들어  `기존 라이브러리의 어떤 컴포넌트`를 바로 import 할 때 경고를 띄우고 있어용

2022-05-15 22:49 UTC, inwalter99 commented on src/components/ProductCard/ProductCard.tsx
> +);
아래 두 개는 이미지, 텍스트일까요? 컴포넌트일까요? @.@ 둘 다 맞겠죠 ..!
저는 `svg 를 그리고 있는 컴포넌트`라고 정의해보고 싶네용..! 저는 `assets` 보단 `component` 에 위치시키고 싶습니다!
`assets/A.svg` 를 만들고 `svg` 를 사용해 `components/AIcon.jsx` 를 만들 수도 있겠지만 `jsx` 내에서 바로 `svg` 를 사용할 수 있으니 바로 컴포넌트만 만들어도 되지 않을까 생각해봅니당
```jsx
const Image = () => {
  return <img src="" />
}

const Text = ({children}) => {
  return <div>{children}</div>
}

2022-05-15 22:51 UTC, inwalter99 commented on src/components/ProductCard/ProductCard.tsx
> +          <p>{price?.toLocaleString('ko-KR')} 원</p>
음 `props` 를 정확하게 딱 받고 싶다면 `Omit` 이나 `Pick` 를 사용하는 게 맞겠지만, `Product` 타입 그대로 받아도 전혀 문제 없지 않을까 생각합니다.

2022-05-15 22:53 UTC, inwalter99 commented on src/pages/MainPage/MainPage.tsx
> +  }, [dispatch]);
저는 `useLayoutEffect` 를 사용한 적은 아직 한 번도 없는 것 같아요 😂 
`동기적으로 실행되므로 데이터를 모두 가져올 때까지 사용자가 기다려야 한다는 단점`이 크지 않을까요? 로딩이라던가 다른 상태를 두어 유려하게 구성해야한다고 생각합니다 ㅎㅎ;

2022-05-15 23:01 UTC, inwalter99 approved these changes
반영 꼼꼼히 해주셔서 감사합니다 :)
커밋에 대해 리뷰를 드리긴 했지만 전반적으로 커밋 단위는 잘 나누고 계신 것 같아요!! 이제 여기서 커밋 내용에 `why`를 좀 더 담아보면 어떨까요? 커밋 타이틀은 코드의 요약이지만, 이 커밋이 왜 발생하게 됐는지에 대해는 정보가 없다면 나중에 아쉬울 때가 생기더라구요! 
리뷰에 대한 수정이라면 리뷰를 링크걸 수도 있고, 간단하게 왜 수정하는 지에 대해서 적어주면 좋을 것 같아요 :) 2단계 때 살짝 기대해보겠습니다ㅎㅎ..

고생하셨습니다! 2단계에서 뵙겠습니당

2022-05-15 23:01 UTC, merged