[1단계 - 장바구니] 시지프(김의진) 미션 제출합니다.
woowacourse/react-shopping-cart pull request #98
Opened 2022-05-12 08:53 UTC by euijinkk

로이정님 안녕하세요. 처음 뵙겠습니다. 시지프라고합니다!
장바구니 미션 잘 부탁드립니다!!

## 데모 페이지(https://euijinkk.github.io/react-shopping-cart)

## 기술 스택
- styled-components
- TypeScript
- redux / redux-thunk
- json-server
- axios
- storybook (많이 사용하지 못 했습니다. 차차 늘려가겠습니다.)

## 구현 사항
- 상품 목록 페이지
- 상품 상세 페이지
- 장바구니 기능 (redux로 API 호출만 가능하게 하고, 페이지에 데이터만 렌더링 시켰습니다.)
- 페이지네이션

## 개발 과정
맨 처음에 컴포넌트 설계, 상태 설계를 하였습니다. 컴포넌트 설계는 작은 컴포넌트 부터 재사용 가능하게 구상하려고 노력했습니다. 상태는 어떤 데이터를 전역으로 두고, 어떤 데이터를 클라이언트 상태로 둘 것인지 고민하였습니다.

## 고민

### redux 전역 상태와, 클라이언트 상태 사이에서의 고민
redux가 필요한 이유가, 전역상태 관리 + 편리한 디버깅 이라고 생각했습니다. 전역 상태관리가 필요없을 때에도 편리한 디버깅만을 위하여 redux를 써야할지 고민이었습니다.  

전역으로 관리한 데이터 - 전체 상품 리스트, 전체 장바구니 리스트
클라이언트 데이터 - 상품 목록 페이지 데이터, 상품 디테일 페이지 데이터

예를 들어, 상품 목록 페이지에서 페이지마다 12개의 데이터를 가지고 옵니다. 이는 전역으로 관리될 필요가 없고, 페이지가 바뀔때마다 12개가 갈아치워지므로, 클라이언트 단에서 보관했습니다. 그래서 이 데이터는 useFetch로 받아오고, 전역 데이터는 useThunkFetch를 정의하여 받아왔습니다. 일관성 면에서 헷갈리는 부분이 있었고, 편리한 디버깅을 위하여 전역으로 정의해도 괜찮은가? 하는 의문이 들었습니다. 

### Custom Hook 사용
재사용이 가능한 useFetch, useSnackbar, useThunkFetch를 정의하였습니다.
useThunkFetch의 경우, useDispatch, useSelector 후 뱉어내는 data, error, loading를 묶은 Hook 입니다.

항상 커스텀훅을 정의하면서 고민인 부분이, 재사용이 어렵지만 기능적으로 분리된 커스텀 훅이 괜찮을까 하는 것입니다. useUpdateCartItem 같은 경우, 장바구니를 추가 (추후 삭제/수정도 구현할 수 있겠습니다.) 하는 로직입니다. cartList를 주입해주고, updateCartItem 함수를 return 하고 있습니다. 

저는 custom hook을 재사용보다는 도메인 로직을 분리하기 위해서도 많이 사용하고 있는데, 로이님은 어떻게 생각하시는지 궁금합니다

### 상품 리스트 전역 데이터를 어디서 받아올까?
장바구니 데이터를 다음과 같이 설계했습니다. 

```typescript
export interface CartItem {
  id: number;
  quantity: number;
}
```

id만 받아오고, 전역에 보관된 상품 리스트를 기준으로 상품 정보를 filtering하여 저장할 계획입니다. 이런 상황에서, 장바구니 페이지를 가도, 전체 상품 리스트를 호출해야하고, 상품 목록 페이지를 가도 전체 페이지를 호출해야하는 상황이 발생했습니다. 그러면, 부모 컴포넌트인 App에서 전역 데이터를 받아와야할까? 하는 고민이 생겼습니다. App에서 저 데이터가 필요하지 않은 경우도 있어서 App에서 받아오는 것은 위험하다고 생각하여 각 페이지에서 데이터를 받아왔습니다. 어떻게 처리하면 좋을지 궁금합니다.

### 타입스크립트
redux, redux-thunk와 타입스크립트를 사용하는게 너무 어려웠습니다 ㅎㅎ...
useThunkFetch로 추상화했는데, data, error, loading에 대한 타입추론은 안 되는 상황이네요. 나머지는 열심히 타입을 달아보려고 노력했습니다!

### redux/redux-thunk
redux-thunk를 처음 써보았는데요. action 정의 -> reducer 정의 -> action creator 정의 순서로 개발했습니다. 처음이라 여러 자료 참고하고, 개발해보았는데 잘 되었는지 모르겠네요 ㅎㅎ 피드백 부탁드립니다!!

편하게 코멘트 주시면 감사하겠습니다!

2022-05-14 18:43 UTC, pocojang requested changes
안녕하세요
@euijinkk !
로이와 첫 만남 기대하셨을텐데 ㅠㅠ 제가 왔어요!
원래는 대타 준....인데 준 어디갔죠?!!

## Component

### Connect Component

스토어에 연결되는 컴포넌트들도 있네요
지금 당장 문제는 없지만 어떤건 페이지 컴포넌트스러워서 페이지로 빼는게 좋지 않을까? 싶기도 합니다.

한마디로 페이지인지 컴포넌트인지 애매모호한 경계도 분리해보시고 어떤 컴포넌트들이 스토어에 접근할 수 있는 권한을 가질 것인가도 기준을 가져보세요

### Common

몇몇 컴포넌트는 여기 있는게 맞나 고민이 들긴하는데 그래도 나름 잘 분리해주신 것 같네요

## 스토어

이미 스토어에 대한 이해도는 어느정도 가지고 접근하신 것으로 보입니다.
`ThunkFetch`에서 살짝 코드 읽는게 헷갈렸는데 그 아이디어는 좋았습니다.

[typesafe-actions](https://github.com/piotrwitek/typesafe-actions)를 보는 것 같기도 했거든요

## 스낵바

지금 당장은 코드가 많지 않은데도 커버리지는 또 넓습니다.
컴포넌트, 훅스, 스토어, 포탈, 여기저기 다 영역을 펼치고 있으니...

향후 여기저기 많아질 것 같고 나름.. 잠재적인 위험요소가 보입니다.
왜 스토어로 분리했을지도 알 것 같아서 기대는 됩니다만 앞으로 코드를 확장하실때 주의해야할 것 같습니다.

## 일관성

네이밍, import 순서, 개행 모든 것에 대해 일관성을 잘 지키고 그 규칙을 지키려는게 눈에 보여 좋았습니다.
정말 일관성만큼은 아주 잘 지켜주셨어요
또한 컴포넌트 내부의 코드 순서조차 제 취향이 정말 많아서 좋았어요
취향저격이네요

다만 위에서 언급한 컴포넌트 분리 기준만 조금 더 가져보시면 좋겠네요

## Hooks

### useFetch

좋은 시도 하셨습니다
다만 우려되는 부분이 있어 코멘트로 리뷰 남겼어요

## TS

이제 정말 잘 사용하시네요
문법적으로 타이핑하는 부분은 굉장히 잘하고 계십니다.
다만 설정 부분 누락되거나 호환되지 않는 것 같은 부분이 종종 보여요

---

이번에도 많은걸 하셨네요
여러가지 남겨준 고민은 로이님이 오실 수 있으니 일단 미뤄두겠습니다.

Redux Typing이 어렵다면 아래의 레퍼런스를 확인해보세요
이미 보셨죠?!
이미 @euijinkk 의 코드와 비슷한게 많이 있어요

- https://github.com/piotrwitek/typesafe-actions
- https://github.com/piotrwitek/react-redux-typescript-guide

2022-05-14 18:43 UTC, pocojang commented on .eslintrc.json
> +      { "blankLine": "always", "prev": "*", "next": "return" },
크.. 저도 이거 좋아해요

2022-05-14 18:43 UTC, pocojang commented on package.json
> +  },
`.eslintrc.json` 랑 겹치는 것에 대해 고려해보셨나요?

2022-05-14 18:43 UTC, pocojang commented on src/components/common/Paginator.tsx
> +    const currentPage = Number(e.target.innerText);
`page` 상태가 따로 있는데 `DOM` 에서 셀렉팅해오는군요 의도되신건가요?

2022-05-14 18:43 UTC, pocojang commented on tsconfig.json
> +    "target": "es5",
`es5`로 하신 이유가 있나요~?

2022-05-14 18:43 UTC, pocojang commented on src/styles/GlobalStyle.ts
> +`;
여기는 포매팅 정리가 안되어있네요~

2022-05-14 18:43 UTC, pocojang commented on src/pages/ItemDetail.tsx
> +        <StyledPriceValue>{price}</StyledPriceValue>
향후 원화 처리를하는게 좋겠네요

2022-05-14 18:43 UTC, pocojang commented on src/pages/Main.tsx
> +      <Paginator maxIndex={itemList.length} />
상품보다 먼저 보이니까 어색하네요!

2022-05-14 18:43 UTC, pocojang commented on src/pages/Main.tsx
> +const Main = () => {
컴포넌트 명도 `ItemList`로 통일하는건 어떨까요?
메인 페이지가 다른 걸로 바뀌면 또 내부에 있는 컴포넌트를 갈아끼우는 형태로 할 필요 없이 라우터만 갈아끼워도 되지 않을까요?

2022-05-15 07:35 UTC, euijinkk commented on .eslintrc.json
> +    "prettier/prettier": ["error", { "singleQuote": true, "jsxSingleQuote": true }]
위에 80%는 저에게 맞는 rules 찾아서 추가했던 것이고,
밑에 몇개는 쓰다가 에러 뜨는거 off 했던 것들입니다.

그래서 순서가 적절하지 않았네요.
pulgin detail rules -> rules 순서로 배치했습니다!

세세하게 봐주셔서 감사합니다.

[4e34e67](https://github.com/woowacourse/react-shopping-cart/pull/98/commits/4e34e675a84501ef2497fca504f63623f5c33601)

2022-05-15 07:54 UTC, euijinkk commented on .prettierrc.js
> +  jsxSingleQuote: true,
음.. 

"es5" - Trailing commas where valid in ES5 (objects, arrays, etc.). No trailing commas in type parameters in TypeScript.

es5, all 설정이 objects에 trailing comma를 붙이므로, 
.prettierrc.js 속 객체 마지막에 prettier formatter가 콤마를 만들어주는 것이 자연스럽다고 생각했습니다!

2022-05-15 07:56 UTC, euijinkk commented on REQUIREMENTS.md
> +  - [ ] GNB의 장바구니 버튼을 누르면, 장바구니 페이지로 이동한다.
기능 구현하느라, 필수적인 요구사항을 체크하지 못 했네요 ㅠ-ㅠ

신경쓰겠습니다!

체크했습니다!

2022-05-15 08:01 UTC, euijinkk commented on public/index.html
> +    <title>Shopping Carrd</title>
앗... 수정했습니다!

[69853fc](https://github.com/woowacourse/react-shopping-cart/pull/98/commits/69853fc130409b389e4cd9598ec8b9ab6be2f33f)

2022-05-15 08:58 UTC, wmakerjun requested changes
시지프 장바구니 1단계 미션 너무 고생했어요~ 주말에 개인 일정이 많아서 리뷰가 좀 늦어졌는데 그 사이에 포코가 많은 양의 리뷰를 해주셨네요. 저도 리뷰를 남기고 펜딩 해놓은 것들이 있어서 마저 작성을 해봤습니다~! 맛난 음식 사진으로 앱을 구현해줘서 데모 페이지 살펴보는데 배가 고파지네요 ㅎㅎ 피드백들은 각 코드라인에 작성해두었구, 질문 올려준 부분에 대해서 로이님이 돌아오시기 전에 한번 더 같이 고민해봤으면 해서 일단 생각할 거리를 남겨봅니다~! 

> 저는 custom hook을 재사용보다는 도메인 로직을 분리하기 위해서도 많이 사용하고 있는데, 로이님은 어떻게 생각하시는지 궁금합니다
> 

⇒ 시지프가 custom hook의 재사용보다는 도메인 로직을 분리하기 위해 많이 사용하는 것에 대해 리뷰어의 의견이 궁금한 것 같은데요. custom hook을 이용하여 도메인 로직을 분리하면서 의문이 들었던 코드나 구조가 있을까요? 시지프가 고민했던 특정 부분이 있다면 함께 공유해주면 더 좋을 것 같아요 😃 

> 상품 리스트 전역 데이터를 어디서 받아올까?
> 

App에서 받아오는 것이 위험할 수 있다고 하였는데 어떤 경우에 위험할 수 있을까요? 그리고 현재는 각 페이지에서 데이터를 받아오는 형태인데, 지금 상태가 고민되는 이유는 무엇일까요? 그 고민되는 부분을 개선하기 위한 해결책에 대해 같이 이야기하면 더 좋을것 같아요~!

2022-05-15 08:58 UTC, wmakerjun commented on public/index.html
> +    <div id="snackbar"></div>
root안에 들어가는 element와 root 영역 밖에 선언되는 elment는 어떤 차이가 있을까요~? 🤔

2022-05-15 08:58 UTC, wmakerjun commented on src/components/Cart/CartList.tsx
> +  if (error) return <RequestFail />;
👍🏻

2022-05-15 08:58 UTC, wmakerjun commented on src/components/common/Paginator.tsx
> +  const handleClickBefore = () => {
pagination과 같이 일반적으로 사용하는 컴포넌트들은 공통되게 사용하는 네이밍들이 있어서, 다른 라이브러리에서  그 의미를 표현하는 어휘를 어떤걸 사용하는지 봐도 좋을 것 같아요~
[mui-pagination](https://mui.com/material-ui/react-pagination/#usepagination)

2022-05-15 08:58 UTC, wmakerjun commented on src/components/common/Paginator.tsx
> +        if (pageStartNumber + index + 1 <= pageLastNumber) {
조건문이 복잡하게 느껴질수도 있을 것 같아요. 수식을 변수로 만들고, early return 해주면 훨씬 이해하기 쉬울것 같아요 😄

2022-05-15 09:03 UTC, wmakerjun commented on src/components/ItemList/ItemContainer.tsx
> +      transform: scale(1.2);
이 디테일에 감동 받았어요 👍🏻

2022-05-15 09:12 UTC, wmakerjun commented on src/components/common/Button.tsx
> +    }
large, medium일때와 small일 때의 width, height 단위가 다른데 혹시 어떤 이유 때문일까요~?

2022-05-15 09:17 UTC, wmakerjun commented on src/pages/ItemDetail.tsx
> +      </Button>
데모 페이지에서 이 장바구니 버튼을 눌렀을 때는 snackbar가 뜨지 않던데 혹시 의도된걸까요~?

2022-05-15 09:24 UTC, wmakerjun commented on src/pages/Cart.tsx
> +    </div>
굳이 <div>로 감쌀 필요가 없어보이네요~!

2022-05-15 09:33 UTC, wmakerjun commented on src/components/ItemList/ItemContainer.tsx
> +            <StyledPrice>{price}</StyledPrice>
금액이 ,로 구분되면 엄청 친절할것 같다는 생각이...!
 
<img width="425" alt="스크린샷 2022-05-15 오후 6 33 04" src="https://user-images.githubusercontent.com/50367798/168466304-4ba2ee32-d63b-418b-b3be-50445fdf8c71.png">

2022-05-16 05:53 UTC, euijinkk commented on public/index.html
> +    <div id="snackbar"></div>
Snackbar에 연관된 것들이, redux, Portal, App, 그리고 해당 컴포넌트에서 openSnackbar 함수를 실행하고 있었습니다. 말씀해주신대로 커버리지가 너무 넓어서 잠재적인 위험성을 가진다고 생각했습니다. 응집도를 높이는 방향으로 리팩터링 시도해보았습니다.

1. useSnackbar는 상태와 dispatcher 모두 가진다. (상태와 dispatcher 응집)
2. snackbar 상태를 지역 상태로 보관한다. (redux 제거)
3. Portal은 유지한다.

Portal을 사용해서 index.html에 미리 div tag를 만들어둔 이유는 다음과 같습니다.
 
1. snackbar가 중첩될 때 처리해주기 위해서 (기존 snackbar를 다른 snackbar로 대체하는 방식으로)
2. 쌓임맥락 문제를 해결하기 위해

Modal을 사용하는 것과 크게 다르지 않다고 생각하고 구현했습니다.
snackbar의 응집도를 높인 상황에서도 Portal 방식이 적절하지 않은 선택이라고 느끼시는지 궁금합니다!

[e18a1a4](https://github.com/woowacourse/react-shopping-cart/pull/98/commits/e18a1a4bcfd58a2a9b843fe81315f1ea39cbda34)

2022-05-16 06:55 UTC, pocojang commented on public/index.html
> +    <div id="snackbar"></div>
`Portal` 사용은 좋으나 `루트 요소`에 리액트 앱이 마운트됨에도 불구하고 또 스낵바라는 `루트 요소 급`의 최상위 요소를 만든다는 것에 경계했습니다.
이런 확장성이 한번 열리면 앞으로 생길 `모달`, `얼럿` 등 다양한 `UI`가 생겨날때마다 모두 루트를 만들어내실건지?
와 같은 질문으로 위험한 선택같다는 코멘트를 남겨봤습니다

2022-05-16 07:54 UTC, euijinkk commented on src/apis/index.ts
> +const LOCAL_BASE_URL = 'http://localhost:4000';
앗,, 놓친 부분이네요. 환경변수로 등록했습니다!
세심하게 봐주셔서 감사합니다.

[refactor: api 주소 환경변수로 저장](https://github.com/woowacourse/react-shopping-cart/pull/98/commits/76ef83be888a8bc7901d531658f233e53968fb2c)

2022-05-16 07:55 UTC, euijinkk commented on src/components/Cart/CartList.tsx
> +const CartList = () => {
앗..

[style: 개행 추가](https://github.com/woowacourse/react-shopping-cart/pull/98/commits/d500b75d8f03580670d1a6878c425aa1eefca77f)

2022-05-16 08:32 UTC, euijinkk commented on src/App.tsx
> +            <Route path='*' element={<NotFound />} />
오오... 확실히 규모가 커지면, 라우터 사용처가 복잡해지겠네요. 
+ 상수로 사용하지 않아 안전하지 못 합니다.
+ navigate, Link를 사용하는 곳에서도 상수로 사용하지 않아 안전하지 못 합니다.

PATH를 상수화 하고, Route를 객체로 관리하는 방식을 적용해보았습니다!

[refactor: router 상수화, 분리](https://github.com/woowacourse/react-shopping-cart/pull/98/commits/5a60db8b1596ad239ce18f647d1a0646478d832d)

2022-05-16 08:36 UTC, euijinkk commented on src/components/ItemList/ItemContainer.tsx
> +    <Link to={`/item_detail/${id}`} onClick={handleClickItemContainer} replace>
Link는 기본적으로 중첩 라우팅되더군요.
ItemContainer는 /main/:id 페이지에 있고, 라우팅될 곳은 /item_detail/:id 입니다.
replace를 붙여주지 않으면 /main/:id/item_detail/:id 이렇게 됩니다.

replace를 붙이면, basePath부터 다시 라우팅하기 때문에, 이 방식을 사용했습니다!

2022-05-16 08:40 UTC, euijinkk commented on src/components/ItemList/ItemContainer.tsx
> +        <CroppedImage src={thumbnailUrl} width='270px' height='270px' alt='상품' />
그렇네요!
음.. 무얼 넣으면 좋을까 하다가 title을 넣었는데요..
밑에 따로 title을 보여주기 때문에, alt로도 title을 넣어줄 필요가 있을까?.. 하는 생각은 드네요.
마땅히 넣어줄 것은 없고요..!

[refactor: img alt를 구체화](https://github.com/woowacourse/react-shopping-cart/pull/98/commits/2a697577de35c6132572de80a58f14a9ee6ce265)

2022-05-16 08:43 UTC, euijinkk commented on src/components/ItemList/index.tsx
> +  } = useFetch<Item[]>(`${BASE_URL}/itemList?_page=${id}&_limit=12`);
놓친게 넘 많네요 ㅠ-ㅠ
상수 분리했습니다!

[refactor: item list max result 분리](https://github.com/woowacourse/react-shopping-cart/pull/98/commits/c6632dc4d585f88625e26410cd11cda216000761)

2022-05-16 08:45 UTC, euijinkk commented on src/components/ItemList/index.tsx
> +  const id = Number(params.id);
현재 서버 id를 number로 짠 상태입니다.
하지만 useParams에서 넘어오는 id는 string입니다.
useParam로 받은 id가 아래 함수의 인자로 들어가기 때문에, number로 변환해주어야 했습니다.

```typescript
const updateCartItemQuantity = (id: number) => {
    const targetItem = cartList.find(cartItem => cartItem.id === id);

    dispatch(putCartItem({ ...targetItem, quantity: targetItem.quantity + 1 }));
  };
```

2022-05-16 11:25 UTC, euijinkk commented on src/hooks/useSnackBar.ts
> +    snackbarDispatch({ type: SnackbarActionType.OPEN_SNACKBAR, payload: 'cart' });
처음 의도는 message의 종류가 늘어날 때마다, contentsType을 추가하여 사용하고자 하였습니다.
아직은 cart type의 메시지밖에 사용하지 않기 때문에 cart밖에 없는 것입니다.

하지만, 쓸데 없이 한단계 더 생각해야 하는 코드라고 생각이 들었습니다. 
굳이 contentType을 넘겨주지 않고, message를 넘겨주는 코드로 변경했습니다.

[refactor: snackbar Props를 message로 변경](https://github.com/woowacourse/react-shopping-cart/pull/98/commits/a28352df6ec7c8489d5592ce81783250a0d6d82b)

2022-05-16 11:28 UTC, euijinkk commented on src/pages/Cart.tsx
> +const Cart = () => {
맞습니다..
2단계 피그마를 보고, 
CartList 와 이외의 컴포넌트들로 구성될 것이라고 생각하여 현재와 같이 구성하였습니다.

2022-05-16 11:49 UTC, euijinkk commented on src/redux/actions/cartList.ts
> +export enum CartListActionType {
enum이 tree shaking 문제가 있다는 것을 알았지만, 시간이 촉박해 다른 해결책을 알아보지 못 했네요.
`const enum` 이 tree shaking 문제가 없으면서, enum과 동일하게 사용이 가능해서 편한것 같아요.
감사합니다!

[refactor: const enum 으로 변경](https://github.com/woowacourse/react-shopping-cart/pull/98/commits/8fa1617ad257060b1703755e2d1a013c19d867c3)

2022-05-16 11:51 UTC, euijinkk commented on src/redux/actions/itemList.ts
> +  GET_ITEM_LIST_FAILURE = 'items/GET_ITEMLIST_FAILURE',
헛... 일관성을 지키기 위해 의도한 것이었다면 다행이었겠지만,
차마 모두 수정하지 못 한 것입니다 ㅠ-ㅠ

넘 보기 불편하네욤.. 수정했습니다!

[style: 상수 사이에 underscore 추가](https://github.com/woowacourse/react-shopping-cart/pull/98/commits/45f2aa21c75be8887a5478309cdf5dd572fe5a2c)

2022-05-16 12:10 UTC, euijinkk commented on src/redux/reducers/cartListReducer.ts
> +};
initialState에 타입을 선언해준 이유는 다음과 같습니다.
- initialState에서 타입을 명시해주면, reducer의 return 타입을 지정해주지 않아도 된다.
- state 타입을 명시하지 않아도 된다.
- 이는 다음과 같이 추론됩니다.
```typescript
const cartListReducer: (state: CartItemState, action: CartListAction) => CartItemState
```

만약 initialState의 타입을 지정해주지 않는다면?
```typescript
const cartListReducer: (state: {
    loading: boolean;
    error: any;
    data: any[];
}, action: CartListAction) => {
    loading: boolean;
    error: any;
    data: any[];
}
```

위와 같이 추론되기 때문에, 최소한 reducer의 return 타입은 지정해주어야 할 것입니다.
그래서 return 타입만 명시해주면 되기 때문에, return type에 명시해주는 것이 더 정확히 보이겠다고 생각하여, 수정하려고 했습니다. 하지만, state에 타입이 정확하게 추론되지 않으니, 
useSelector를 사용하는 곳에서 아래와 같이 추론되더라고요. 

```typescript
{
    loading: boolean;
    error: any;
    data: any[];
}
```

그래서 initialState에 한번 지정해주면, state, reducer return 타입이 모두 정해지기 때문에 적절하다고 생각했습니다.

하지만 readonly 키워드의 경우, 제가 사용해본적이 없어서 조금 공부해보았습니다. reducer에서 상태 불변성을 유히가 위해 사용하면 좋겠더라구요. readonly를 추가하고나니, state의 상태를 수정하려고 하는 human error를 잡아줘서 더 정확한 것 같아요!



[refactor: reducer State에 readonly 속성 추가](https://github.com/woowacourse/react-shopping-cart/pull/98/commits/075850347b3e4accec3d9a647f21288ed8f70413)

2022-05-16 12:23 UTC, euijinkk commented on src/styles/GlobalStyle.ts
> +import reset from 'styled-reset';
확인해보지 못 했네요 ㅠ,,

https://github.com/zacanger/styled-reset/blob/master/src/index.ts

돌아보니 굳이 라이브러리에 의존할 필요는 없다고 생각이 들긴 하네요!..!
제 개발 스타일에 맞는 커스텀한 reset css를 사용하면 좋을 것 같네요!
포코는 보통 css를 reset 하기 위해 어떤 방식을 사용하시는지 궁금해요!

2022-05-16 12:34 UTC, euijinkk commented on src/types/index.d.ts
> +declare module '*.svg';
헉... react-app-env.d.ts 가 무슨 파일인지도 모르고, 그냥 지워버렸습니다 ㅠ-ㅠ...

`/// <reference types="react-scripts" />`
react-scripts 가보면 이미 다 정의되어 있군요.....

하나하나 신중히 대하는 습관을 길러야겠습니다!!

[chore: react-app-env.d.ts 파일 추가](https://github.com/woowacourse/react-shopping-cart/pull/98/commits/a5382e2f499d4279a01d3771b4b2509ab261f9b7)

2022-05-16 13:39 UTC, pocojang commented on src/hooks/useSnackBar.ts
> +    snackbarDispatch({ type: SnackbarActionType.OPEN_SNACKBAR, payload: 'cart' });
제 의도를 잘 이해하셨네요 맞아요!
확장성이라는 것은 굉장히 중요하지만 컨텐츠 타입 같은 타입이 늘어나면 도메인이 추가될때마다 어떻게 관리될 것인가 애매모호해질 것이라고 생각했는데 좋은 변경이라고 생각합니다.

이런게 궁금하시다면 다른 스낵바 라이브러리는 어떻게 옵션들을 받는지 그 사례를 찾아보시는 것도 좋습니다

2022-05-16 15:26 UTC, euijinkk commented on src/redux/reducers/snackbarReducer.ts
> +      return { ...state, isSnackbarOpen: false };
위 코멘트를 보고, 지역 상태로 바꾸어서 이 코드는 이제 없습니다!

제가 이전에 의도했던 코드에서는 contentsType을 넘겨줄 필요가 없었습니다.
스낵바를 관장하는 상태를 하나이기 때문에, CLOSE할 때는 type을 제거해주기만 하면 문제가 없었습니다

2022-05-16 15:36 UTC, euijinkk commented on tsconfig.json
> +  "include": ["src"]
혹시.. strict 모드를 말씀하시는 걸까요?

strict 모드로 하기엔 너무 빡세서 지웠어요. 그래서 null check가 안되었던거군요..
null check가 안되면, 위험성이 클 것 같아요. 
추후에 strict모드로 수정한 후 리팩터링 해보겠습니다!

2022-05-16 15:40 UTC, euijinkk commented on src/redux/reducers/itemListReducer.ts
> +  error: string | null;
말씀해주신 것을 정확히 이해하지 못 했습니다 ㅠ-ㅠ

앱이 커질 때, optional로 지정하는 것이 안전하지 못 하다는 의미일까요?

null 가능성을 열어두면, 매번 null을 할당해주어야해서 귀찮으므로, optional로 아예 없애버리는 것이 나을 수 있다. 이러한 의미일까요??!!

2022-05-16 16:02 UTC, euijinkk commented on package.json
> +    "eslint-plugin-react-hooks": "^4.5.0",
헉.. 

eslint-plugin-import, eslint-plugin-jsx-a11y, eslint-plugin-react, eslint-plugin-react-hooks
모두 내장돼있네요. 

한 때 lint 열심히 정리했었는데, 전혀 몰랐네요 ㅠ-ㅠ

세심하게 봐주셔서 감사합니다!!

2022-05-16 16:15 UTC, euijinkk commented on src/components/ItemList/ItemContainer.tsx
> +  const handleClickItemContainer = (e: MouseEvent<HTMLAnchorElement, globalThis.MouseEvent>) => {
음... 잘 안 나오네요..
일단 event에 마우스 hover해서 타입을 그대로 가져왔습니다.

조금 추론을 해보면...
globalThis는 웹환경 이외에도 전역 객체를 가리키는 객체입니다.
그러므로, 제네릭에 globalThis.MouseEvent를 쓰면, 웹 이외의 환경에서의 마우스 이벤트도 감지할 수 있을 것이다고 생각이 들었습니다.

2022-05-16 16:32 UTC, euijinkk commented on src/components/common/Header.tsx
> +          <button onClick={() => navigate('/cart')}>장바구니</button>
Link 는 a 태그를 생성하고, Navigate는 a 태그를 생성하지 않습니다.
그러므로, Link는 SEO가 필요할 때에 사용하고, 이외의 경우는 Navigate를 사용했습니다.

장바구니 같은 경우는, SEO가 필요하지 않으므로 Navigate를 사용했습니다.
적절할까요?..

2022-05-17 00:21 UTC, pocojang commented on src/components/common/Header.tsx
> +          <button onClick={() => navigate('/cart')}>장바구니</button>
그래도 찾아 보셨군요!
`SEO` 여부와 관계없이 페이지를 이동할때 `<a href>`를 사용하는 것은 기본적인 `HTML`에서의 약속 아닐까요?
앞으로는 불편하고 힘들지만 방법을 찾아보시면 좋아요 :)

2022-05-17 00:23 UTC, pocojang commented on src/components/ItemList/ItemContainer.tsx
> +  const handleClickItemContainer = (e: MouseEvent<HTMLAnchorElement, globalThis.MouseEvent>) => {
https://github.com/typescript-cheatsheets/react
추천 레퍼런스입니다~

2022-05-17 00:24 UTC, pocojang commented on tsconfig.json
> +  "include": ["src"]
`include` 확인해보세요 ㅎㅎ

2022-05-17 00:25 UTC, pocojang commented on src/redux/reducers/itemListReducer.ts
> +  error: string | null;
이해하신게 맞습니다ㅎㅎ
그렇게도 생각해볼 수 있다~~
정도로 받아들여주시면 좋아요

2022-05-17 05:40 UTC, euijinkk commented on src/components/common/Paginator.tsx
> +    const currentPage = Number(e.target.innerText);
익명함수 n개를 만들어야 해서, DOM에 접근하여 가지고 왔습니다..!

말씀하신 것처럼, DOM에 접근하는 것, 상태로 접근하는 것이 혼재되어 어색하네요.
익명함수 10개에 너무 많은 신경을 쓴 것 같습니다 ㅎㅎ...

[refactor: handleClickNumber 인자로 page 받아오기](https://github.com/woowacourse/react-shopping-cart/pull/98/commits/01a06d0a7c2bdff340193dcf8db8bd072c323fd4)

2022-05-17 06:05 UTC, euijinkk commented on tsconfig.json
> +    "target": "es5",
앗,, 기본 tsconfig 설정입니다.

자세히 알아보지 않았네요 ㅠ-ㅠ
문제가 되지 않으면, 딱히 건드리지는 않았습니다!

공부 결과, target은 자바스크립트로 컴파일된 결과물을 의미합니다.

저번에 hash 접근자를 사용하기 위해 es6 이상으로 올렸던 기억이 있습니다.

컴파일 되는 코드의 버전이 낮을 수록, 크로스 브라이징 이슈가 적어지리라 생각하는데요.

문제 없으면 낮게 사용해도 괜찮을까요?!

2022-05-17 06:06 UTC, euijinkk commented on src/styles/GlobalStyle.ts
> +`;
꼼꼼히 확인하고 PR 올리도록 하겠습니다... ㅠ-ㅠ

[style: GlobalStyle 포매팅](https://github.com/woowacourse/react-shopping-cart/pull/98/commits/28861a2f4140145efdd6acb2fe8f4122725a406c)

2022-05-17 06:08 UTC, euijinkk commented on src/pages/ItemDetail.tsx
> +        <StyledPriceValue>{price}</StyledPriceValue>
세세하게 봐주셔서 감사합니다!!

[feat: 금액에 toLocaleString 적용](https://github.com/woowacourse/react-shopping-cart/pull/98/commits/f6058d2006872bcb67867f9799bf75f1101dd9d3)

2022-05-17 06:14 UTC, euijinkk commented on src/components/common/CroppedImage.tsx
> +const StyledImageWrapper = styled.div<{ width: string; height: string }>`
굿 아이디어입니다!!
감사합니당!!

[refactor: Pick Utility Type 적용](https://github.com/woowacourse/react-shopping-cart/pull/98/commits/3beb2ac71eb78aa46ba45db65061b65e3737e105)

2022-05-17 06:43 UTC, euijinkk commented on src/pages/Main.tsx
> +      <Paginator maxIndex={itemList.length} />
Pagination을 ItemList로 넣고, Main을 빼서 해결했습니다!
감사합니다!

[refactor: ItemList 페이지 통합](https://github.com/woowacourse/react-shopping-cart/pull/98/commits/9fa65c50126a02fda19becb27de0208926053496)

2022-05-17 06:44 UTC, euijinkk commented on src/pages/Main.tsx
> +const Main = () => {
말씀하신것과 같이 Main 보다 구체적인 컴포넌트 명을 짓는 것이 나아보입니다!
감사합니다!

[refactor: ItemList 페이지 통합](https://github.com/woowacourse/react-shopping-cart/pull/98/commits/9fa65c50126a02fda19becb27de0208926053496)

2022-05-17 06:46 UTC, euijinkk commented on .storybook/main.js
> +}
ㅠㅠ 해결했습니다.

2022-05-17 06:49 UTC, euijinkk commented on src/components/ItemList/index.tsx
> +  } = useFetch<Item[]>(`${BASE_URL}/itemList?_page=${id}&_limit=12`);
힛,,, 클린하지 못 했네요 ㅠ-ㅠ

수정했습니다~!~

[refactor: item list max result 분리](https://github.com/woowacourse/react-shopping-cart/pull/98/commits/c6632dc4d585f88625e26410cd11cda216000761)

2022-05-17 06:50 UTC, euijinkk commented on src/App.tsx
> +            <Route path='/item_detail/:id' element={<ItemDetail />} />
Path를 상수로 분리하고, 라우터를 객체로 분리하여 구현해보았습니다!

감사합니당~!~!

[refactor: router 상수화, 분리](https://github.com/woowacourse/react-shopping-cart/pull/98/commits/5a60db8b1596ad239ce18f647d1a0646478d832d)

2022-05-17 06:51 UTC, euijinkk commented on src/components/common/Loading.tsx
> +  return <div>Loading..</div>;
2단계에 더 멋진 UI로 수정해보겠습니다!

2022-05-17 06:51 UTC, euijinkk commented on src/App.tsx
> +            <Route path='*' element={<NotFound />} />
히히,, payments에서 피드백 받아서,, 성장했습니다!
감사합니다~!~

2022-05-17 06:56 UTC, euijinkk commented on public/index.html
> +    <div id="snackbar"></div>
음.. 질문이 두가지 측면에서 해석할 수 있겠어요

1. index.html에서 #snackbar를 #root 속에 넣어두면?
2. snackbar를 portal로 사용하는 것과, 그냥 컴포넌트 속에서 사용하는 것의 차이?

첫번째 경우는, root 속에 #snackbar를 넣어두면, 초기 렌더링 시 createRoot에 의해, root가 갈아끼워지므로 #snackbar는 없어질 것입니다.

두번째 경우는 portal을 사용하면, 쌓임 맥락 문제를 해결할 수 있으므로, z-index를 지어줄 필요가 없어집니다. 거기에 서로 다른 snackbar가 동시에 눌리고, 다른 상태로 관리되고 있으면 snackbar를 컨트롤 하기가 어려우리라 생각했습니다. 그래서 snackbar를 index.html에서 선언해두고 portal을 활용하면 snackbar가 겹치더라도, #snackbar 속 엘리먼트 자체를 갈아끼울 수 있기 때문에, 이 문제에서도 벗어날 수 있었습니다.

2022-05-17 06:57 UTC, euijinkk commented on src/components/Cart/CartList.tsx
> +  if (error) return <RequestFail />;
감사합니다!

2022-05-17 06:58 UTC, euijinkk commented on src/components/common/Paginator.tsx
> +  const handleClickBefore = () => {
너무 좋은 접근이에요!
공통적으로 사용하는 것들에 대해 레퍼런스를 참고해보자!

감사합니다!!

Pagination 전체적인 수정은 전체 코멘트로 달아둘게요!

2022-05-17 06:58 UTC, euijinkk commented on src/components/ItemList/ItemContainer.tsx
> +      transform: scale(1.2);
히히 감사합니다!

2022-05-17 08:21 UTC, euijinkk commented on src/components/common/Button.tsx
> +    }
Component 기반 개발을 해보려고, 피그마에서 공통 요소를 찾아보았어요.
피그마 사안에서 총 버튼이 3가지 종류로 나눌 수 있어서 저렇게 표현해보았어요!

저렇게 3가지로 분기처리한 부분이, 확장성이 떨어지는 걸까요?

항상 동적인 style을 받아오는게 헷갈렸어요.
스타일적인 요소를 최소화하는게 재사용성이 좋겠죠?..

컴포넌트 내에서 스타일 요소를 뺀다면,
inline style props로 ( style={{width: 13.8rem}} 이런 방식!) 넘겨받거나
styled-component를 상속해서 사용하거나 할 수 있을 것 같아요.

2022-05-17 08:28 UTC, euijinkk commented on src/pages/ItemDetail.tsx
> +      </Button>
급하게 마무리해서 적용하지 못 했네요!
다음번엔 세세하게 검토해보겠습니다!

[feat: ItemDetail에서 장바구니 클릭 시 snackbar 보여주기](https://github.com/woowacourse/react-shopping-cart/pull/98/commits/52e37ac2fdb2eccec8fe2815e89894848c43a107)

2022-05-17 08:29 UTC, euijinkk commented on src/components/ItemList/ItemContainer.tsx
> +            <StyledPrice>{price}</StyledPrice>
이것도 한다는 걸.. 까먹었네요!
세세하게 봐주셔서 감사합니다!

[feat: 금액에 toLocaleString 적용](https://github.com/woowacourse/react-shopping-cart/pull/98/commits/f6058d2006872bcb67867f9799bf75f1101dd9d3)

2022-05-17 08:38 UTC, euijinkk commented on .prettierrc.js
> +module.exports = {
찾아보니, js, json, yml, yaml, cjs 등 다양한 확장자를 지원하는게, 호환성을 위한 선택이네요.

말씀해주신 것 처럼, 프로젝트 내에서 일관성만 지켜주면 좋을 것같아요.
json으로 통일했어요!

세세하게 짚어주셔서 감사합니다.

[prettier Configuration File](https://prettier.io/docs/en/configuration.html)

[chore: lint, prettier 확장자 json으로 통일](https://github.com/woowacourse/react-shopping-cart/pull/98/commits/6c5d0b91218c9b2716b94f0c5d273756c795ce7c)

prettier 설정들은 모두 고려하여 작성했습니다.
default 값이라도 그냥 써두었는데, default값 변화 가능성, 명시적인 선언을 위해서 작성했습니다!

2022-05-17 09:02 UTC, euijinkk commented on src/hooks/useFetch.ts
> +  const [error, setError] = useState<string>(null);
흠.. 이 부분이 감이 안잡혔어요.

ItemList의 경우 3가지 데이터를 가지고 옵니다.

1. AllItemList - pagination의 maxLength를 측정하기 위해 가지고 옵니다.
2. ItemList - 페이지네이션이 바뀔때마다 12개의 데이터를 가지고 옵니다.
3. CartList - 장바구니 post/put 하기 위해 가지고 옵니다.

실제 서버가 있었다면, 굳이 저렇게 가져올 필요는 없었겠지만!
이렇게 3가지 통신을 하는 상황에서 어떻게 해야할지 고민이 되었네요.

실제로 UI에 보여지는 것은 2번 ItemList 통신 밖에 없었습니다.
그래서 1,3번이 loading을 만들 필요는 없고, itemList만 loading을 보여주고자 했습니다.

에러도 그렇게 한 것은 잘못된 선택 같습니다. 에러는 3가지 모두 통과하면, 뷰를 보여주어야겠습니다. 
아래와 같이 3가지 에러를 모두 체크하였는데, 괜찮을까요?

[refactor: ItemList API 통신 에러 처리](https://github.com/woowacourse/react-shopping-cart/pull/98/commits/ba55bc0605be0c69a9d9787b212d4a103c4a1855)

2022-05-17 12:12 UTC, pocojang commented on tsconfig.json
> +    "target": "es5",
벌써부터 크로스 브라우징 대응할 필요가 있을까요 ㅎㅎ
다음부터는 마음껏 즐기세요!

2022-05-17 12:39 UTC, euijinkk commented on src/redux/reducers/cartListReducer.ts
> +  }
음.. 시도해보려고 했는데, Object 에서 다음과 같이 key에 type을 넣고, value에 state를 return 하는 함수를 넣었습니다.

switch 에서는 action.type으로 타입 내로잉이 이루어져서, action.payload를 추론이 가능합니다.

밑 코드로는 타입 내로잉이 안 돼서 payload 타입 에러가 뜨네요. 음,, step2 하면서 다른 방법 많이 고민해보겠습니다..!

```typescript
const reducerObj = {
  [CartListActionType.GET_CART_LIST_START]: (state: CartItemState, action: CartListAction) => ({
    loading: true,
    error: null,
    data: state.data,
  }),
  [CartListActionType.GET_CART_LIST_SUCCESS]: (state: CartItemState, action: CartListAction) => ({
    loading: false,
    error: null,
    data: action.payload,
    // Property 'payload' does not exist on type 'CartListAction'.
  }),
};
```

2022-05-17 12:39 UTC, euijinkk commented
@wmakerjun 
준 코멘트 감사합니다!
바쁘신데 세세하게 봐주셔서 감사해요!

## Pagination Component 리팩터링

급하게 작성하다 보니, 저도 지금 읽기가 어려운 코드네요!
mui 참고하여, 통상적으로 사용하는 변수, 컴포넌트명을 참고하여 수정했습니다.
- 변수명 수정
- 상수 분리
- 컴포넌트명 수정 (Paginator -> Pagination)
- early return
[refactor: Pagination 컴포넌트 수정](https://github.com/woowacourse/react-shopping-cart/pull/98/commits/3417a72a3788cb3e5e5857710495d91a1c8798aa)

## custom hook
> 시지프가 custom hook의 재사용보다는 도메인 로직을 분리하기 위해 많이 사용하는 것에 대해 리뷰어의 의견이 궁금한 것 같은데요. custom hook을 이용하여 도메인 로직을 분리하면서 의문이 들었던 코드나 구조가 있을까요? 시지프가 고민했던 특정 부분이 있다면 함께 공유해주면 더 좋을 것 같아요

useCartList나, useUpdateCartItem 같은 컴포넌트는 재사용을 위한 것보다, 컴포넌트 내 로직을 분리하기 위해 사용했습니다. 비즈니스 로직 - UI를 분리하여, 컴포넌트가 < hook - return > 이와 같이 읽히도록 만들고자 하였습니다. 

## 전역 상태를 저장하는 장소

> App에서 받아오는 것이 위험할 수 있다고 하였는데 어떤 경우에 위험할 수 있을까요? 그리고 현재는 각 페이지에서 데이터를 받아오는 형태인데, 지금 상태가 고민되는 이유는 무엇일까요? 그 고민되는 부분을 개선하기 위한 해결책에 대해 같이 이야기하면 더 좋을것 같아요~!

- App에서 전역 상태를 받아오는 것이 위험한 이유
  App에서 전역상태를 dispatch하면, 그 데이터가 필요하지 않음에도 저장하게 돼요. 앱이 확장됨에 따라 이런 일이 더 심각해지리라 생각했습니다. 그래서 각 컴포넌트에서 매번 dispatch 하는 것이 맞다고 생각했어요. 

- 지금 상태가 고민 되는 이유
  같은 데이터를 계속 dispatch 하니까 비효율적이긴 하다고 생각했답니다.

- 개선하기 위한 해결책
  캐싱할 수 있으면 좋겠네요.. swr이나 react-query를 사용할 때에는 캐싱이 가능하기 때문에, 각 컴포넌트에서 호출해도 상관이 없었습니다. 캐싱.. 더 고민해보도록 하겠습니다!

혹시 준이 추천하는 방향성도 있을까요?

2022-05-17 15:13 UTC, euijinkk commented on public/index.html
> +    <div id="snackbar"></div>
아하 이해했습니다.
`snackbar`, `modal`, `alert`이 모두 최상위에 있다라...
아직은 어떤 사이드 이펙트가 있을까??.. 정확히 감은 잘 안 잡히는데요.

혹시 어떤 부분이 위험할지 힌트를 주실 수 있을까요?!

2022-05-17 16:01 UTC, euijinkk commented on src/components/ItemList/index.tsx
> +  const id = Number(params.id);
오오... 그렇네요. 
밑에 경우가 더 효율적이고 코드도 깔끔하네요!

상세하게 설명해주셔서 너무 감사합니다!!

수정해보았습니다~!~

[refactor: useParams에서 id를 구조분해할당](https://github.com/woowacourse/react-shopping-cart/pull/98/commits/f3eb41d3f7c5540633a53bafb47e662b3bc2ba98)

2022-05-17 16:02 UTC, euijinkk commented on src/hooks/useSnackBar.ts
> +    snackbarDispatch({ type: SnackbarActionType.OPEN_SNACKBAR, payload: 'cart' });
감사합니다!!

2022-05-17 16:22 UTC, euijinkk commented on tsconfig.json
> +  "include": ["src"]
음..

`"include": [src/**/*]`
를 말씀하시는 걸까요??!

찾아봤는데, 모두 `**/*` 를 붙이고 있네요. src 안에 assets 도 있으므로, 확장자를 ts로 고정시키지는 않는게 좋겠군요!

[절대 경로 세팅 CRA 문서](https://create-react-app.dev/docs/importing-a-component/)에서 `include": ["src"]` 이와 같이 설정한 것을 보고 그대로 적용했었습니다.

두 가지가 확장자를 표시하지 않는다면, 기능적으로는 차이가 없어 보이는데요..!!
혹시 이부분 말씀하시는게 아닐까요? ㅠ-

2022-05-17 16:23 UTC, euijinkk commented on src/redux/reducers/itemListReducer.ts
> +  error: string | null;
감사합니다!!

2022-05-17 16:25 UTC, euijinkk commented on src/components/ItemList/ItemContainer.tsx
> +  const handleClickItemContainer = (e: MouseEvent<HTMLAnchorElement, globalThis.MouseEvent>) => {
우와,, 이렇게 멋진 문서가!
감사합니다!

2022-05-17 16:34 UTC, euijinkk commented
@pocojang 
포코 코멘트 정성스럽게 남겨주셔서 너무 감사합니다.
생각하지 못 한 부분도 짚어주셔서 많이 공부했습니다!!

## Connect Component
하위 컴포넌트에서 스토어에 연결되면 어떤 단점이 있을지,
페이지에서만 스토어를 연결하면 어떤 장점이 있을지 고민해보았습니다.

1. 하위 컴포넌트 재사용이 쉬워진다.
2. 하위 컴포넌트 테스트가 쉬워진다.

아직 필요성을 느끼지는 못 했는데요..! 더 찾아보고 고민해보겠습니다..

## useFetch
이 부분은 2단계 하면서 더 고민해보도록 하겠습니다!

## TS
칭찬 감사합니다!!

## Palette
2단계하면서 꼭 수정해보겠습니다.

여러 참고자료 열심히 읽어보겠습니다!
감사합니다!!

2022-05-18 02:22 UTC, pocojang approved these changes
안녕하세요
@euijinkk 

이미 충분히 코드 리뷰는 주고 받기도 했고 빠른 미션 진행을 위해 바로 머지합니다

## 고민

<details>
  <summary>Q1. redux 전역 상태와, 클라이언트 상태 사이에서의 고민</summary>

모든 것을 전역으로 관리할 필요 없습니다.
그리고 이런 고민을 하는게 이번 미션의 목표이기도 해요.
리덕스를 사용해라! 써봐라! 라는 측면속에는 이런 고민을 하라는 요구사항도 암묵적으로 포함되어있는거죠.

많이 고민해보세요!

다만 개인적인 생각이지만 상태 관리를 안하는게 가장 편합니다.
전역 상태, 지역 상태 분리하고 영속성 관리하고 그러다보면 결국 상태 관리를 위한 관리 즉 일을 위한 일을 하게 됩니다.

프론트엔드 개발자라면 서비스 목적에 따라서 가장 최신의 데이터를 보여줘야하거나 어느정도 최적화를 해서 캐시를 제공한다든가 다양한 고민해야합니다.

즉 서비스에 따라 사용자가 최신 데이터를 봐야만 하는 것이 최선일 수 있고 적절히 캐시를 적용해 보여주는게 최선일 수 있습니다.

그럼 상태관리를 안하는 방법은 무엇인가?
컴포넌트가 적절한 상태를 가지고 적절한 생명주기를 가진다면?

컴포넌트가 마운트되고 또 언마운트되면서 알아서 상태관리 되기때문에 개발자는 신경 쓸 필요가 없겠죠 ㅎㅎ

하지만 현대 앱과 요구사항은 복잡합니다.
전역이냐 지역이냐로 단편적인 생각이 아닌 컴포넌트 관점에서 산태 관리를 고민해보세요 :)
+ 사용자까지

</details>



<details>
  <summary>Q2. Custom Hook 사용</summary>

수업시간에 많이 다룬 내용이라 생략해서 대답하자면 이제 커스텀 훅으로 할 수 있는 일이 너무나 많아요

일단 지금은 다 시도해보세요 :)
너무 개발적으로만 생각하지말고 의미있는 커스텀 훅을 만들었느냐로 고민해보세요
타인이 봤을때는 뭐하러 분리했을까 싶을 수 있지만 스스로 의미있는 훅을 분리했고 합당한 고민과 근거가 있으면 좋겠습니다
</details>



<details>
  <summary>Q3. 상품 리스트 전역 데이터를 어디서 받아올까?</summary>

질문과 내용이 살짝 다른 느낌이네요.


[Normalizing State Shape](https://redux.js.org/usage/structuring-reducers/normalizing-state-shape)를 참고해보세요

</details>

<details>
  <summary>Q4. 타입스크립트</summary>

이정도면 잘쓰셨어요
저번에 말씀드린 것처럼 [typesafe-actions](https://github.com/piotrwitek/typesafe-actions)과 `RTK` 인스톨 후에 나오는 `index.d.ts(타입 선언 파일)`을 확인해보세요

</details>

<details>
<summary>Q5. redux/redux-thunk</summary>

문제 없이 잘 사용하셨습니다

</details>


---

고생하셨습니다
2단계 진행 부탁드려요!

2022-05-18 02:22 UTC, merged

2022-05-18 02:25 UTC, pocojang commented on src/hooks/useFetch.ts
> +  const [error, setError] = useState<string>(null);
이건 2단계까지 하면서 직접 겪어보셔야 감이 잡히실 것 같네요 ㅎㅎ
2단계까지 더 해보시죠~!

2022-05-18 02:25 UTC, pocojang commented on src/components/common/CroppedImage.tsx
> +const CroppedImage = ({ src, width, height, alt }: CroppedImageProps) => {
많이 좋아졌습니다 ㅎㅎ
추가적으로 아예 기본 이미지 썸네일을 대비하는게 좋아요 :)

2022-05-18 02:26 UTC, pocojang commented on tsconfig.json
> +  "include": ["src"]
`index.d.ts` 누락되었습니다 ㅎㅎ

2022-05-18 02:30 UTC, pocojang commented on public/index.html
> +    <div id="snackbar"></div>
`portal`을 위한 `root element`가 엄청 늘어날 수 있다.
그러니 그에 대한 대응이 필요할 수 있다다는 이야기였어요 ㅎㅎ

예)
```html
<div id="root"></div>
<div id="snackbar"></div>
<div id="modal"></div>
<div id="toast"></div>
<div id="spinner"></div>
```

2022-05-18 02:34 UTC, pocojang commented on src/styles/GlobalStyle.ts
> +import reset from 'styled-reset';
이런 경우 웬만한 유명한 CSS 프레임워크가 쓰는 초기화 전용 스타일이 뭐가 있을지 알아보세요 ㅎㅎ

- https://github.com/jensimmons/cssremedy
- https://github.com/necolas/normalize.css
- https://github.com/csstools/sanitize.css
- https://meyerweb.com/eric/tools/css/reset

2022-05-18 15:29 UTC, juunzzi commented on src/components/common/Portal.tsx
> +const Portal = ({ children, id }: PortalProps) => {
```jsx
function PageTemplate({ children }: React.PropsWithChildren<EmptyObject>) {
  return (
    <>
      <Header />
      <Styled.Main>{children}</Styled.Main>
    </>
  );
}

```

`React.PropsWithChildren` 활용해봐도 좋을듯?

2022-05-18 15:29 UTC, juunzzi commented on src/components/common/Portal.tsx
> +const Portal = ({ children, id }: PortalProps) => {
ㅋㅋㅋ 시짚처럼 다루는게 더 좋을려나 ?

2022-05-18 15:51 UTC, euijinkk commented on src/components/common/Portal.tsx
> +const Portal = ({ children, id }: PortalProps) => {
저런게 있었군 ㅋㅋ 
```typescript
type PropsWithChildren<P> = P & {
    children?: ReactNode | undefined;
}
```

이거 밖에 해주는게 없는데 굳이 왜 만들어뒀지? ㅋㅋ

뭐 있으니까 쓰면 편하긴 할듯 ㅋㅋ

children 외 다른 props 없을 때는

`PropsWithChildren<unknown>`
와 같이 사용하는 것 같은데, 보기 괜찮으려나?

2022-05-18 15:57 UTC, juunzzi commented on src/components/common/Portal.tsx
> +const Portal = ({ children, id }: PortalProps) => {
오 unknown으로 해도되겟네 ㅋㅋㅋ 굳 좋은듯